- src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/Pagination.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/Pagination.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/__snapshots__/Pagination.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | introduced in #4203 
This PR renders the initial loader for the `Datagrid` within the `Datagrid` container component.
Because this way the initial loader always looks the same, and it is handled in a central place instead of multiple times.
This also fixes a bug, in which the `TableAdapter` resp. any adapter using the `Pagination` were not showing a loader but an empty list at the beginning.
> consolidate initial loader for Datagrids

- src/Sulu/Bundle/ContactBundle/Entity/Contact.php
- src/Sulu/Bundle/ContactBundle/Entity/ContactInterface.php
| Q | A
| --- | ---
Add `setNote` and `getNote` to ContactInterface
It are needed contact interface functions. Also phpstan did fail in project because of this.
> Add `setNote` and `getNote` to ContactInterface

- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4103 
| Related issues/PRs | n/a
Fixes  redirects that contain query parameters.
> Hotfix - redirect pages with trailing slashes were missing query params

- src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
| Q | A
| --- | ---
Added autoconfigure for sulu admin class.
When use autoconfigure in your project sulu should autoconfigure the admin class.
1. Create AppAdmin
~~~php
<?php
namespace App\Admin;
use Sulu\Bundle\AdminBundle\Admin\Admin;
class AppAdmin extends Admin
{
}
~~~
2. Activate autoconfigure in your `config/services.yaml`
~~~php
services:
_defaults:
autowire: true
autoconfigure: true
public: false
App\:
resource: '../src/*'
exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
App\Controller\:
resource: '../src/Controller'
tags: ['controller.service_arguments']
~~~
> Added autoconfigure for sulu admin class

- src/Sulu/Bundle/CoreBundle/Resources/config/list_builder.xml
- src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml
| Q | A
| --- | ---
Added support for autowire for rest helper and field descriptor factory.
To support autowire for some sulu services
Use configured interface aliases.
> Added support for autowire for rest helper and field descriptor factory

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
| Q | A
| --- | ---
| Related issues/PRs | #4211 
This PR only shows the loader if the `pageCount` of the datagrid is zero.
Because only then it makes sense to show the general loader. E.g. the `ColumnListAdapter` uses the `FullLoadingStrategy`, which causes the `pageCount` to be undefined, leading to a full loader on every click on an item in the Webspace overview.
> fix loading in ColumnListAdapter when activating item

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaSection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR adds deleting of media to our feature set. In addition to that it cleaned up the existing code for the Datagrid view, and introduced a dialog, which has to be confirmed before deleting.
Because sometimes people want to delete medias :smiley:
> implement deleting of media in datagrid

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/datagridAdapterDefaultProps.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
| Q | A
| --- | ---
| Related issues/PRs | #4159 
This introduces default props for `DatagridAdapters` in the same way #4159 did for `FieldType`s.
Because it makes tests less tedious to write.
> Introduce datagridAdapterDefaultProps

- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Controller/TargetGroupControllerTest.php
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
| Q | A
| --- | ---
This PR improves the performance of our functional tests.
Because a lot of entities are generated although they are not always needed in the tests, because all of them are generated in the `setUp` of the PHPUnit test.
> Make AudienceTargeting and Category tests faster

- .travis.yml
| Q | A
| --- | ---
Debug php 5.5 on travis
Currently composer install fails on php 5.5
> fixed travis timeout for php 5.5 test case

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Option.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/tests/SingleSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adjusts the single-select component to not show any value, if nothing is selected. Furthermore, this PR implements the support for options with the value undefined. An option with the value undefined can be used to reset the current selection.
We need to display select-components that do not have a value initially. In these cases it is misleading, if the component contains the value of the first option.
> implemented handling of undefined-value in single-select component

- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/checker.xml
| Q | A
| --- | ---
| Related PRs? | #4228, #4223
Added autowire services for SecurityCheckerInterface and WebspaceManagerInterface.
It allows to autowire webspace manager and security manager interface for the admin class.
```yaml
services:
_defaults:
autowire: true
autoconfigure: true
public: false
App\:
resource: '../src/*'
exclude: '../src/{Migrations,Tests,Kernel.php}'
```
```php
// src/App/AppAdmin.php
namespace App\Admin;
use Sulu\Bundle\AdminBundle\Admin\Admin;
use Sulu\Component\Security\Authorization\SecurityCheckerInterface;
use Sulu\Component\Webspace\Manager\WebspaceManagerInterface;
class AppAdmin extends Admin
{
/**
* @var WebspaceManagerInterface
*/
private $webspaceManager;
/**
* …
```
> Added autowire services for SecurityCheckerInterface and WebspaceManagerInterface

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/Block.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/SortableBlock.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/datagridAdapterDefaultProps.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/ImageFocusPoint.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/imageFocusPoint.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/tests/ImageFocusPoint.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/tests/__snapshots__/ImageFocusPoint.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/FocusPointOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/focusPointOverlay.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/mediaDetail.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/FocusPointOverlay.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds the overlay for setting the focus point of an image.
Because this is a feature being already available in the old UI.
> Add focus point overlay

- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/CoreBundle/Tests/DependencyInjection/SuluCoreExtensionTest.php
- src/Sulu/Component/Rest/ListBuilder/Metadata/Provider/ChainProvider.php
- src/Sulu/Component/Rest/RestHelperInterface.php
| Q | A
| --- | ---
| Related issues/PRs | #4147
Added support for list-builder configuration in project config directory. 
As the application itself is not longer a bundle we should allow to store `list-builder` configuration in project `config` directory to allow create custom entities in a project.
Create `config/list-builder/Test.xml`
~~~xml
<class xmlns="http://schemas.sulu.io/class/general"
xmlns:orm="http://schemas.sulu.io/class/doctrine"
xmlns:list="http://schemas.sulu.io/class/list">
<properties>
<property name="id" visibility="always" list:translation="app.id" searchability="yes">
<orm:field-name>id</orm:field-name>
<orm:entity-name>App\Entity\Test</orm:entity-name>
</property> …
> Added support for list-builder configuration in project config directory

- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
- src/Sulu/Component/Rest/RestHelper.php
| Q | A
| --- | ---
Use field descriptor interface in resthelper and fixed error with flow.
Avoid problems with [phpstan](https://github.com/phpstan/phpstan).
~~~php
$fieldDescriptors = $this->fieldDescriptorsFactory->getFieldDescriptorForClass(Location::class);
$this->restHelper->initializeListBuilder($this->listBuilder, $fieldDescriptors);
~~~
> Use field descriptor interface in resthelper

- src/Sulu/Bundle/HttpCacheBundle/Resources/config/cache-lifetime-enhancer.xml
| Q | A
| --- | ---
This PR set the `sulu_http_cache.cache_lifetime.enhancer` public.
Without this the  `X-Reverse-Proxy-TTL` will not be set.
> Fixed website caching by setting cache_lifetime.enhancer public

- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
| Q | A
| --- | ---
Get media file extension based on it's mimetype.
Images without extension in filename will not get the correct extension.
> Get media file extension based on mimetype

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js
| Q | A
| --- | ---
Fixed url field type initial value.
It should not submit a url with just a protocol. 
1. Create a template with url field type e.g.:
~~~xml
<property name="website" type="url" colspan="4">
<meta>
<title>app.website</title>
</meta>
</property>
~~~
2. try to save the template 
**before**
Value was: `https://`
**after**
Value is *empty*
> Fixed url field type initial value

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Input.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Input.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
| Q | A
| --- | ---
This PR adds the handling for the `headline` param to the input field type. This will allow to have bigger input fields, e.g. for the names in the contact or the title on pages.
Because this way it is easier to recognize the very important fields for the content manager.
> add headline param to Input field type

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Build/UserBuilder.php
| Q | A
| --- | ---
Set default locale for admin user to "en".
This is more friendlier to international users.
> Set default locale for admin user to "en".

- config/packages/test/massive_search.yaml
- config/packages/test/security_admin.yaml
- config/packages/test/sulu_test.yaml
| Q | A
| --- | ---
Added configuration for test environment.
To allow using authenticated client from the test bundle and avoid writing into the live index for tests.
> Added configuration for test environment

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Option.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Select.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
- src/Sulu/Bundle/ContentBundle/Content/Types/Select.php
- src/Sulu/Bundle/ContentBundle/Resources/config/content_types.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
- src/Sulu/Component/Content/Metadata/ItemMetadata.php
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
| Q | A
| --- | ---
| Fixed Issues | fixed #4142
| Related PRs? | needs #4263
| Docs PRs? | https://github.com/sulu/sulu-docs/pull/402
Implement multi select field type.
Needed for selecting multiple items instead of single items.
~~~xml
<property name="select" type="select">
<meta>
<title lang="en">Multiple Select</title>
<title lang="de">Multiple Select</title>
</meta>
<params>
<param name="default_values" type="collection">
<param name="0"/>
<param name="1"/>
</param>
<param name="values" type="collection">
<param name="0">
<meta>
<title lang="en">Option 1</title>
<title lang="de">Option 1</title>
</meta>
</param>
<param name="1">
<meta>
<title lang="en">Option 2</title>
<title lang="de">Option …
> Added multi select field type

- src/Sulu/Component/Hash/Serializer/Subscriber/HashSerializeEventSubscriber.php
- src/Sulu/Component/Hash/Tests/Unit/Serializer/Subscriber/HashSerializeEventSubscriberTest.php
- src/Sulu/Component/Security/Tests/Unit/Serializer/Subscriber/SecuredEntitySubscriberTest.php
- src/Sulu/Component/Serializer/ArraySerializationVisitor.php
| Q | A
| --- | ---
Replace deprecated `addData` function with `setData` function to avoid a serialization error when serialize [inline](https://jmsyst.com/libs/serializer/master/reference/annotations#inline). ~~Replace deprecated [GenericSerializationVisitor](https://github.com/schmittjoh/serializer/blob/1.13.0/src/JMS/Serializer/GenericSerializationVisitor.php#L11)~~
To fix hash serializer for inline serialization. If you have subentities which are also auditable and you try to inline them it will error with `_hash` exist instead. 
~~~php
/**
* @Serializer\Expose
* @Serializer\Inline
*
* @ORM\OneToOne(targetEntity="App\Model\Location\LocationDimensionRestaurant", mappedBy="locationDimension", …
> Fixed hash serializer for inline serialization

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Menu/Divider.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Action.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Option.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelect/MultiSelect.js
| Q | A
| --- | ---
This PR refactors the already implemented select components to use props with exact object types.
Exact object types provide a better type safety and allow for better static code checking.
The implementation of the `Option` component allows for not setting the `value` prop. This is desired behaviour that allows to implement valueless-options that can be used to reset the value of a single-selection.
Unfortunately, the `SingleSelect` component and `MultiSelect` component are incompatible with these valueless-options as they do not expect undefined values in their `handleSelect()` methods. These inconsistencies were not detected by flow until now, because we were not using exact …
> refactored select components to use exact object types

- composer.json
| Q | A
| --- | ---
The docs of composer state the branch-alias settings should be placed under extra.
See https://getcomposer.org/doc/articles/aliases.md#branch-alias
This makes it possible to require a development version without having issues with other packages requirements
~~~bash
composer require sulu/sulu:2.0.x-dev
~~~
none
> Put branch alias in extra section

- src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaSelectionStore/MediaSelectionStore.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaSelectionStore/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaSelectionStore/tests/MediaSelectionStore.test.js
- src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
| Q | A
| --- | ---
| BC breaks? | hopefully no
This PR splits up the `MediaSelection` component into a field-type component and a container-component.
This allows to use the `MediaSelection` component outside of a form. Also, most other input-components are split into a container-component and a field-type too.
> extracted media-selection field-type from media-selection container

- src/Sulu/Bundle/ContactBundle/Content/Types/SingleContactSelection.php
- src/Sulu/Bundle/ContactBundle/Resources/config/content.xml
- src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php
| Q | A
| --- | ---
This PR adjusts the single-contact-selection content-type to use the reference store to invalidate cache entires if the contact value changes
> use reference-store in single-contact-selection content-type to invalidate cache

- .editorconfig
| Q | A
| --- | ---
This PR adds a `.editorconfig` file into the root directory of the project.
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. See https://editorconfig.org/
> added .editorconfig file to improve code style consistency

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
- src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds the possibility to delete a draft via the `edit` menu in the toolbar.
Because it already existed in the old UI.
> add toolbar item for draft deletion of page

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/MultiMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MultiMediaSelectionStore/MultiMediaSelectionStore.js
| Q | A
| --- | ---
This PR adjusts the selection components to not fire the given change-handler while their selection-store is loading.
The current implementation calls the given change handler two times when a selection component is created with an initial value. This is because the selection-store needs to load the data asynchronously and the change handler is fired automatically when the data is loaded.
The behaviour described above can be reproduced with the `contact-selection` on the *Page Settings* tab.
>  adjusted selection components to not fire change-handler while selection-store is loading

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
| Q | A
| --- | ---
This PR adjusts the `SingleSelection`  component to load the whole item with a separate request after it was selected in the overlay.
Because the item returned from the overlay may not contain all properties that are used as `displayProperties`.
> load full item on select in single-selection

- src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
| Q | A
| --- | ---
This PR allows to have `null` as a value in the `ExcerptExtension`.
Because it was not possible to remove e.g. the value of the title field in the excerpt tab. It just appeared again after saving.
> allow to delete content of properties in excerpt

- src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/CKEditor5.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/tests/CKEditor5.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes ----
| Related issues/PRs | #4254
This PR fixes the handling of `undefined` in the ckeditor.
When a form included a CKEditor, which was empty and another field was changed and the form was saved, the save button stayed active, even though the form save was successful.
> fix dirty state after saving empty ckeditor

- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/SingleItemSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/singleItemSelection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/SingleItemSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/__snapshots__/SingleItemSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
| Q | A
| --- | ---
This PR introduces a `loading` prop for the `SingleItemSelection` component. If the `loading` prop is set to true, a loading icon ist displayed on the right side of the component.
Furthermore, the PR changes the `SingleSelection` component and the `SingleMediaSelection` component to use the introduced prop.
Because we want to signal to the user that the selection is loading. With the current implementation, it looks like the input field is empty while the component is loading. The current behaviour can be seen at the `contact-selection` on the **Page Settings** tab.
>  added and implemented loading prop for single-item-selection component

- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaUpload.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaUpload.test.js
| Q | A
| --- | ---
This PR adds a dummy `contentLocale` property to the `UserStore`. The `contentLocale` defines the locale in which localized content should be displayed.
The implementation in this PR returns a `contentLocale` fallback value all the time. In the future, the `contentLocale` should be updated and persisted when the user changes the displayed locale of a localized content in the UI.
Because we need a standardized way to access the locale in which localized content should be displayed.
> implemented content-locale property in user store

- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/SingleItemSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/singleItemSelection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/SingleItemSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/__snapshots__/SingleItemSelection.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
| Q | A
| --- | ---
This PR implements a `valid` prop for the `SingleMediaSelection` component and the `SingleItemSelection` component. The `valid` prop works similar to the `valid` prop of other input components and can be used to signal a validation error.
Because we want need a way to signal to the user that the content of a `SingleMediaSelection` component is not valid.
> implemented valid prop in single-media-selection and single-item-selection

- src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php
- src/Sulu/Component/Content/Query/ContentQueryBuilder.php
| Q | A
| --- | ---
If you save a sulu document multiple properties where added that where just duplications.
We imported 1.500 nodes and got 7.000.000 properties.
> Properties are redundantly added on a document save

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR add a second type of single selection for account.
> Added "datagrid_overlay" type to single_contact/single_account selection

- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js
| Q | A
| --- | ---
Prevent rerendering of items in `MultiItemSelection`.
Not usable for user inputs when the component is rerendered all the time.
> Prevent rerendering in MultiItemSelection

- package.json
- src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
- webpack.config.js
| Q | A
| --- | ---
| Related PRs? | https://github.com/sulu/sulu/pull/4287, https://github.com/sulu/sulu-minimal/pull/141
The basepath where to build the js should be easy overwriteable over env variables.
And the public-dir is read from the composer.json configuration see https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory.
In some cases you want to change the basepath where the js is build to.
```js
const webpackConfig = require('./vendor/sulu/sulu/webpack.config.js');
module.exports = (env, argv) => {
if (!env) {
env = {};
}
env.base_path = 'admin-build';
return webpackConfig(env, argv);
};
```
and changing public dir in symfony:
```json
{
... …
```
> Added easier way to overwrite public directory and base path

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
| Q | A
| --- | ---
This PR add an `apiOptions` option to the `Form` view that allows to set attributes which are then passed to the `FormStore`. The attributes are passed to the `FormStore` analog to the attributes specified in the `routerAttributesToFormStore` option.
Because it might be useful to define some data in the route definition that is sent to the server when the `Form` is saved.
~~~php
$route = new Route('sulu_category.add_form', '/categories/:locale/add', 'sulu_admin.resource_tabs');
$route->addOption('resourceKey', 'categories')
$route->addOption('toolbarActions', $formToolbarActions)
$route->addOption('apiOptions', ['apiKey' => 'value-that-is-sent-as-query-param'])
~~~
> Add apiOptions-option to form-view

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/FormatLoader/schema/formats/formats-1.1.xsd
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetTypesController.php
| Q | A
| --- | ---
| Related PRs | sulu/sulu-minimal#143
Allow empty image formats configuration.
To provide an example image-formats.xml
~~~php
<?xml version="1.0" encoding="UTF-8"?>
<formats xmlns="http://schemas.sulu.io/media/formats"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://schemas.sulu.io/media/formats http://schemas.sulu.io/media/formats-1.1.xsd">
</formats>
~~~
> Allow empty image formats configuration

- src/Sulu/Bundle/AdminBundle/Metadata/Form/FormMetadataProvider.php
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_nested_sections.xml
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_schema.xml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/Form/FormMetadataProviderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Component/Content/Metadata/Loader/schema/form-1.0.xsd
- src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
- src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
- src/Sulu/Component/Content/Metadata/PropertiesMetadata.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
- tests/Resources/DataFixtures/Page/template_with_nested_sections.xml
| Q | A
| --- | ---
This PR allows to nest sections within each other.
Because it is IMO an intuitive behavior. And we need that in the contact form, because we have sections splitting the screen vertically, and in the right section we want to have a few section headlines.
Put e.g. the following part in a page template.
~~~xml
<section name="test2" colspan="9">
<properties>
<property name="article" type="text_editor">
<meta>
<title lang="en">Article</title>
<title lang="de">Artikel</title>
</meta>
</property>
<section name="test3">
<meta>
<title>Test</title>
</meta>
<properties>
<property name="test" type="text_area" /> …
> Allow to nest sections in forms

- UPGRADE.md
- src/Sulu/Bundle/CategoryBundle/Content/Types/CategorySelection.php
- src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
- src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
- src/Sulu/Bundle/CategoryBundle/Tests/Unit/Content/Types/CategorySelectionTest.php
- src/Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Export/WebspaceExportTest.php
- src/Sulu/Bundle/MediaBundle/Resources/config/forms/Media.xml
| Q | A
| --- | ---
| Fixed tickets | parts of #3624 
Rename category_list to category_selection.
Normalize content and field type names see #3624 .
```xml
<property name="yourname" type="category_selection">
</property>
```
See UPGRAD.md
> Rename category_list to category_selection

- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml
- src/Sulu/Bundle/ContentBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/ContentBundle/Tests/Application/config/templates/pages/html5.xml
- src/Sulu/Bundle/ContentBundle/Tests/Application/config/templates/pages/invalidhtml.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Export/WebspaceExportTest.php
- src/Sulu/Bundle/MediaBundle/Resources/config/forms/Media.xml
- src/Sulu/Bundle/TagBundle/Content/Types/TagSelection.php
- src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
- src/Sulu/Bundle/TagBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Fixed tickets | part of #3624 
Rename tag_list to tag_selection.
See #3624
~~~php
<property name="tags" type="tag_selection">
</property>
~~~
> Rename tag_list to tag_selection

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Form/Type/AbstractStructureBehaviorType.php
- src/Sulu/Bundle/ContentBundle/Form/Type/BasePageDocumentType.php
- src/Sulu/Bundle/ContentBundle/Form/Type/UnstructuredType.php
- src/Sulu/Bundle/SnippetBundle/Form/SnippetType.php
| Q | A
| --- | ---
Fix form submit of unstructured data.
Symfony seems since the latest release https://github.com/symfony/symfony/issues/29809 only allow scalar values be submit in the TextType.
> [structure.stagedData] This value is not valid. ({"{{ value }}":"NULL"})
I not really happy with the solution but currently seems the only working one.
> Fix compatibility to symfony 3.4.21, 4.1.10 and 4.2.2

- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/SingleItemSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/SingleItemSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/__snapshots__/SingleItemSelection.test.js.snap
| Q | A
| --- | ---
Do not display empty text while loading in SingleItemSelection.
Display three dots instead.
Do not display empty text while loading, this could mislead some users.
> Do not display empty text while loading in SingleItemSelection

- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Content/InternalLinksContainer.php
- src/Sulu/Bundle/ContentBundle/Content/Types/InternalLinks.php
- src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
- src/Sulu/Bundle/ContentBundle/Resources/config/content_types.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/export.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/services.xml
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/InternalLinksContainerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Types/InternalLinksTest.php
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
- src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php
- src/Sulu/Bundle/MediaBundle/Resources/config/ffmpeg.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/search.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_local.xml
- src/Sulu/Bundle/MediaBundle/Search/Subscriber/MediaSearchSubscriber.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Search/Subscriber/MediaSearchSubscriberTest.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/import.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php
- src/Sulu/Component/Content/Import/WebspaceImport.php
- src/Sulu/Component/DocumentManager/EventDispatcher/DebugEventDispatcher.php
- src/Sulu/Component/Snippet/Import/SnippetImport.php
| Q | A
| --- | ---
| BC breaks? | yes constructors changed
Make logger service optional and use `PSR\Log\NullLogger` when not available.
Currently sulu container does not build without monolog bundle installed. So in many cases like in bundles which does not need monolog need to require monolog for there tests:
e.g.:
- [Community Bundle](https://github.com/sulu/SuluCommunityBundle/blob/8c67eb0fc4970064b36c4a3b827c17bd7fce4187/composer.json#L35)
-  [SuluFormBundle](https://github.com/sulu/SuluFormBundle/blob/7bc6e35d6d3619f3d0de9249ed3bbbb52f367122/composer.json#L15)
- [SuluArticleBundle](https://github.com/sulu/SuluArticleBundle/blob/5f6b4e90821f71da9179aeb7ca642d88fba1bce1/composer.json#L18)
> Make logger service optional

- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/Navigation.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/Navigation.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
- src/Sulu/Component/Util/SuluVersionPass.php
| Q | A
| --- | ---
| Fixed tickets | fixes ---
I add app version to navigation bar.
Now you see your composer version in backend.
> Add app version from composer.json to admin navigation

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
| Q | A
| --- | ---
Remove false deprecation from website controller renderStructure.
There should be no deprecation without providing an alternative way to use. The renderStructure is still the correct way to render a structure element.
This deprecation mostly confuse people the first time creating a custom controller.
> Remove false deprecation of WebsiteController::renderStructure

- src/Sulu/Bundle/TagBundle/Resources/config/services.xml
| Q | A
| --- | ---
Add autowiring for tag manager.
To easily use the tag manager in your project.
~~~php
use Sulu\Bundle\TagBundle\Tag\TagManagerInterface;
/**
* @var TagManagerInterface
*/
private $tagManager;
public function __construct(TagManagerInterface $tagManager)
{
$this->tagManager = $tagManager;
}
~~~
> Add autowiring for tag manager

- UPGRADE.md
- src/Sulu/Bundle/TagBundle/Controller/TagController.php
- src/Sulu/Bundle/TagBundle/Resources/config/services.xml
- src/Sulu/Bundle/TagBundle/Tag/TagManager.php
- src/Sulu/Bundle/TagBundle/Tag/TagManagerInterface.php
- src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/TagControllerTest.php
| Q | A
| --- | ---
| Related PRs | #4336
Remove required userId parameter from TagManagerInterface methods
The userId is not longer used and the changer is set over the AuditableInterface.
~~~php
$tagManager->findOrCreateByName($name);
$tagManager->save($data);
~~~
> Remove required userId parameter from TagManagerInterface methods

- src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
| Q | A
| --- | ---
Remove tolowercase from default snippet manager.
Was introduced because of a strange behaviour in <3.4 symfony versions where `get` method did strtolower but the array wasn't set strtolower:
See https://github.com/symfony/symfony/pull/24065#issuecomment-326638713
> Remove tolowercase from default snippet manager

- UPGRADE.md
- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Set default sulu context of the SuluKernel to Admin.
It allow in not ContextBased tests extend from the `Symfony\Bundle\FrameworkBundle\Test\KernelTestCase`.
~~~php
namespace App\Tests\Functional\Migration;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
class MigrationTest extends KernelTestCase
{
}
~~~
> Add a default context to sulu kernel

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
Updated MediaBundle's MediaManager to get the video dimensions when ffprobe is available.
| Q | A
| --- | ---
| Fixed tickets | N/A
| Related issues/PRs | <not-created>
The MediaManager in the MediaBundle allows videos to be uploaded and processed with ffmpeg and ffprobe but the dimension informations are not saved. This PR adds, when available, the width and height of the video files to the media file properties.
It is useful to have the video dimensions available in Twig. It could for instance be used when we want to have a cover video while keeping the video's aspect ratio.
~~~twig
{# Provided you have a media_selection field called 'video' #}
<video …
> Added dimension properties to video media

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
| Q | A
| --- | ---
| Documentation PR | ----
This PR adds a check, to not rerender the `AutoComplete` field in a form when a new tag is added.
Before the component has been rerendered in an infinite loop if some tag was added.
> Fix rerenderings of AutoComplete

- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
Adding file and line numbers for the error display in dev environments to support and speed up template development.
| Q | A
| --- | ---
It adds template file path and error line number to the preview error display.
Otherwise it is almost impossible to swiftly find the mistake in complex templates. Often the error message only is to short.
Well, just add an error to some template and check the preview out ;)
> Better error display for dev environments

- UPGRADE.md
- config/webspaces/sulu-test.xml
- src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
- src/Sulu/Bundle/SearchBundle/Resources/config/routing_website.xml
- src/Sulu/Bundle/SearchBundle/Resources/config/search.xml
- src/Sulu/Bundle/SearchBundle/Tests/Unit/Controller/WebsiteSearchControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/ExceptionControllerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
- src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
| Related PRs | https://github.com/sulu/sulu-minimal/pull/148
Add support for different request format for webspace templates.
Page and other templates allow to render the view in different formats. Search for example can now with this change be allowed to have a `/search.json?q=query` so its easier to create a live search.
~~~php
<templates>
<template type="search">templates/search</template>
<template type="error">templates/error</template>
</templates>
~~~
Create a `search/search.json.twig` and access http://127.0.0.1:8000/search.json?q=query
See UPGRADE.md
> Add support for different request format for webspace templates

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/ContactBundle/Api/Account.php
- src/Sulu/Bundle/ContactBundle/Api/Contact.php
- src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/account_details.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/contact_details.xml
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
| Q | A
| --- | ---
This PR adds the fields for categories and tags to the forms for accounts and contacts.
Because our entities have these values, and the fields were also there in the old UI.
The `categories` field in the contacts and accounts API constists of IDs instead of objects now.
> Add taxonomy fields to form for contacts and accounts

- src/Sulu/Bundle/AdminBundle/Metadata/Schema/Schema.php
- src/Sulu/Bundle/AdminBundle/Serializer/Handler/SchemaHandler.php
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/Form/FormMetadataProviderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/Schema/SchemaTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
| Q | A
| --- | ---
This PR makes the JSON schema objects (also the ones in `anyOf` and `allOf` properties) always return at least the property `required`, even if it is empty.
I've also tried to completely use JMS serializer, which would have allowed to fix that specific problem without the `required` property to be always returned. However, therefore all `properties` would have been returned, which would cause even more unnecessary data.
Because this allows to extend forms without any additional schema information. Before this would have returned an empty array in an `allOf` array, which is invalid JSON.
So before it was …
> Fix extending forms without any schema information

- src/Sulu/Bundle/CoreBundle/SuluCoreBundle.php
| Q | A
| --- | ---
This PR increases the priority of the context compiler pass.
This will avoid the collecting and auto-wiring of tagged services.
> Fix auto-wiring for context based services

- src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/SecurityBundle/Resources/views/mail_templates/reset_password.html.twig
| Q | A
| --- | ---
Adds missing translation for reset-password mail and changes translation key to new standard.
Also: changed line endings of mail template from CRLF to LF.
The mail message was not translated yet. The plain translation key `security.reset.mail-message` was shown in the mail
> Add missing translation for reset-password mail message

- src/Sulu/Bundle/ContactBundle/Resources/config/list-builder/Contact.xml
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineJoinDescriptor.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
Add missing upgrade for field descriptors encode alias trait for 1.6.24
And fix DoctrineJoinFieldDescriptor without a relation by cherry picking: https://github.com/sulu/sulu/pull/4285 **So maybe not squash merge this PR**?
It is not documented that you need to use the EncodeAliasTrait now if you have custom field descriptors.
The FieldJoinDescriptor did not longer work without relation.
See Upgrade.md
> Fix FieldJoinDescriptor without a relation

- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Add possibility to load context based services.
If you use autowiring to bind some services or values to a variable e.g.:
```yaml
services:
_defaults:
autowire: true
autoconfigure: true
public: false
bind:
$importConnection: '@doctrine.dbal.import_connection'
```
and only a `$importConnection` is used in a admin context based service Symfony will throw the following error when binding the container:
> Unused variable "$importConnection" binded
Create a `services/services_admin.yaml`
~~~yaml
services:
_defaults:
autowire: true
autoconfigure: true
public: false
bind:
$test: true
App\:
resource: '../src/*'
exclude: '../src/{Migrations,Tests,Kernel.php}'
tags:
- name: 'sulu.context' …
> Add possibility to load context based services

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/massiveart/MassiveSearchBundle/pull/126
Allow massive search 0.17 version in sulu 1.6.24
In some cases it runs into a problem with php 7.2 so this version is needed to be allowed.
> Fix compatibility to massive search with php7.2 fix

- .circleci/config.yml
- .gitignore
- UPGRADE.md
- package.json
- preinstall.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/preview.scss
- tests/js/check-yarn-warning.sh
- webpack.config.js
| Q | A
| --- | ---
| Related PRs | https://github.com/sulu/sulu-minimal/pull/154
~~Fix building sulu with yarn.~~
Add warning message when try to install npm dependencies using yarn 
~~If somebody want to use yarn to build sulu he should not end up with an error.~~
We will currently not supporting yarn because of yarn is not supporting symlinks:
~~~php
yarn install
~~~
> You must use npm to install, yarn is not supported
> Add warning message when try to install npm dependencies using yarn

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
| Q | A
| --- | ---
This PR fixes a bug which happened when you switched from a template to another template, whereby the second template was missing at least one field that exists in the first template.
I've omitted the tests, because I am going to refactor that part tomorrow anyway, and have to adapt even more tests.
Because it was not possible to change the template without an erorr in certain cases.
> Fix error when switching template

- src/Sulu/Bundle/AdminBundle/Metadata/Form/Field.php
- src/Sulu/Bundle/AdminBundle/Metadata/Form/FormMetadataProvider.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlock.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/SortableBlock.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/fieldTypeDefaultProps.js
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/Form/FormMetadataProviderTest.php
| Q | A
| --- | ---
This PR uses the default type configuration on the `types` node from our XML template to determine which type should be preselected when a new block is added.
Because otherwise it wouldn't make a lot of sense to have this configuration anyway.
> Use default type of blocks when adding a new block

- composer.json
| Q | A
| --- | ---
Allow installation of layershift/tld-extract ^2.0
We should support the widest range of required libraries which are possible.
> Allow installation of layershift/tld-extract ^2.0

- webpack.config.js
| Q | A
| --- | ---
This PR adds `regenerator-runtime` to the entrypoints in put webpack config. This is needed because we want to produce an ES5 build that includes ckeditor.
See: 
* https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target
* https://github.com/ckeditor/ckeditor5/issues/568
> Add regenerator runtime to webpack config to fix ckeditor build

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Resources/config/serializer/Webspace.xml
- src/Sulu/Bundle/PageBundle/Resources/js/index.js
- src/Sulu/Bundle/PageBundle/Resources/js/stores/WebspaceStore/types.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/TemplateToolbarAction.test.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/TemplateToolbarAction.js
| Q | A
| --- | ---
This PR uses the default template configured in the webspace XML to set the default template when a page is added.
Because it would be nice to be able to select the default template.
> Use default template from webspace when adding new pages

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/CardCollection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
This PR contains an update to jexl 2.1, and use the new `evalSync` function.
Because this way we can avoid having unnecessary asynchronity and therefore easier to read code.
> Update jexl to avoid having callbacks

- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
| Q | A
| --- | ---
This PR uses `has` instead of `get` to check if a value is in the user settings map. In addition to that it clears the array for the dirty settings after the changes have been set.
This allows to also persist the unpinned state of the navigation. It also avoids sending settings to the server that have already been persisted.
> Persist persistent user settings with a value of false

- composer.json
| Q | A
| --- | ---
Upgrade imagine library version to allow ^1.0.
To support webp in future release.
> Add support for newest imagine version

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/MultiMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
| Q | A
| --- | ---
This PR changes our selection containers to use a `reaction` instead of a `autorun` to observe changes in the store of the container.
Because the listener that calls the `onChange` callback of the container should only be executed if the value of the store of the container changes. In contrast to `autorun`, `reaction` allows us to specify precisely which data should be observed.
Right now, when using `autorun`, our `onChange` handler is unnecessarily called multiple times in various places. For example, this can be observed when changing the value of a `SingleSelection` inside a `Form` (ie. the author selection on the page-settings tag).
Furthermore, the unnecessary calls to our …
> Use reaction instead of autorun to observe changes in stores of selection containers

- src/Sulu/Bundle/AdminBundle/Admin/Routing/DatagridRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/DatagridRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/DatagridRouteBuilderTest.php
| Q | A
| --- | ---
This PR adds a `setBackRoute` method to the `DatagridRouteBuilder`.
Because we want to display a back-button when using a datagrid-view inside of a resource-tab.
> Add set-back-route method to datagrid-route-builder

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Documentation PR |-
Finally found the issue why the translation export count of messages where different between the languages and fixed by using the correct key for them.
False key was used and it did fallback in some languages.
~~~php
bin/console sulu:translate:export
~~~
> Fix translation for snippet taxonimies

- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
| Q | A
| --- | ---
| Related issues/PRs | #4424 
There was a second occurence of jexl which can be used in sync mode since #4424. But the update missed to apply it to the `ResourceTabs` as well.
> Make use of jexl.evalSync in ResourceTabs component

- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
| Q | A
| --- | ---
We want to hide the title inside the first tab of a ResourceTabs view. This PR adjusts the logic that decides if the title should be displayed to respect the tabOrder of the tabs.
> Respect tab order when deciding if title of resource-tabse should be displayed

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
| Q | A
| --- | ---
This PR adjusts the `DatagridView` to set a `backButton` in its `ToolbarConfig` if a `backRoute` is set in its route-options.
Because we want to display a button that makes use of the `backRoute`. Otherwise the `backRoute` option in the `DatagridRouteBuilder` is quite pointless 🙂
> Render back-button in datagrid-view when back-route of route is set

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
| Q | A
| --- | ---
Fix empty table look in firefox by set the table height to auto when empty.
The **empty** table currently looks really strange on current Firefox (65):
This happens because of the table height 100% (introduced in https://github.com/sulu/sulu/pull/3893) ~~as I'm not sure why this height 100% there I introduced a new class table-empty to fix this problem.~~ **EDIT:** As discussed with @danrot we remove the height 100% as we could not find a need for it. 
Firefox behaviour happens because of the placeholder as the placeholder is on the same level as the table and the table height is 100% firefox add the height of the placeholder as this is at rendering time …
> Fix empty table look in firefox

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/field.scss
- src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
This PR allows to pass `null` as value for categories in the contacts and accounts API.
Because creating a new contact or account failed when no categories were selected.
> Allow to create contacts and accounts without categories

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
| Q | A
| --- | ---
This PR adds some hooks to interfere the routing process, in order to enable the form to avoid routing if it has been edited.
Because doing this leads to data loss, so the user should be asked for confirmation.
> Ask for confirmation when leaving an edited form

- src/Sulu/Bundle/AdminBundle/Admin/Routing/RouteBuilderFactory.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/RouteBuilderFactoryInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/TabRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/TabRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/resourceTabs.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tabs.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/Tabs.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/__snapshots__/Tabs.test.js.snap
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/TabRouteBuilderTest.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceOverview/webspaceOverview.scss
- src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
| Q | A
| --- | ---
A simple tab view that is used for the Webspace Overview.
It is necessary because there will appear more tabs later, which don't share a `ResourceStore`, and therefore it is not possible to use the `ResourceTabs`.
> Add simple tab view for Webspaces

- src/Sulu/Bundle/WebsiteBundle/Controller/CacheController.php
| Q | A
| --- | ---
This PR makes the cache clear route return an empty response.
Because the loader in the confirmation overlay breaks otherwise.
> Fix closing of confirmation overlay for clearing the website cache

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
| Q | A
| --- | ---
Fix bug in Requester for nested objects.
Because `undefined` is not converted to `null` currently, therefore the property will not be included in the payload.
> Fix bug in Requester for nested objects

- src/Sulu/Bundle/PageBundle/Resources/config/serializer/Document.BasePageDocument.xml
- src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Preview/preview.html.twig
| Q | A
| --- | ---
| Fixed tickets | fix #4455 
This PR fixes the rendering process of the preview when invalid HTML is provided
Its not really a BC-Break but the `#content` id isnt needed anymore.
> Fix rendering of preview

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ListRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ListRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ListRouteBuilderTest.php
| Q | A
| --- | ---
Add resource store properties to list store route options.
In some cases you want to use resourceStore properties as list store options to example filter by a specific value.
```php
$this->routeBuilderFactory->createListRouteBuilder(...)
->addResourceStorePropertiesToListStore([
'resourceStoreProperty' => 'listStoreProperty',
]);
```
This pull request also change the `addRouterAttributesToListStore` from:
```php
->addRouterAttributesToListStore([
'listStoreProperty' => 'routeAttribute',
]);
```
to
```php
->addRouterAttributesToListStore([
'routeAttribute' => 'listStoreProperty',
]);
```
> Add resource store properties to list store options

- src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php
| Q | A
| --- | ---
Remove `isRequired` from `sulu_core.content.structure.paths`.
Because it causes problems when trying to define for example only the `default_type`:
```
sulu_core:
content:
structure:
default_type:
article: "default"
```
> Sulu core configuration: Remove required attribute from paths

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
by unboxing locale before passing it to the the requester
| Q | A
| --- | ---
This PR fixes the generation of the resource-locator when a new page is created. 
Before this PR, the `ResourceLocator` field-type passed the locale as `boxed observable` to the `Requester`. 
After https://github.com/sulu/sulu/pull/4460 was merged, this boxed observable lead to an infinite loop in the `transformRequestData` method of the `Requester` because boxed observables` do contain circular references.
Because we want to be able to automatically generate resource-locators for new pages 🙂
> Fix resource-locator generation when creating a new page

- src/Sulu/Bundle/MediaBundle/Media/FormatLoader/BaseXmlFormatLoader.php
- src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader10.php
- src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader11.php
- src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image-formats/version11.xml
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoader10Test.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoader11Test.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4449
Fix generation of inset thumbnails.
Some constants in the imagine library where changed from strings (inset, outbound)  to integer values so we need to change our xml loader to match inset / outbound to the new values.
```xml
<format key="small">
<meta>
<title lang="en">Small</title>
</meta>
<scale x="343" y="343" mode="inset"/>
</format>
```
> Fix generation of inset thumbnails

- src/Sulu/Component/Content/Compat/Block/BlockProperty.php
- src/Sulu/Component/SmartContent/ContentType.php
- src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
| Q | A
| --- | ---
This PR fix the preview for null values of tags/categories.
When you selct no tag/category the value is now null.
> Fix smart-content to allow null data

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4441 
This PR avoids setting the default type if a resource already exists. This fixes #4441.
> Do not set default type for already existing resources

- src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php
| Q | A
| --- | ---
It fixes the fresh User object comparison to the deserialized User object to make sure that they represent the same user.
Once the user is logged in, the entire User object is serialized into the session. On the next request, the User object is deserialized. Then, the value of the id property is used to re-query for a fresh User object from the database. Finally, the fresh User object is compared to the deserialized User object to make sure that they represent the same user. This is not working now because the username, password and salt are not serialized.
[Understanding serialize and how a user is saved …
> Fix fresh User object comparison to the deserialized User object

- src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/SingleMediaSelectionTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4463
In SingleMediaSelection returned content data wraped in try-catch block.
> Fix single media selection content data for deleted media

- src/Sulu/Component/Rest/Handler/DateHandler.php
| Q | A
| --- | ---
Handle DateTimeImmutable in array serialization correctly.
DateTimeImmutable is lost.
> JMS Serializer: Handle DateTimeImmutable correctly

- src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverTest.php
| Q | A
| --- | ---
| Related PRs | fixes https://github.com/sulu/sulu/pull/4492
Add webspace and portal name to template attributes.
Currently its not possible to access the portal and webspace name in twig.
> Add webspace and portal name to template attributes

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/SingleAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/tests/SingleAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/SearchStore/SearchStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/SearchStore/tests/SearchStore.test.js
| Q | A
| --- | ---
This PR adds a `options` parameter to the constructor of the `SearchStore` class. The properties of the given `options` object are included as query parameters in the requests sent by the `SearchStore`. This behaviour is analogous to the `options` parameter of the `ListStore` class and the `ResourceFormStore` class.
Furthermore, this PR add a `options` prop to the `SingleAutoComplete` container that allows to specify options that are passed to the `SearchStore` that is constructed by the `SingleAutoComplete` container. This behaviour is analogous to the `options` prop of the `SingleListOverlay` and the `MultiListOverlay`.
Because it might be useful to set some options that will be sent to the …
> Add options constructor-parameter to SearchStore

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/phpunit.xml.dist
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
| Q | A
| --- | ---
This PR fixes the ghost locale handling when you query for pages in a non-existing locale for the given webspace.
When you have 2 webspace with different locales:
* test1: de
* test2: en
And create a new custom-url for `test1` the content tree don't show any titles (user locale is en).
This PR uses the first available locale to display the titles
> Set ghost-locale to first available-locale if locale not exists in webspace

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
| Q | A
| --- | ---
This PR sets the CSS `position` property of the content section of our `Dialog` to `relative`. This is needed in order to actually hide overflow in the y direction.
Because we want to hide elements that are placed inside the `Dialog` content but would be positioned outside of the `Dialog`.
> Set position of content section of Dialog to relative to hide overflow

- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormOverlayListRouteBuilderTest.php
| Q | A
| --- | ---
| Related issues/PRs | based on #4452
Add overlaySize option to FormOverlayList and Builder.
In some cases you want to have a bigger overlay for this edit form.
~~~php
$route = (new FormOverlayListRouteBuilder($name, $path))
->setOverlaySize('large')
->getRoute();
~~~
- ~~[ ] Create a documentation PR~~
- ~~[ ] Add breaking changes to UPGRADE.md~~
>  Add overlaySize option to FormOverlayList and Builder 

- src/Sulu/Bundle/AdminBundle/Admin/Routing/Route.php
| Q | A
| --- | ---
Add setView for Admin Route object.
In some cases you just want to extend an exist view and in this case you need to allow to overwrite the `view` attribute of the Route.
~~~php
$this->routeBuilderFactory->createFormOverlayListRouteBuilder('app.locations', '/locations')
....
->getRoute()
->setView('my_custom_view');
~~~
```js
// @flow
import React, {Fragment} from 'react';
import {observer} from 'mobx-react';
import FormOverlayList from 'sulu-admin-bundle/views/FormOverlayList';
import type {ViewProps} from 'sulu-admin-bundle/containers/ViewRenderer';
import type {ElementRef} from 'react';
@observer
export default class FormOverlayListFilter extends React.Component<ViewProps> { …
```
> Add setView for Admin Route object

- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
Add autowiring for template attribute resolver service.
That you can autowire the template attribute service.
~~~php
class TestController {
public function __construct(
EngineInterface $templating,
TemplateAttributeResolverInterface $attributeResolver
) {
$this->templating = $templating;
$this->attributeResolver = $attributeResolver;
}
public function testAction()
{
return new Reponse(
$this->templating->render('test.html.twig', $this->attributeResolver->resolve([]));
);
}
}
~~~
> Add autowiring for template attribute resolver service

- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/CoreBundle/Tests/Unit/DependencyInjection/SuluCoreExtensionTest.php
| Q | A
| --- | ---
Add own parameter for the structure default type.
Currently only the snippet default type is set to a parameter this should be done for all default types so they can be used.
~~~yaml
sulu_core:
content:
structure:
default_type:
test: default_test
~~~
```bash
bin/websiteconsole debug:container --parameter sulu.content.structure.default_type.test
```
> Add own parameter for the structure default type

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/LinkCommand.js
| Q | A
| --- | ---
| Related issues/PRs | #4305 
This PR sets the title only if an actual title not being `undefined` has been added.
Because otherwise parts of the link remain, when it is added without selecting a text and it is removed afterwards.
> Avoid remains of link set without selection

- CHANGELOG.md
- src/Sulu/Component/PHPCR/PathCleanup.php
- src/Sulu/Component/PHPCR/Tests/Unit/PathCleanupTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4496
| Related issues/PRs | bug was introduced in #4313
Fix pathcleanup whitespace character problems.
Not only spaces are whitespace characters also `'` and `:` should be replaced.
Add title with `'` or `:` should be replaced correctly.
> Fix pathcleanup whitespace character problems

- src/Sulu/Component/Rest/ListBuilder/ListRestHelperInterface.php
| Q | A
| --- | ---
This PR adds the `getIds` and `getExcludedIds` method signature to the `ListRestHelperInterface `.
> Add methods to access ids and excludedIds to ListResetHelperInterface

- src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
| Q | A
| --- | ---
Fix webspace validate command by validate the correct template.
As in 2.0 the webspace templates are configured without `.html.twig` the validate command need to add this itself like it does for the page templates.
~~~bash
bin/adminconsole sulu:content:validate:webspaces
~~~
> Fix webspace validate command

- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/ExportToolbarAction.js
| Q | A
| --- | ---
| Fixed tickets | fixes none
This PR add the list-store-options to export api call.
The `routerAttributesToListStore` will be ignored b the export button.
~~~php
$this->routeBuilderFactory->createListRouteBuilder('app_tickets.list', '/tickets')
->setResourceKey('tickets')
->setListKey('tickets')
->setTabTitle('app.tickets')
->addListAdapters(['table'])
->addToolbarActions(['sulu_admin.export'])
->addRouterAttributesToListStore(['id' => 'showId'])
->setParent('app_shows.list')
->getRoute(),
~~~
> Add api options to export api call

- composer.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/symfony/symfony/pull/31108, https://github.com/symfony/symfony/issues/31152, https://github.com/symfony/symfony/pull/31156
Conflict symfony/framework-bundle 4.2.7
It will crash the current sulu state as the translation can not be set correctly.
> Conflict symfony/framework-bundle 4.2.7

- src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/TextArea.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/tests/TextArea.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/CKEditor5.test.js
| Q | A
| --- | ---
This PR makes the `TextArea` and `TextEditor` field type return undefined if they are an empty string.
Because this fixes some issue with the validation.
> Return undefined in TextArea and CKEditor5 field types when empty

- src/Sulu/Component/Content/ContentTypeInterface.php
| Q | A
| --- | ---
Set correct mixed return type for content type interface.
Its also possible to return objects or null in getContentData and getViewData.
> Set correct mixed return type for content type interface

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Command/FormatCacheCleanupCommand.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/437
Add command to media cache files which not longer exists.
In a multi server setup it can happen that not all images where deleted so we need a command to remove image formats which media does not longer exist in the database.
> Add command to media cache files which not longer exists

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/MediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/DropzoneOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/dropzoneOverlay.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/__snapshots__/MultiMediaDropzone.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/package.json
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds a button in the toolbar of the media overview, which allows to upload media files without drag and drop.
Because it improves UX.
> Add button to upload media

- .circleci/config.yml
- .eslintignore
- .flowconfig
- UPGRADE.md
- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/FocusPointOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/FocusPointOverlay.test.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/WebspaceTabs.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/tests/WebspaceTabs.test.js
| Q | A
| --- | ---
This PR introduces a priority on the `UpdateRouteHook`s.
Because this gives us more control on when to cancel the navigation, and let other hooks not be executed at all. This is required, because the `ResourceStore` was reloaded before the confirmation dialog was confirmed when the tab is changed in a dirty form. This already resulted in data loss, and a second change of the tab is not caught anymore.
> Fix accidental reload when tab is changed from dirty form

- .eslintignore
- .flowconfig
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/updateRouterAttributesFromView.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/index.js
| Q | A
| --- | ---
| Related issues/PRs | facebook/flow#6318
This PR fixes the typing for the `getDerivedRouteAttributes` function of a `View`.
Because this allows to encounter errors in this function even earlier.
> Fix types for getDerivedRouteAttributes function

- CHANGELOG.md
- src/Sulu/Component/CustomUrl/Routing/Enhancers/RedirectEnhancer.php
- src/Sulu/Component/CustomUrl/Routing/Enhancers/SeoEnhancer.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/RedirectEnhancerTest.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/SeoEnhancerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4537 
Url generation in the redirect behavior now respects the current request schema.
> CustomUrl with redirect behavior redirects to HTTP schema

- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormOverlayListRouteBuilderTest.php
| Q | A
| --- | ---
This PR is build on top of @nnatter #4452 and my #4477 overlaySize feature and extend the FormOverlayList to a option to provide resourceStoreProperties to the formStore which will be used to load the resource.
Sometimes you need to forward listStore properties also to the formStore. In my case the list is filtered by a specific dimensionId and only the dimension which is currently shown should be edit in the FormOverlayList so this property need to be forwared from the listStore to the formStore. 
EDIT: as mentioned by danrot we will forward the property directly from the resourceStore so you can have different …
> Add resourceStorePropertiesToFormStore option to FormOverlayList

- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
- src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR allows to unpublish a page, in the same way as a draft can be deleted.
Because it was already possible in Sulu 1.x.
> Allow to unpublish a page

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/SingleAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
- src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
This PR fixes a bug, which appears when a new contact is created. It is only possible to assign an organization to a contact, if also a position is chosen.
Because that should work.
> Allow to create a contact with an account but without a position

- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
| Q | A
| --- | ---
This PR add the errors array to the list view.
Can be used in ToolbarAction to propagate errors.
```
getToolbarItemConfig() {
return {
icon: 'su-upload',
label: translate('app.import_ticket_passes'),
onClick: () => this.list.errors.push('This is an error'),
type: 'button',
};
}
```
> Added errors array to list view

- .circleci/config.yml
- package.json
- src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/SmartContentQueryBuilderTest.php
- src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php
| Q | A
| --- | ---
This PR will return null for the URL on a ghost locale, because this URL does not exist.
This way the JS code knows that it has to generate an URL for ghost locales as well.
> Generate URL for ghost locales

- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap
- src/Sulu/Bundle/PreviewBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/PreviewBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds a reload button to reload the preview.
Although the situation has improved, the refresh button is still needed, e.g. because some JS which is loaded in the preview might not support changing the content while it is running.
> Add reload button for preview

- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
- src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/forms/snippet_taxonomies.xml
| Q | A
| --- | ---
| Related issues/PRs | depends on #4552
This PR adds the taxonomies tab to snippets.
Because this information should be edible.
> Add tab for snippet taxonomies

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/AbstractAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/List.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/ListOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/tests/ListOverlay.test.js
| Q | A
| --- | ---
The `ListOverlay` which is used e.g. in the `Selection` fields will show a search field now.
This overlay is also used for entity type with loads of instances, so a search is very convenient.
> Add search field in ListOverlay

- config/bundles.php
- config/routes/fos_js_routing_admin.yaml
| Q | A
| --- | ---
Adds FOSJsRoutingBundle to the bundles registration and routes configuration
sulu/sulu was missing the registration of FosJsRoutingBundle which is a new dependency of the admin area in 2.x.
> Registered FOSJsRoutingBundle in bundles.php and added a route config

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/CategoryBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/ContactBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/test_page.xml
- src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/with_snippet.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
- src/Sulu/Bundle/PersistenceBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/ResourceBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/RouteBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/SearchBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
- src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/pages/hotel_page.xml
- src/Sulu/Bundle/TagBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/simple.xml
| Q | A
| --- | ---
| Related issues/PRs | #3624 
| Documentation PR | https://github.com/sulu/sulu-docs/pull/438
Rename snippet content type.
Normalize content type names: #3624 
~~~php
<property name="snippets" type="snippet_selection" />
~~~
See UPGRADE.md
> Rename snippet content type to snippet_selection

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/plugins/ExternalLinkPlugin/ExternalLinkOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/plugins/ExternalLinkPlugin/__snapshots__/ExternalLinkOverlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/__snapshots__/CopyLocaleDialog.test.js.snap
| Q | A
| --- | ---
This PR allows to define a `mailto:` link in the `Url` component.
Because this functionality is needed in the text editor.
> Add possibility to define a mailto link

- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php
- src/Sulu/Bundle/ContactBundle/Resources/config/content.xml
- src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactAccountSelectionTest.php
| Q | A
| --- | ---
| Related issues/PRs | #3624 
| Documentation PR | https://github.com/sulu/sulu-docs/pull/439
Rename contact content type to contact_account_selection.
Normalize content type names: #3624 
~~~php
<property name="contacts" type="contact_account_selection" />
~~~
**UI Missing**
See UPGRADE.md
> Rename contact content type to contact_account_selection

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3745
Fix binary file response of html files.
A binary file response set the file in the x-sendfile header and so the content is [not editable](https://github.com/symfony/symfony/blob/v3.4.27/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L315-L335) and should not be edited by the appendanalytics listener.
~~~php
$response = new BinaryFileResponse(__DIR__ . '/test.html');
return $response;
~~~
> Fix BinaryFileResponse of html files

- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/MediaDetails.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/MediaDetails.test.js
| Q | A
| --- | ---
This PR resets the `mediaPage` route parameter to 1 each time the back button in a `MediaDetail` view is pressed.
Because previously the following scenario made problems:
1. Go to a collection
2. Change to the table view
3. Go to the second page in the table view
4. Click on the edit button on any media
5. Press the back button in the form
6. You land on the list again, but in the Masonry view and the mediaPage parameter, resulting in skipping the first few images.
> Reset page of medias to one when returning from MediaDetails view

- src/Sulu/Bundle/ContactBundle/Resources/js/index.js
| Q | A
| --- | ---
This PR removes the wrong `translate` calls for the social media names.
Because these values are taken directly from the database, and are no translation keys.
> Remove wrong call to translate for non-translatable social media services

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Command/WebspaceCopyCommand.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/WebspaceCopyCommandTest.php
- src/Sulu/Bundle/ContentBundle/Tests/app/Resources/pages/teasers.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #4539
Process teaser_selection content type.
> Fix copying of teaser selection in WebspaceCopyCommand

- .travis.yml
- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormRouteBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormRouteBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ResourceTabRouteBuilderTest.php
- src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
| Q | A
| --- | ---
This PR introduces a new route option on the form route called `routerAttributesToBackRoute`, which works exactly as the `routerAttributesToEditRoute` parameter, with the only exception that the passed router attribute are passed when the form navigates to the passed back route.
This allows to add the `webspace` in the page form whenever the back button is clicked. This is necessary, because in certain situations the webspace was missing when clicking the back button.
The following steps show a way to reproduce this problem:
1. Make a reload on a page form
2. Click on the back button
3. The webspace select …
> Fix missing webspace and active item on back navigation when page form was directly loaded

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Section.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/types.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignments.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignments.test.js.snap
| Q | A
| --- | ---
This PR fixes the width of the `ResourceMultiSelect` in the `RoleAssignment` and also fixes the corresponding flow types, which allowed the wrong configuration. It also sorts the roles from the `ResourceMultiSelect` by name.
Because it does not look good if the select takes the whole width, and it is hard to find a role if the roles are "randomly" sorted.
> Fix width of role select size and order it by name

- src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
- src/Sulu/Bundle/SnippetBundle/Snippet/SnippetResolver.php
- src/Sulu/Bundle/SnippetBundle/Snippet/SnippetResolverInterface.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetContentTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/SnippetResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverInterface.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php
- src/Sulu/Component/Content/Compat/PageInterface.php
- src/Sulu/Component/Content/Compat/Structure/PageBridge.php
- src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Tests/Unit/Compat/Structure/StructureBridgeTest.php
| Q | A
| --- | ---
| Fixed tickets | enhances #4564 
| Documentation PR | sulu/sulu-docs#440
This PR adds the possibility to load the extension data from snippets in the `snippet_selection` content type.
Because this information might be useful.
> Resolve taxonomies in snippet_selection ContentType

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverTest.php
| Q | A
| --- | ---
Fix language switcher for static routes.
The sulu_content_path does prefix 
Webspace Setting:
```xml
<urls>
<url>{host}/{localization}</url>
</urls>
```
Example Route:
```yaml
test_route:
path:         /{_locale}/test
controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
defaults:
template: test.html.twig
methods: GET
```
Twig:
```twig
{{- include 'SuluWebsiteBundle:Extension:seo.html.twig' with {
seo: extension.seo|default([]),
content: content|default([]),
urls: urls|default([]),
shadowBaseLocale: shadowBaseLocale|default(),
defaultLocale: request.defaultLocale|default('en')
} -}}
{# …
```
> Fix language switcher for static routes

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4568
Check for the existence of the requested template and only throw then a 406 error and not always when a InvalidArgumentException happens.
Currently this 406 catch hide other InvalidArgumentException which should not be converted to 406 status code.
E.g. use a not exist content type in your template.
> Fix false 406 status code for controller InvalidArgumentExceptions

- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
- src/Sulu/Bundle/SnippetBundle/SuluSnippetBundle.php
- src/Sulu/Component/DocumentManager/EventDispatcher/DebugEventDispatcher.php
| Q | A
| --- | ---
Change the priority of the SnippetAreaCompilerPass to have access to the translator service.
The priority of the translator servcie has change in https://github.com/symfony/symfony/commit/31d7a09bf5c423ad2003d6863d7372e49a195af1#diff-687bdbb38a4dc672ca2a79f23e764892R110
~~~php
bin/console cache:clear
~~~
> Fix symfony 4.3 compatibility by change priority of SnippetAreaCompilerPass

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
| Q | A
| --- | ---
This PR allows to click the entire search button in the list.
Because previously it was necessary to click exactly the icon, which is not good for usability.
> Make click area of search button in List bigger

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
- src/Sulu/Bundle/PageBundle/Content/PageSelectionContainer.php
- src/Sulu/Bundle/PageBundle/Controller/NodeController.php
- src/Sulu/Bundle/PageBundle/Controller/PageController.php
- src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerFieldsTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/SmartContentQueryBuilderTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Content/PageSelectionContainerTest.php
- src/Sulu/Bundle/SnippetBundle/Content/SnippetDataProvider.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetDataProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/SmartContent/ContentDataItem.php
- src/Sulu/Component/Content/SmartContent/PageDataProvider.php
- src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4212
This PR lets the `ListStore` reload without the passed IDs, if the request with the IDs fails.
Because currently the user just sees a loader if the page which was last selected according to his user settings was deleted.
The `NodeController` returns now the correct results instead of being modified in the `PageController`. We should merge these two to a single `PageController` at some point.
> Fix failing ColumnList after deleting the last selected page

- src/Sulu/Bundle/AdminBundle/Admin/NavigationRegistry.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/Tabs.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/NavigationRegistryTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ResourceTabRouteBuilderTest.php
- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
- src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/account_details.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/lists/account_contacts.xml
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
| Q | A
| --- | ---
This PR adds a list to show all the contacts assigned to an account and allow to assign a main contact to the account using an auto complete field.
Because it already was possible to do that in the old Admin.
> List and assign contacts to accounts

- src/Sulu/Bundle/RouteBundle/SuluRouteBundle.php
| Q | A
| --- | ---
| Related issues/PRs | #4583 
This PR fixes a bug occuring in combination with the SuluArticleBundle and Symfony > 4.3.
Because we would still like to use the translator service in the router bundle.
> Fix usage of translator in SuluRouteBundle

- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Twig/SnippetTwigExtensionTest.php
- src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtension.php
- src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtensionInterface.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverInterface.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4573
Fix loading of extension data in parameter resolver for pages.
The parameter resolver did return excerpt in the past.
Not sure was there a bc break implemented in #4573 with the structureResolver?
> Add loadExcerpt to snippet twig extension  and fix loadExcerpt for pages

- config/templates/pages/default.xml
- config/templates/pages/homepage.xml
- templates/templates/pages/default.html.twig
- templates/templates/pages/homepage.html.twig
| Q | A
| --- | ---
This PR removes the deprecated highlight section and makes the two templates provided in this repo differ a bit.
While trying to write some E2E tests I recognized that the highlight section is still in these template, and they break the design. Also, both template were exactly the same, which makes not a lot of sense, and doesn't allow to easily test if the correct template is shown.
> Remove deprecated highlight section and make default and homepage template differ

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/Matrix.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/Row.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/matrix.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/row.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/tests/__snapshots__/Matrix.test.js.snap
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Permissions/tests/__snapshots__/PermissionMatrix.test.js.snap
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Permissions/tests/__snapshots__/Permissions.test.js.snap
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignment.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignments.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/roleAssignment.scss
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/roleAssignments.scss
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/RoleAssignment.test.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignment.test.js.snap
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignments.test.js.snap
| Q | A
| --- | ---
This PR replaces the divs in components that should actually be tables.
Because tables can and should still be used for table like representations.
> Replace divs with proper tables in Permission components

- src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3990
Fix sulu document init routes generation.
When you did forget to run sulu:document:init the route nodes where never created and it was hard to fix this manually.
1. Run sulu document init
2. Add a new language to the webspace
3. Go into the webspace and save the homepage in the new language
4. Try to create a page in the new language
5. Run `sulu:document:init` (should create new route node (this wasn't the case before))
6. Now you should be able to create new pages
--
>  Fix sulu document init routes generation 

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
| Q | A
| --- | ---
This PR writes the list store settings to the user settings before the actual change is written on the observable (that means it is done using an `intercept` call instead of an `autorun`).
Because otherwise this setting will be reset by the router again.
This can be tested when clicking on a navigation item. If the default limit is selected, then there are two entries in the history. That means that e.g. clicking the history back button of the browser had no effect unless changing the parameters of the current URL.
> Fix double route redirects and polluted history when clicking on navigation item showing a list

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds the handling if a page or snippet has been edited in the mean time. Currently the user just got an error if another user has changed the page since he opened it, but had no option to override the changes with his current ones.
Because this was already possible in the old UI.
> Handle conflict if other user has changed snippet or page in the mean time

- src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201905071542.php
| Q | A
| --- | ---
| Fixed tickets | fixes
Check in the migration for teaser that the property which is changed is an array.
Else properties like:
```
"i18n:en-homeBlocks-length"
5
```
will error with:
> In Version201905071542.php line 58:
> Warning: array_key_exists() expects parameter 2 to be array, int given
~~~php
bin/adminconsole phpcr:migrations:migrate
~~~
> Fix migration of teaser with other properties

- UPGRADE.md
- assets/admin/index.js
- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkPlugin.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/InternalLinkPlugin.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/ResourceLocatorHistory.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/ResourceLocatorHistory.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/PageBundle/Controller/PageResourcelocatorController.php
- src/Sulu/Bundle/PageBundle/Repository/ResourceLocatorRepository.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php
- src/Sulu/Bundle/RouteBundle/Controller/RouteController.php
- src/Sulu/Bundle/RouteBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/RouteBundle/DependencyInjection/SuluRouteExtension.php
- src/Sulu/Bundle/RouteBundle/Entity/BaseRoute.php
- src/Sulu/Bundle/RouteBundle/Resources/js/index.js
- src/Sulu/Bundle/RouteBundle/Resources/js/package.json
- src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/RouteBundle/Tests/Application/config/test_config.yml
- src/Sulu/Bundle/RouteBundle/Tests/Functional/Controller/RouteControllerTest.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
| Q | A
| --- | ---
This PR adds the `route` FieldType, which is very similar to the `resource_locator` field type. However, the `resource_locator` FieldType is only working for pages. Both make use of the abstract `ResourceLocator` FieldType, which had to be adapted in order to work for both cases.
Because the `route` FieldType is used in the SuluArticleBundle, which has been updated to Sulu 2.0 in sulu/SuluArticleBundle#377.
> Add separate FieldType for route paths

- assets/admin/index.js
- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
- src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
- src/Sulu/Bundle/CategoryBundle/Controller/KeywordController.php
- src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
- src/Sulu/Bundle/CategoryBundle/Resources/config/forms/category_keywords.xml
- src/Sulu/Bundle/CategoryBundle/Resources/config/lists/category_keywords.xml
- src/Sulu/Bundle/CategoryBundle/Resources/js/containers/List/fieldTransformers/CategoryKeywordsMultipleUsageTransformer.js
- src/Sulu/Bundle/CategoryBundle/Resources/js/containers/List/tests/fieldTransformers/CategoryKeywordsMultipleUsageTransformer.test.js
- src/Sulu/Bundle/CategoryBundle/Resources/js/index.js
- src/Sulu/Bundle/CategoryBundle/Resources/js/package.json
- src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/KeywordControllerTest.php
| Q | A
| --- | ---
This PR adds a new tab, which allows to add/delete/edit keywords attached to a category.
Because this feature existed already in the old UI.
> Add separate tab for handling category keywords

- src/Sulu/Bundle/PageBundle/Resources/config/lists/pages.xml
| Q | A
| --- | ---
This PR prevents the page id from being displayed by default.
Because this value is not really useful.
> Adjust listed field in page tree table view to avoid showing id

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/MediaDetails.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/MediaDetails.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/MediaFormats.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/tests/MediaFormats.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/MediaHistory.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/tests/MediaHistory.test.js
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
| Q | A
| --- | ---
This PR uses `router.navigate` instead of `resourceStore.setLocale`.
Because this way the dirty check is working correctly. Previously the dirty check was triggered but still the locale change was immediately done. That meant that the navigation could not be canceled.
Removed the `setLocale` resource store method, since this was the only use case for it.
> Use router navigate to change locale in order to avoid ignoring dirty check

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/button.scss
| Q | A
| --- | ---
This title avoid line-breaks in the toolbar buttons.
Because if you had a long title for a template, then the dropdown in the toolbar of the Page form looked strange.
> Avoid linebreak with long template titles in toolbar dropdown

- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
| Q | A
| --- | ---
With this change in every project the admin base template is overridable and can be extended with project custom options.
> Using alias so that every project can override template

- src/Sulu/Component/Content/SmartContent/PageDataProvider.php
- src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
| Q | A
| --- | ---
This PR fixes smart-content without dataSource and jackrabbit.
> Fix smart-content with empty data-source and jackrabbit

- src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/searchField.scss
| Q | A
| --- | ---
Fix search button dropdown in firefox.
Before:
After:
> Fix search button dropdown in firefox

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php
| Q | A
| --- | ---
This PR uses the correct language to load resp. redirect to the correct page.
Because currently it is always referring to the english version of a page.
> Fix choosing correct language for custom url

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
| Q | A
| --- | ---
This PR fixes the order of the hooks being executed when a routing takes place.
Because after the first time switching the webspace in the `WebspaceTabs` switching the webspace does not work anymore.
> Fix switching between webspaces

- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignment.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/roleAssignment.scss
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignment.test.js.snap
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignments.test.js.snap
| Q | A
| --- | ---
This PR fixes the with of the last column in the `RoleAssignment` table.
Because then it stops changing its width when the content of the localization select is changed.
> Fix jumping width of RoleAssignment

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/TemplateToolbarAction.test.js
- src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
- src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
- src/Sulu/Bundle/SecurityBundle/Resources/js/index.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/tests/toolbarActions/EnableUserToolbarAction.test.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/tests/toolbarActions/LockUserToolbarAction.test.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/toolbarActions/LockUserToolbarAction.js
- src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
- src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
| Q | A
| --- | ---
Builds upon: #4641 
This PR adds a toggler toolbar-action that allows to lock and unlock the current user to the Permissions tab of the Contact form.
Because we do not want to manually modify the database every time we need to lock a user 😉
> Add toolbar-action for locking users to permission-tab of contact form

- README.md
| Q | A
| --- | ---
Update readme badge to show latest pre release tag.
Should show 2.0.0-RC1
[![GitHub tag (latest pre-release)](https://img.shields.io/github/tag-pre/sulu/sulu.svg)](https://github.com/sulu/sulu/releases)
and not 2.0.0-alpha6
[![GitHub tag (latest by date)](https://img.shields.io/github/tag-date/sulu/sulu.svg)](https://github.com/sulu/sulu/releases)
> Update readme badge to show latest pre release tag

- src/Sulu/Bundle/PageBundle/Controller/SmartContentItemController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/SmartContentQueryBuilderTest.php
- src/Sulu/Component/Content/SmartContent/QueryBuilder.php
| Q | A
| --- | ---
Fix for the sorting function of the smart-content type. The `QueryBuilder` for smart-content anticipated a `sortBy` array, but from the website-view only a `string` was given. Thus the orderBy defaulted to `sulu:order`.
Previously the sorting function was only working in the admin view but not on the website.
> Fix smart-content sorting

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/UserManager/UserManagerTest.php
- src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4447 
This PR makes the `getFullNameByUserId` method of the `UserManager` not fail anymore, if a not existing User ID is given.
Because this function was called when the CustomURLs for the datagrid are loaded. That means that if a user has created a Custom URL, and this user was deleted later, then the response for the list returned a 500 error code.
> Fix loading custom url list if creator has been deleted

- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/symfony/symfony/pull/31620
This PR removes the prepended configuration for sessions.
Because it was not working as intended anymore, and caused an error since Symfony 4.3.3 because of https://github.com/symfony/symfony/pull/31620.
> Fix wrong session configuration

- src/Sulu/Bundle/TestBundle/Testing/KernelTestCase.php
| Q | A
| --- | ---
Set the default message to empty string instead of null in assertHttpStatusCode.
The message need to be a string in phpunit >=7 and can't be null anymore.
> Fix assertHttpStatusCode phpunit 7 compatibility

- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/multiItemSelection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/variables.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/field.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/multiSelection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContentItem.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/smartContentItem.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/SmartContentItem.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/multiMediaSelection.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/__snapshots__/MultiMediaSelection.test.js.snap
| Q | A
| --- | ---
This PR fixes the following styling issues:
* The width of the form was determined by its content, which meant that if something was very long, the width of the preview got smaller
* The texts in the components using the `MultiItemSelection` components are now cropped.
Because these issues lead to strange displaying when long titles were listed in the `MultiItemSelection`.
> Correct styling of MultiItemSelection

- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/SecurityBundle/Controller/PermissionController.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/Controller/PermissionControllerTest.php
| Q | A
| --- | ---
This PR checks the permission for changing the security before saving the permission tab.
Because if a user is missing the security permission, they should not be allowed to save the permission tab.
> Check permissions before saving information from permission tab

- src/Sulu/Component/Rest/Exception/EntityNotFoundException.php
- src/Sulu/Component/Webspace/Manager/WebspaceCollection.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluRedirectBundle/pull/32
Allow id in EntityNotFoundException to be a string.
For phpstan static analyizer in RedirectBundle the id is a uuid and so a string.
> Fix some static types issues with EntityNotFoundException and WebspaceManager

- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Documentation PR |
This PR detachs the file and file version in the delete method of the media manager. 
Currently an error occurs in the form bundle if the delete method of the media manager is called, followed by another remove call to the entity manager with another entity. The error message says that _a new entity was found through the relationship Sulu\Bundle\MediaBundle\Entity\File#media that was not configured to cascade persist operations for entity_.
> Detach file and file version in delete of media manager

- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Resources/config/forms/page_settings.xml
- src/Sulu/Bundle/PageBundle/Resources/config/services.xml
- src/Sulu/Bundle/PageBundle/Resources/js/index.js
- src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
| Q | A
| --- | ---
This PR removes the infinite loader under the changelog line in the settings tab of the pages, when the versioning is deactivated.
Because loaders are confusing and power-consuming if they are infinite.
> Remove loader in settings tab when versioning is deactivated

- src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php
- src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php
- src/Sulu/Bundle/ContactBundle/Controller/ContactMediaController.php
- src/Sulu/Bundle/ResourceBundle/Controller/FilterController.php
| Q | A
| --- | ---
This PR removes all the `fieldsAction`s in the system, which have been necessary for the old datagrid in 1.x, but are obsolet now.
Because that's basically dead code.
> Remove obsolete fieldsActions

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4628
Allow mapping between form properties within a block element and nested JSON data.
Previously it was not possible to map data from a nested JSON object to a form property within a block element.
> Fix nested properties within block

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/ResourceMultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/tests/ResourceMultiSelect.test.js
| Q | A
| --- | ---
This PR add posibility to change api-options and resource-key in resource-multi-select.
> Add posibility to change api-options and resource-key in resource-multi-select

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
| Q | A
| --- | ---
This PR replaces the `ResourceLocator` field with a simple '/' on the homepage.
Because the URL of the homepage should not be editable, since it should always be the entry point of the website.
> Disallow editing of resource locator on homepage

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
| Q | A
| --- | ---
This PR splits the URL used by the `ResourceLocator` component into pieces also after updating the URL.
Because the old behavior resulted in a strange behavior, when a page is created as child of another page (so that the leaf resourcelocator would generate a URL with a slash).
> Fix generation of URL for child pages

- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
| Q | A
| --- | ---
This PR moves the edit form router for the contacts after the contacts add form.
Because if the edit form is listed first, then the `/contacts/add` route will be recognized as edit route, with "add" being the id. This results in a request being sent to the server with "add" as an id, which will fail.
> Fix rendering contact add form

- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/mediaCard.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardAdapter.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardOverviewAdapter.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/package.json
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
| Q | A
| --- | ---
This PR adds a loader while the image is loading in the `MediaCard` component.
Because in some environments it might take a while until the image is readily converted to the desired format, and in the mean time it looks like an error.
> Add loader to MediaCard while image is loading

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/columnList.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/ColumnListAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/adapters/MediaCardAdapter.js
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Resources/js/index.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/PageList.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/__snapshots__/PageList.test.js.snap
| Q | A
| --- | ---
This PR hides the actions for the first column in the ColumnList containing the Homepage.
Because it should not be possible to delete or add a homepage.
> Hide actions for the Homepage Column in the ColumnList

- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/RolePermissions.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/tests/RolePermissions.test.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/tests/__snapshots__/RolePermissions.test.js.snap
- src/Sulu/Bundle/SecurityBundle/Resources/js/index.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/stores/SecurityContextStore/SecurityContextStore.js
- src/Sulu/Bundle/SecurityBundle/Resources/js/types.js
- src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
| Q | A
| --- | ---
This PR uses the permissions from the security context for the permissions if no permission on the object has been set. It also fixes the bug causing wrong behavior when a role has been created after object permission has been set.
> Use permissions from security context if no object security has been set

- src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
| Q | A
| --- | ---
| Related issues/PRs | #4579
Fix controller reference validation with FQCN.
Its recommended way to reference controllers and the bundle syntax is deprecated now.
~~~xml
<controller>Sulu\Bundle\WebsiteBundle\Controller\DefaultController::indexAction</controller>
~~~
> Fix controller validation definition as fcqn

- src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
| Q | A
| --- | ---
Removes the `?string` type hint in the `ValidateWebspaceCommand.php` file to remove a warning caused by PHP 7.3.
The warning happens only after the installation of the sulu/theme-bundle: https://github.com/sulu/SuluThemeBundle/pull/11
```
In ValidateWebspacesCommand.php line 74:
Argument 7 passed to Sulu\Bundle\PageBundle\Command\ValidateWebspacesComman
d::__construct() must be of the type string or null, object given, called i
n /Users/thomas.duenser/Development/websites/boneco.lo/sulu/var/cache/admin
/dev/ContainerCLYMCtY/getConsole_Command_PublicAlias_SuluPage_Command_Valid
ateWebspacesService.php on line 12
```
> Fixed construct type for activeTheme in validate webspace command

- UPGRADE.md
- appveyor.yml
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseRole.orm.xml
| Q | A
| --- | ---
| Fixed tickets | https://github.com/sulu/sulu/issues/4658
This PR renames the `security` column of the `se_roles` table to `securitySystem` to make Sulu compatible with MySQL 8.0.
Because `SYSTEM` is a keyword since MySQL 8.0.3. See: https://dev.mysql.com/doc/refman/8.0/en/keywords.html
> Rename security column of se_roles table to securitySystem for MySQL 8.0 compatibility

- src/Sulu/Bundle/ContentBundle/Resources/config/services.xml
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
- src/Sulu/Component/PHPCR/PathCleanup.php
| Q | A
| --- | ---
This PR makes the `ContentRepository` return an empty array only if no permissions at all are set on the corresponding node. In case some permissions are set, empty arrays or missing information for a role will be interpreted as having no permissions at all.
Because an empty array will be interpreted as having all permissions in our security system.
That this behavior is not correct can be tested in the following way:
1. Create a role without the security permission for a webspace
2. Create a page in that webspace
3. Remove all permissions from the role of step 1
4. See that the page has an edit icon in …
> Fix permissions in page list for roles without any permission

- src/Sulu/Bundle/MediaBundle/EventListener/MediaAudienceTargetingSubscriber.php
- src/Sulu/Bundle/MediaBundle/Resources/config/audience_targeting.xml
| Q | A
| --- | ---
This PR adjusts the `MediaAudienceTargetingSubscriber` to set the `targetEntity` of the `targetGroups` association of the `FileVersion` to the configured `TargetGroup` class.
Setting the `targetEntity` of the association to `TargetGroupInterface` will cause the following error on `bin/console doctrine:schema:validate`:
```
The entity-class Sulu\Bundle\MediaBundle\Entity\FileVersion mapping is invalid:
* The target entity 'Sulu\Bundle\AudienceTargetingBundle\Entity\TargetGroupInterface' specified on Sulu\Bundle\MediaBundle\Entity\FileVersion#targetGroups is unknown or not an entity.
```
> Fix target entity of target-group association of FileVersion

- src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/SingleMediaSelectionTest.php
| Q | A
| --- | ---
Implemented `getViewData` for the single media selection content type similar to the media selection content type.
To make view data like the display options available.
> Add view data for the single media selection content type

- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationItem.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
| Q | A
| --- | ---
Add uuid property to contentmapper besides the id.
Avoid twig developers to change all twig template which access uuid so introduce a bc layer with uuid.
Introduced in: https://github.com/sulu/sulu/pull/4550/files#diff-2a74d79cea8c966c3ad6a835206c6c3bL751
- smart content
- navigation twig extension
- breadcrumb return uuid
- page return uuid
> Avoid bc break in twig templates by provide uuid and id properties for pages

- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
| Q | A
| --- | ---
This PR adjusts `Initializer` javascript class to prevent unnecessary requests if no user is logged in.
To prevent unnecessary 401 responses that will reset cached Basic Authentication credentials.
Without this change, if the Sulu admin runs behind a webserver with enabled Basic Authentication, the user must provide Basic Authentication credentials **two times** before he is able to log in with his sulu credentials.
Right now, the following happens if the Sulu admin runs behind a webserver with enabled Basic Authentication:
- The browser will ask for Basic Authentication credentials on the initial `admin/` request and cache the given credentials
- The `Initializer` dispatches the …
> Prevent unnecessary config request if user is not logged in

- src/Sulu/Bundle/AudienceTargetingBundle/EventListener/AudienceTargetingCacheListener.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/AudienceTargetingCacheListenerTest.php
| Q | A
| --- | ---
This PR adjusts the `AudienceTargetingCacheListener` to catch `NotFoundHttpException`s  that may happen during the `targetGroupRequest`. 
Because in the admin-context there is no route configured for the `/_sulu_target_group` url. Furthermore, the `AudienceTargetingCacheListener` is called on every `ConsoleEvents::TERMINATE` event. 
Therefore, right now, the `targetGroupRequest` will throw an `NotFoundHttpException` at the end of every command that is executed in the admin-context in the prod-environment.
> Catch NotFoundHttpException in the AudienceTargetingCacheListener

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ItemButton.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/ColumnListAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
- src/Sulu/Bundle/PageBundle/Controller/NodeController.php
- src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
- src/Sulu/Bundle/PageBundle/Repository/NodeRepositoryInterface.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerFieldsTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
| Q | A
| --- | ---
This PR hides the edit button for pages in the column list if the view permission is missing.
Because if the permission is missing the API won't return any information, leading to an error.
> Hide buttons in column list if view permissions for pages is missing

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
- src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/pageList.scss
| Q | A
| --- | ---
This PR adds some more flexbox css statements.
Because without them the `PageList´ component is not shown in Safari.
> Fix PageList in Safari

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/listOverlay.scss
| Q | A
| --- | ---
| Related issues/PRs | #4710
While fixing the column list for safari in #4710 another regression was introduced. The lists for analytics and custom URLs are currently always scrolling, even if the lists are empty, and there is just empty space.
This PR fixes this issue.
Because if there is nothing to see, the user should not be able to scroll.
> Fix height of list under WebspaceTabs

- src/Sulu/Bundle/PersistenceBundle/DependencyInjection/PersistenceExtensionTrait.php
| Q | A
| --- | ---
| Related issues/PRs | built upon #4697
This PR makes all repositories lazy services.
This is a part of the problem that doctrine tries to connect to the database on `cache:warmup`.
> Make repositories lazy

- src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/webspaceTabs.scss
| Q | A
| --- | ---
| Related issues/PRs | probably #4710 
This PR makes the HTML container for the `WebspaceSelect` take only as much width as it needs.
Because the container component lies over the `AdapterSwitch` of the `List`, making it impossible to switch to the tree view.
> Make AdapterSwitch in PageList clickable

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR makes the `List` component remember its last selected `Adapter`.
Because it is more comfortable for the user.
> Remember last selected Adapter

- src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
- src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/blocks.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
| Q | A
| --- | ---
This PR fixes the transformation of the `minOccurs` and `maxOccurs` properties from the XML files.
Because it seems like for quite a while the `minOccurs` and `maxOccurs` properties in the form XML have no impact on the frontend.
~~~xml
<block name="blocks" default-type="editor" minOccurs="1" maxOccurs="2">
<types>
<type name="editor">
<properties>
<property name="editor" type="text_editor" />
</properties>
</type>
</types>
</block>
~~~
> Fix missing occurs properties in forms

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
- src/Sulu/Bundle/PageBundle/Controller/NodeController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
| Q | A
| --- | ---
This PR will allow to delete pages which are linked to other pages. This does currently not work, because the server returns a 409 response, which is not handled in our application.
Because it should not fail as it does now.
> Delete page which is linked on another page

- .gitignore
- UPGRADE.md
- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
- src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
- src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheInterface.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManagerInterface.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImageConverterInterface.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/LocalFormatCacheTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs |  #3729 ~~#1139 #595~~
Implements several bc breaks in the storage and image format services and interfaces so that in the future the following features can be implemented without breaking the interfaces:
- ~~ExternalStorage: can be implemented using flysystem~~ see #4264
- Support WebP: every image should be possible be requested in other formats
~~It allow to create later a FlysystemStorage based on the ExternalStorageInterface.~~ see #4264
It allow to create later that image formats are outputed in other formats `50x50.webp`
Upload an image over the UI it should be converted still correctly.
You can change the extension in the url so you will get another …
> Add support for multi image format support jpg, png, webp

- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/FormRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/ListRouteBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/PreviewFormRouteBuilderInterface.php
| Q | A
| --- | ---
This PR fixes the PHPDoc of `Routebuilder::addToolbarActions`
> Fix phpdoc of 'addToolbarActions' methods

- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Fix loading of routes_admin.yaml and routes_website.yaml.
They should be loaded when a specific context is active.
> Fix loading of routes_admin.yaml and routes_website.yaml

- src/Sulu/Bundle/AdminBundle/Admin/Routing/PreviewFormRouteBuilder.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/index.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/PreviewFormRouteBuilderTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PreviewBundle/Admin/PreviewAdmin.php
- src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/index.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/package.json
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
| Q | A
| --- | ---
This PR adds two more selects in the preview toolbar, in order to change the webspace and target group.
Because it was already possible in the old UI.
> Add webspace and target group selection to preview

- src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
| Q | A
| --- | ---
Fix container build with unused media environment parameters
Sometimes when you use S3 storage but want to run it local under `prod` environment you want to use local storage. Currently this ends up with following error:
>   Environment variables "S3_KEY", "S3_SECRET", "S3_REGION", "S3_BUCKET_NAME", "S3_ENDPOINT" are never used. Please, check your container's configuration.
~~~yaml
sulu_media:
storage: '%env(SULU_MEDIA_STORAGE)%'
storages:
s3:
key: '%env(S3_KEY)%'
secret: '%env(S3_SECRET)%'
region: '%env(S3_REGION)%'
bucket_name: '%env(S3_BUCKET_NAME)%'
endpoint: '%env(S3_ENDPOINT)%'
~~~
```.env …
```
> Fix container build with unused media environment parameters

- UPGRADE.md
| Q | A
| --- | ---
Fix link in upgrade for skeleton
2.0.0-RC2 was in sulu-minimal repository and the new tag in sulu/skeleton so this link need a fix commit id and should show to the new repository.
> Fix link in upgrade for skeleton

- composer.json
- src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateRoleCommandTest.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateUserCommandTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4758
Upgrade DoctrineFixturesBundle to newest verison
To avoid outdated dependencies in our dependency tree.
~~~xml
<service id="sulu_media.fixtures.media_types" class="Sulu\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaTypes">
<tag name="doctrine.fixture.orm"/>
</service>
~~~
> Upgrade DoctrineFixturesBundle to newest verison

- src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
| Q | A
| --- | ---
Fix route for account contacts list in organization view.
Because the route was wrongly configured and the listview didn't list the added people for the organization.
> Fix account contacts route

- src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4662
Check Preview token and generate one if not exist.
First I wanted to remove the whole preview cache but there is not only the HTML cached also the loading of the provided object I think. So currently the best to avoid a central store is to check for exist of a token and else generate a new one.
> Check Preview token and generate one if not exist

- UPGRADE.md
- src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/cache-lifetime-enhancer.xml
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
This PR adjusts our default `WebsiteController` to extend the new `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` class instead of the deprecated `Symfony\Bundle\FrameworkBundle\Controller\Controller` class.
This means that we need to configure the controller as a service from now on.
Because the `Symfony\Bundle\FrameworkBundle\Controller\Controller` class is deprecated and will be removed in the future.
* `WebsiteController` extends `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` now
> Extend WebsiteController from AbstractController instead of deprecated Controller class

- src/Sulu/Bundle/MediaBundle/Controller/MediaRedirectController.php
- src/Sulu/Bundle/MediaBundle/Resources/config/routing.yml
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/SnippetBundle/Controller/LanguageController.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/routing_api.yml
- src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
- src/Sulu/Bundle/WebsiteBundle/Controller/CacheController.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/routing.yml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | Builds upon https://github.com/sulu/sulu/pull/4762
This PR refactors multiple controllers to use constructor injection instead of extending the deprecated `Symfony\Bundle\FrameworkBundle\Controller\Controller` class.
Because the `Symfony\Bundle\FrameworkBundle\Controller\Controller` class is deprecated and constructor injection is the preferred method for injecting dependencies now.
> Refactor deprecated controllers to use constructor injection for its dependencies

- .travis.yml
- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/routing_admin.yml
- src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
- src/Sulu/Bundle/SecurityBundle/Controller/ContextsController.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/routing.yml
- src/Sulu/Bundle/SecurityBundle/Resources/config/routing_api.yml
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ProfileControllerTest.php
| Q | A
| --- | ---
Add rest routes to api endpoint
Rest endpoints should be all under `/admin/api` and the current definition in the `routing.yml` website does not work for older symfony version without the name_prefix and break currently when the container is build thats why in the travis ci I added the container build for both contexts.
> Add profile and security contexts rest routes to api endpoint

- src/Sulu/Component/Rest/AbstractRestController.php
- src/Sulu/Component/Rest/RestControllerTrait.php
| Q | A
| --- | ---
Fix deprecated RestController viewHandler.
The Trait is included by the RestController extends itself included it in the trait overwrite the methods / variables of the other trait and so in this class the viewHandler is not set and will currently error when a controller is extending the old RestController.
> Fix deprecated RestController viewHandler

- UPGRADE.md
- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | related to #188
Make webspace manager environment variable in functions optional.
Avoid that the developer needs to inject the current environment as services should not depend on environments.
> Make webspace manager environment variable optional

- src/Sulu/Bundle/CoreBundle/Resources/config/serializer.xml
- src/Sulu/Component/Serializer/ArraySerializer.php
| Q | A
| --- | ---
Make array serializer service public.
At some places user want to get the array serializer over the container e.g. SuluArticleBundle https://github.com/sulu/SuluArticleBundle/blob/40bc58a247e86a1fa1a54ad1fca1d07425046bba/Controller/WebsiteArticleController.php#L127-L129.
> Make array serializer service public

- src/Sulu/Component/Rest/Listing/ListQueryBuilder.php
| Q | A
| --- | ---
This PR removes the wrong `count()` check and simplifies it. There is no need to check the values when count() === 0.
The previous check was not correct and can be simplified.
> Simplify the count() check

- src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
This PR reuses the `$navigation` variable to remove some duplicate code.
The code can be reused as the result of `getNavigation()`is already stored.
> Reuse the $navigation variable

- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/RatioNormalizer.js
| Q | A
| --- | ---
This PR removes the initial `width` value.
The initial value `data.width` is never used.
> Remove the unused width value

- .travis.yml
- composer.json
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaWebsiteControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | symfony/symfony#33487
This PR fixes some regressions that were introduced by Symfony.
Because the tests were failing.
> Fix symfony session regression

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/ResourceLocatorHistory.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/ResourceLocatorHistory.test.js
- src/Sulu/Bundle/PageBundle/Repository/ResourceLocatorRepository.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php
| Q | A
| --- | ---
This PR fixes the history button of the custom urls.
Because the history url was always shown as empty.
Yes, and not totally sure if we should do them, or already start having multiple paths in our code. BC breaks are in the `ResourceLocatorHistory` JS component (using the `resourcelocator` field instead of `path`), and in the `PageResourcelocatorController` (returns a `resourcelocator` field instead of `path`).
> Show history URL for custom urls

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelectionOverlay/SingleMediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelectionOverlay/tests/SingleMediaSelectionOverlay.test.js
| Q | A
| --- | ---
This PR adds the possibility to restrict the selectable media types in a `SingleMediaSelection`.
Because this was already possible in the old UI.
> Add possibility to restrict SingleMediaSelection by type

- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
| Q | A
| --- | ---
Add computed method to get locales from the route and props.
Because the parent locales were not correctly inherited from the list view.
$formOverlayListViewBuilder = new FormOverlayListViewBuilder(static::LIST_VIEW, '/automation');
$formOverlayListViewBuilder->setResourceKey(Task::RESOURCE_KEY)
->setListKey(Task::RESOURCE_KEY)
->setFormKey('task_details')
->setTabTitle('sulu_automation.automation')
->addToolbarActions($listToolbarActions)
->addListAdapters(['table'])
->setTabOrder(4096)
->addRouterAttributesToFormRequest(['id' => 'entity-id']) …
> Add computed locales to list view

- src/Sulu/Bundle/TestBundle/Testing/ContainerTrait.php
- src/Sulu/Bundle/TestBundle/Testing/PhpCrInitTrait.php
| Q | A
| --- | ---
The container accidently resonses sometimes the real container instead of test container because symfony does not reset `static::$kernel` to null after 
The correct test container is again available and initPhpCr does not error if a WebtestCase is run as first test.
Most of the `ContainerTrait` could be removed because of the Symfony 4.3 upgrade.
> Fix getContainer and initPhpCr for tests

- src/Sulu/Bundle/AdminBundle/Exception/ViewNotFoundException.php
| Q | A
| --- | ---
Fix exception message in ViewNotFoundException.
Route where renamed to View and so the exception message does not make any sense now.
> Fix exception message in ViewNotFoundException

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/Dialog.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/GhostDialog.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/DeleteToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
- src/Sulu/Bundle/PageBundle/Controller/PageController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
| Q | A
| --- | ---
This PR introduces an error message when an account which is the parent of another account is trying to be deleted.
Because we don't want to delete the child accounts when a parent account is deleted. What should happen instead is not completely clear, and this way the user can decide how to resolve this conflict.
And it is the same behavior as in Sulu 1.6.
> Show error when deleting parent account

- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Entity/Account.php
- src/Sulu/Bundle/ContactBundle/Entity/AccountInterface.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3942
Allow set null of some fields on the AccounterInterface and remove the deprecated notes function from the interface.
With the AccountInterface refractoring of https://github.com/sulu/sulu/pull/3942 its not longer possible to unset some fields on the account. Sadly this is a bc break, but think we need accept this bc break to fix this bug.
AccountInterface changed.
> Fix account interface function types

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Search/SearchManagerTest.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
| Q | A
| --- | ---
Fix no host in parse_url of PreviewRenderer.
Accessing a bool as array will throw an error on php 7.4. See PreviewBundle in: https://travis-ci.org/sulu/sulu/jobs/595280938
> Fix no host in parse_url of PreviewRenderer

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
| Q | A
| --- | ---
Optimize image output.
The output of gifs will be smaller. For resizing a gif [coalesce](https://www.php.net/manual/de/imagick.coalesceimages.php) for the layers is called. To optimize every layer again the optimize flag need to be set so not every layer contain again the whole image.
Strangely the memory usage was with an animated gif also reduced. I measured it with `\Imagick::getResource(\Imagick::RESOURCETYPE_MEMORY)` reduced from 870mb -> 811mb, memory_get_usage did stay the same. Still seems like a win-win situation smaller filesize and less memory usage.
> Optimize image output

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SmartContent.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/FilterOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/SmartContent.test.js
| Q | A
| --- | ---
This PR adds the possibility to use the `category_root` parameter in the xml templates in order to choose where selecting a category starts in the SmartContent.
Because this was already possible in the 1.x version, and is documented in the [documentation](http://docs.sulu.io/en/2.0/reference/content-types/smart_content.html).
~~~xml
<property name="smart" type="smart_content">
<params>
<param name="category_root" value="test1"/>
</params>
</property>
~~~
> Use category_root parameter of SmartContent

- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Scaler/Scaler.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Scaler/ScalerTest.php
| Q | A
| --- | ---
Return a rounded int value in the scaler width height calculation.
A image in the following format:
```xml
<format key="1273x">
<scale x="1273"/>
</format>
```
And original image in the format `220x442` will result in `219x442` because the float is converted falsely from `220.0` -> `219`. The round does fix this problem.
> Fix image width calculation problems with float values

- src/Sulu/Bundle/ContactBundle/Resources/js/index.js
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/LocationBundle/Resources/translations/admin.de.json
| Q | A
| --- | ---
This PR adds the coordinate (longitude and latitude) to the address overlay in contacts and accounts.
These fields existed in Sulu 1.6 but have disappeared in Sulu 2.0.
> Add coordinate fields to address for contact and accounts

- src/Sulu/Bundle/ContactBundle/Content/Types/SingleAccountSelection.php
- src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php
| Q | A
| --- | ---
This PR fixes the type mismatch between the `single_account_selection` field type and the ´SingleAccountSelection` content type.
Because otherwise the `single_account_selection` field type throws an error when used on a page.
> Fix SingleAccountSelection ContentType

- src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4827 
| Related issues/PRs | #4024 
This PR removes the storage options parameter in the call to FormatManager->getFormats() from the CollectionManager.
> removed storageOptions param in getFormats call

- src/Sulu/Bundle/CoreBundle/Resources/config/doctrine.xml
- src/Sulu/Bundle/PersistenceBundle/DependencyInjection/Compiler/ResolveTargetEntitiesPass.php
- src/Sulu/Component/Doctrine/ReferencesOption.php
| Q | A
| --- | ---
This PR enhances the `ResolveTargetEntitiesPass` to pass a target-entity mapping to the `ReferencesOption` service.
To allow for using interfaces in a `references` option inside of a doctrine schema.
~~~xml
<field name="userId" column="userId" type="integer" unique="true" nullable="false">
<options>
<option name="references">
<option name="entity">Sulu\Component\Security\Authentication\UserInterface</option>
<option name="field">id</option>
<option name="onDelete">CASCADE</option>
<option name="onUpdate">CASCADE</option>
</option>
</options>
</field>
~~~
> Resolve persistence-bundle entities in references option of doctrine schemas

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/SingleSelectionStore/SingleSelectionStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/SingleSelectionStore/tests/SingleSelectionStore.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4808
This PR removes the current selection in a `SingleSelection` if the selected item does not exist anymore.
> Reset SingleSelection to null if the selected item was deleted

- src/Sulu/Bundle/TestBundle/Testing/TestUserTrait.php
| Q | A
| --- | ---
Make getTestUser functions static
To make it possible to access the TestUser in a `setUpBeforeClass`.
~~~php
public static function setUpBeforeClass(): void
{
self::getTestUserId();
}
~~~
> Make getTestUser function static

- composer.json
- src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
- src/Sulu/Bundle/MediaBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
| Q | A
| --- | ---
Removes the php-ffmpeg config from the TestKernel and adds it to the MediaBundle test configuration.
Because the dependency is only used in the MediaBundle and should not be required in all the other bundles.
> Fix optional ffmpeg configuration

- src/Sulu/Component/Rest/ListBuilder/ListBuilderInterface.php
| Q | A
| --- | ---
This PR fixes the documented return types of various methods of the `ListBuilderInterface`.
Because I dont like that phpstan forces me to check if `$listBuilder->createOrExpression()` returns null in every project.
> Fix return typehints in ListBuilderInterface

- src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/complex.xml
- src/Sulu/Component/Content/Exception/InvalidBlockDefaultTypeException.php
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
- tests/Resources/DataFixtures/Page/template_with_invalid_block_default_type.xml
| Q | A
| --- | ---
This PR throws a proper exception when a block is defined in a XML template without an existing `default-type`.
Because when you are configuring this in a wrong way at the moment, then the XML template is interepreted without any error, but when a new block is added in the UI, it will show a strange error like this:
```
FieldBlocks.js:76 Uncaught TypeError: Cannot read property 'form' of undefined
```
This is very confusing, and does not really help.
Try to use the following template and add a new block in the UI.
~~~xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template" …
> Show proper error message when not available default type is set on a block

- composer.json
| Q | A
| --- | ---
The FOSRest bundle removed a dependency (`symfony/templating`), which we were still prepending a configuration. We have to add the dependency on our own now, because otherwise Symfony will complain that this configuration does not exist.
> Fix templating error

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
| Q | A
| --- | ---
| Documentation PR | sulu/sulu-docs#457
This PR adds the possibility to use a `types` schema option in the XML for selection fields, in order to only list elements of a certain type.
Because this was already possible in the old UI, and enables the developer to make sure that e.g. the right type of snippet is assigned in a `snippet_selection`.
The parameter is now called `types` instead of `snippetType`.
> Add possibility to filter by types in Selection component for snippets

- src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_google_cloud.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_s3.xml
| Q | A
| --- | ---
This PR add a configuration for a path-prefix in aws s3 and google-cloud adapter.
If you want to reuse a bucket you can specifiy a path-prefix to use sub paths inside of the bucket.
~~~yaml
sulu_media:
storage: s3
storages:
s3:
key: '%env(resolve:S3_KEY)%'
secret: '%env(resolve:S3_SECRET)%'
region: '%env(resolve:S3_REGION)%'
bucket_name: '%env(resolve:S3_BUCKET_NAME)%'
path_prefix: '%env(resolve:S3_PATH_PREFIX)%'
endpoint: '%env(resolve:S3_ENDPOINT)%'
~~~
None
> Add path_prefix config for s3 and google-cloud media-storage

- src/Sulu/Bundle/TestBundle/Testing/AssertHttpStatusCodeTrait.php
| Q | A
| --- | ---
| Documentation PR | sulu/sulu-docs
Avoid the instanceOf checks for $client->getResponse() 
Which problem does the PR fix? (remove this section if you linked an issue above)
This avoids a check in project code for phpstan if $response is really from class Response.
~~~php
$this->assertHttpStatusCode(200, $response));
~~~
> Improve assert http status for client phpstan return type

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/smartContentStorePool.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SmartContent.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/smartContentStorePool.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/stores/SmartContentStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/SmartContentStore.test.js
| Q | A
| --- | ---
This PR makes use of the already existing `exclude_duplicates` parameter.
Because the preview in the admin showed the correct entries including this option, but the field itself in the form did not.
~~~xml
<property name="smart" type="smart_content">
<params>
<param name="exclude_duplicates" value="true"/>
</params>
</property>
<property name="smart2" type="smart_content">
<params>
<param name="exclude_duplicates" value="true"/>
</params>
</property>
<property name="smart3" type="smart_content">
<params>
<param name="exclude_duplicates" value="true"/>
</params>
</property>
<property name="smart4" …
> Use exclude_duplicates parameter of SmartContent

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
- src/Sulu/Bundle/PageBundle/Resources/config/services.xml
- src/Sulu/Bundle/PageBundle/Resources/js/index.js
- src/Sulu/Bundle/PageBundle/Resources/js/stores/webspaceStore/types.js
- src/Sulu/Bundle/PageBundle/Resources/js/utils/Webspace/index.js
- src/Sulu/Bundle/PageBundle/Resources/js/utils/Webspace/loadResourceLocatorInputTypeByWebspace.js
- src/Sulu/Bundle/PageBundle/Resources/js/utils/Webspace/tests/loadResourceLocatorInputTypeByWebspace.test.js
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/WebspaceControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/EventListener/WebspaceSerializeEventSubscriberTest.php
- src/Sulu/Bundle/RouteBundle/Resources/js/index.js
| Q | A
| --- | ---
This PR makes use of the `resource-locator-strategy` configuration of the webspace xml.
Because previously this setting was ignored, and although the configuration said that the entire resource locator should be editable, it wasn't.
~~~xml
<resource-locator>
<strategy>tree_full_edit</strategy>
</resource-locator>
~~~
The `mode` schema option of the `resource_locator` field type is gone now.
> Use ResourceLocatorStrategy in UI based on webspace configuration

- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/metadataStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MetadataStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
| Q | A
| --- | ---
Adds the possibility to add custom metadata to the form of the FormOverlay and the FormView.
Because we want the possibility to add custom metadata to views.
~~~php
$formOverlayListViewBuilder->setResourceKey(Example::RESOURCE_KEY)
->setListKey(Example::RESOURCE_KEY)
->setFormKey('example_details')
->addListAdapters(['table'])
->addMetadataRequestParameters(['test-data' => $data]);
~~~
~~~php
class CustomMetadataLoader implements FormMetadataLoaderInterface
{
public function getMetadata(string $key, string $locale, array $metadataOptions): ?MetadataInterface
{
//do …
> Add MetadataRequestParameters to FormView and FormOverlayListView

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
| Q | A
| --- | ---
This PR uses `restore` when going back to the list after deleting an item in the form.
That avoids an error when a webspace is missing after deleting a page, if the webspace has never been chosen manually. If this is done before the fix, then the webspace select is empty.
> Fix missing webspace when page is deleted in form

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
| Q | A
| --- | ---
| Bug fix? | Yes
PR generally reduces the size of the editor so that the problem of overlapping (see "Why?" below) will only occur in rare cases. If it still happens, then the sticky-toolbar of ck editor will be positioned below the header inside the visible area of the editor.
CK Editors toolbar overlaps the SULU header when top of editor is below header after scrolling. This happens when a lot of lines are in content area.
> Prevent editor toolbar to overlap sulu header

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ChangelogLine.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ChangelogLine.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4845 
This PR sets the creator and changer to a value of `undefined` if the user has been deleted in the mean time.
Because if we don't handle this case, an infinite loader appears.
> Fix infinite loader in ChangelogLine when user was deleted

- src/Sulu/Bundle/AudienceTargetingBundle/TargetGroup/TargetGroupEvaluator.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/TargetGroupEvaluatorTest.php
| Q | A
| --- | ---
Fix target group evaluator without webspace.
If you have a `_requestAnalyer: false` route and AudienceTargeting activated the webspace is not set and will fail on that route.
> Fix target group evaluator without webspace

- composer.json
| Q | A
| --- | ---
Add branch aliases for development
Allow to use @dev for specific version.
~~~json
"sulu/sulu": "^2.0@dev"
~~~
> Add branch aliases for development

- src/Sulu/Bundle/AdminBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/SecurityBundle/Security/AuthenticationHandler.php
- src/Sulu/Bundle/SecurityBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/LoginControllerTest.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationEntryPointTest.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationHandlerTest.php
| Q | A
| --- | ---
Redirect to correct login page `/admin` when it fails.
The current route `sulu_admin.login` does not longer exist and the login form is shown on `/admin`.
> Fix authentication handler redirect

- src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
- src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
| Q | A
| --- | ---
Register specific bundles if they exist in TestKernel.
Not all bundles are required but should be registered if they exist.
In Sulu 2.0 FosRestBundle is also activated on website and so it should also be in the TestKernel on the website. MonologBundle is optional dependency and should not be needed for other Bundles. 
~~~php
class Kernel extends SuluTestKernel {
}
~~~
> Register specific bundles only if they exist in TestKernel

- composer.json
- src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Documentation PR | TODO
This PR adds a command that downloads the JS build in the correct version for the developer.
Because that should make the update easier.
~~~bash
bin/console sulu:admin:download-build
~~~
> Implement a command that downloads the current JS build

- src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Rule/PageRuleTest.php
| Q | A
| --- | ---
Remove the `symfony.lock` file when a new project is created.
Because we also remove the `composer.lock` file :slightly_smiling_face:
> Remove symfony.lock file from gitignore after create-project

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationItem.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php
| Q | A
| --- | ---
This PR removes code that is not used anymore.
Because these methods will confuse people, when they are trying to use, and nothing at all happens.
> Remove unused code from NavigationItems

- src/Sulu/Bundle/MediaBundle/Media/Storage/S3Storage.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/S3StorageTest.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/461
This PR fixes the media original download.
The path prefix is missing there.
> Add path prefix to media url

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
| Q | A
| --- | ---
| Related issues/PRs | #4441 / #4485 (this still works but was the issue why the id was added in the TypeToolbarAction and cause my problem)
Fix set of template type on exist entity when not set.
Currently if you have a entity and with an id which does not have yet content it will error and not show any form. Currently it is handled in the TypeToolbarAction which I think is also the false place this to handle it as maybe you don't want that ToolbarAction, so I moved this to the ResourceFormStore.
> Set default type on existing entity without type

- composer.json
| Q | A
| --- | ---
| Related issues/PRs |-
Fix branch aliases for development.
Seems like a merge conflict didn't happened or was not resolved correctly when merging 1.6 to 2.0.
> Fix branch aliases for development

- src/Sulu/Bundle/ContactBundle/Content/Types/SingleAccountSelection.php
- src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php
| Q | A
| --- | ---
This PR fixes the pre-resolve for tags-cache purging.
> Fix pre-resolve for single-account-selection

- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TypedFormMetadata.php
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/webspaces/sulu.io.xml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/PreviewFormViewBuilderTest.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Component/Webspace/Loader/XmlFileLoader11.php
- src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.1.xsd
- src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
- src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
- src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
- src/Sulu/Component/Webspace/Webspace.php
- tests/Resources/DataFixtures/Webspace/valid/sulu.io.xml
| Q | A
| --- | ---
| Documentation PR | sulu/sulu-docs#462
This PR allows to exclude certain templates in webspaces.
Because some templates might not be allowed in all webspaces.
~~~xml
<?xml version="1.0" encoding="utf-8"?>                                                                                                                                                                                                                                          
<webspace xmlns="http://schemas.sulu.io/webspace/webspace" …
> Allow to exclude templates in webspaces

- src/Sulu/Bundle/MediaBundle/DependencyInjection/AbstractImageFormatCompilerPass.php
| Q | A
| --- | ---
This PR adds the a `FileResource` for every image formats file.
Because otherwise the cache is not correctly cleared in dev mode.
> Clear cache if image formats are changed

- src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4865 
Fix sitemap provider tags definition.
Because currently custom sitemap provider breaks admin interface.
> Fix sitemap provider tags definition

- src/Sulu/Bundle/CoreBundle/Resources/config/localization.xml
| Q | A
| --- | ---
Add autowiring of LocalizationManagerInterface
So you can get easier the localizations for a Admin class in a project.
> Add autowiring of LocalizationManagerInterface

- src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #4302
This PR checks if the value in PHPCR for a media type is valid. If it is not we return a value of `null` instead.
Sometimes there are invalid values for the `media_selection` content type in PHPCR. These values made the UI crash, because it assumed a different structure. I originally wanted to fix this in the JS code, but then I realized that the `single_media_selection` does not have this problem. After a quick check I realized that the content type already returned `null` when a wrong value was passed, instead of blindly passing the value.
So I decided that it indeed makes more sense to …
> Fix crashing when media_selection contains invalid value

- templates/base.html.twig
| Q | A
| --- | ---
| Fixed tickets | fixes #4864
| Related issues/PRs | sulu/skeleton#20
This PR adds the webspace key when generating a url for the navigation.
> Consider the webspace when creating navigation links

- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
| Q | A
| --- | ---
Pass the exception in the FormatManager to the LoggerInterface.
https://www.php-fig.org/psr/psr-3/#13-context describes how it is done.
https://github.com/symfony/console/blob/master/EventListener/ErrorListener.php#L48 shows that symfony may pass an exception as context.
I want to ignore a MediaNotFoundException on a staging system.
Without passing the exception one has to interpret the error message string instead which is inconvenient and perhaps not reliable.
The stack trace is no longer logged as context. One can get that from the exception instead.
> Pass the exception in the logger context

- UPGRADE.md
- src/Sulu/Bundle/RouteBundle/Entity/RouteRepository.php
- src/Sulu/Bundle/RouteBundle/Entity/RouteRepositoryInterface.php
- src/Sulu/Bundle/RouteBundle/Manager/RouteManager.php
- src/Sulu/Bundle/RouteBundle/Manager/RouteManagerInterface.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Manager/RouteManagerTest.php
| Q | A
| --- | ---
This PR add a method to the `RouteManager` to handle routables without the `RoutableInterface`.
This will be used by the SuluContentBundle.
~~~php
$this->routeManager->createOrUpdateByAttributes(
$localizedContentDimension->getContentClass(),
(string)$localizedContentDimension->getContentId(),
$dimension->getLocale(),
$routePath
);
~~~
New method in the `RouteManagerInterface` and `RouteRepositoryInterface`.
> Add method to handle routables without the routable interface

- src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ArrayMetadata.php
- src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php
- src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_blocks.xml
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/ArrayMetadataTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/ConstMetadataTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/SchemaMetadataTest.php
- src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/overview.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
- src/Sulu/Component/Content/Metadata/Parser/SchemaXmlParser.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4629
This PR considers the block content type when generating the JSON schema for a form.
Because this way the validation for required fields will also work in blocks.
~~~xml
<block name="blocks" default-type="text" minOccurs="0">
<meta>
<title lang="de">Text</title>
<title lang="en">Text</title>
</meta>
<types>
<type name="text">
<meta>
<title lang="de">Text</title>
<title lang="en">Text</title>
</meta>
<properties>
<property name="title" type="text_line" mandatory="true">
<meta>
<title lang="de">Title</title>
<title lang="en">Title</title>
</meta>
</property>
<property name="editor" type="text_editor" …
> Validate required fields in form blocks

- config/packages/framework.yaml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/skeleton/pull/21
Change cookie name to `SULUSESSID` to avoid conflict with `PHPSESSID`.
Avoids conflicts to applications running on the same domain overwriting this cookie session.
> Change cookie name to SULUSESSID

- src/Sulu/Bundle/PageBundle/Resources/config/lists/pages.xml
| Q | A
| --- | ---
| Fixed tickets | fixes(?) #4875
This PR removes the sorting functionality in page lists.
Because the API does not support sorting. Apart from that we have to think if this is a good idea at all, because the pages have a fixed place in the tree (also the position between its siblings) and being able to change it might make things look "wrong".
> Avoid sorting of pages in tree view because it does not work

- composer.json
- src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
- src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
| Q | A
| --- | ---
Remove the preload of the css and js files in main.html.twig.
Fix loading of unbuilt js files in chrome over https push.
Sometimes the Chrome cancel the request after only loading 6.6mb of the ~25mb file.
> Fix loading of unbuilt js files in chrome over http2 push

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
| Q | A
| --- | ---
Reset URL in `ExternalLinkOverlay`.
Because otherwise the URL stays there, if multiple external links are added.
Reproducation:
1. Go to a page with a `text_editor`
2. Write some text
3. Add an external link with some URL
4. Select another text and add another External Link
5. The URL from step 3 will still be in the input field
> Fix missing reset of URL if multiple external links are set in CKEditor5

- src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php
| Q | A
| --- | ---
Extracts the teaser attributes to the `getAttributes` method. The same structure is already used in the `ArticleTeaserProvider`.
For custom attributes it is easier to override only the `getAttributes` method instead of the `find` method.
> Extract teaser attributes to getAttribute method

- src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4798
Fix strange error in SuluHttpCacheExtension Tests.
They are failing not sure why they were not required before symfony 4.4.
> Fix strange error in SuluHttpCacheExtension Tests

- src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4798
Fix strange error in SuluHttpCacheExtension Tests.
They are failing not sure why they were not required before symfony 4.4.
> Fix services in SuluHttpCacheExtension tests

- config/packages/security_admin.yaml
- config/packages/test/security_admin.yaml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/skeleton/pull/26, symfony/symfony#34596
Provide a default user provider for the firewall
Avoid following error message in test environment when using Symfony 4.4.
> Not configuring explicitly the provider for the "anonymous" listener on "admin" firewall is ambiguous as there is more than one registered provider.
> Provide a default user provider for the firewall

- src/Sulu/Bundle/TestBundle/Testing/AssertHttpStatusCodeTrait.php
| Q | A
| --- | ---
Fix assertHttpStatusCode for 201 response
A 201 can be a redirect but the Response instance could be not a RedirectResponse.
~~~php
$this-assertHttpStatusCode($response, 200); // But response is 201
~~~
> Fix assertHttpStatusCode for 201 response

- phpunit.xml.dist
- src/Sulu/Bundle/AudienceTargetingBundle/phpunit.xml.dist
- src/Sulu/Bundle/CategoryBundle/phpunit.xml.dist
- src/Sulu/Bundle/ContactBundle/phpunit.xml.dist
- src/Sulu/Bundle/CoreBundle/phpunit.xml.dist
- src/Sulu/Bundle/CustomUrlBundle/phpunit.xml.dist
- src/Sulu/Bundle/DocumentManagerBundle/phpunit.xml.dist
- src/Sulu/Bundle/HttpCacheBundle/phpunit.xml.dist
- src/Sulu/Bundle/LocationBundle/phpunit.xml.dist
- src/Sulu/Bundle/MarkupBundle/phpunit.xml.dist
- src/Sulu/Bundle/MediaBundle/phpunit.xml.dist
- src/Sulu/Bundle/PageBundle/phpunit.xml.dist
- src/Sulu/Bundle/PersistenceBundle/phpunit.xml.dist
- src/Sulu/Bundle/PreviewBundle/phpunit.xml.dist
- src/Sulu/Bundle/RouteBundle/phpunit.xml.dist
- src/Sulu/Bundle/SearchBundle/phpunit.xml.dist
- src/Sulu/Bundle/SecurityBundle/phpunit.xml.dist
- src/Sulu/Bundle/SnippetBundle/phpunit.xml.dist
- src/Sulu/Bundle/TagBundle/phpunit.xml.dist
- src/Sulu/Bundle/WebsiteBundle/phpunit.xml.dist
| Q | A
| --- | ---
This PR makes sure that the deprecations are listened on every phpunit call.
Because this setting was not used on my local machine.
> Add the SymfonyTestsListener to all phpunit configuration files

- src/Sulu/Bundle/HttpCacheBundle/Cache/SuluHttpCache.php
| Q | A
| --- | ---
Change the http_cache folder to the http_cache subdirectory of the common cache dir.
Only the http_cache subdirectory is cleared see:
https://github.com/sulu/sulu/blob/8b8c674c5f9254ceab0014095387c11ee004a603/src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php#L96-L106
1. Create new page
2. Add it to navigation context
3. Publish it
4. Click Cache Clear Website
The new page does not appear on the homepage navigation as the http cache was written into the false directory.
> Fix http cache directory for symfony cache

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SmartContent.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/stores/SmartContentStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/SmartContentStore.test.js
- src/Sulu/Bundle/PageBundle/Controller/SmartContentItemController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/SuluArticleBundle/issues/413
This PR add the params parameter to the smart-content items request for the admin form field.
See the linked issue from the ArticleBundle.
The Provider uses the params to filter for types/structureTypes
> Add params to smart-content items request

- UPGRADE.md
- composer.json
- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/SearchBundle/Tests/Resources/TestBundle/Controller/SearchController.php
- src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
- src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
- templates/base.html.twig
| Q | A
| --- | ---
| Related issues/PRs | Symfony 5 compatibility #4798
Remove templating requirement and use new template reference syntax.
The templating bridge is deprecated and should not longer be used.
> Remove templating requirement

- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
| Q | A
| --- | ---
This PR displays the `MimeTypeIndicator` in the media overview and the upload in the media form if loading the image throws an error.
Because seeing an infinite loader then is not the solution either. This e.g. happens when uploading a video without `ffmpeg` being installed.
> Show MimeTypeIndicator instead of infinite loader if image cannot be loaded for a reason

- public/index.php
| Q | A
| --- | ---
There's a link for "http-method-override" that points to the Symfony 3.4 documentation but Sulu 2.0 requires Symfony 4.3 or later.
The link should use the newer Symfony documentation version.
Open /public/index.php in an editor and open the link in line 59 in a web browser.
> Update Documenation link

- dependency-cruiser.json
| Q | A
| --- | ---
Add a Rule to avoid the AdminBundle to depend on other bundles.
Because the AdminBundle is the base for all the other bundles, and we would like to avoid bidirectional dependencies.
> Add rule to avoid that the AdminBundle depends on other bundles

- src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationItem.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php
| Q | A
| --- | ---
The NavigationItem features the methods find and findChildren.
This pull requests fixes the phpdoc and behaviour of these methods by returning Navigationitem or null.
In case of  find it is documented that it would return false if no navigation item is found.
However find returns void instead of false if no navigation item is found.
In case of findChildren the phpdoc states that it would return a NavigationItem or null.
However findChildren returns a NavigationItem or void instead.
> find and findChildren should return either a NavigationItem or null

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Dropdown.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/OptionList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/option.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/optionList.scss
| Q | A
| --- | ---
| Fixed tickets | fixes #3061
This PR allows to scroll in the Toolbar selects.
Because if many templates or languages exist in a template, then the last ones cannot be clicked, because they stick out of the display.
> Allow scrolling in toolbar select

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldTransformers/ThumbnailFieldTransformer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldTransformers/ThumbnailFieldTransformer.test.js
| Q | A
| --- | ---
The `alt` tag is not passed in the list response, therefore we should not render it.
It could even cause problems if an image format named `alt`, because then this content instead of a proper alt text would be used.
> Remove alt from Thumbnail transformer because alt is not delivered by API

- src/Sulu/Component/CustomUrl/Manager/CustomUrlManagerInterface.php
| Q | A
| --- | ---
CustomUrlManagerInterface::findByUrl needs to have the locale as 3rd parameter.
The CustomUrlRequestProcessor works with a CustomUrlManagerInterface and calls findByUrl with the locale as 3rd parameter.
As consequence the locale must be added to the CustomUrlManagerInterface. It is not sufficient, that CustomUrlManager::findByUrl has the locale in its signature.
> CustomUrlManagerInterface::findByUrl needs locale parameter

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/stores/SmartContentStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/SmartContentStore.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4931
This PR fixes the SmartContent, if the datasource that was selected was deleted.
Because previously the smart content showed an infinite loader, and the datasource could not be changed anymore.
> Fix SmartContent when the data source has been deleted

- .env
- .travis.yml
- appveyor.yml
- bin/console.php
- config/packages/doctrine.yaml
- config/packages/prod/routing.yml
- config/packages/routing.yaml
- config/packages/security_admin.yaml
- config/packages/test/twig.yaml
- config/packages/twig.yaml
- config/routes/dev/twig.yaml
- config/routes/sulu_admin.yaml
- config/secrets/prod/.gitignore
- public/index.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig
| Q | A
| --- | ---
| Related issues/PRs | sulu/skeleton#23
Adopts changes from sulu/skeleton#23.
Because we want to be the setup in here as similar as possible to the skeleton.
> Update to latest flex recipes

- UPGRADE.md
- appveyor.yml
- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormOverlayListViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/ListViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/PreviewFormViewBuilderTest.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
| Q | A
| --- | ---
| Related issues/PRs | sulu/SuluFormBundle#211
This PR add following methods:
* `ListViewBuilderInterface::addResourceStorePropertiesToListMetadata`
* `ListViewBuilderInterface::addRequestParameters`
* `FormViewBuilderInterface::addRequestParameters`
* `FormOverlayListViewBuilderInterface::addRequestParameters`
* `PreviewFormViewBuilderInterface::addRequestParameters`
See PR in sulu-form-bundle.
New methods in interfaces.
> Add method to add resource-store-properties to metadata-request

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/GhostIndicator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/ghostIndicator.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/tests/GhostIndicator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/tests/__snapshots__/GhostIndicator.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/AbstractTableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/abstractTableAdapter.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/ColumnListAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TreeTableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/TableAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
- src/Sulu/Bundle/CategoryBundle/Api/Category.php
- src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/mediaCard.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/adapters/MediaCardAdapter.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/MediaCardAdapter.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardAdapter.test.js.snap
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
- src/Sulu/Bundle/PageBundle/Serializer/Subscriber/LocaleSubscriber.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
- src/Sulu/Component/Content/Repository/Serializer/SerializerEventListener.php
| Q | A
| --- | ---
This PR adds the ghost indicator to snippets and categories.
Because this is a useful information and was already shown in Sulu 1.x.
> Show GhostIndicator for Categories and Media

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormOverlayListViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/ListViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/PreviewFormViewBuilderTest.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
We should keep this feature in 2.0 version to keep compatability of form bundle on 2.0 and not on 2.1
| Q | A
| --- | ---
| Related issues/PRs | sulu/SuluFormBundle#211
This PR add following methods:
* `ListViewBuilderInterface::addResourceStorePropertiesToListMetadata`
* `ListViewBuilderInterface::addRequestParameters`
* `FormViewBuilderInterface::addRequestParameters`
* `FormOverlayListViewBuilderInterface::addRequestParameters`
* `PreviewFormViewBuilderInterface::addRequestParameters`
See PR in sulu-form-bundle.
New methods in interfaces.
> Merge "Add method to add resource-store-properties to metadata-request" into release/2.0

- src/Sulu/Bundle/AdminBundle/Admin/View/ToolbarAction.php
| Q | A
| --- | ---
To allow for determining the type of an existing toolbar action.
> Add getter for type property of ToolbarAction class

- .travis.yml
- src/Sulu/Bundle/CoreBundle/Resources/config/list_builder.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
| Q | A
| --- | ---
Add linting of container to test if services are defined correctly.
Invalid definition of services should be avoided with this linting commands.
Will need symfony 4.4.2 release because of the following bugfix symfony/symfony#34794
> Add linting of container to ci

- src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperTest.php
| Q | A
| --- | ---
In https://github.com/sulu/sulu/blob/46ca99928872780a0034854bb1d72d89a4c06c1d/src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php#L93 there was an bug in swapped arguments for sitemap render. Also fixes swapped arguments in tests.
> Swap render index arguments

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
| Q | A
| --- | ---
Interate over layers only when there exist more then 1 layer.
As I did analysed the changes we did for the [vips adapter](https://github.com/sulu/sulu/pull/4862) I did see that we always got into the multi layer part.
Tests did give that the memory usage was reduced from my test images 40mb -> 8mb (- ~80%) and another test image from 435mb -> 162mb memory usage (- ~62%).
To test the memory usage I used in ImagineImageConverter:
```php
// var_dump($this->humanFileSize($image->getImagick()->getResource(\Imagick::RESOURCETYPE_MEMORY)));
// var_dump($this->humanFileSize(memory_get_usage()));
```
No BC Break
> Improve performance for one layered images

- bin/runtests
| Q | A
| --- | ---
This PR removes the `doctrine:phpcr:dbal:init` step. 
Because this step is failing on travis for Sulu 2.0, and the tests still succeed. Therefore I guess that this step would not be necessary at all.
And because it always feels good to delete something from this script :see_no_evil:
> Remove unnecessary PHPCR initialization in build script

- src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
| Q | A
| --- | ---
This PR hides the add button inside the tree-table list-adapter of the category list if the current user does not have the respective permission.
Because Sulu usually hides control elements for which the current user does not have sufficient permissions. Eg. toolbar actions are only displayed if the current user has the permissions to execute the action.
> Display add button in category list only if user has sufficient permissions

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/TableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/TreeTableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TreeTableAdapter.test.js
| Q | A
| --- | ---
This PR adjust the TableAdapter and the TreeTableAdapter of the List container to display different icons in their buttons based on item-specific permissions of the current user.
Because it is kind of misleading to display a `pen` icon if the current user is not allowed to edit anything.
> Render buttons of TableAdapter and TreeTableAdapter based on item-specific permissions

- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/OptionMetadata.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
| Q | A
| --- | ---
This PR adds the type information for options to the form metadata serialization.
Because if this information is missing the smart content is not loading the items in the administration interface if something has been selected and the `properties` param has been passed.
~~~xml
<property name="smart_content" type="smart_content">                                                                                                                                                                                                                    
<params> …
> Fix bug when loading items in admin for smart content with properties param

- src/Sulu/Component/Persistence/Model/UserBlameInterface.php
- src/Sulu/Component/Persistence/Model/UserBlameTrait.php
| Q | A
| --- | ---
Add nullable to UserBlameInterface getCreator and getChanger functions.
The creator and changer can be null if the user was deleted or the entity was created over an cli script. This phpdocs should improve static code analyzes and so avoid errors. 
Should throw an error in static code analyzes as getCreator could return null and would end up in calling getId on null.
```php
$creatorId = $entity->getCreator()->getId();
```
instead it should be:
```php
$creatorId = null;
$creator = $entity->getCreator();
if ($creator) {
$creatorId = $creator->getId();
}
```
> Add nullable to UserBlameInterface getCreator and getChanger functions

- src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php
- src/Sulu/Component/Content/SimpleContentType.php
| Q | A
| --- | ---
This PR only executes a `preg_replace` to remove illegal characters if the passed value is actually a string.
Because `preg_replace` also changes the type of the passed value, which means that a number will be converted to a string. This will cause to trigger the save button for e.g. the `SingleContactSelection` immediately, because the type changes and we are doing a type-strict check to realize if something changed.
~~~xml
<property name="single_contact" type="single_contact_selection" />
~~~
Assign a value and reload the form, then the save button will be activated.
> Avoid SingleContactSelection to trigger save button when contact is loaded

- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/DeleteToolbarAction.js
| Q | A
| --- | ---
This PR add a `disabled_condition` option to the DeleteToolbarAction of the List view. This allows to pass a `jexl` expression that is evaluated on every selected item. If the expression evaluates to true for at least one selected item, the toolbar action is rendered in a disabled state.
One usecase is to disable the toolbar action if the user does not have sufficient permissions to delete one of the selected items.
~~~php
new ToolbarAction(
'sulu_admin.delete',
['disabled_condition' => (_permissions && !_permissions.delete)']
);
~~~
> Add disabled_condition option to DeleteToolbarAction of List view

- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilder.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderInterface.php
- src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderTrait.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/TableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/TreeTableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TreeTableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormOverlayListViewBuilderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/ListViewBuilderTest.php
- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
| Q | A
| --- | ---
This PR adds a `itemDisabledCondition` to the `List` view that allows to pass a `jexl` expression. This `jexl` expression is evaluated on each item of the list. If the expression evaluates to true for an item, the item is rendered in a disabled state.
Additionally, this PR adds a `setItemDisabledCondition` method to the `FormOverlayListViewBuilderInterface` and the `ListViewBuilderInterface` that allows to set the `itemDisabledCondition` via a view-builder instance.
The PR builds upon the existing `disabledIds` prop of the `ListAdapterProps` type. With this PR, the following list adapters mind the given `disabledIds`:
* ColumnListAdapter
* TableAdapter
* TreeTableAdapter
One …
> Add itemDisabledCondition option to List view

- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
- src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
- src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManagerInterface.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
| Q | A
| --- | ---
This PR fixes the message when a referenced snippet is tried to be deleted.
Because now a JS error was thrown, which caused all other clicks to have no effect.
> Fix conflict message when referenced snippet is being deleted

- src/Sulu/Component/Rest/ListBuilder/Metadata/Resources/schema/list-2.0.xsd
| Q | A
| --- | ---
This PR add a missing attribute `distinct` to GroupConcat node in xml schema.
This is used to load and also for the query but not allowed in the XML.
> Add distinct attribute to group-concat node in xml schema for list

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteDraftToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SetUnpublishedToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyLocaleToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteDraftToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithPublishingToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
| Q | A
| --- | ---
This PR renames the `display_condition` option of various toolbar actions of the Form view to `visible_condition`. The old `display_condition` was deprecated and will log a deprecation warning if it is used.
Because we already support a `visibleCondition` attribute in our Form XML files that allows to hide specific field-types and i would like to provide a consistent naming. 
~~~php
new ToolbarAction(
'sulu_admin.copy_locale',
[
'visible_condition' => '(!_permissions || _permissions.edit)',
]
),
~~~
The `display_condition` option of the following toolbar actions was deprecated:
* CopyLocaleToolbarAction
* DeleteDraftToolbarAction
* DeleteToolbarAction
* …
> Rename display_condition option of toolbar actions of Form view to visible_condition

- src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/symfony/symfony/pull/35065 #4998
Fix TestUserProvider supportsClass call.
The TestUserProvider should call the other user provider for supportsClass. This did work before as symfony before 3.4.37 didn't call supportsClass. Related PR: https://github.com/symfony/symfony/pull/35065
> Fix TestUserProvider supportsClass call

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Teaser/ContentTeaserProvider.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Teaser/ContentTeaserProviderTest.php
- src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4331 
This PR fixes the bug that only 10 teaser items are returned if there are more than 10 assigned.
> Fix assigning more than 10 teasers when using elasticsearch

- composer.json
| Q | A
| --- | ---
This pull requests add the used PHP extensions to the composer.json file.
Composer should fail at install time instead of having runtime errors in Sulu.
One can compile a nice list of dependencies when migrating servers.
It's a very good practice to always add the used dependencies.
Citing https://getcomposer.org/doc/04-schema.md
> Note: It is important to list PHP extensions your project requires.
| Extension | Usage
| --- | ---
| ext-json | All over the place
| ext-dom | \Sulu\Bundle\MediaBundle\Media\FormatLoader\BaseXmlFormatLoader, \Sulu\Bundle\AdminBundle\FormMetadata\FormXmlLoader
| ext-fileinfo | …
> add used PHP extensions to composer.json

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/ListOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/tests/ListOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiListOverlay/MultiListOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiListOverlay/tests/MultiListOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleListOverlay/SingleListOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleListOverlay/tests/SingleListOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
| Q | A
| --- | ---
This PR adds a `itemDisabledCondition` option to the `Selection` and `SingleSelection` field type that allows to pass a `jexl` expression. If the expression evalues to true for an item, the item is rendered in a disabled state and cannot be selected in the selection.
With this PR, the following selection types support the `itemDisabledCondition` option:
* Selection / list_overlay
* Selection / list
* SingleSelection / list_overlay
One usecase is to disable items for which the current user does not have sufficient permissions. When using the TreeTableAdapter, it is not possible to hide those rows because the user might have sufficient permissions for a child row.
~~~xml
<property …
> Add itemDisabledCondition schemaOption to Selection and SingleSelection field-type

- src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
- src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManagerInterface.php
- src/Sulu/Component/Content/Compat/StructureInterface.php
| Q | A
| --- | ---
| BC breaks? | possible
Fix phpdoc types in CollectionManagerInterface and StructureInterface.
Because they are wrong, to improve static code analyzers.
> Fix types in CollectionManagerInterface and StructureInterface

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | Builds upon #4992
This PR adjusts the behaviour of the `List` container to only select **non-disabled** items if the`onAllSelectionChange` callback is fired by a `ListAdapter` (for example when the select-all checkbox of the `TableAdapter` is clicked). 
Furthermore, this PR fixes a bug that rendered the select-all checkbox of the `TableAdapter` with the wrong skin. Also, the select-all checkbox of the `TableAdapter` is now rendered as checked if all non-disabled rows are selected.
Because the goal of disabling items is that they cannot get selected.. 😉
> Do not select disabled items when select-all checkbox in List is clicked

- src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/views/Template/hit-script.html.twig
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/matomo/head-close.html.twig
| Q | A
| --- | ---
Remove unneeded type attribute from script tags. 
Avoid warnings w3c warnings like:
> Remove unneeded type attribute in script tags

- src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/CollectionStore.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/tests/CollectionStore.test.js
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5005 
This PR only shows the add, delete and edit operations on Collections not being a SystemCollection.
> Disallow add, delete and edit operations on SystemCollections

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
| Q | A
| --- | ---
| Fixed tickets | fixes #5009
This PR gives the content section of a block a fixed width.
Because otherwise the content of the block might overflow on the x-axis.
Use the following template and make sure that a page listed in the smart content has a very long title.
~~~xml
<block name="test" default-type="test2">
<types>
<type name="test2">
<properties>
<property name="text" type="text_line">
<meta>
<title lang="en">Text</title>
</meta>
</property>
<property name="smart" type="smart_content">
<meta>
<title lang="en">Text</title>
</meta>
</property>
</properties>
</type>
</types>
</block>
~~~
> Fix width of content in blocks to avoid overflow

- src/Sulu/Bundle/AdminBundle/Resources/js/components/PermissionHint/PermissionHint.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PermissionHint/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PermissionHint/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PermissionHint/permissionHint.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PermissionHint/tests/PermissionHint.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PermissionHint/tests/__snapshots__/PermissionHint.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Form.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaVersionUpload.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/tests/MediaVersionUpload.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #2300
This PR shows a hint for missing permissions, when a form is loaded which is not granted access for the current user. This can easily happen when single languages are restricted for certain users.
> Show hint for missing permissions in forms

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/loadingStrategies/AbstractLoadingStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/structureStrategies/ColumnStructureStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/structureStrategies/ColumnStructureStrategy.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/RequestPromise.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/RequestPromise.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4912 
This PR cancels the request from a list when a new request for the same list has been sent.
Because otherwise it can happen that sooner requests finish later than the ones starting later, causing the wrong page to display. E.g. if you navigate from page 1 to page 10 by clicking the next icon without waiting for the requests to finish, you could e.g. to be shown page 9, although the list shows page 10.
> Fix fast pagination of List view

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/TemplateToolbarAction.test.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/TemplateToolbarAction.js
| Q | A
| --- | ---
Add disable and visible condition to TypeToolbarAction.
Allows to hide or disable TypeToolbarAction.
> Add disable and visible condition to TypeToolbarAction

- src/Sulu/Bundle/AdminBundle/Admin/Admin.php
- src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/AddAdminPass.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/DependencyInjection/Compiler/AddAdminPassTest.php
- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
- src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
| Q | A
| --- | ---
| Related issues/PRs | used in sulu/SuluFormBundle#225
This PR introduces a `getPriority` function in the admin.
This allow to put the concrete admin at a specific place inside the admin chain.
It will be used in the form bundle to ensure that the check if a view is available will be called as the last admin.
~~~php
class AppAdmin extends Admin
{
public static function getPriority(): int
{
return -1024;
}
...
}
~~~
No BC break all the admins existing admin automatically get the priority `0`.
> Add getPriority function to admin pool compiler pass

- src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4877
Show better preview content block exception
The current code end up in an error without throwing a exception why it did happened.
Remove the `block content` the following exception should then be shown.
> Show better preview content block exception

- src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5031 
Fix build download for other platforms by removing all whitespaces in hash check.
When the developer using different Line breaks or have other indention of the file the hash check currently fails. With removing the whitespaces before the hash check this will fix proble,.
Change whitespaces or change linbreaks in and run:
~~~php
bin/console sulu:admin:download-build
~~~
> Fix build download for other platforms

- src/Sulu/Bundle/PreviewBundle/Preview/Exception/PreviewRendererException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/RouteDefaultsProviderNotFoundException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/TemplateNotFoundException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/TwigException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/UnexpectedException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/WebspaceLocalizationNotFoundException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/WebspaceNotFoundException.php
| Q | A
| --- | ---
Currently TwigException uses
https://github.com/sulu/sulu/blob/ade35fff4cb8ced777c726dcb730c5c5f5720960/src/Sulu/Bundle/PreviewBundle/Preview/Exception/TwigException.php#L22
https://github.com/sulu/sulu/blob/ade35fff4cb8ced777c726dcb730c5c5f5720960/src/Sulu/Bundle/PreviewBundle/Preview/Exception/TwigException.php#L23
The parent uses:
https://github.com/sulu/sulu/blob/ade35fff4cb8ced777c726dcb730c5c5f5720960/src/Sulu/Bundle/PreviewBundle/Preview/Exception/PreviewRendererException.php#L44
https://github.com/sulu/sulu/blob/ade35fff4cb8ced777c726dcb730c5c5f5720960/src/Sulu/Bundle/PreviewBundle/Preview/Exception/PreviewRendererException.php#L45
And I matched those types.
Just wrong …
> Fixing TwigException parameter types

- UPGRADE.md
- src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Bundle/HttpCacheBundle/Cache/CacheManager.php
- src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/InvalidationSubscriber.php
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/cache-manager.xml
- src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/Cache/CacheManagerTest.php
- src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Application/config/webspaces/sulu.io.xml
- src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/command.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
- tests/Resources/DataFixtures/Webspace/multiple/massiveart.xml
- tests/Resources/DataFixtures/Webspace/valid/sulu.io.xml
- tests/Resources/DataFixtures/Webspace/valid/sulu.io_hostReplacer.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #5020
This PR will replace the host immediately after the webspace collection is loaded from the cache. This has the advantage, that nobody else has to take care of the `{host}` placeholder.
Because it solves #5020, and allows to delete other code handling the exact same thing.
The `{host}` placeholder is not available anymore. Code that relies on that is not necessary and anymore and can be deleted. In case somebody abused that placeholder for something else, that code might not work anymore.
> Replace host right after loading webspaces to avoid repeating this logic

- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/MultiItemSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/__snapshots__/MultiItemSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/SingleItemSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/singleItemSelection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/SingleItemSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/__snapshots__/SingleItemSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Checkbox.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/multiSelection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/__snapshots__/SingleSelection.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | Builds upon #4992
This PR adjusts the `SingleSelection` component and the `MultiSelection` component to render items in a disabled state if they fulfill the given `itemDisabledCondition` or their id is contained in the given `disabledIds`. Furthermore it adds a `allow_deselect_for_disabled_items` option that allows to configure if the user should be able to deselect/remove disabled items from a selection.
Because the user should see if a selected item is disabled without opening the `ListOverlay`.
> Adjust style of disabled items in SingleSelection and MultiSelection component

- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5024 
Make scheme in sulu_content_path optional and use the correct default scheme from the router context if generating routes.
Currently the scheme is required and we should use when generating routes from cli as default the `%router.request_context.scheme%` parameter. See https://symfony.com/doc/4.1/console/request_context.html#configuring-the-request-context-globally. This avoids that sulu behave different to symfony routes.
Apply the following patch to the sulu skeleton
<details>
<summary>patch.diff</summary>
~~~php
diff --git a/config/services.yaml b/config/services.yaml
index 9ef2ff7..4df6ccf 100644 …
> Use correct default scheme for sulu_content_path

- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/tests/SingleSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/FilterOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/SmartContent.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/types.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/PageBundle/Controller/SmartContentItemController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/QueryBuilderTest.php
- src/Sulu/Component/Content/SmartContent/PageDataProvider.php
- src/Sulu/Component/Content/SmartContent/QueryBuilder.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5017
This PR allows to set the default sort order for the `PageDataProvider`. This is the admin order as given in our webspace page tree if the "Include sub folder" toggle is not set, and an alphabetic representation if the toggle is set.
> Add default sorting for PageDataProvider

- src/Sulu/Component/Rest/ListBuilder/Metadata/Resources/schema/list-2.0.xsd
| Q | A
| --- | ---
This PR add the default values for the `visibility` and `searchability` attribute inside of list comfiguration files.
Because I would like to see the default values for these attributes in my IDE 🙂
> Add default values to schema for attributes inside of list xml files

- src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4100 and fixes #2147
Adds 'id' and 'type' to the array of reserved properties
Using 'id' or 'type' as a property name in a page template results in errors when trying to create/edit pages
> Add 'id' as a reserved property

- composer.json
| Q | A
| --- | ---
| Related issues/PRs | phpDocumentor/ReflectionDocBlock#203
This PR fixes our tests failure cause by an external library for now. I have already created a testcase in the other library: phpDocumentor/ReflectionDocBlock#203
Because otherwise our tests fail.
> Add reflection-docblock conflict to avoid test failures

- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
| Q | A
| --- | ---
Add autowiring for MediaManagerInterface.
Easier usage of the media manager.
```bash
bin/websiteconsole debug:container Sulu\Bundle\MediaBundle\Media\Manager\MediaManagerInterface
```
or:
```php
__construct(MediaManagerInterface $mediaManager) {
}
```
> Add autowiring for MediaManagerInterface

- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5044 
This PR adjusts the `delete()` method of the `MediaManager` to detach all `FormatOptions` of a `FileVersion` before deleting the media. 
This prevents the error described in #5044 .
> Detach FormatOptions entities before deleting Media

- src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig
| Q | A
| --- | ---
Fix sulu view in web profiler without symfony templating.
The symfony/templating syntax can not longer be used.
> Fix sulu view in web profiler without symfony templating

- src/Sulu/Bundle/RouteBundle/Resources/config/manager.xml
| Q | A
| --- | ---
To allow for autowiring the sulu_route.manager.route_manager service.
> Register RouteManagerInterface::class as alias for sulu_route.manager.route_manager service

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/config/list-builder/Media.xml
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
Adds a field for the Download counter in the media list view.
Sadly there is no Issue for this problem, but we needed it.
You can change the list view style in the options.
> Add download counter for media list view

- .github/workflows/test-application.yaml
| Q | A
| --- | ---
| Related issues/PRs | #5072
This PR caches the php-cs-fixer binary.
Because this should result in better performance of the task. Also, this way the cache is actually used, and not only confusingly uploaded at the end.
> Improve php-cs-fixer execution by caching binary

- config/packages/prod/sulu_document_manager.yaml
- config/packages/stage/sulu_document_manager.yaml
| Q | A
| --- | ---
Provide configuration for metadata an dnodes cache provider
Update of the skeleton: https://github.com/sulu/skeleton/pull/36
> Add cache providers for phpcr metadata and nodes

- src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TagMetadata.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TypedFormMetadata.php
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form.xml
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/overview.xml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/FormMetadataProviderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Component/Content/Metadata/Loader/schema/form-1.0.xsd
| Q | A
| --- | ---
This PR add tags to form metadata and the ability to filter types by tags.
This is needed in the article bundle to allow article-type based forms.
~~~php
$this->viewBuilderFactory->createPreviewFormViewBuilder(static::EDIT_FORM_VIEW_DETAILS . '_' . $typeKey, '/details')
->setResourceKey('articles')
->addMetadataRequestParameters([
'tags[sulu_article.type]' => $typeConfig['type'] ? true : false,
'tags[sulu_article.type][type]' => $typeConfig['type'],
])
~~~
OR:
~~~php
$this->viewBuilderFactory->createPreviewFormViewBuilder(static::EDIT_FORM_VIEW_DETAILS . '_' . $typeKey, '/details') …
> Add tags to metadata and add filter for metadata provider

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/Chip.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/chip.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/Chip.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/__snapshots__/Chip.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/multiAutoComplete.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | Extracts 9c735cc007ea5391c35593e106281e1f6284f040 and e7bccf51edcc10e3efa015c08a00000a315b28a0 from #5035 
This PR allows to further customize the `Chip` component.
Because in #5035 we need a bigger representation of them.
> Add size and skin props to Chip component

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/FormInspector.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
- src/Sulu/Bundle/RouteBundle/Controller/RouteController.php
- src/Sulu/Bundle/RouteBundle/DependencyInjection/SuluRouteExtension.php
- src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
- src/Sulu/Bundle/RouteBundle/Resources/js/index.js
- src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/RouteBundle/Tests/Functional/Controller/RouteControllerTest.php
| Q | A
| --- | ---
This PR enables route-generation inside the form without saving for route field-type.
This is a missing feature for article and content-bundle.
Yes - the resource-locator sends now the rlp parts as an object (associated array) to the resource-locator generation API.
> Add generation for route field-type

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/registries/resourceRouteRegistry.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/registries/resourceRouteRegistry.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/Date/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/Date/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/Date/tests/transformDateForUrl.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/Date/transformDateForUrl.js
| Q | A
| --- | ---
| Related issues/PRs | extracts c8d6b514c10e0a54f721a00cec4d92f633926609, parts of 0ce0e153572cff3cdabb613911782dee39191825, b878502fd1e2eb5460218333b89ea1a9c0b6a320 and 2f73e8cbc9f0b32efce6ac27ebda6677e36a62b7, 52fa43d596f7168d7e6c01f8645c5aadf07d8673 and c1dd535e246723439e1575489ef4a07b750e2311 from #5035
This PR allows to add non-scalar values as routing parameters (date, objects, arrays) in the frontend.
Because #5035 needs more complicated routing paramters in order to work.
```diff
diff --git a/src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js …
```
> Allow non-scalar routing parameters in the frontend

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
| Q | A
| --- | ---
This PR adjusts the `List` container to still render the column-options dropdown when searching is disabled for the `List` container.
Because it should still be possible to change the displayed columns even if the list is not searchable.
> Fix display column options in List container even when searching is disabled

- src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/registries/resourceRouteRegistry.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/registries/resourceRouteRegistry.test.js
| Q | A
| --- | ---
For example, the `SetUnpublishedToolbarAction` passes the current locale as boxed observable. Without this fix, this will lead to the following error: `Uncaught RangeError: Maximum call stack size exceeded`
> Fix ResourceRouteRegistry to accept boxed observable inside of parameters

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js
- src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap
- src/Sulu/Bundle/PageBundle/Content/Types/Url.php
| Q | A
| --- | ---
| Fixed tickets | part of #5082
| Documentation PR | https://github.com/sulu/sulu-docs/pull/499
Fix support for custom url protocols and add `tel:` as default.
We should only validate protocols we know how to validate other protocols should just be ignored as valid.
> Fix support for custom url protocols

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/FilterOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/MultiSelectionStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/tests/MultiSelectionStore.test.js
- src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | extracts parts of 28ee000668f12642121777573238297388df2c58 and very small part of b9675176a43d5b397326482ca9519743d864d29a from #5035 
This PR changes the `MultiAutoComplete` container component to accept the `MultiSelectionStore` instead of creating it on its own.
Because this way it is possible to reuse the same store for multiple things, which will result in less requests. Required for the `SelectionFieldFilterType` in #5035.
It changes the interface of the `MultiAutoComplete` container component.
> Allow to reusing MultiSelectionStore by passing it to the MultiAutoComplete

- UPGRADE.md
- src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslation.php
- src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslationMedia.php
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.xml
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslationMedia.orm.xml
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5073 
Fix sorting of category medias
The categories are sortable in the UI so the position should also be saved to the database.
Documented in the UPGRADE.md
> Fix sorting of category medias

- src/Sulu/Bundle/WebsiteBundle/EventListener/RouterListener.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/RouterListenerTest.php
| Q | A
| --- | ---
Use `getBoolean` value for getting `_requestAnalyzer` attribute to support esi correctly.  
When disabling the requestAnalyzer for a esi request like here:
```twig
{{ render_esi(controller('SuluFormBundle:FormWebsite:token', {
'form': form.parent.vars.name,
'html': true,
_requestAnalyzer: false }))
}}
```
On **PROD** environment the esi will generate a url with `/_fragment?...&_requestAnalyer=0` which will then by symfony set as request.attributes. As it is a string it currently does not work and if you called controller does not match sulu will throw a `UrlMatchNotFoundException`. …
> Fix disabled request analyzer for esi requests

- src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
To allow for autowiring the `sulu_category.category_manager` service.
> Register CategoryManagerInterface::class as alias for sulu_category.category_manager service

- src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineJoinDescriptor.php
- src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/FieldDescriptorFactoryTest.php
- src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/Resources/options.xml
| Q | A
| --- | ---
Do not escape join without relation to allow aliases in none relation joins.
Currently if you have a join to an entity without a relation you can not set an alias.
Without alias:
```xml
<joins name="dimension">
<join>
<entity-name>%sulu.model.dimension.class%</entity-name>
<condition>%sulu.model.dimension.class%.locale = :locale AND %sulu.model.dimension.class%.stage = 'draft'</condition>
</join>
</joins>
```
With alias:
```xml
<joins name="dimension">
<join>
<entity-name>dimension</entity-name>
<field-name>%sulu.model.dimension.class%</field-name> 
<condition>dimension.locale = :locale …
```
> Fix aliases for joins without relations

- composer.json
| Q | A
| --- | ---
| Related issues/PRs | part of #4798
Allow usage and installation of twig ^3.0
To allow also the newer version of twig to be installed, will also be needed for Symfony 5 upgrade.
> Allow usage of twig ^3.0

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/CategoryBundle/Content/Types/CategorySelection.php
- src/Sulu/Bundle/CategoryBundle/Content/Types/SingleCategorySelection.php
- src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
- src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/CategoryBundle/Tests/Unit/Content/Types/SingleCategorySelectionTest.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/500
This PR add the configuration for `single_category_selection` and add the `request_parameter` schema-param to the single-selection.
~~~xml
<property name="languageCategory" type="single_category_selection">
<meta>
<title>app.language_category</title>
</meta>
<params>
<param name="request_parameters" type="collection">
<param name="rootKey" value="test"/>
</param>
</params>
</property>
~~~
> Add single-category-selection configuration

- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | part of #4798
Remove kernel.root_dir requirement from cache clearer.
The kernel.root_dir is deprecated since symfony 4 and should not longer be used.
The CacheClearer constructor arguments changed.
> Remove kernel.root_dir requirement from cache clearer

- src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
- src/Sulu/Bundle/CategoryBundle/Command/RecoverCommand.php
- src/Sulu/Bundle/ContactBundle/Command/AccountRecoverCommand.php
- src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
- src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
- src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php
- src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php
- src/Sulu/Bundle/MediaBundle/Command/FormatCacheCleanupCommand.php
- src/Sulu/Bundle/MediaBundle/Command/InitCommand.php
- src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php
- src/Sulu/Bundle/PageBundle/Command/CleanupHistoryCommand.php
- src/Sulu/Bundle/PageBundle/Command/ContentLocaleCopyCommand.php
- src/Sulu/Bundle/PageBundle/Command/MaintainResourceLocatorCommand.php
- src/Sulu/Bundle/PageBundle/Command/ValidatePagesCommand.php
- src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
- src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php
- src/Sulu/Bundle/PageBundle/Command/WebspaceExportCommand.php
- src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
- src/Sulu/Bundle/SecurityBundle/Command/CreateRoleCommand.php
- src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
- src/Sulu/Bundle/SnippetBundle/Command/SnippetExportCommand.php
- src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php
- src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php
- src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
| Q | A
| --- | ---
| Related issues/PRs | part of #4798
Add missing exit status for all commands.
Having commands without exit status is deprecated all commands need to return int in Symfony 5.
None.
> Add missing exit code for all commands

- src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
| Q | A
| --- | ---
This PR fixes the creating of media references in category manager.
When overwriting the media in a project and want to add medias to a category
> Fix creating of media reference in categories

- src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php
- src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
- src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
| Q | A
| --- | ---
A bugfix for smart content with the media provider.
When you add a smart content property using the media provider, the admin will give an error if you select a source without selecting the "include sub elements" option.
The AJAX error response without the fix : 
`{
"code": 0,
"message": "Notice: Undefined index: includeSubFolders",
"errors": [
"ErrorException: Notice: Undefined index: includeSubFolders in /var/www/html/vendor/sulu/sulu/src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php:80\nStack trace:\n#0 /var/www/html/vendor/sulu/sulu/src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrai …
> Fix error when using smart content media provider without includeSubFolders

- src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/config_website.yml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/overview.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/simple.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/templates/default.html.twig
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/WebsiteControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/symfony/symfony/issues/36136
Set the content-type header manually to avoid autodetection of symfony and so avoid a false cache page.
Symfony changed the behaviour in 4.4 and will use the `Accept` header of the client to set the `Content-Type` so if the first request does not accept `text/html` it will be cached as `text/plain` and you then the source code instead of the rendered html.
> Fix handling of content-type header in Website and SearchController

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
| Q | A
| --- | ---
This PR avoids setting the value of the `observable.box` passed to the `Router.bind` function, if it would just be set to `undefined` and back to its original value. That happens when the `Router` has the parameter already set to `undefined`, and the passed `observable.box` already would have the default value.
When a list is loaded with the default limit of 10, it always sends a `settings` request setting the limit to 10, although it has already been 10 previously.
> Avoid setting limit if the default limit has already been set

- src/Sulu/Bundle/CategoryBundle/Category/CategoryManagerInterface.php
| Q | A
| --- | ---
Because the current return type is obviously wrong. 🙂
> Adjust return type of getApiObject method on CategoryManagerInterface

- src/Sulu/Component/Rest/ListBuilder/Filter/DateTimeFilterType.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Filter/DateTimeFilterTypeTest.php
| Q | A
| --- | ---
This PR allows to filter only for the `from` or `to` date. It's working same as when both values are set, just that omitting it means it goes back or forth into infinity.
> Allow to filter with only from or to date

- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/DatePicker.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/DateTimeFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/NumberFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/SelectionFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/TextFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/MultiAutoComplete.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5035 
This PR adds the possibility to retrieve the refs for input elements of the `MultiAutoComplete` and `DateTime` component. This is done to set the focus on these elements in there respective `FieldFilterType`s.
Because this results in a better usability, because less clicks are necessary to setup a filter.
> Focus elements in FieldFilterTypes where appropriate

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/AbstractFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/BooleanFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/DateTimeFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/DropdownFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/TextFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/BooleanFieldFilterType.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/DateTimeFieldFilterType.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/DropdownFieldFilterType.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/TextFieldFilterType.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | introduced in #5035 
This PR also saves the user settings, when only undefined values are removed. But the list should still not reload.
Because otherwise the list will set the stored user setting as default again, when the last item is `undefined` and removed.
> Allow to remove undefined filter

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5100 
This PR introduces a new `showColumnOptions` prop for the `List` container, that allows to hide the  column options.
Because otherwise the column options are also shown in the `selection` field type, as you can see e.g. in the page excerpt and taxonomies tab (the categories and audience targeting selections have the column options displayed, although they should not).
> Hide ColumnOptions in Selection FieldType

- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | part of #4798
Add sulu admin http client service.
The `http_client` service is not available by default in Symfony 5 and the config to activate the `http_client` service does only exist since Symfony 4.4 so we have 2 possibilities.
**A.:** **Keep support for symfony 4.3** Create a custom http_client service like in this pull request. Disadvantage request by a custom http_client are not displayed in the symfony web profiler.
**B.:** **Drop support for `symfony/framework-bundle` 4.3** which basically means dropping whole symfony 4.3 support for sulu 2.1 then we could `prepend` the framework bundle configuration: …
> Add sulu admin http client service

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/ArrowMenu.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/Backdrop.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/tests/Backdrop.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/tests/__snapshots__/Backdrop.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/Dialog.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/Popover.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/__snapshots__/Popover.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/FilterOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | #5138 
This PR makes sure the `Backdrop` of a `DatePicker` is behind the `DatePicker` it self. It does that by putting the `Backdrop` into the same `Portal` as the `DatePicker`, and renders it before the `DatePicker`.
Previously the functionality was dependant on the correct calls of the `createPortal` function. If the `createPortal` for the `Backdrop` was called after the one for the `DatePicker`, the order in the DOM was wrong, and therefore the user clicked on the invisible `Backdrop` instead of the `DatePicker`.
Because otherwise the user cannot click any date on the date picker.
Some props might be …
> Make the datepicker elements clickable for the user

- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/tests/MultiSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Select.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/SelectionFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/SelectionFieldFilterType.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/ResourceMultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/tests/ResourceMultiSelect.test.js
- src/Sulu/Bundle/ContactBundle/Controller/PositionController.php
- src/Sulu/Bundle/ContactBundle/Resources/config/lists/contacts.xml
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/PositionControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5035, dependant on #5138
This PR introduces a new `type` parameter for the `selection` filter. This allows to render the possible values as a simple select dropdown instead of an auto complete field.
Because sometimes this variant is more comfortable to use.
~~~xml
<filter type="selection">                                                                
<params>                          
<param name="displayProperty" value="name" />                                                                                                                                          
<param name="resourceKey" …
> Add select type for SelectionFieldFilterType

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/ResourceMultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/tests/__snapshots__/ResourceMultiSelect.test.js.snap
| Q | A
| --- | ---
Because right now, the loader that is displayed during loading is higher than the `MultiSelectComponent` that is displayed after the data is loaded. This means that the height of the component changes unnecessarily after the data is loaded. This causes a "jump" in the ui as the position of all elements below the component is changed. 
Example: https://sulu.rocks/admin/#/contacts/2/permissions
> Adjust size of Loader in ResourceMultiSelect to prevent height changes

- src/Sulu/Bundle/SecurityBundle/EventListener/SuluSecurityListener.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/SuluSecurityListenerTest.php
| Q | A
| --- | ---
Fix problems with callable classes as controller actions
The SuluSecurityController have problems if the given controller is a callable by itself with a `__invoke` function. 
[InvokeableController](https://symfony.com/doc/4.4/controller/service.html#invokable-controllers)
~~~php
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
* @Route("/api/admin/my-resource", name="my")
*/
class MyAction {
public function __invoke(Request $request, $id) {
return new JsonResponse(['id' => 1, 'name' => 'Test']);
}
}
~~~
> Fix SuluSecurityListener with InvokeableControllers

- src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/SymfonyExpressionTokenProviderTest.php
| Q | A
| --- | ---
Fixes the route generation in articles that have translated routes.
Wrong Route Translation when adding new Article: https://github.com/sulu/SuluArticleBundle/issues/432
> Fixed correct locale for article route generation

- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/index.js
| Q | A
| --- | ---
This PR uses the `array-move` package to sort arrays, because the one from `react-sortable-hoc´ is deprecated
> Use array-move package directly instead of deprecated version from react-sortable-hoc

- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5161
This PR adjusts the `PageAdmin` to include the security systems of the webspaces of the application in the result of the `getSecurityContexts()` method and the `getSecurityContextsWithPlaceholder()` method.
Because the `CreateRoleCommand` and the `SecuritySystemsSelect` rely on the result of these methods to display the available security systems. See #5161.
> Include security systems of configured webspaces in PageAdmin

- src/Sulu/Bundle/ContentBundle/Search/EventListener/HitListener.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Search/EventListener/HitListenerTest.php
| Q | A
| --- | ---
| Bug fix? | Yes
| Fixed tickets | no Ticket existing
| Documentation PR | no documentation
It is a fix to use the indizes for e.g. search. Some indizes aint working without that fix. E.g. Contact.
There exists a problem with the indizes where Contacts would not be able to be searched.
```php
$contactHits = $this->searchManager
->createSearch($queryString)
->locale($locale)
->index('contact')
->execute();
```
> Fix problem with Contacts in Search Index

- UPGRADE.md
- src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
- src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
- src/Sulu/Bundle/SecurityBundle/Entity/Role.php
- src/Sulu/Bundle/SecurityBundle/Exception/RoleKeyAlreadyExistsException.php
- src/Sulu/Bundle/SecurityBundle/Exception/RoleNameAlreadyExistsException.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/forms/role_details.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/lists/roles.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
- src/Sulu/Component/Security/Authentication/RoleInterface.php
| Q | A
| --- | ---
| Related issues/PRs | #3675
This PR adds a `key` property to the `Role` entity. The `key` property is implemented similar to the `key` property of the `Category` entity. 
Furthermore, it adjust the logic to use the `key` property instead of the `name` property for generating the identifier of a role. The identifier of a role is used for restricting access of a user in the [Symfony security configuration](https://symfony.com/doc/current/security.html#securing-url-patterns-access-control).
At the moment, we use the `name` property for generating the identifier of a role. This means that changing the `name` of a role might break the Symfony security configuration of the project. …
> Add key property to Role entity

- config/packages/prod/sulu_document_manager.yaml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/skeleton/pull/40
Currently it not works between website and admin context correctly.
Remove nodes cache config. See also https://github.com/sulu/skeleton/pull/40
> Remove nodes cache config

- UPGRADE.md
- composer.json
- config/bundles.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4798,  https://github.com/sulu/skeleton/pull/46
| Documentation PR | https://github.com/sulu/sulu-docs/pull/503
Remove symfony/web-server-bundle.
The web server bundle is deprecated instead the raw php server or symfony cli should be used.
> Remove symfony/web-server-bundle

- src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
- src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
- src/Sulu/Bundle/PageBundle/Resources/config/command.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Command/ValidateWebspacesCommandTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4798
Make ControllerNameParser optional.
The controller parser does not longer exist in Symfony 5 as there FQCN are used for controller action references. So we need to make the controller parser which is used by the `sulu:content:validate:webspaces` optional.
> Make ControllerNameParser optional

- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/skeleton/pull/45
Use central cache directory for symfony filesystem cache pool.
When change the cache adapter to something like like apc or redis which is more common in production it would behave the same as using the same directory. So there should be no difference when using the filesystem cache or something else and in future we want to go more to be single kernel.
> Use central cache directory for symfony filesystem cache pool

- src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AdminControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing.yml
- src/Sulu/Bundle/PageBundle/Tests/Application/config/routing.yml
- src/Sulu/Bundle/SecurityBundle/Tests/Application/config/routing.yml
| Q | A
| --- | ---
| Related issues/PRs | #4597
This PR removes a few routes that are unnecessary in the tests because of #4597.
Because then appveyor might stop stalling. And better perfomance is always better :slightly_smiling_face:
> Improve test performance by removing some routes that are not neccessary anymore

- config/router.php
| Q | A
| --- | ---
| Related issues/PRs | sulu/skeleton#47
| Documentation PR | sulu/sulu-docs#504
This PR adds the router.php script from the Symfony WebServerBundle.
Because it is required to run Sulu (e.g. the generation of images will not work otherwise).
```bash
php -S 127.0.0.1:8000 -t public config/router.php
```
> Add router script for internal webserver

- phpstan.neon
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5180, https://github.com/sulu/skeleton/pull/45, https://github.com/sulu/sulu/pull/5189
Fix generated container class name.
In all contexts admin, website and preview the `getContainerClassName` should be the same as it is used by symfony as cache seed https://github.com/symfony/symfony/blob/v4.4.7/src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php#L56
> Normalize generated container class name

- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
| Q | A
| --- | ---
Add aliases for the `sulu_media.system_collections.manager` and `sulu_security.salt_generator` services.
The aliases are needed to use the services using a `ServiceSubscriber`
> Add missing service aliases

- composer.json
- src/Sulu/Bundle/PageBundle/Resources/config/export.xml
- src/Sulu/Bundle/PageBundle/Resources/views/Export/Snippet/1.2.xliff.twig
- src/Sulu/Bundle/PageBundle/Resources/views/Export/Snippet/base.export.twig
- src/Sulu/Bundle/PageBundle/Resources/views/Export/Webspace/1.2.xliff.twig
- src/Sulu/Bundle/PageBundle/Resources/views/Export/Webspace/base.export.twig
- src/Sulu/Bundle/SnippetBundle/Resources/config/export.xml
- src/Sulu/Bundle/WebsiteBundle/Controller/SitemapController.php
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap-index.xml.twig
- src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/TestSitemapProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/services.yml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/webspaces/test_with_index.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php
- src/Sulu/Component/Export/Export.php
| Q | A
| --- | ---
Currently on some places we use deprecated `spaceless` and on others we used the newer `apply spaceless` (e.g.: https://github.com/sulu/sulu/blob/2.0.0/src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig#L1). I adjusted all to use the newer version and set the min version to twig to `2.9`.
Apply is availabe since [1.40](https://twig.symfony.com/doc/1.x/tags/apply.html) / [2.9](https://twig.symfony.com/doc/2.x/tags/apply.html)
When adding tests for sitemap index I found also out the if there are multiple providers and only one does return data for the current host still a sitemap index …
> Remove deprecated twig spaceless tag and fix sitemap index for multiple providers

- src/Sulu/Bundle/AdminBundle/Admin/Admin.php
- src/Sulu/Bundle/AudienceTargetingBundle/Admin/AudienceTargetingAdmin.php
- src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
- src/Sulu/Bundle/CustomUrlBundle/Admin/CustomUrlAdmin.php
- src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
- src/Sulu/Bundle/SecurityBundle/Build/UserBuilder.php
- src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
- src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php
- src/Sulu/Bundle/WebsiteBundle/Admin/WebsiteAdmin.php
| Q | A
| --- | ---
This PR is another take on the problem I was trying to solve in #5169.
The PR deprecates the `sulu_security.system` and adds a `SULU_ADMIN_SECURITY_SYSTEM ` constant to make the array returned by the `getSecurityContexts()` method of the `Admin` classes more understandable.
Because setting the `sulu_security.system` in the admin context currently breaks permission related things in the admin. We cannot remove the option because somebody might use it in the website context.
> Deprecate sulu_security.system configuration option

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5177 
This PR makes sure the `SingleMediaSelection` does not endlessly reload if the linked media has been deleted.
> Fix endless reloading if single_media_selection contains deleted image

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5155
This PR changes the way the min size of the crop is calculated. Previously it was based on the ratio between the real and the displayed size, which is only correct for the values that are passed. If the reqeusted format is bigger than the full image the calculation was wrong, because it was downsizing too less.
> Fix minimum size calculation for crops

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Controls.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Items.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap
| Q | A
| --- | ---
This PR makes the toolbar of the Preview shrink, i.e. make the texts disappear, on small screens. It behaves the same way the main toolbar on top does.
> Collapse the preview toolbar on small screens

- .eslintrc.json
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
| Q | A
| --- | ---
I've added a rule to ensure there is only one statement per line.
I've put two lines into a single one by accident and it was not caught by the linter. I've added the rule and almost had no changes to make, so I decided to create a PR.
> Add eslint rule to ensure only one statement is written per line

- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
- src/Sulu/Bundle/MediaBundle/Resources/config/lists/media.xml
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
| Q | A
| --- | ---
This PR fixes the Media list to display the preview image of a media, if one is set. 
This can be tested by the following steps:
1. Upload a `.xls` file (eg [this example file](https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_10.xls))
2. Edit the `.xls` file and set a preview image
3. Navigate back to the media list and see the preview image
Because we want to display the preview image, if the user sets one.
Also, this finally fixes the `MediaControllerTest::testCgetWithPreview` test that annoyed me for quite some time 🙂
> Fix preview image in Media list

- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/DatePicker.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/DateTimeFieldFilterType.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/dateTimeFieldFilterType.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/DateTimeFieldFilterType.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldFilterTypes/__snapshots__/DateTimeFieldFilterType.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
| Related issues/PRs | #5035 
This PR adds labels to the fields in the `ArrowMenu` and updates the texts being shown on the blue `Chip` when only one of both fields is filled.
Because this improves the UX.
> Fix texts for DateTimeFieldFilterType

- src/Sulu/Bundle/PreviewBundle/EventSubscriber/CacheCommandSubscriber.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/EventSubscriber/CacheCommandSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4369
Fix clearing of preview cache.
Currently the preview cache is not cleared when running `bin/console cache:clear` and so changes in twig files has no effect under `prod`. 
1. Change env to `.prod`
2. Open page with preview
3. Change `.html.twig`  preview
4. Run bin/console cache:clear
5. Preview should show changes
> Fix clearing of preview cache

- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Security/LogoutSuccessHandler.php
| Q | A
| --- | ---
Handle logout for normal http requests
Sometime we may need to call the logout action from pages that don't use ajax to do it.
> Handle non ajax logout request

- src/Sulu/Bundle/PreviewBundle/EventSubscriber/CacheCommandSubscriber.php
| Q | A
| --- | ---
| Related issues/PRs | #4782
Aslong the PreviewKernel extends from App\Kernel we need to check in this listener if `App\Kernel` exist and only then allow to clear also the preview cache.
This lines can be removed when https://github.com/sulu/sulu/issues/4782 is fixed.
Currently all bundles with use of `cache:warmup` to generate data for phpstan crash because they don't have a App\Kernel in it.
> Run preview cache clear command only when App\Kernel exists

- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5185 
This PR avoids sending the internal `__id` from the blocks to the server. This sometimes introduced some problems, see e.g. #5185.
> Avoid setting id properties on block values

- src/Sulu/Bundle/MediaBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/SuluMediaExtensionTest.php
- src/Sulu/Bundle/PageBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
- src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4798
Get ride of usage of kernel.root_dir.
The kernel.root_dir is deprecated, as the test SuluTestKernel did use it as project_dir I copied there logic the from Symfony 4.4 https://github.com/symfony/symfony/blob/3aa7f0c5bfc108161bce6e2e8bf74fe696f49af2/src/Symfony/Component/HttpKernel/Kernel.php#L346-L347 to avoid breaking TestKernels.
> Get ride of usage of kernel.root_dir

- phpstan.neon
| Q | A
| --- | ---
Because these errors no longer occur as the behaviour of `class_exists()` was changed in version 0.12.19 of phpstan: https://github.com/phpstan/phpstan/releases/tag/0.12.19
> Remove ignoreErrors section from phpstan.neon

- src/Sulu/Bundle/AudienceTargetingBundle/EventListener/DeviceDetectorSubscriber.php
- src/Sulu/Bundle/AudienceTargetingBundle/EventListener/TargetGroupSubscriber.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/TargetGroupSubscriberTest.php
- src/Sulu/Bundle/MarkupBundle/Listener/MarkupListener.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/MarkupListenerTest.php
- src/Sulu/Bundle/SecurityBundle/EventListener/SuluSecurityListener.php
- src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/SuluSecurityListenerTest.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/UserLocaleListenerTest.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/RedirectExceptionSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/RouterListener.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorListener.php
- src/Sulu/Bundle/WebsiteBundle/EventSubscriber/GeneratorEventSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/Routing/RequestListener.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/RouterListenerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorListenerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RedirectExceptionSubscriberTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RequestListenerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4798
Update usage of new kernel event classes.
The old classes are deprecated since symfony 4.3 so and the new classes extends from the old one so you have on the event classes access to the same.
> Update usage of new kernel event classes

- src/Sulu/Bundle/WebsiteBundle/DataCollector/SuluCollector.php
| Q | A
| --- | ---
| Related issues/PRs | part of https://github.com/sulu/sulu/pull/4798
Update symfony/http-kernel and fix SuluCollector compatibility.
PHP 7.2 and 7.3 does not support override a function with less specified type. (Covariance and Contravariance in PHP)[https://www.php.net/manual/en/language.oop5.variance.php]. So to get around this error we would need to upgrade http-kernel to 4.4. EDIT: update was done in #5238
> Fix SuluCollector compatibility

- UPGRADE.md
- composer.json
- src/Sulu/Bundle/CategoryBundle/Event/CategoryDeleteEvent.php
- src/Sulu/Bundle/PreviewBundle/Preview/Events/PreRenderEvent.php
- src/Sulu/Bundle/SearchBundle/Search/Event/StructureMetadataLoadEvent.php
- src/Sulu/Bundle/TagBundle/Event/TagDeleteEvent.php
- src/Sulu/Bundle/TagBundle/Event/TagMergeEvent.php
- src/Sulu/Component/Content/Mapper/Event/ContentNodeDeleteEvent.php
- src/Sulu/Component/Content/Mapper/Event/ContentNodeEvent.php
- src/Sulu/Component/Content/Mapper/Event/ContentNodeOrderEvent.php
- src/Sulu/Component/DocumentManager/Event/AbstractEvent.php
- src/Sulu/Component/DocumentManager/EventDispatcher/DebugEventDispatcher.php
- src/Sulu/Component/Rest/ListBuilder/Event/ListBuilderCreateEvent.php
- src/Sulu/Component/Security/Event/PermissionUpdateEvent.php
| Q | A
| --- | ---
| Related issues/PRs | part of https://github.com/sulu/sulu/pull/4798
Extend sulu event from new event class. ~~This is no BC Break as the new class does extend the old one in symfony 4.3 and 4.4.~~
The Symfony Component Event was deprecated in 4.3 and moved the event contracts.
> Extend sulu event from new event class

- src/Sulu/Bundle/PageBundle/Resources/config/forms/page_settings.xml
| Q | A
| --- | ---
| Related issues/PRs | related to #1527
Remove navigation context from homepage.
Currently the homepage is never shown so we should hide that option from the settings tab for the homepage.
> Remove navigation context from homepage

- src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | part of #4798, https://github.com/symfony/symfony/issues/36495 
Change service definition for DefaultController.
~~Not sure why but the alias does not longer work and the controller does not get the container correctly set. So at current state only switch alias and id did work supporting symfony 5.~~
As shown in the linked symfony issue we need to make the service and alias public that it works in symfony 5.
> Change service definition for DefaultController

- CHANGELOG.md
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4422
Fix copy language with different template
If you copy the template should also be the same as from the source language.
> Fix copy language with different template

- src/Sulu/Bundle/CustomUrlBundle/EventListener/CustomUrlSerializeEventSubscriber.php
- src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/CustomUrlSerializeEventSubscriberTest.php
| Q | A
| --- | ---
| Related issues/PRs | part of #4798 
Fix custom url serialization without creator or changer.
Some tests did fail because of this on symfony 5 branch but for performance I would avoid try to load a creator fullname and so I thought its good to backport it to the 2.0 branch.
> Fix custom url serialization without creator or changer

- src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php
- src/Sulu/Bundle/WebsiteBundle/Event/CacheClearEvent.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Cache/CacheClearerTest.php
| Q | A
| --- | ---
Fix deprecated cache clear event.
Throwing an event without an object is deprecated, so we need to create a new CacheClearEvent class.
> Fix deprecated cache clear event

- src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/fields/PageTreeRoute.js
| Q | A
| --- | ---
New articles are currently created with the path of the parent page instead of the url. Thus new articles for parent-pages could be created, but the smart-content never listed them correctly, if the url was changed.
> Fix PageTreeRoute component

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5219 
This PR makes sure that an empty array and `undefined` are handled the same in the `auto_complete` type of the `selection` field type.
When creating a new page with the given `example` template, there will be a message asking if you want to leave the form before the user is redirected to the edit form.
> Avoid setting form to dirty in autocomplete selection when creating a new page

- config/webspaces/sulu-test.xml
- src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/TeaserSelection.js
- src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/tests/TeaserSelection.test.js
| Q | A
| --- | ---
The `autorun` call of the `TeaserSelection` was not disposed when the component is unmounted.
When switching between the locale on a page with a `teaser_selection` multiple times, you can observe how more and more requests for loading teasers are sent.
There is another bug which makes the teaser being loaded for the old and new language, so there are still two loads currently. This is not fixed in this PR, but also multiple switching should not increase that number anymore.
> Fix multiple requests when switching between locales for teaser selection

- src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php
- src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes  #5245 
Invalidate media cache file on warmup.
I have changed test to use PHPUnit without `prophesize`. I think it's more clear . WDT?
No BC Breaks
> Invalidate System collections cache in warmUp

- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslationMedia.orm.xml
| Q | A
| --- | ---
When overwriting the `CategoryTranslation` Entity, an error is thrown after the execution of `bin/adminconsole doctrine:schema:validate`.
```
[FAIL] The entity-class Sulu\Bundle\CategoryBundle\Entity\CategoryTranslationMedia mapping is invalid:
* The association Sulu\Bundle\CategoryBundle\Entity\CategoryTranslationMedia#categoryTranslation refers to the inverse side field Sulu\Bundle\CategoryBundle\Entity\CategoryTranslation#medias which does not exist.
```
This PR fixes the `target-entity` of the `CategoryTranslationMedia.orm.xml` file to prevent this error.
> Use interface of CategoryTranslation for CategoryTranslationMedia

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5253
This PR adjusts the `MediaSelection` field to throw an error with a meaningful message if the given value does not match the expected format.
Because it is a frequent mistake to pass an array of ids to the field. This leads to a cryptic error message at the moment.
Adjust the `read()` method of the `MediaSelectionContentType` to match this:
```
public function read(
NodeInterface $node,
PropertyInterface $property,
$webspaceKey,
$languageCode,
$segmentKey
) {
$data = json_decode($node->getPropertyValueWithDefault($property->getName(), '{"ids": []}'), true);
$property->setValue(isset($data['ids']) ? [] : null);
}
```
Then open the `Create Page` form, …
> Throw meaningful error when value of MediaSelection field does not match expected format

- src/Sulu/Component/Security/Authorization/SecurityChecker.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/SecurityCheckerTest.php
| Q | A
| --- | ---
| Related issues/PRs | part of #4798 
Fix deprecation in authorizationChecker isGranted.
Symfony does not longer allow to give an array to the isGranted function it need to be a single entity [now](https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#security).
> Fix deprecation in authorizationChecker isGranted

- src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ChildrenCollectionTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/Collection/QueryResultCollectionTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ReferrerCollectionTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/Metadata/BaseMetadataFactoryTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/ProxyFactoryTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/Query/QueryTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/FindSubscriberTest.php
- src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/RefreshSubscriberTest.php
| Q | A
| --- | ---
| Related issues/PRs | part of #4798 
Fix EventDispatcher Test compatibility.
In Symfony 5.0 the dispatch function must return an object.
> Fix EventDispatcher Test compatibility

- config/templates/pages/homepage.xml
- src/Sulu/Bundle/AdminBundle/Resources/config/serializer/ProviderConfiguration.xml
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SmartContent.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContent.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/SmartContent.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/types.js
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Content/SnippetDataProvider.php
- src/Sulu/Component/Contact/SmartContent/AccountDataProvider.php
- src/Sulu/Component/Contact/SmartContent/ContactDataProvider.php
- src/Sulu/Component/Content/SmartContent/ContentDataItem.php
- src/Sulu/Component/Content/SmartContent/PageDataProvider.php
- src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
- src/Sulu/Component/SmartContent/Configuration/Builder.php
- src/Sulu/Component/SmartContent/Configuration/BuilderInterface.php
- src/Sulu/Component/SmartContent/Configuration/ProviderConfiguration.php
- src/Sulu/Component/SmartContent/Configuration/ProviderConfigurationInterface.php
- src/Sulu/Component/SmartContent/Tests/Unit/BuilderTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5219 
| Documentation PR | sulu/sulu-docs#511
This PR adds deep links to the smart content. Therefore the configuration returned by different `DataProvider`s had to be extended, so that the smart content knows where the link should go.
Because it is a useful feature.
> Add deep links for smart content

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
| Q | A
| --- | ---
This PR fixes the `userSchema` property of the `ListStore` to include all properties of the schema if there are existing `schemaSettings` for the current user. At the moment, the `userSchema` contains only schema properties that were present when the `schemaSettings` were saved.
Because the `userSchema` property is used for rendering the display options of the list. At the moment, if there are existing `schemaSettings` for a user, the user will not see new schema properties in his UI. This is a common problem during development.
> Include all schema properties in userSchema of ListStore

- bin/runtests
- src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/exception_controller.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Controller/ExceptionControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5266, part of #4798 
Register deprecated exception controller when decorated service exist.
Else it will fail on symfony 5 when the parent services dont exist in container build.
> Register deprecated exception controller when decorated service exist

- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/PublishIndicator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/publishIndicator.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/SmartContentItem.test.js.snap
| Q | A
| --- | ---
| Fixed tickets | fixes #5268 
This PR adjusts the `PublishIndicator`, so that it does not break over multiple lines.
> Fix broken PublishIndicator in SmartContent

- src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionBuilderTest.php
- tests/Resources/DataFixtures/Webspace/language-specific/sulu.io.xml
| Q | A
| --- | ---
Fix partial portal matching for url for specified language.
When have the following portal:
```xml
<url language="en" country="uk">uk.mydomain.com/{language}</url>
<url language="de" country="at">austria.mydomain.com/{language}</url>
```
The partial portal mapping does not work this means `/`is not redirected to `/en` and `/sitemap.xml` will not work.
In the project they had the following url `austria.mydomai.com/de` but as we can not just replace `de` i suggested to use `{language}` placeholder but that doesn't currently work so it need to replaced correctly also there and that the partial map work the …
> Fix partial portal matching for url for specified language

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SetUnpublishedToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
| Q | A
| --- | ---
This PR adjusts the `SetUnpublishedToolbarAction` to not throw an error if the resource store of the form does not have a locale.
Because right now, the `SetUnpublishedToolbarAction` cannot be used for unlocalized entities.
> Allow to use SetUnpublishedToolbarAction for unlocalized entities

- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR adjusts the `MediaOverview` view to disable the upload toolbar-action when a system collection is opened.
Because the dropzone for uploading images does not work inside of system collections. This is quite confusing if you do not know that it is not possible to upload something into a system collection via the administration interface.
> Disable upload toolbar-action inside of system collections

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #5283
Conflict doctrine/infector 1.4.0 and 2.0.0 version.
They are not compatible with sulu as they introduced a bug which should be fixed in newer version (https://github.com/doctrine/inflector/pull/142).
> Conflict doctrine/infector 1.4.0 and 2.0.0 version to fix media routes

- src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/LinkTagTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5286
| Related issues/PRs |
Check if href attribute is set if not ignore it and mark link as not validate.
It should not crash if an invalid sulu-link without href is in the text editor. Seems like the new ckeditor does remove an empty href tag.
> Fix error when sulu link has no href attribute

- src/Sulu/Component/SmartContent/PublishInterface.php
| Q | A
| --- | ---
Allow DateTimeInterface in PublishInterface.
In some cases we use the \DateTimeImmutable which works but phpstan will fail.
No BC Break as it now allows more be returned as before and as it only is a phpdoc the inheritance will not fail.
> Allow DateTimeInterface in PublishInterface

- src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
- src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
| Q | A
| --- | ---
This PR fixes a bug that occured when the `DataProviderRepositoryTrait` without any sorting. This can be reproduced by using the following property in an XML file:
```xml
<property name="accounts" type="smart_content">
<meta>
<title lang="en">Accounts</title>
</meta>
<params>
<param name="provider" value="accounts"/>
</params>
</property>
```
The following error should appear without this fix:
```
Notice: Trying to access array offset on value of type null
```
> Fix sorting of smart content when used with doctrine

- config/templates/pages/example.xml
- src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
- templates/pages/example.html.twig
| Q | A
| --- | ---
| Fixed tickets | fixes #5295 
| Related issues/PRs | #5106 
This PR adds the missing service for the `SingleCategorySelection` field type.
Because otherwise the content type cannot be used.
~~~xml
<property name="single_category" type="single_category_selection" />
~~~
> Add missing service definition for SingleCategorySelection

- src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202005250917.php
- src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php
| Q | A
| --- | ---
Adds missing migration for `sortBy` property in snippets and pages.
> Add smart-content migration for sortBy

- src/Sulu/Bundle/WebsiteBundle/Controller/ErrorController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Controller/ErrorControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5314 
Fix for #5314
> Fix errors happening on error template rendering

- src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5184
Use in test same container class name as in other env.
Was forgot in https://github.com/sulu/sulu/pull/5184
If used for phpstan he need to configure phpstan to the new path, but that was also the case for projects.
> Use in test same container class name as in other env

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Document/SnippetInitializer.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
- src/Sulu/Component/Util/SuluNodeHelper.php
| Q | A
| --- | ---
Fix /cmf/snippets node not exist in live workspace.
Currently /cmf/snippets is only created in default workspace which will fail on website  until a new snippet is created.
Use https://github.com/sulu/sulu/blob/851fc5464886e8cee65e4d2ed523620e16b00a96/config/templates/pages/homepage.xml#L48-L55
and do `bin/console sulu:build dev --destroy` and visit snippet error.
> Fix /cmf/snippets node not exist in live workspace

- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/SnippetAreas.js
- src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/tests/SnippetAreas.test.js
- src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/tests/__snapshots__/SnippetAreas.test.js.snap
- src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
- src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManagerInterface.php
- src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/snippets/car.xml
- src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/snippets/hotel.xml
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetAreaControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
- src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5311 
This PR fixes the name of the query parameter used for filtering snippet areas.
> Fix filtering of snippets when choosing snippet areas

- appveyor.yml
| Q | A
| --- | ---
Use in appveyor stable version of composer.
Currently appveyor does install a 2.0.0-dev version.
> Use in appveyor stable version of composer

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/Login.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/updateUserStoreContentLocaleFromRouterAttributes.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/PageList.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/PageTabs/PageTabs.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
- src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/SnippetAreas.js
| Q | A
| --- | ---
This PR removes the `any` type from the router attributes, which allows flow to warn us if router attributes are not used in a safe manner.
To avoid errors [like in this PR](https://github.com/sulu/sulu/pull/5277#discussion_r435861926).
> Add better typing for router attributes

- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5332 
The wrong variables were used for checking if the user has permission to delete accounts, this PR fixes that.
> Fix account permissions

- src/Sulu/Component/Rest/Exception/InvalidSearchException.php
- src/Sulu/Component/Rest/Exception/SearchFieldNotFoundException.php
- src/Sulu/Component/Rest/ListBuilder/AbstractListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- src/Sulu/Component/Rest/RestHelper.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
- src/Sulu/Component/Rest/Tests/Unit/RestHelperTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5227 
This PR adds better error messages, when invalid list search are triggered.
Because #5227 shows that this irritated people, because the shown error messages were very cryptic.
1. Call a URL like this: ` /admin/api/contacts?page=1&limit=10&fields=avatar,firstName,lastName,mainEmail,account,city,mainPhone,id&flat=true&search=Daniel&searchFields=non-existing`
2. Do a search form a list where not a single search field has been defined.
> Show better error messages for invalid list searches

- src/Sulu/Bundle/PageBundle/Resources/js/stores/webspaceStore/tests/webspaceStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5277 
In #5277 the structure of the webspace changes, and therefore the `defaultWebspace` object changed as well. But it was not already used everywhere, so I am introducing that here, in order to make the other PR smaller.
> Use defaultWebspace in tests where appropriate

- composer.json
| Q | A
| --- | ---
This PR introduces `psr/event-dispatcher` as a dev dependency.
Because in version 1 of [`symfony/event-dispatcher-contracts`](https://github.com/symfony/event-dispatcher-contracts/blob/v1.1.7/EventDispatcherInterface.php#L16) this dependency is optional and will not be installed. And then extending from it will make phpstan fail.
> Fix phpstan error

- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/PublishIndicator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/AbstractTableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/abstractTableAdapter.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TreeTableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/TableAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
| Q | A
| --- | ---
| Fixed tickets | fixes #5225
Show publish indicator on list
Because it's displayed in the `column_list` adapter, but not in the `table` and `tree_table` adapters.
> Show publish indicator on list

- composer.json
| Q | A
| --- | ---
Add svg support by default.
I think we should provide the svg support by default, its just something which will be forget in many projects to be added. As the svg library doesn't have big [requirements](https://github.com/contao/imagine-svg/blob/master/composer.json) I think we should install it by default. Also there will be a stable 1.0 release soon: https://github.com/contao/imagine-svg/issues/22
/cc @sulu/core-team what do you think?
> Add svg support by default

- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_webspace_expression_param.xml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/FormMetadataProviderTest.php
| Q | A
| --- | ---
This PR allows to use the `metadataOptions` passed to the `AdminController::metadataAction` as variables in the a parameter expression.
Because that might be useful in certain situations. It was actually implemented for #5277, but it turned out that we can't use it there. Would be a shame to just withdraw it, therefore I am creating a separate PR.
Call of metadata URL like `/admin/metadata/form/page?webspace=sulu-blog` could use the `webspace` variable containing a value of `sulu-blog` like in the following metadata definition:
~~~xml
<?xml version="1.0" ?>
<form …
> Add metadataOptions to FormMetadataProvider evaluations

- src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslationInterface.php
| Q | A
| --- | ---
Fix category medias typehint.
We should use the MediaInterface instead directly the Media entity in typehints.
> Fix category medias typehint

- src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/LocationOverlay.js
- src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/LocationOverlay.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5389
This PR adjusts the overlay of the `Location` component to accept 0 as valid latitude and valid longitude.
> Accept zero as valid latitude and longitude in Location component

- src/Sulu/Component/Content/Document/Subscriber/Compat/ContentMapperSubscriber.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5376
project/vendor/sulu/sulu/src/Sulu/Component/DocumentManager/Subscriber/Phpcr/RemoveSubscriber.php:46 is set to 500 as well. So I change this weight to 550 and it runs before the PHPCR node is set to "removed".
See #5376
> Make sure ContentMapperSubscriber runs before the RemoveSubscriber

- webpack.config.js
| Q | A
| --- | ---
Activate cacheDirectory for the webpack [babel-loader](https://webpack.js.org/loaders/babel-loader/).
Performance Improvements for multiple builds:
*Without cache active:*
```bash
59.18 real        86.69 user         5.81 sys
```
*With cache active:*
```bash
26.96 real        37.32 user         3.66 sys
```
I'm targeting master branch as I'm not sure if it could have any side effects in our setup. 
~~~bash
time npm run build
~~~
> Activate babel cacheDirectory

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/variables.scss
| Q | A
| --- | ---
| Fixed tickets | fixes #5377
This PR sets a `max-height` to the `Dialog` component. The height handling is implemented similar to the existing height handling of the `Overlay` component. 
Because the `Dialog` might overflow the screen and therefore hide the control buttons if there is a lot of content. If this happens, the user cannot close the dialog via the user interface anymore. See #5377
> Set max-height for Dialog component to prevent hidden controls

- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentPathTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5364
This PR adjusts the `WebspaceManager` to add the port of the current request to generated urls, if the urls match the host of the current request. This fixes the url generation for the following services when serving a website via a non-default port:
* `ContentPathTwigExtension` (port was already added by the service itself before)
* `PageLinkProvider`
* `PagesSitemapProvider`
* `ContentRouteProvider`
* `SitemapTwigExtension`
* `RedirectEnhancer`
* `SeoEnhancer`
Because a lot of developers serve their application via a non-default (eg `8080`) port during development. At the moment, in such a setup, the links generated by the services listed above …
> Add port to urls generated by the WebspaceManager

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Cropper/Cropper.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Cropper/CropperTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5372, fixes #5385
This PR fixes two different issues that occur when defining crops for images:
At the moment, the selected area is not updated to match the ratio of the selected format, when a format that has no defined crop is selected. 
The problem here is that `RectangleSelection` component rendered its content before updating the `normalizers` that are used for determining the selected area in its `componentDidUpdate` method. After the `normalizers` were updated, the component was not rerendered because the `this.normalizers` property is no observable.
Currently, the `RectangleSelection` behaves incorrectly when the minimum dimensions are bigger …
> Fix behaviour of crops when minimum dimensions are bigger than selectable area

- composer.json
| Q | A
| --- | ---
| Related issues/PRs | #5353
Remove requirement to urlizer.
The urlizer was removed in #5353 but seems in a merge commit a conflict was false resolved.
> Remove urlizer requirement

- src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php
- src/Sulu/Bundle/RouteBundle/Document/Subscriber/RoutableSubscriber.php
| Q | A
| --- | ---
Fix nullable metadata in routeable subscriber.
Metadata can be returning null and should then fallback to the default behaviour.
> Fix nullable metadata in routeable subscriber

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/field.scss
| Q | A
| --- | ---
Set the width of the types select field to 150px to also show longer block names
To show longer block names in full length
> Fix block types select width and overflowing form width in Firefox

- src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
- src/Sulu/Bundle/SearchBundle/Tests/Application/Kernel.php
- src/Sulu/Bundle/SearchBundle/Tests/Application/config/config.yml
- src/Sulu/Bundle/SearchBundle/Tests/Application/config/config_test_search_adapter.yml
- src/Sulu/Bundle/SearchBundle/Tests/Application/config/routing.yml
- src/Sulu/Bundle/SearchBundle/Tests/Application/config/webspaces/sulu.io.xml
- src/Sulu/Bundle/SearchBundle/Tests/Application/templates/search.html.twig
- src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php
- src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/WebsiteSearchControllerTest.php
- src/Sulu/Bundle/SearchBundle/Tests/Unit/Controller/WebsiteSearchControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluHeadlessBundle/pull/37 https://github.com/sulu/sulu/pull/3263
This PR adjusts the `WebsiteSearchController` to not add quotes around the query string for the fuzzy matching search terms. 
These removed quotes were introduced in #3263 with the reason `Words containing special characters have led to empty search result.`. I am not sure if this reason was correct because the `preg_replace('/([^\pL\s\d])/u', '?', $queryValue)` should actually remove all special characters.
At the moment, searching for `keywor` creates the following query: `+("keywor" OR "keywor*" OR "keywor~")`
As the fuzzy matching search terms (`"keywor*"`, …
> Fix fuzzy matching in WebsiteSearchController by omiting quotes from query

- src/Sulu/Bundle/ContactBundle/Api/Contact.php
- src/Sulu/Bundle/ContactBundle/Entity/Contact.php
- src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5358
| Related issues/PRs | replaces #4895
This PR adds a `positionName` property to the serialized representation of the contact entity. This serializer representation is returned by the `ContactAccountSelection` and by the `contacts` smart-content data-provider.
The PR also adjusts the `ContactRepository` to join the respective tables to prevent the lazy-loading of entities during serialization. I tested the adjustments and did not notice any additional queries in the Symfony profiler.
See #5358
> Add position name to serialized contact

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Entity/AbstractAccount.php
- src/Sulu/Bundle/ContactBundle/Entity/Contact.php
| Q | A
| --- | ---
This PR sets the type of the `tags` property to `array`.
In a project JMS Serializer was not able to recognize this type correctly, but used `ArrayCollection` instead of `array` as type. And because the type is not set correctly, a function is called with a wrong argument, and a PHP error is thrown because of that. I don't really know why that happens, and it does not occur in the core of Sulu, but this addition fixes that problem for that project.
> Correct serialization type of tags for Accounts and Contacts

- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
| Q | A
| --- | ---
This PR removes a scalar type hint from the code.
Because scalar type hints do not work in PHP 5.5, which is still supported by Sulu 1.6
> Fix compatibility of tests with PHP 5.5 by removing scalar type hint

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Entity/FormatOptions.php
- src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5409
I added type casts and return types to the FormatOptions Entity Object.
As JS could provide FLOATs this might be a good place to make sure SULU and it's DB is working with INTs in the end.
By doing this I figured that
`$fileVersion->addFormatOptions($formatOptions);`
relies on
`$formatOptions->setFormatKey($formatKey);`
is already called or the array key will be NULL
No clue how this ever could have been able to run but probably the array of format options is never used.
PHPStorm tells me that return self is PHP > 7 and the 1.6 still supports 5.5
JS might provide FLOATS and at least PGSQL will not save the crop then.
> Store values from image crop as integers

- src/Sulu/Bundle/AudienceTargetingBundle/Content/Types/AudienceTargetingGroups.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Content/Types/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Content/Types/AudienceTargetingGroupsTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Export/WebspaceExportTest.php
| Q | A
| --- | ---
This PR fixes the export function of the audience-target selection when the data is empty.
The export requires a string as result.
> Fix export data function of audience-target selection

- src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateCommand.php
- src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateFormats.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Command/FormatCacheRegenerateCommandTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Command/FormatCacheRegenerateFormatsTest.php
| Q | A
| --- | ---
| Bug fix? | Kinda
| New feature? | Yes
In this PR i added a command which iterates over the current image cache and refreshes it.
You can use this command instead of `rm -rf public/media/uploads` to regenerate/refresh image cache.
This because removing the image cache `rm -rf public/uploads/media` is a bad idea. 
When you do this, you create a giant load on your server because it start alot of PHP-fpm processes for cutting out the images. 
We've expierenced a problem where OOMKILLER jumped in to shoot mysql and elastic and the website went down.
I was discussing this with @alexander-schranz in slack and he asked me to create a PR for this command.
https://sulu-io.slack.com/archives/C0430GGCV/p1593690512302700 
``` …
```
> Add command for regeneration formats

- src/Sulu/Bundle/PageBundle/Resources/config/document.xml
- src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
| Q | A
| --- | ---
This PR will also write security information of pages on the live workspaces.
Because we need that information in the live workspace, in order to implement security for pages on the website. That is a prerequisite for #5439 and #5446.
> Write permissions of pages also to live workspace

- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
- src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
| Q | A
| --- | ---
This PR adds all available permissions from a anonymous role to the anonymous role of this system.
Because the security system is implemented in a way, that it does not grant access, if it does not have any permissions on the given security context, even if the object under investigation has added security for the given role.
Because of that it might also make sense to make the anonymous roles editable in the UI, because if e.g. a new webspace is added, the anonymous role will lack the permissions for that webspace. Also somebody might want to disallow an entire webspace only for the anonymous role. That …
> Add all available permissions to anonymous roles

- src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateCommand.php
| Q | A
| --- | ---
| Related issues/PRs | #5393 
Fix format regenerate command on windows.
The command didn't use the directory seperator so it failed on windows. Appveyor did fail but did not notice that because we currently have a failing appveyor because of the audience targeting / jms serializer bug.
> Fix format regenerate command on windows

- src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | that the permissions are written to live workspace #5439 is needed
Add Pages Security Check in ContentRouteProvider.
We want to disallow specific user to access specific pages on the website.
1. Add System to Webspace
2. Activate Security for the Project
3. Run `bin/console sulu:security:init`
4. Disallow Anonymous user for a specific page
-
> Add Pages Security Check in ContentRouteProvider

- config/packages/fos_http_cache.yaml
- config/packages/fos_rest.yaml
- config/routes/fos_http_cache.yaml
- tests/Kernel.php
| Q | A
| --- | ---
Add user context based cache configuration.
See https://github.com/sulu/skeleton/pull/70
> Add user context based cache configuration

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Select.test.js
| Q | A
| --- | ---
| Bug fix? | maybe
| Fixed tickets | fixes #5388
This PR adjusts the `Select` field to filter out invalid entries when the selection is changed.
Because the current value might contain entries which are not valid (see #5388). For example, this happens if a selected value is removed from the template of a page.
> Filter out obsolete entries when changing value of Select field

- src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5439 
This PR fixes an issue that was probably introduced by #5439. If a webspace does not have a security system attached (that means no `<security>` tag in the webspace config), no elements are shown in e.g. the navigation or smart content.
Because in #5439 that case was not considered.
Use the sulu/skeleton template repository, create a few pages, and assign them to the navigation. The navigation will still be empty, unless this PR is checked out.
> Fix security for webspaces without a system

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
| Q | A
| --- | ---
| Related issues/PRs | mobxjs/mobx#2430, webpack/webpack#11312
This PR adds a `toJS` to the JSX passed via a mobx store, because since mobx 4.15.5 the internals of react also seem to be tracked by mobx, and causes an error when react tries to change those later. See also mobxjs/mobx#2430 for more details.
1. Make a development build using `npm run watch`
2. Open an existing page in Sulu
3. Before this PR the screen will turn blank and an error is shown in the dev tools
> Fix mobx regression causing error in development build

- src/Sulu/Bundle/AdminBundle/Exception/InvalidRootTagException.php
- src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_invalid_root_tag.xml
| Q | A
| --- | ---
This PR throws a proper exception when a file with a root tag not suitable for a form is interpreted as a form.
Because when people want to make use of XML Includes, they might want to create a `fragments` folder within `config/forms` and put them there. If they do so, it will result in a cryptic error like this:
```
Notice: Trying to get property 'nodeValue' of non-object
```
That's because the program tries to load the key from the form, but the fragment most often does not even have a `key` under a `form` tag, and that's why the code fails.
In order to make that at least a little bit more …
> Throw proper error message when invalid form XML is loaded

- composer.json
| Q | A
| --- | ---
Require https://github.com/composer/package-versions-deprecated
Fix composer 2 compatibility for php 7.3 and lower. Think require it will make the developers which use sulu the least problems.
Alternative require https://github.com/sulu/skeleton/pull/60 and add it here only as dev dependency.
This is needed as following https://github.com/Ocramius/PackageVersions/pull/133 was not backported to supported PHP Versions of Ocramius/PackageVersions.
We currently targeting `release/2.0` branch as the bridge package does only support `php 7` and our `1.6` still supports PHP 5: …
> Fix composer 2 compatibility for php 7.3 and lower

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleListOverlay/SingleListOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleListOverlay/tests/SingleListOverlay.test.js
| Q | A
| --- | ---
| New feature? | maybe
| Documentation PR | https://github.com/sulu/sulu-docs/pull/541
The PR implements the handling of the `resource_store_properties_to_request` schema-option for the `SingleSelection` field.
The functionality is implemented for the `list_overlay` type of the field and behaves the same as the `resource_store_properties_to_request` schema-option of the `Selection` field.
Because there was a request in our Slack channel for this some time ago. Also, the `Selection` field already implements this functionality.
~~~xml
<property name="testParameter" type="text_line" mandatory="true">
<meta>
<title lang="en">Test Parameter</title>
<title lang="de">Test Parameter</title>
</meta> …
> Implement handling of resource_store_properties_to_request param in SingleSelection field

- src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
| Q | A
| --- | ---
Fix user refresh on test user provider. Not sure how to test it as the TestBundle itself has no test setup.
Currently refreshUser will return false user when requesting a none test user in it.
Website Login Test:
```php
$client->request('POST', '/login', ["_username": "..", "_password": "..."]);
$client->followRedirect(); // should be redirect to a url secured by the firewall
$this->assertHttpStatus(200, $client->getResponse()); // will fail and redirect ro login
```
Will be redirect to login as username of the refresh user doesn't match with the one in the session
> Fix user refresh on test user provider

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tab.scss
| Q | A
| --- | ---
This PR avoids that the tab component adds a line break to longer texts.
Because the text is not supposed to be broken into multiple lines. You can test that e.g. when having the navigation pinned on the page form with a preview on the right side. Then the "Excerpt & Taxonomies" tab will be written in two lines.
> Avoid line break in tab with long text

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/README.md
| Q | A
| --- | ---
| Related issues/PRs | #4459
| Documentation PR |---
This PR fixes the documentation for the `Form` component in our styleguide.
The name of the `size` property was changed to `colSpan` in #4459, and it seems updating the documentation was forgotten.
> Replace obsolete size property with colSpan in Form documentation

- src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5277
This PR adds the segment to the `update-context` action of the `PreviewController`.
Because it is required and seems to be forgotten in #5277.
> Fix template switching for pages preview

- src/Sulu/Bundle/SecurityBundle/Entity/Role.php
- src/Sulu/Component/Security/Authentication/RoleInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5483
This PR avoids using the `AuthenticatedVoter::IS_ANONYMOUS` constant, because it does not exist before Symfony 5.1.
As described in #5483 some requests fail when used with Symfony versions before 5.1. E.g. the permissions tab of pages does not stop loading at all.
> Avoid using IS_ANONYMOUS constant introduced in Symfony 5.1

- src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/508
Add export tag to service definition of route and page-tree-route content-type.
To be able to export them in the article bundle.
> Fix xliff export/import for documents with route content-types

- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/webspaces/sulu.io.xml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/pages/default.xml
- src/Sulu/Component/Webspace/Exception/InvalidTemplateException.php
- src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionBuilderTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
- tests/Resources/DataFixtures/Webspace/excluded-default-template/sulu.xml
- tests/Resources/DataFixtures/Webspace/missing-default-template/sulu.xml
| Q | A
| --- | ---
This PR throws an exception if a template is configured as default using the `default-template` tag in a webspace configuration, but this template does not exist in this webspace.
Because this leads just to confusing behavior, and the developer does not immediately know what's going wrong.
> Throw exception if invalid default template is configured in webspace

- src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/registries/resourceRouteRegistry.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/Date/tests/transformDateForUrl.test.js
| Q | A
| --- | ---
This PR fixes the timezone issues in tests by always setting a time when a date object is created in the tests.
In the real application creating a date object never happens without a time. Even if only a date is passed, e.g. the [`Router` makes sure that a time is appended](https://github.com/sulu/sulu/blob/da60751a0249eaf23d46ccfb4c97a419797d4b26/src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js#L28). Therefore it also does not make sense to test these functions with a `Date` object that does not have a time attached.
In addition to that the current tests fail based on the timezone …
> Fix tests for different timezone

- src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
- src/Sulu/Bundle/SecurityBundle/AccessControl/AccessControlQueryEnhancer.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
This PR fixes an issue with the smart content for media by adjusting the query adjustion done in the `AccessControlQueryEnhancer`.
Before that fix the media was wrongfully displayed on the website by the smart content, if the collection e.g. forbid the displaying on the system used on the website, if the collection also had all permissions for the Sulu system were set.
See e.g. the settings in the following screenshot:
> Fix media smart content for collections with multiple permissions

- src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
| Q | A
| --- | ---
This PR makes sure that the permissions are deleted from a page if en empty set of permissions is sent to the API.
Because otherwise it is not possible to completely remove the permissions from a page by deactivating the toggler for all systems from a page.
> Handle empty permissions for pages correctly

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/conditionDataProviders/bundlesConditionDataProvider.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/conditionDataProviders/bundlesConditionDataProvider.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/initializer/initializer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/initializer/tests/initializer.test.js
- src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
- src/Sulu/Bundle/PageBundle/Resources/config/forms/page_block_settings.xml
- src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
- src/Sulu/Component/Content/Tests/Unit/Block/BlockContentTypeTest.php
- src/Sulu/Component/Content/Types/BlockContentType.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4997 
This PR adds a selection of target groups to block settings. Then the audience targeting feature will filter the blocks accordingly.
> Add target groups to block settings

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
| Q | A
| --- | ---
Adds the `request_parameters` to the options of the `SingleAutoComplete` component.
The same functionality was already implemented for the multi-selection types.
> Add request parameters to SingleSelection auto_complete

- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
| Q | A
| --- | ---
Add a `reaction` to call the `fillArrays` function when the `blocks` data is updated e.g. via the `ResourceFormStore`.
For a project I have the use-case, that I have to copy data from `Tab 1` to `Tab 2`.
The `fillArrays` method is only called in the `constructor`, thus after copying the `blocks` from `Tab 1` to `Tab 2` the two arrays `generatedBlockIds` and `expandedBlocks` are not updated accordingly.
> Update BlockCollection arrays on setting new block-data

- config/templates/pages/example.xml
- src/Sulu/Bundle/PageBundle/Content/Types/Date.php
- src/Sulu/Bundle/PageBundle/Content/Types/DateTime.php
- src/Sulu/Bundle/PageBundle/Resources/config/content_types.xml
- src/Sulu/Bundle/PageBundle/Tests/Unit/Content/Types/DateTimeTest.php
- templates/pages/example.html.twig
Added datetime content type and configuration.
| Q | A
| --- | ---
| Fixed tickets | no
| Related issues/PRs | no
| Documentation PR | https://github.com/sulu/sulu-docs/pull/533
Adds DateTime content type.
There was a Time and a Date content type but no datetime content type. 
in config/templates/pages/{yourpagename}.xml inside <properties> : 
```
<property name="my_datetime" type="datetime">
<meta>
<title lang="en">DateTime</title>
<title lang="de">DateTime Duits</title>
</meta>
</property>
```
fix failed tests?
> Add DateTime content type

- package.json
| Q | A
| --- | ---
This PR removes the `null-loader` dependency.
Because is not used anymore since #3463
> Remove null-loader because it is not used anymore

- src/Sulu/Bundle/TestBundle/Testing/AssertHttpStatusCodeTrait.php
| Q | A
| --- | ---
Improve assert http status code error message with exception message and exception file.
If you have a html error page 
~~~php
echo '{{% block test %}' > src/Sulu/Bundle/WebsiteBundle/Tests/Application/templates/default.html.twig
bin/runtests -i -t WebsiteBundle -C --flags="--filter=WebsiteControllerTest::testPage"
~~~
> Improve assert http status code error message

- src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
- src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
- src/Sulu/Bundle/MediaBundle/Entity/Collection.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/CollectionRepositoryTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Collection/CollectionManagerTest.php
- src/Sulu/Bundle/PageBundle/Resources/config/document.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
- src/Sulu/Bundle/SecurityBundle/Entity/PermissionInheritanceInterface.php
- src/Sulu/Bundle/SecurityBundle/EventListener/PermissionInheritanceSubscriber.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/PermissionInheritanceSubscriberTest.php
- src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
- src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
- src/Sulu/Component/Security/Authorization/AccessControl/PhpcrAccessControlProvider.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/PhpcrAccessControlProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | needs #5457 
This PR uses the parent permissions when a new page or media collection is created. 
This way we can make sure that a page being created under a restricted page is no publicly visible by accident.
> Use permissions of parents when creating new collections or pages

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/MediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/MediaSelectionOverlay.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
| Q | A
| --- | ---
This PR adds the table adapter to the list in the `MediaSelection`.
Because this view is more useful if a list of documents with similar names are displayed.
> Add table list to MediaSelectionOverlay

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/List.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
- src/Sulu/Bundle/PageBundle/Resources/config/services.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/ContentRepositoryTest.php
- src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/SecurityBundle/Serializer/Subscriber/SecuritySubscriber.php
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Content/Repository/Serializer/SerializerEventListener.php
- src/Sulu/Component/Content/Tests/Unit/Repository/ContentRepositoryTest.php
- src/Sulu/Component/Security/Serializer/Subscriber/SecuredEntitySubscriber.php
- src/Sulu/Component/Security/Tests/Unit/Serializer/Subscriber/SecuredEntitySubscriberTest.php
| Q | A
| --- | ---
| Related issues/PRs | depends on #5461
This PR will ask the user if it is OK to move the item without touching the different securities of an element and its new parent. The user can only confirm or cancel that operation.
Because that will be enough, since the User can still move and change the permissions afterwards. Also, we think that this won't happen very often.
> Warn when a page or collection with permissions is moved

- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/TestController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/routing_portal_loader_test.yml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/routing_website.yml
- src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/webspaces/example.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Routing/PortalLoaderTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5489
| Related issues/PRs | #5428
This PR adjusts the `PortalLoader` to generate routes that match only if the path prefix is configured for a webspace.
It builds upon #5428, as I am not able to test this on `release/1.6`. Would be nice if someone else is motivated to backport it 🙂 
At the moment, the path `/_profiler/search` does also match the search portal route. This is wrong, as only routes with a specific portal prefix should match.
> Adjust portal route type to match path prefix against webspace configuration

- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5515
This PR adjusts the  `WebspaceManager` to use the current webspace for generating URLs if no `$webspaceKey` is given. Without this change, the first webspace that includes the given `$languageCode` is used for generating the URL.
Because using the current webspace is a better default IMO. Also, see #5515
> Fallback to current webspace when generating URL in WebspaceManager

- src/Sulu/Bundle/MediaBundle/Media/Storage/AzureBlobStorage.php
| Q | A
| --- | ---
| Fixed tickets | part of #5468
| Related issues/PRs | Requires #5526
Build on top of #5526 it does not longer require that azure storage return a seekable resource so the performance can be improved so not the whole resource need to be inside the memory.
It should be avoided to load big files inside the memory.
> Improve performance of azure resources

- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
| Q | A
| --- | ---
Fix portal route loader by use another regex for empty prefix match.
When merging 2.0 to 2.1 this did fail in symfony 4.4 / 5.0 so we need to adjust it.
```php
rm -rf src/Sulu/Bundle/WebsiteBundle/Tests/Application/var/cache/
vendor/bin/phpunit src/Sulu/Bundle/WebsiteBundle/ -c src/Sulu/Bundle/WebsiteBundle/phpunit.xml.dist --filter=ErrorControllerTest::test404ErrorTemplate
```
> Fix portal route loader

- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5526
Fix ImagineImageConverterTest test for svgs.
Since #5526 the ImagineImageConverter give the mimeType to the extractor so it don't need to seek the resource. The expected call did so changed.
> Fix ImagineImageConverterTest test for svgs

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/README.md
| Q | A
| --- | ---
Add sulu icons to js docs.
To improve the developer experience the js docs should contain all available icons.
Open JS docs:
> Add sulu icons to js docs

- .eslintrc.json
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContentItem.js
| Q | A
| --- | ---
It seems like there was a change in the `jsx-indent-props` rule. I would argue that we don't want that change, and even if I apply that change, `eslint` still fails, because it seems that the standard `indent` rule of eslint already checks JSX by itself. So I decided to remove two of the react rules from eslint, because invalid formatted JSX still fails.
> Remove jsx-indent-props rule because indent rule covers it already

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/TextEditor.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/TextEditor.test.js
| Q | A
| --- | ---
This PR adjusts the `TextEditor` field type to use the content-locale of the user when rendered inside of a unlocalized form. This is also implemented in the `Selection`, `SingleSelection` and `TeaserSelection` field type.
Because otherwise the locale that is passed to the `CKEditor5` component is `undefined`. This leads to an error when trying to add an internal link.
> Pass content-locale of user to TextEditor if Form has no locale

- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
| Q | A
| --- | ---
| Documentation PR | sulu/sulu-docs#567
This PR adds a `add_button_text ` param to the `block` content-type. The `add_button_text ` param allows to set the text of the add button which is displayed in the administration interface. The param is implemented analogous to the `label` param of the `checkbox` content-type.
The `block` content type is often used in a specific context. For example, in the Sulu demo, the `block` content-type is used for managing tracks of an album. In these cases, it would be nice to set a specific text instead of the generic `Add block` to the add button. 
~~~xml
<params>
<param name="add_button_text">
<meta>
<title lang="en">Add track</title>
<title …
> Add add_button_text param to adjust text of add button to block content-type

- src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
| Q | A
| --- | ---
Fix auto detection for imagine adapter without vips extension, by check also if the extension is installed correctly.
If you have a website like sulu.io which example have the imagine vips adapter installed, it will fail if a developer check it out with a php version not having the extension installed. The auto detection should use vips only when the adapter is installed and the extension loaded else it should fallback to the other adapters.
1. Install the vips imagine adapter
2. Have no vips extension installed
3. Sulu should use imagick/gd then instead
> Fix auto detection for imagine adapter without vips extension

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
- src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5288
This PR adds a `sort_by` option to the `TypeToolbarAction`. Furthermore it adjusts the `PageAdmin` and the `SnippetAdmin` to enable this option for page templates and snippet types. 
Because there should be a understandable sorting. See #5288
> Sort templates by their title by adding sort_by option to TypeToolbarAction

- src/Sulu/Bundle/PageBundle/Content/Types/SinglePageSelection.php
- src/Sulu/Bundle/PageBundle/Markup/Link/PageLinkProvider.php
- src/Sulu/Bundle/PageBundle/Resources/config/content_types.xml
- src/Sulu/Bundle/PageBundle/Resources/config/link-tag.xml
- src/Sulu/Bundle/PageBundle/Tests/Functional/Markup/LinkTagTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Content/Types/SinglePageSelectionTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Markup/Link/PageLinkProviderTest.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php
- src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
- src/Sulu/Component/Security/Authorization/SecurityCondition.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
- src/Sulu/Component/Webspace/Webspace.php
- templates/pages/example.html.twig
| Q | A
| --- | ---
| Fixed tickets | fixes #5530
This PR moves the permission check from the `SinglePageSelection` to the `sulu_content_load` twig function and to the `sulu-link` tag.
~~~php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)
$foo = new Foo();
// Now we can do
$foo->doSomething();
~~~
> Handle permissions of SinglePageSelection correctly

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/PageBundle/Resources/js/index.js
| Q | A
| --- | ---
| Related issues/PRs | #5548
This PR adjusts the `resource_locator` field-type to include the `parentId` in the request for generating the URL on the edit form. This is needed for including the parent in the generated URL when editing an **existing page in a new language**.
This fixes one aspect of #5548
On the **add form**, the `parentId` is included via the `FormInspector::options` object. The `parentId` is set to the `FormInspector::options` object because of the `addRouterAttributesToFormRequest` call in the `PageAdmin`.
This strategy does not work on the **edit form**, because the `routerAttributes` do not contain the `parentId` in that case.
1. Save and publish a page …
> Include parentId in request of resource_locator field-type after copying language

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
- src/Sulu/Bundle/PageBundle/Controller/PageController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5548
This PR makes the request after confirming the `GhostDialog` return the language of the destination language. In addition it adjusts the page REST API in a way to make this possible without a BC break.
This also replaces #5559.
> Load correct language after copying content for ghost page from other language

- src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/InitCommandTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5499
Add updating of exist anonymous roles.
As the content manager can not add permission for anonymous user a new added webspace need to add permission over the `sulu:security:init` command else the anonymous user will not have access to a new webspace in the same security system.
1. `cp sulu-blog.xml sulu-blog2.xml`
2. Change `<key>` to `sulu-blog2`
3. `bin/console sulu:security:init`
Exist anonymous role for same system should be updated and anonymous role should now have access to the new webspace.
> Add updating of exist anonymous roles

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/resourceLocator.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/ResourceLocatorHistory.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/ResourceLocatorHistory.test.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
| Fixed tickets | fixes #4221, fixes #5547
| Related issues/PRs | #5340
This PR adds a *Refresh URL* button to the `ResourceLocator` field-type. The button allows to regenerate the URL based on the current values of the Form.
Because it is frequently requested feature 🙂 
See #4221 and #5340.
> Add refresh button to ResourceLocator field-type

- src/Sulu/Bundle/PageBundle/Resources/js/stores/webspaceStore/webspaceStore.js
- src/Sulu/Bundle/RouteBundle/Resources/js/index.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5565
This PR adjusts the `index.js` of the `RouteBundle` to register the `route` field-type one on the first login.
Because otherwise, this will throw an error if somebody logs in, logs out and logs in again without reloading the application.
1. Login into the administration interface
2. Logout
3. Login again
4. Try to Logout again
5. **A third Login is not possible anymore**
> Register route field-type only on first login

- src/Sulu/Bundle/ContactBundle/Api/Contact.php
- src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
| Q | A
| --- | ---
| Related issues/PRs | #5380
This PR adds a `titleName` property to the serialized representation of the contact entity. This serializer representation is returned by the `ContactAccountSelection` and by the `contacts` smart-content data-provider.
The PR also adjusts the `ContactRepository` to join the respective table to prevent lazy-loading of `ContactTitle` entities during serialization. I tested the adjustments and did not notice any additional queries in the Symfony profiler.
The serialized representation already includes a `title` property that contains the id of the `ContactTitle` entity. In most cases, you dont care about the `id`, but just want to output the selected …
> Add name of title to serialized contact

- src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
- src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5439 
This PR fixes the signature of the `MediaDataProvider` constructor to also accept `null` for the `Security` class.
Because if no security is configured in `config/packages/security_website.yaml` the `Security` class is not available and therefore null. In that case the website currently breaks, if a SmartContent displaying media is on the page.
> Fix MediaDataProvider if no security is configured

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/4987
Fixes the default-values in blocks. See https://github.com/sulu/sulu/issues/4987
An additional `value` attribute is introduced to save the state of the `value`. Previously the `value` was saved in the properties (`this.props`), but the properties are updated after the `default-value` is set for the next `single_select`, thus the `value` is not up to date during the rendering of the other components.
Now the new `value` attribute is manually updated before the next component is rendered.
The default value was only working for the last component.
> Fix default-values for multiple-select in blocks

- config/templates/pages/example.xml
- src/Sulu/Bundle/SnippetBundle/Content/SingleSnippetSelection.php
- src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
- src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
- src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SingleSnippetSelectionTest.php
- templates/pages/example.html.twig
| Q | A
| --- | ---
| Fixed tickets | fixes #5568
| Documentation PR | https://github.com/sulu/sulu-docs/pull/576
This PR implements a `single_snippet_selection` content type.
Sulu already includes a `snippet_selection` content-type. In a lot of cases, it would be useful to allow for selecting only a single snippet in the administration interface. See #5568
```xml
<property name="single_snippet_selection" type="single_snippet_selection">
<meta>
<title lang="en">Single Snippet Selection</title>
<title lang="de">Schnipsel</title>
</meta>
<params>
<param name="types" value="default"/>
<param name="loadExcerpt" value="true"/>
</params>
</property>
```
> Implement single_snippet_selection content-type

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
| Fixed tickets | fixes #5540
This PR adjusts the `MediaOverview` view to display an error bar when the upload of a file fails. To do this, the `MediaUploadStore`, `MultiMediaDropzone` and `MediaCollection` were adjusted to support the handling of upload errors.
Because there is no feedback to the user if an error happens at the moment. See #5540.
> Display error bar when media upload fails in MediaOverview

- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_evaluations.xml
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/5539
See https://github.com/sulu/sulu/issues/5539
Simple conditions like `true` didn't work as expected.
> Fix condition parsing for xml-files

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5434 
This PR avoids collecting tags in the `AbstractFormStore`, if the passed data is not an array.
The code only works with arrays, and it throws an error if the passed data is of a different type. This didn't happen before, but started happening with the `image_map` field type now, since this is the first one making use of the `types` other than the blocks. The way this is implemented now, the system skips tags within the `image_map` field type. This is not an optimal solution, but the best I can come up with.
The problem is that now every property can make use of types, and we don't really have an idea …
> Collect tags from types only if data is an array

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5576 
This PR updates the redundant `value` variable in the `FieldBlocks` also when the type changes.
Otherwise the type change does nothing.
> Fix broken type select in blocks

- src/Sulu/Component/Webspace/Analyzer/Attributes/SegmentRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/SegmentRequestProcessorTest.php
| Q | A
| --- | ---
| Documentation PR |-
Currently the SegmentProcessor will fail if no portalInformation or Webspace is set.
This should not fail as you could run under an own domain.
> Fix segment request processor without webspace

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/utils.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5250
This PR adjusts the upcast conversion that is created in the`addLinkConversion` helper method to match the [code of the official `ckeditor5-link` package](https://github.com/ckeditor/ckeditor5/blob/5fe1d6394bbaf4aaf7285c64401296cb58642018/packages/ckeditor5-link/src/linkediting.js#L82-L94). The method is used by the `ExternalLinkPlugin` and `InternalLinkPlugin` for the ckeditor.
See #5250.
> Fix link inside of table cell in ckeditor

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5507
This PR deprecates the `data_path_to_auto_complete` schema-option of the `SingleSelection` field. See #5507.
> Deprecate data_path_to_auto_complete schema-option in SingleSelection

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/MediaSelectionOverlay.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5411
This PR passes 1 as initial pages when constructing the `ListStore` in the `MediaSelectionOverlay`. The same thing is done in the `SingleListOverlay`, `MultiListOverlay` and `PageSettingsVersions`.
Because otherwise, the paginator will be disabled. See #5411
> Initialize ListStore with page 1 in MediaSelectionOverlay

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/overlay.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/__snapshots__/ResourceLocatorHistory.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceSingleSelect/tests/__snapshots__/EditOverlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/js/containers/TargetGroupRules/tests/__snapshots__/RuleOverlay.test.js.snap
- src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | #5608
This PR uses specific classes to style some stuff of the `Dialog` and `Overlay` components instead of relying on the tag name.
Because using the tag names might introduce problems (as happened in #5608). When some children are passed to the `Dialog` or `Overlay` their styling is affected if they use some `header`, `article` or `footer` tags.
> Isolate styling of modals from their children

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/5301 and https://github.com/sulu/sulu/issues/5462
Fixes https://github.com/sulu/sulu/issues/5301 and https://github.com/sulu/sulu/issues/5462
Adds validation for the `ResourceLocator` input field. Upper case letters are replaced with lower case letters and slashes are replaced with dashes in `leaf` mode.
The input field of the `ResourceLocator` has unexpected behaviour when inserting strings with `/` and capital letters result in a validation error on the backend.
> Replace invalid characters in resource locator

- .travis.yml
- composer.json
| Q | A
| --- | ---
Avoid warnings for composer 2 autoloader.
```
composer dump-autoload --optimize
```
end with:
```bash
Class Sulu\Bundle\CustomUrlBundle\Version201904110902 located in ./vendor/sulu/sulu/src/Sulu/Bundle/CustomUrlBundle/Resources/phpcr-migrations/Version201904110902.php does not comply with psr-0 autoloading standard. Skipping.
Class Sulu\Bundle\PageBundle\Version201511171538 located in ./vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201511171538.php does not comply with psr-0 autoloading standard. Skipping.
Class Sulu\Bundle\PageBundle\Version201510210733 …
```
> Avoid warnings for composer 2 autoloader

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/PageBundle/Controller/ResourcelocatorController.php
- src/Sulu/Bundle/PageBundle/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/ResourceLocatorStrategyTest.php
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/TreeFullEditStrategyTest.php
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/TreeLeafEditStrategyTest.php
- src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
- src/Sulu/Component/Content/Types/ResourceLocator/Mapper/ResourceLocatorMapperInterface.php
- src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php
- src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategyInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5603
This pr changes the behaviour of the resource locator generation to consider, if a generated resource locator already exists for the exact same page
> Fix refresh resource locator button

- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5612
This PR adds the `filter` attribute to the list of ignored attributes when navigating away from the documents list of the account.
Because the administration interface breaks when navigating from the documents list to the people list. See #5612
> Reset filter parameter when navigating away from account documents

- composer.json
| Q | A
| --- | ---
Add 2.2 branch alias
Allows to use `2.2.*@dev`as version constraint to get the dev version of 2.2.
> Add 2.2 branch alias

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5621
This PR avoids that the navigation is stopped from the `Form` view, if the form has been changed, but it was already confirmed that this is ok.
Because as in #5621 reported, that made problems when the user navigated to a `Tab` view starting from a dirty `Form` view. The `Tab` view did another `redirect`, which caused the `UpdateRouteHook` of the `Form` view to be called again, stopping that redirect from happening.
Therefore we included a check in that hook now, which makes sure it only runs if the view is still active. Until now it was also ran if React already showed another view, but this one …
> Fix redirect after navigation with confirmation dialog from dirty Form

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MemoryFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
| Q | A
| --- | ---
Right now, it is not possible to use a `text_line` property inside of the `page_block_settings` form because of this. See https://github.com/sulu/sulu-demo/pull/86 for how to extend the `page_block_settings` form.
> Do not discard existing data in setMultiple method of MemoryFormStore

- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
| Q | A
| --- | ---
Add autowire for media TypeManagerInterface.
To autowire the TypeManagerInterface to the TypeManager.
~~~php
use Sulu\Bundle\MediaBundle\Media\TypeManager\TypeManagerInterface;
class MyService {
public function __construct(
TypeManagerInterface $mediaTypeManager
) {
~~~
> Add autowire for media TypeManagerInterface

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
| Q | A
| --- | ---
Currently preview of collapsed blocks with sections doesn't work properly.
This PR removes the sections from the `blockSchemaTypeForm` for the block preview rendering and fixes this bug.
Additionally a check was added to skip potential preview fields without a value. So that the first fields with a value are shown in the preview.
Because the block preview should also work as properly with sections.
> Fix block preview with sections

- .eslintrc.json
- flow-typed/globals.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- webpack.config.js
| Q | A
| --- | ---
This PR adjusts the `AdminBundle` to log an error if the version of the Sulu backend does not match the version of the admin javascript build.
Because a lot of users forget to update the javascript build of the administration interface when upgrading their application.
> Log error to javascript console if administration build does not match Sulu version

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5641
Somehow the `fast-deep-equal` package does not work with observable arrays that contain objects. As far as I tested, even `equals(observable([{key: 'value1'}]), observable([{key: 'value2'}]))` returns `true` 🙈. 
Because of this, setting the `value` props of the `FieldBlocks` component does not update the internal `this.value`. This means that the value that was set from the outside will be discarded as soon as a block is changed. 
Unfortunately, I am not sure how to reproduce this in the core. But it happens with the `SuluFormBundle` (see #5641)
> Fix setting value prop of FieldBlocks from the outside

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/Block.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlock.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
- src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/tests/fields/PageTreeRoute.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5608
This PR adds a flag to the `BlockCollection` component, that allows to disable the moving feature in it.
Because in #5608 we need the blocks, but it should not be possible to move them.
> Add flag to disable moving in BlockCollection

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/Block.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlock.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/SortableBlock.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | #5608 
This PR adds a flag to make blocks not collapsable.
We need that for #5608, because the schedule blocks should not be collapsable.
> Add flag to disable collapsing of blocks

- UPGRADE.md
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/PageBundle/Resources/config/smart_content.xml
- src/Sulu/Bundle/SnippetBundle/Content/SnippetDataProvider.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetDataProviderTest.php
- src/Sulu/Component/Content/SmartContent/PageDataProvider.php
- src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
- src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
- src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
- src/Sulu/Component/SmartContent/DataProviderPool.php
- src/Sulu/Component/SmartContent/Tests/Unit/DataProviderPoolTest.php
| Q | A
| --- | ---
Removes the reference to the `AudienceTargetingBundle` in the `DataProviderPool`. Now every provider, which requires the audience targeting bundle has to enable it by itself only when the `AudienceTargetingBundle` is really enabled.
> Remove AudienceTargeting reference in DataProviderPool

- src/Sulu/Bundle/PageBundle/Content/Types/SegmentSelect.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Content/Types/SegmentSelectTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5653
| Related issues/PRs | #5425 
This PR makes sure the segment property is correctly removed on the live workspace, when no segment is selected anymore.
> Fix unselecting segments for live workspace

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/DisplayValue.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/README.md
| Q | A
| --- | ---
This PR allows to use html elements or React components with the `DisplayValue` component.
Currently `DisplayValue` only supports strings. When used in combination with other components like `Icon` the resulting display value would be `[object Object]`.
~~~js
<SingleSelect disabled={disabled} value={value} onChange={this.handleInputChange} id={dataPath} valid={!error}>
<Option value="fa-info-circle"><Icon name="fa-info-circle"/></Option>
<Option value="fa-user"><Icon name="fa-user"/></Option>
</SingleSelect>
~~~
> Allow components as children of Select Option

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
| Q | A
| --- | ---
This PR adjusts the `ResourceLocator` field-type to use the `userStore.contentLocale` if a form is not localized.
Because the `ResourceLocator` components expects a non-null locale. Also, the API that is called in the `ResourceLocatorHistory` expects a non-null locale. Because of this, the `ResourceLocator` field-type is not usable for unlocalized entities at the moment (see https://github.com/sulu/sulu-demo/pull/87 for example).
We used the same fallback strategy in multiple other field-types including the `SingleSelection`, `TextEditor`, `MediaSelection` and `TeaserSelection`.
> Fallback to content-locale of user in ResourceLocator field-type

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
| Q | A
| --- | ---
Right now, the `ResourceLocator` component crashes if the given `locale` prop is not a valid BCP 47 code. For example, this happens when `de_ch` is used as locale.
> Fallback to unlocalized toLowerCase if locale is not BCP 47 in ResourceLocator

- src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/SymfonyExpressionTokenProviderTest.php
This PR allows to use the `is_array` and `implode` function inside of rout schemas:
```yml
sulu_route:
mappings:
App\Entity\Event:
generator: schema
options:
route_schema: '/events/{is_array(object) ? implode("-", object) : object.getName()}'
```
There are two basic strategies when it comes to route generation at the moment.
In this strategy, properties that have a `sulu.rlp.part` tag are sent to the server via AJAX request when the form is edited. The value of the route is updated directly in the form, even without saving. On save, the already generated route-path is included in the data that sent to the API. This strategy is used for pages. 
In this strategy, the route field in the form is updated only after save. When saving the form, the respective entity is persisted and the route …
> Allow to use is_array and implode in route schema

- UPGRADE.md
- src/Sulu/Bundle/RouteBundle/Manager/RouteManager.php
- src/Sulu/Bundle/RouteBundle/Manager/RouteManagerInterface.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Manager/RouteManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5579
This PR adds a `resolveConflict` parameter to the `RouteManagerInterface::createOrUpdateByAttributes` method. This makes the available parameter consistent to the `RouteManagerInterface::create` and `RouteManagerInterface::update`.
When using the `RouteBundle` for a custom entity, it is not possible to implement the `RoutableInterface` in some cases (eg for unlocalized entities or when using the SuluContentBundle). You need to use the `RouteManagerInterface::createOrUpdateByAttributes` method for these entities. We should allow to resolve possible conflicts in these cases too.
> Add resolveConflict parameter to createOrUpdateByAttributes method of RouteManager

- src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php
- src/Sulu/Bundle/MarkupBundle/Resources/config/services.xml
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/LinkTagTest.php
| Q | A
| --- | ---
This PR adjusts the implementation of the `<sulu-link>` tag to render an `<a>` tag without any `href` if the target of the link is not published. Right now, only the text of the link is rendered, this breaks the styling for unpublished links in the preview.
Right now, only the text of the link is rendered. This means that the style for `<a>` elements will not be applied to unpublished links. This is behaviour is a bit confusing for the content manager.
> Render anchor tag instead of text if target of sulu-link is not published in preview

- src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
- src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
- src/Sulu/Bundle/PreviewBundle/Preview/PreviewCacheItem.php
- src/Sulu/Bundle/PreviewBundle/Preview/PreviewInterface.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRendererInterface.php
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5608
This PR refactors some interfaces as described in https://github.com/sulu/sulu/pull/5608#issuecomment-734724110.
Because everytime we add some new option to the preview toolbar (this time it will be a `DatePicker` for previewing the block scheduling) we had to touch the `PreviewInterface` and some other classes.
Some interfaces in the PreviewBundle will be changed, which is a BC break.
> Refactor preview to avoid changing interface for every addition

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
Skip json schema "type" validation errors.
Because there is always a more specific error behind the `type` error
> Skip json schema "type" validation errors

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Dropdown.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Popover.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/dropdown.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/popover.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Dropdown.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Popover.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Dropdown.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Popover.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Select.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap
| Q | A
| --- | ---
This PR adds a new `Toolbar.Popover` component.
Because it allows to show anything after a button has been clicked in a `Popover` component, and that's exactly what we need for #5608, where we should show a `DatePicker` component in such a way.
```javascript
<Toolbar.Popover label="Show content">
{() => 'Content'}
</Toolbar.Popover>
```
> Add new Toolbar.Popover component to display anything in a Toolbar

- src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/TemplateAttributeResolverTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5697
Add handling for `urls` and `loclzations` to the `TemplateAttributeResolver` which handles static routes.
It should have the same behaviour as the ParameterResolver which handles dynamic structure routes.
> Fix localizations for the TemplateAttributeResolver

- UPGRADE.md
- config/packages/sulu_website.yaml
- src/Sulu/Bundle/PageBundle/Content/PageSelectionContainer.php
- src/Sulu/Bundle/PageBundle/Content/Types/PageSelection.php
- src/Sulu/Bundle/PageBundle/Resources/config/content_types.xml
- src/Sulu/Bundle/PageBundle/Resources/config/smart_content.xml
- src/Sulu/Bundle/PageBundle/Tests/Unit/Content/PageSelectionContainerTest.php
- src/Sulu/Bundle/PageBundle/Tests/Unit/Content/Types/PageSelectionTest.php
- src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
- src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationMapper.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Navigation/NavigationMapperTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/StructureResolverTest.php
- src/Sulu/Component/Content/SmartContent/PageDataProvider.php
- src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4128
Remove the path attribute from twig templates.
The `path` get mostly be confused by the `url` and so should be removed from the twig side. This effects the StructureResolver (page data) and the ContentMapper (smart content, page selection, navigation). 
~~~php
sulu_website:
twig:
attributes:
path: false
~~~
> Remove the path attribute from twig templates

- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5599
Fix for sulu_content_load when is used in articles and snippets
@alexander-schranz getStructureType does not exists and no there is no similar function. I use PageInterface to check it , WDT? 
Because now the error `Call to a member function getSecurity() on null` occurs
> Fix sulu_content_load for non pages

- src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/PageList.js
- src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/PageList.test.js
| Q | A
| --- | ---
This PR will show a loader until the available page types have been loaded.
This will avoid a race condition, that caused all pages to being shown as broken.
> Fix race condition causing pages being shown as broken

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/ResourceMultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/tests/ResourceMultiSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceSingleSelect/ResourceSingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceSingleSelect/tests/ResourceSingleSelect.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #5680
| Related issues/PRs | #5691
This PR adjusts the `ResourceSingleSelect` and `ResourceMultiSelect` to send an empty `limit` parameter to the server.
When sending an empty `limit` parameter, the `ListRestHelper` will not use the default limit of `10` and therefore will not paginate the response. We cannot paginate the response because the `ResourceSingleSelect` and `ResourceMultiSelect` do not provide a way to load the next page.
> Disable pagination in ResourceSingleSelect and ResourceMultiSelect

- .github/workflows/test-application.yaml
| Q | A
| --- | ---
GitHub actions seems to use PHP 8 as default version now, and php-cs-fixer does not seem to support that yet.
> Fix PHP version for github actions

- src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php
- src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_locale_expression_param.xml
- src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/FormMetadataProviderTest.php
| Q | A
| --- | ---
This PR adds the locale to the context that is used for evaluating expressions in form configurations. For example, these expressions can be used to display values from a service in a `single_select` property: https://docs.sulu.io/en/2.2/cookbook/select-values-service.html
Because metadata is always evaluated for a specific locale. At the moment, I need to access the locale of the user inside of my service. With this PR, I can pass the locale to the service like this:
```xml
<property name="eventType" type="single_select">
<meta>
<title lang="en">Event Type</title>
</meta>
<params>
<param name="values" type="expression" …
```
> Allow to access locale in expression in form configuration

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/field.scss
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
This PR adds a hint to the datetime input in the preview toolbar that explains how to reset the selected date. The hint is displayed as `info_text` of the field. 
(The padding between toolbar and popover is already documented in a separate issue: https://github.com/sulu/sulu/issues/5718)
> Add hint about using current date to datetime input in preview
