sulu/sulu

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php, src/Sulu/Component/Content/Mapper/ContentMapper.php
__Tasks:__
| Fixed tickets | fixes #648 
| Doc           | https://github.com/sulu-cmf/docs/commit/9bb8d1661e2045cde3cd3fda33e63fe90dd6a624
=> Added published date to resolver

src/Sulu/Bundle/ContactBundle/Api/Account.php
__Tasks:__
| Bug fix?   | yes
| BC Breaks     | 
=> [Bugfix] Bonus and Member tab breadcrumb

CHANGELOG.md, src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php, src/Sulu/Bundle/SecurityBundle/Entity/BaseRole.php, src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php, src/Sulu/Bundle/SecurityBundle/Entity/BaseUserRole.php, src/Sulu/Bundle/SecurityBundle/Entity/Group.php, src/Sulu/Bundle/SecurityBundle/Entity/RoleInterface.php, src/Sulu/Bundle/SecurityBundle/Entity/User.php, src/Sulu/Bundle/SecurityBundle/Entity/UserGroup.php, src/Sulu/Bundle/SecurityBundle/Entity/UserRole.php, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseRole.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseUser.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseUserRole.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/User.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/UserGroup.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/UserRole.orm.xml
Enhancements to add the possibility to inherit from BaseUser class.
=> User Inheritance

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/EventListener/SetThemeEventListener.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/SetThemeEventListenerTest.php, src/Sulu/Component/Webspace/Analyzer/WebsiteRequestAnalyzer.php
- Do not try and set the theme on non-existant portal
Fixes #724 
__Tasks:__
| BC Breaks     | [description]
| Doc           | [url to commit|none]
=> Do not fatal error when the host does not match the portal

src/Sulu/Bundle/ContactBundle/Import/Import.php, src/Sulu/Bundle/ContactBundle/Resources/config/services.yml
__Tasks:__
| Bug fix?      | no
| New feature?  | yes
=> [FEATURE] contact import fixes

src/Sulu/Bundle/ContactBundle/Import/Import.php
__Tasks:__
| Bug fix?      | no
| New feature?  | yes
=> [BUGFIX] contact-import: only map data if available

src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Import/ImportTest.php
this bugfix is fixing issue with importing contacts by id.
reverted tests to old version (which was actually right)
=> [BUGFIX] bug in contact-import and reverted tests

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Content/Structure/SeoStructureExtension.php, src/Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/ContentBundle/Resources/views/Template/seo.html.twig, src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Structure/SeoStructureExtensionTest.php, src/Sulu/Bundle/ContentBundle/Tests/WebTests/Controller/NodeControllerTest.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapContentQueryBuilder.php
__Tasks:__
| Fixed tickets | fixes #714 
=> Add Hide in sitemap checkbox to page

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php
__Tasks:__
| Fixed tickets | fixes #786 
=> Fixes request locale twig var in 404 page

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Controller/NodeController.php, src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php, src/Sulu/Bundle/ContentBundle/Repository/NodeRepositoryInterface.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Mapper/ContentMapperInterface.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
__Tasks:__
| Fixed tickets | fixes https://github.com/sulu-cmf/sulu-standard/issues/398
=> Enabled save shadow for index pages

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/Command/WebspacesInitCommand.php
=> Added set title to index page for init webspaces

CHANGELOG.md, src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/TagBundle/Resources/config/services.xml
Use parameters instead of injecting class FQNs and templates directly
Fixes #674 
__Tasks:__
| Fxed tickets | #674
| Doc           |
=> Use params in di

CHANGELOG.md, composer.json, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/samples/export.all.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/samples/export.backend.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/samples/export.frontend.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/samples/export.newsletter.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/samples/export.portals.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/samples/export.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/sulu.en.xlf, src/Sulu/Bundle/TranslateBundle/Tests/Functional/Translate/ExportTest.php, src/Sulu/Bundle/TranslateBundle/Translate/Export.php
=> Bumped symfony version to 2.6

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
Fix redirect when there is a `:port` in the URL.
Fixes #716
=> Fixed redirect with port

src/Sulu/Bundle/SecurityBundle/Behat/SecurityContext.php
Fixed tests because of changes in #838
=> adjusted behat tests to new login

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php, src/Sulu/Bundle/ContentBundle/Tests/WebTests/Controller/NodeControllerTest.php, src/Sulu/Bundle/ContentBundle/Tests/app/Resources/pages/internallinks.xml, src/Sulu/Component/Content/Mapper/ContentMapperInterface.php
__tasks:__
| q             | a
| tests pass?   | yes
| fixed tickets | none
| bc breaks     | none
| doc           | none
=> fixed page deletion reference issue

src/Sulu/Component/Content/Mapper/ContentMapperInterface.php
Added missing public method to the ContentMapperInterface.
=> Added missing method to ContentMapperInterface

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/NodeRepositoryTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Template/Resources/Skeleton/StructureClass.php.twig, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
=> Added webspace and locale to page in smart-content to load snippet in correct language

src/Sulu/Bundle/AdminBundle/Behat/AdminContext.php, src/Sulu/Bundle/CategoryBundle/Tests/Features/category_management.feature, src/Sulu/Bundle/CategoryBundle/Tests/Features/content_type_category_list.feature, src/Sulu/Bundle/ContactBundle/Tests/Features/people_management.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_checkbox.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_color.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_date.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_email.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_intrenal_links.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_password.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_phone.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_single_internal_link.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_time.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_url.feature, src/Sulu/Bundle/LocationBundle/Tests/Features/content_type_location.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/collection_management.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/content_type_media_selection.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/media_move.feature, src/Sulu/Bundle/SnippetBundle/Tests/Features/content_type_snippet.feature, src/Sulu/Bundle/SnippetBundle/Tests/Features/snippet_management.feature, src/Sulu/Bundle/TagBundle/Tests/Features/content_type_tag_list.feature, src/Sulu/Bundle/TagBundle/Tests/Features/tag_management.feature, src/Sulu/Bundle/TestBundle/Behat/DefaultContext.php
Behat scenarios now include the missing `When` steps.
Please read: https://github.com/cucumber/cucumber/wiki/Given-When-Then
=> Improved behat scenarios

CHANGELOG.md, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
__Tasks:__
| Fixed tickets | fixes #883
=> Fixed URL Generation after copying language of a child node

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/ScaleCommand.php
Imagine mode is a string: https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/ManipulatorInterface.php#L24
__Tasks:__
| Doc           | https://github.com/sulu-io/docs/blob/master/detail-specification/500-assets/DET-507-ImageConverter.md#user-content-scale
=> Fix scale mode

composer.json, src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php, src/Sulu/Bundle/DocumentManagerBundle/Resources/config/services.xml, src/Sulu/Bundle/DocumentManagerBundle/SuluDocumentManagerBundle.php, src/Sulu/Bundle/DocumentManagerBundle/Tests/Document/PageDocument.php, src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/DocumentManagerTest.php, src/Sulu/Bundle/DocumentManagerBundle/Tests/app/AppKernel.php, src/Sulu/Bundle/DocumentManagerBundle/Tests/app/config/config.yml, src/Sulu/Bundle/DocumentManagerBundle/phpunit.xml.dist, src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php, src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php
Have separated the document manager into its own repository for now. We can merge it back in after the refactoring has been completed.
=> Added document manager Bundle

src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml
=> [FEATURE] media supplier collection

src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml
Reverts sulu-io/sulu#986
currently not intended to be merged to sulu-io/sulu
=> Revert "[FEATURE] media supplier collection"

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php
__Tasks:__
| Fixed tickets | fixes https://github.com/sulu-io/sulu/issues/890
=> Set locale on render request

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/FormatManager/DefaultFormatManager.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
__Tasks:__
| Fixed tickets  | fixes #1003
=> Remove interlacing from to fix animated gifs

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/Manager/DefaultMediaManager.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
Set the right download url
__Tasks:__
=> fix download url

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php, src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
__Tasks:__
| Fixed tickets | fixes #600 fixes #601
=> fixes trailing slashes and query point problem

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/CommandInterface.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/CropCommand.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/ResizeCommand.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/ScaleCommand.php, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image/formats/valid.xml, src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image/formats/valid_no_options.xml, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoaderTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/AbstractCommandTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/CropCommandTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/ResizeCommandTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/ScaleCommandTest.php
__Tasks:__
| Fixed tickets | fixes #809, fixes #457 
| Doc           | https://github.com/sulu-io/docs/blob/master/detail-specification/500-assets/DET-507-ImageConverter.md
=> Add Image Scale forceRatio Option

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Behat/AdminContext.php, src/Sulu/Bundle/CategoryBundle/Tests/Features/category_management.feature, src/Sulu/Bundle/MediaBundle/Behat/MediaContext.php, src/Sulu/Bundle/MediaBundle/Tests/Features/collection_management.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/content_type_media_selection.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/media_move.feature
__tasks:__
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/26
=> Fixed collection and category behat tests

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/SuluMediaExtensionTest.php, src/Sulu/Bundle/MediaBundle/Tests/app/config/config.yml
__Tasks:__
| BC Breaks     | yes
| Doc           | https://github.com/sulu-io/docs/blob/master/detail-specification/500-assets/DET-510-Storage.md#user-content-local
=> Media format cache parameters configurateable

CHANGELOG.md, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseUserRole.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/UserGroup.orm.xml
__Tasks:__
| Fixed tickets | fixes #1066 
=> Increase locale db field for big locale jsons

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.en.xlf
https://github.com/sulu-io/SuluProductBundle/pull/155
https://github.com/sulu-io/SuluContactExtensionBundle/pull/9
=> [REFACTORING] Moved translations from admin-bundle to specific bundles

CHANGELOG.md, src/Sulu/Bundle/SecurityBundle/Tests/app/Resources/webspaces/sulu.io.xml, src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php, src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php, tests/Resources/DataFixtures/Webspace/not-valid/sulu.io.xml, tests/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilderTest.php
__Tasks:__
| Fixed tickets | fixes #583 
=> Throw NoValidWebspaceException if no valid webspaces are found

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
=> [FEATURE] Moved initialization of field-descriptors before init of list-builder

src/Sulu/Bundle/CoreBundle/Resources/config/content.xml, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Mapper/ContentMapperInterface.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
This PR aims to tidy up the refactoring branch, remove unnecessary services, fix naming conventions and review the code generally.
=> [WIP] Tidying up

composer.json, src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureDriver.php
This PR updates the search structure driver to be compatible with the latest version of Massive Search.
=> Update to latest massive search branch

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
Now account-contacts are sorted by last name.
Removed sorting in tab.
=> [ENHANCEMENT] Added sorting to account-contacts

src/Sulu/Bundle/ContentBundle/Controller/NodeController.php, src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/column/main.js, src/Sulu/Bundle/ContentBundle/Tests/WebTests/Controller/NodeControllerTest.php
__tasks:__
| Fixed tickets    | fixes #1111 
| BC breaks        | Node API changed
=> Correct Node API for column navigation

CHANGELOG.md, src/Sulu/Component/Content/Block/BlockContentType.php, src/Sulu/Component/Content/Block/BlockPropertyInterface.php, tests/Sulu/Component/Content/Block/BlockContentTypeTest.php
=> fixed preview with multiple blocks

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/SecurityBundle/Entity/BaseRole.php, src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/PermissionControllerTest.php, tests/Sulu/Component/Security/Authorization/AccessControl/SymfonyAccessControlManagerTest.php
[short description]:
__tasks:__
| Fixed tickets    | fixes #1159 
| BC breaks        | yes
| Documentation PR |
=> ENHANCEMENT: Change Role naming to keep symfony2 convention

src/Sulu/Bundle/ContentBundle/Resources/config/services.xml, src/Sulu/Bundle/ContentBundle/Resources/public/js/main.js
__tasks:__
| Fixed tickets    | fixes #1116 
=> set existing default for content language

src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php, src/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriber.php, src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php, tests/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriberTest.php, tests/Sulu/Component/Content/Document/Subscriber/StructureSubscriberTest.php
=> Revising DM option names

src/Sulu/Bundle/ContentBundle/Form/Type/BasePageDocumentType.php, src/Sulu/Bundle/ContentBundle/Search/EventListener/ReindexListener.php, src/Sulu/Component/Content/Document/Subscriber/StructureRemoveSubscriber.php, src/Sulu/Component/Content/Form/DataTransformer/DocumentToUuidTransformer.php, src/Sulu/Component/Content/Form/Type/DocumentObjectType.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
Applies the changes from https://github.com/sulu-io/sulu-document-manager/pull/6
=> applied change to DocumentManagerInterface

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php, src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.en.xlf
__tasks:__
| Fixed tickets    | fixes #888
| BC breaks        | UI text changes
=> change permission translation

src/Sulu/Bundle/MediaBundle/Resources/public/js/components/media-selection/main.js
__Tasks:__
__Informations: data changed event for media selection
| Q            | A
| Bug fix?      | yes
| New feature?  | no
| Tests pass?  | yes
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1274
| Doc          | none
=> [BUGFIX] DATA_CHANGED event for media selection 

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
__tasks:__
| Fixed tickets    | fixes #1210 
=> fixed external link redirect

src/Sulu/Component/Content/Compat/Structure/LegacyPropertyFactory.php, tests/Sulu/Component/Content/Compat/Structure/LegacyPropertyFactoryTest.php
Structure template properties were not created with keys
=> Fixed properties

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGenerator.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php, src/Sulu/Component/Content/Query/ContentQueryExecutor.php, src/Sulu/Component/Content/Query/ContentQueryExecutorInterface.php, src/Sulu/Component/Content/Query/ListToTreeConverter.php, tests/Sulu/Component/Content/Query/ListToTreeConverterTest.php
__tasks:__
| Fixed tickets    | fixes sulu-io/sulu-standard#311
| BC breaks        | sub pages of test-pages will not be merge into upper layer
=> Navigation child test pages

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContactBundle/Twig/ContactTwigExtension.php, src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/block.html.twig, src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/smart_content.html.twig, src/Sulu/Bundle/ContentBundle/Resources/views/Template/content.html.twig, src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/multiple.html.twig, src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/section.html.twig, src/Sulu/Bundle/ContentBundle/Tests/WebTests/Controller/TemplateControllerTest.php, src/Sulu/Bundle/ContentBundle/Twig/ContentTwigExtension.php, src/Sulu/Bundle/LocationBundle/Resources/views/Template/content-types/location.html.twig, src/Sulu/Bundle/MediaBundle/Resources/views/Template/content-types/media-selection.html.twig, src/Sulu/Bundle/MediaBundle/Twig/DispositionTypeTwigExtension.php, src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig, src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Meta/MetaTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/SitemapTwigExtension.php
__tasks:__
__Related PR:__
* https://github.com/sulu-io/sulu-standard/pull/464
* https://github.com/sulu-io/sulu-docs/pull/37
| Fixed tickets    | fixed sulu-io/sulu-standard#216
| BC breaks        | yes see UPGRADE.md
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/37
=> Prefix twig extension functions with "sulu_"

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Behat/AdminContext.php, src/Sulu/Bundle/MediaBundle/Tests/Features/collection_management.feature
Main PR: https://github.com/sulu-io/sulu-docs/pull/26
=> Fixed behat typos

CHANGELOG.md, src/Sulu/Component/Content/Mapper/ContentMapper.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
__tasks:__
| Fixed tickets    | fixes #868
=> Fixed delete page which has children with history url

CHANGELOG.md, src/Sulu/Component/Content/Mapper/ContentMapper.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
=> Added additional query before generate new url

src/Sulu/Bundle/ContentBundle/Document/BasePageDocument.php, src/Sulu/Bundle/ContentBundle/Resources/config/serializer/Document.BasePageDocument.xml, src/Sulu/Component/Content/Compat/Structure/StructureBridge.php, src/Sulu/Component/Content/Document/Behavior/OrderBehavior.php, src/Sulu/Component/Content/Document/Subscriber/OrderSubscriber.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, tests/Sulu/Component/Content/Document/Subscriber/OrderSubscriberTest.php
Fixes ordering issues when ContentMapper#rowToArray is used.
=> Added ->getSuluOrder to OrderInterface

CHANGELOG.md, src/Sulu/Component/Content/Structure.php
__tasks:__
| Fixed tickets    | fixes #1010 , fixes #1225
=> Ensure that concrete languages will be serialized as array not as object

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Command/CleanupHistoryCommand.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/CleanupHistoryCommandTest.php
__tasks:__
| Fixed tickets    | fixes #1239
=> Added cleanup resource-locator history command

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Command/ContentLocaleCopyCommand.php
__tasks:__
| Fixed tickets    | fixes #1240 
=> Added ignore of ghost pages when content copy locale 

CHANGELOG.md, composer.json
Updated version of liip theme bundle in order to get the assetic bugfix.
__tasks:__
| Fixed tickets    | fixes #1217 
=> updated liip theme version

composer.json, src/Sulu/Bundle/ContentBundle/Document/PageDocument.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php, src/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriber.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, tests/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriberTest.php, tests/Sulu/Component/Content/Document/Subscriber/SubscriberTestCase.php
=> Fixed ghost snippet behavior

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Resources/views/Template/media-info.html.twig, src/Sulu/Bundle/MediaBundle/Resources/views/Template/media-multiple-edit.html.twig
=> Added link to original image in media edit-overlay

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
Since this is just causing problems.
Wasn't able to detect any performance impacts.
| Fixed tickets    | fixes #1287
=> [ENHANCEMENT] Removed partial-load hint from getMediaById

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/MetaTwigExtensionTest.php, src/Sulu/Bundle/WebsiteBundle/Twig/Meta/MetaTwigExtension.php
Show correct alternative links and remove invalid meta tag
__Tasks:__
| Fixed tickets | fixes #1086
=>  hreflang alternate

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201504271608.php, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201504281842.php
Fixes the issues from the phpcr migrations in combination with jackrabbit.
=> fixed migration commands for jackarabbit

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php, src/Sulu/Bundle/ContentBundle/Resources/config/preview.xml, src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/PreviewRendererTest.php
__tasks:__
| Fixed tickets    | fixes #1280 
=> Fixed translator locale for preview

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
__tasks:__
| Fixed tickets    | fixes #1312  
=> Get system temp directory during image conversion

src/Sulu/Bundle/ContentBundle/Document/BasePageDocument.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php, src/Sulu/Bundle/SnippetBundle/Document/SnippetDocument.php, src/Sulu/Component/Content/Mapper/ContentMapper.php
Merge together with https://github.com/sulu-io/sulu-document-manager/pull/23
=> fixed missing properties on copy locale

CHANGELOG.md, src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml, src/Sulu/Component/PHPCR/PathCleanup.php
__tasks:__
__Related:__
* https://github.com/sulu-io/sulu-document-manager/pull/25
=> Fixed creator for website

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php, src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yml, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Tests/Unit/Twig/MediaTwigExtensionTest.php, src/Sulu/Bundle/MediaBundle/Twig/MediaTwigExtension.php
__tasks:__
| Fixed tickets    | fixes #1380
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/54
=> Added resolve media twig extension

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/Resources/config/content.xml, src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
__tasks:__
| Fixed tickets    | fixes #1337
=> Added regex replace for media download

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Entity/AccountContactRepository.php, src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php, src/Sulu/Bundle/ContactBundle/Entity/AddressRepository.php, src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php, src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/SecurityBundle/Entity/GroupRepository.php, src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php, src/Sulu/Bundle/SecurityBundle/Entity/SecurityTypeRepository.php, src/Sulu/Bundle/TranslateBundle/Entity/CatalogueRepository.php, src/Sulu/Bundle/TranslateBundle/Entity/CodeRepository.php, src/Sulu/Bundle/TranslateBundle/Entity/PackageRepository.php
=> Removed partial load hints

CHANGELOG.md, src/Sulu/Bundle/SnippetBundle/Tests/Unit/SnippetTwigExtensionTest.php, src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtension.php
__tasks:__
| Fixed tickets    | fixes #1384 
=> Added try-catch to avoid exception for snippet load

CHANGELOG.md, src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php, tests/Resources/DataFixtures/Page/template_lifetime_0.xml, tests/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoaderTest.php
__tasks:__
| Fixed tickets    | fixed #1385
=> Fixed error for cacheLifetime is "0"

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
=> Fixed hard-coded values in search metadata

src/Sulu/Component/Content/Compat/Block/BlockPropertyWrapper.php
This should fix StyleCI failing on you.
=> Inheritdoc fixes

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/ScaleCommand.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/AbstractCommandTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/ScaleCommandTest.php
__Tasks:__
| Fixed tickets | fixes #1335, fixes sulu-io/sulu-standard#473
=> fix image thumbnail scale forceRatio parameter to keep right ratio

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Resources/config/document.xml, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201507231648.php, src/Sulu/Component/Content/Document/Subscriber/ShadowCopyPropertiesSubscriber.php, tests/Sulu/Component/Content/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
this three values will now be copied from base locale to shadowed locale.
__tasks:__
| Fixed tickets    | fixes #1007
| BC breaks        | PHPCR-Migration => see UPGRADE.md
=> Fixed tags, categories and navigation context for shadow pages

src/Sulu/Bundle/SnippetBundle/Resources/public/js/main.js
__tasks:__
| Fixed tickets    | fixes https://github.com/sulu-io/sulu-standard/issues/482
=> fixed default language for snippets

src/Sulu/Bundle/ContactBundle/Resources/public/js/components/contacts/edit/details/main.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/components/contacts/list/decorators/contact-view.js, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.en.xlf
fixed contact-bundle translations
fixed cropz-size for contact-card datagrid decorator
=> fixed contact-bundle translations

src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/ContactBundle/Api/Account.php, src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php, src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php, src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Entity/AccountInterface.php, src/Sulu/Bundle/ContactBundle/Entity/BaseAccount.php, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml, src/Sulu/Bundle/ContactBundle/Resources/config/services.xml, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
__tasks:__
| Documentation PR | None
=> implemented rest-actions for accounts logo

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php, src/Sulu/Bundle/AdminBundle/Tests/app/AppKernel.php, src/Sulu/Bundle/AdminBundle/Tests/app/Resources/templates/overview.xml, src/Sulu/Bundle/AdminBundle/Tests/app/Resources/webspaces/sulu.io.xml, src/Sulu/Bundle/AdminBundle/Tests/app/config/routing.yml, src/Sulu/Bundle/AdminBundle/Tests/app/console, src/Sulu/Bundle/AdminBundle/Tests/bootstrap.php, src/Sulu/Bundle/AdminBundle/phpunit.xml.dist, src/Sulu/Bundle/SecurityBundle/Entity/User.php
=> Fixed bug with serializing user settings

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Entity/AbstractAccount.php, src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php, src/Sulu/Bundle/ContactBundle/Resources/config/services.xml, src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/AccountRepositoryTest.php, src/Sulu/Component/Contact/SmartContent/AccountDataProvider.php, src/Sulu/Component/Contact/SmartContent/BaseDataProvider.php, src/Sulu/Component/Contact/SmartContent/ContactDataProvider.php, tests/Sulu/Component/Contact/SmartContent/AccountDataProviderTest.php
__tasks:__
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/67
=> Added account provider for SmartContent

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/MetaTwigExtensionTest.php, src/Sulu/Bundle/WebsiteBundle/Twig/Meta/MetaTwigExtension.php
__tasks:__
| Fixed tickets    | fixes #1533
=> Fixed format of hreflang-tag locale

src/Sulu/Bundle/AdminBundle/Resources/public/scss/modules/header.scss, src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-delete-dialog.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-router.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/services/contact-manager.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/services/contact-router.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/services/collection-manager.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/services/media-manager.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/services/media-router.js
=> cleaned code style in services

src/Sulu/Bundle/ContactBundle/Resources/public/js/components/accounts/list/main.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/components/contacts/list/main.js, src/Sulu/Bundle/ContactBundle/Resources/public/js/main.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/collection-select-overlay/main.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/edit/files/main.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/root/main.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/main.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/services/overlay-manager.js
fixed multiple overlays in media-edit.
fixed external decorator require-paths
=> fixed multiple overlays in media-edit

CHANGELOG.md, src/Sulu/Component/Content/Compat/Structure/StructureBridge.php, src/Sulu/Component/Content/Document/Extension/ManagedExtensionContainer.php, src/Sulu/Component/Content/Document/Subscriber/ExtensionSubscriber.php, src/Sulu/Component/Content/Extension/ExtensionManager.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, tests/Sulu/Component/Content/Document/Subscriber/ExtensionSubscriberTest.php, tests/Sulu/Component/Content/Extension/ExtensionManagerTest.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php, tests/app/config/routing.yml
__tasks:__
| Fixed tickets    | fixes #1549 
=> Fixed copy extension data

CHANGELOG.md, src/Sulu/Bundle/DocumentManagerBundle/CacheWarmer/ProxyCacheWarmer.php, src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
__tasks:__
| Fixed tickets    | fixes #1464 
=> added configuration object for proxy manager

CHANGELOG.md, src/Sulu/Bundle/GeneratorBundle/Command/GenerateBundleCommand.php
=> fixed sulu bundle generator path generation

src/Sulu/Bundle/AdminBundle/Behat/AdminContext.php, src/Sulu/Bundle/CategoryBundle/Behat/CategoryContext.php, src/Sulu/Bundle/ContactBundle/Behat/ContactContext.php, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_intrenal_links.feature, src/Sulu/Bundle/LocationBundle/Tests/Features/content_type_location.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/collection_management.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/media_upload.feature, src/Sulu/Bundle/SnippetBundle/Tests/Features/content_type_snippet.feature
=> fixed bugs in behat tests

CHANGELOG.md, src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
__tasks:__
| Fixed tickets    | fixes https://github.com/sulu-io/sulu/issues/1613
=> Fixed resource segment subscriber for order internal link

.travis.yml, CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
__tasks:__
| Fixed tickets    | fixes https://github.com/sulu-io/sulu-standard/issues/516
=> fixed bugs occuring with postgresql

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/AccountRepositoryTest.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php, src/Sulu/Bundle/ContentBundle/Resources/config/smart_content.xml, src/Sulu/Bundle/TagBundle/Resources/config/services.xml, src/Sulu/Bundle/TagBundle/Tests/Unit/Twig/TagTwigExtensionTest.php, src/Sulu/Bundle/TagBundle/Twig/TagTwigExtension.php, src/Sulu/Component/Content/SmartContent/QueryBuilder.php, src/Sulu/Component/SmartContent/ContentType.php, src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php, src/Sulu/Component/Tag/Request/TagRequestHandler.php, src/Sulu/Component/Tag/Request/TagRequestHandlerInterface.php, tests/Sulu/Component/Content/SmartContent/SmartContentQueryBuilderTest.php, tests/Sulu/Component/SmartContent/ContentTypeTest.php, tests/Sulu/Component/Tag/Request/TagRequestHandlerTest.php
__tasks:__
__Related PR:__
* https://github.com/sulu-io/sulu-standard/pull/500
* https://github.com/sulu-io/sulu-docs/pull/64
=> Added tags parameter for smartcontent website URL

src/Sulu/Component/Content/Compat/Block/BlockProperty.php, src/Sulu/Component/Content/Compat/Block/BlockPropertyType.php, src/Sulu/Component/Content/Compat/Property.php, src/Sulu/Component/Content/Types/BlockContentType.php, tests/Sulu/Component/Content/Block/BlockPropertyTest.php
__tasks:__
| Fixed tickets    | fixes #1582 , maybe #1608 
=> Fixed serialization of block content for preview

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/CategoryBundle/Api/Category.php
__tasks:__
| Fixed tickets    | fixes #1556 
=> Removed automatic category translation

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/block.html.twig
__tasks:__
| Fixed tickets    | fixes #1588 
=> fixed floating of block type select

CHANGELOG.md, src/Sulu/Component/Security/Authorization/AccessControl/PhpcrAccessControlProvider.php, tests/Sulu/Component/Security/Authorization/AccessControl/PhpcrAccessControlProviderTest.php
__tasks:__
__related PR:__
* https://github.com/sulu-io/sulu-document-manager/pull/46
| Fixed tickets    | fixes #1647 
=> Fixed ghost pages and phpcr access control provider

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/DataFixtures/ReplacerXmlLoader.php, src/Sulu/Bundle/CoreBundle/DataFixtures/replacers.xml, src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/ReplacersCompilerPass.php, src/Sulu/Bundle/CoreBundle/Resources/config/content.xml, src/Sulu/Bundle/CoreBundle/SuluCoreBundle.php, src/Sulu/Bundle/CoreBundle/Tests/Unit/ReplacerXmlLoaderTest.php, src/Sulu/Bundle/CoreBundle/Tests/Unit/replacers.xml, src/Sulu/Component/PHPCR/PathCleanup.php, tests/Sulu/Component/Content/Rlp/Strategy/RlpStrategyTest.php, tests/Sulu/Component/Content/Rlp/Strategy/TreeStrategyTest.php, tests/Sulu/Component/PHPCR/PathCleanupTest.php
__tasks:__
| Fixed tickets    | fixes #1371 , fixes #1548
=> Added path replacer xml

CHANGELOG.md, src/Sulu/Component/Content/Document/Structure/ManagedStructure.php, tests/Sulu/Component/Content/Document/Structure/ManagedStructureTest.php
__tasks:__
| Fixed tickets    | fixes #1376 
=> fixed smart content for usage with block property

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Content/Types/ContactSelectionContentType.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactSelectionContentTypeTest.php, src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml, src/Sulu/Component/Rest/Handler/DateHandler.php, src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
endless serialization circle when serializing contact for contact selection (contact-account-contact-...) Additionally datetime was not serialized with format array.
__tasks:__
=> Fixed contact serialization

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/MediaBundle/Api/Media.php, src/Sulu/Bundle/MediaBundle/Controller/MediaController.php, src/Sulu/Bundle/MediaBundle/Controller/TemplateController.php, src/Sulu/Bundle/MediaBundle/Entity/FileVersionMeta.php, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionMeta.orm.xml, src/Sulu/Bundle/MediaBundle/Resources/config/routing.yml, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/copyright.html, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/info.html, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/main.js, src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/versions.html, src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
__tasks:__
__related PRs:__
* https://github.com/sulu-io/sulu-standard/pull/529
| Fixed tickets    | fixes sulu-io/sulu-standard#528
| BC breaks        | see upgrade.md
=> Added copyright to media metadata

composer.json, src/Sulu/Bundle/MediaBundle/Entity/FileVersionMetaRepository.php, src/Sulu/Bundle/MediaBundle/Entity/FileVersionMetaRepositoryInterface.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionMeta.orm.xml, src/Sulu/Bundle/MediaBundle/Resources/config/massive-search/FileVersionMeta.xml, src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/FileVersionMetaRepositoryTest.php
__tasks:__
| Fixed tickets    | fixes #1323 
=> stopped multiple indexing from media

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Controller/MediaController.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php, src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php, src/Sulu/Bundle/SnippetBundle/Snippet/SnippetRepository.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Snippet/SnippetRepositoryTest.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php, tests/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilderTest.php
__tasks:__
| Fixed tickets    | fixes #1706 
=> use asterisk as placeholder in list builder searches

CHANGELOG.md, src/Sulu/Bundle/PersistenceBundle/Resources/config/services.xml, src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php, tests/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriberTest.php
=> fixed UserBlameSubscriber for new DoctrineBundle

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Entity/BaseCollection.php, src/Sulu/Bundle/MediaBundle/Entity/Collection.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/BaseCollection.orm.xml, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml
=> Moved collection key functions to base collection

CHANGELOG.md, src/Sulu/Component/Persistence/EventSubscriber/ORM/MetadataSubscriber.php
@Swader it would be nice if you can tell me if that helps you.
__tasks:__
=> improved performance of metadata subscriber

UPGRADE.md
=> Fix upgrade add missing updgrades

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php, src/Sulu/Component/Cache/CacheInterface.php, src/Sulu/Component/Cache/DataCache.php, src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php, tests/Sulu/Component/Cache/DataCacheTest.php, tests/Sulu/Component/Media/SystemCollections/SystemCollectionManagerTest.php
__tasks:__
| BC breaks        | none 
=> Fixed cache handling of system collections

CHANGELOG.md, src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php, src/Sulu/Bundle/SnippetBundle/Tests/app/Resources/snippets/hotel.xml
=> Added translated template to snippet list

CHANGELOG.md, UPGRADE.md, composer.json, src/Sulu/Bundle/CategoryBundle/Content/Types/CategoryList.php, src/Sulu/Bundle/CategoryBundle/Tests/Unit/Content/Types/CategoryListTest.php, src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php, src/Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml, src/Sulu/Bundle/ContentBundle/Resources/config/search.xml, src/Sulu/Bundle/ContentBundle/Resources/config/services.xml, src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php, src/Sulu/Bundle/TagBundle/Resources/config/services.xml, src/Sulu/Bundle/TagBundle/Search/TagsConverter.php, src/Sulu/Bundle/TagBundle/Tests/Unit/Search/TagsConverterTest.php, src/Sulu/Component/Content/Document/Behavior/ExtensionBehavior.php, src/Sulu/Component/Content/Extension/AbstractExtension.php, src/Sulu/Component/Content/Extension/ExtensionInterface.php, src/Sulu/Component/Persistence/Model/UserBlameInterface.php
__tasks:__
__related PRs:__
* https://github.com/massiveart/MassiveSearchBundle/pull/60
| Fixed tickets    | fixes #1636 
| BC breaks        | CategoryList id array instead of complete data => see UPGRADE
=> Added excerpt values to search indexing

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/Exception/MediaException.php, src/Sulu/Bundle/MediaBundle/Media/Exception/OriginalFileNotFoundException.php, src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
__Tasks:__
| Fixed tickets | fixes #1764
| Doc           | no
=> No expires headers for 404 media thumbnails

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php, src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php, tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
__tasks:__
| Fixed tickets    | fixes #1765
| BC breaks        | REST response for pages being internal links slightly change
=> fixed data returned for internal link in settings tab

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml
=> Added cascade options to account and contact

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Controller/NodeController.php, src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
__tasks:__
| Fixed tickets    | fixes #1681 
=> Removed webspace as required parameter for get action

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/DataFixtures/replacers.xml
=> Added replacer for box brackets

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
__tasks:__
| Fixed tickets    | fixes #1679 
| BC breaks        | none 
=> Fixed not removed deleted original files

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/MetaTwigExtensionTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtensionTest.php, src/Sulu/Bundle/WebsiteBundle/Twig/Meta/MetaTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php, src/Sulu/Component/Localization/Localization.php, src/Sulu/Component/Webspace/Loader/XmlFileLoader.php, src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.0.xsd, src/Sulu/Component/Webspace/Portal.php, src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig, tests/Resources/DataFixtures/Webspace/xdefault/sulu.io_no_xdefault_locale.xml, tests/Resources/DataFixtures/Webspace/xdefault/sulu.io_xdefault_locale.xml, tests/Sulu/Component/Webspace/Loader/XmlFileLoaderTest.php, tests/Sulu/Component/Webspace/LocalizationTest.php, tests/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilderTest.php, tests/Sulu/Component/Webspace/Manager/WebspaceManagerTest.php, tests/Sulu/Component/Webspace/PortalTest.php
__tasks:__
| Fixed tickets    | fixes #1085
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/134
=> Fixed alternate links with custom x-default locale and remove links to homepage

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Content/Types/Date.php, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201511171538.php, src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Types/DateTest.php
__tasks:__
| BC breaks        | see UPGRADE
=> Fixed content type date to save date data-type in phpcr

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Resources/public/js/components/contact-form/address.form.html, src/Sulu/Bundle/ContactBundle/Resources/views/Template/base.form.html.twig
__tasks:__
| Fixed tickets    | fixes #1773
=> Added title to address list and fixed style of title

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
=> Fixed serialization depth for column-navigation

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201511240844.php
__tasks:__
| BC breaks        | see UPGRADE
=> Fixed migrate url script

CHANGELOG.md, src/Sulu/Bundle/TagBundle/Controller/TagController.php, src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/TagControllerTest.php
=> Added tag serialization groups to tag controller

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php, src/Sulu/Component/PHPCR/PathCleanup.php, src/Sulu/Component/PHPCR/PathCleanupInterface.php
…n for files with special characters
=> Normalized file names

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php, src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Structure/ExcerptStructureExtensionTest.php, src/Sulu/Bundle/TagBundle/Tests/Unit/Search/TagsConverterTest.php
=> Fixed load data in correct locale for excerpt

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Preview/Preview.php, src/Sulu/Bundle/ContentBundle/Preview/PreviewInterface.php, src/Sulu/Component/Content/Compat/Serializer/PageBridgeHandler.php, src/Sulu/Component/Content/Compat/Structure/PageBridge.php, src/Sulu/Component/Content/Compat/Structure/StructureBridge.php, tests/Sulu/Component/Content/Compat/Serializer/PageBridgeHandlerTest.php
=> Fixed preview to save before render and avoid over writing cached values

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/DataFixtures/replacers.xml
filled with all letters from <http://unicode.e-workers.de/zirkumflex.php>
=> Filled xml with special letters

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/SitemapController.php, src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig, src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapXMLGenerator.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapXMLGeneratorInterface.php, src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathInterface.php, src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php, src/Sulu/Component/Webspace/Manager/WebspaceManager.php, src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php, tests/Sulu/Component/Webspace/Manager/WebspaceManagerTest.php
=> Added scheme parameter

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201511240843.php
=> Added date upgrade script for blocks

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Entity/FileVersionMetaRepository.php
__tasks:__
| Related PRs      | https://github.com/massiveart/MassiveSearchBundle/pull/69
=> Improve memory usage of rebuilding search indexes

CHANGELOG.md, src/Sulu/Component/Content/Repository/ContentRepository.php, tests/Sulu/Component/Content/Repository/ContentRepositoryTest.php
=> Fixed sql generation for user roles

CHANGELOG.md, src/Sulu/Component/Content/Repository/ContentRepository.php
__tasks:__
| Fixed tickets    | fixes sulu-io/sulu-standard#571
| Related PRs      | replaces https://github.com/sulu-io/sulu/pull/1858
=> Fixed directory separator for windows

src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/CategoryBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/LocationBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/ResourceBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/SearchBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/TagBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/WebsiteBundle/Resources/translations/sulu/backend.fr.xlf
Add Base Translations fr_FR:
__tasks:__
| Fixed tickets    |  none
=> Add missing translation fr_FR for all sulu's bundles

CHANGELOG.md, src/Sulu/Bundle/LocationBundle/Content/Types/LocationContentType.php, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
added countries to LocationContentType
=> fixed issue 580 for release 1.0

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/CollectionRepositoryTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php, src/Sulu/Bundle/SearchBundle/Rest/SearchResultRepresentation.php, src/Sulu/Bundle/SnippetBundle/Snippet/SnippetRepository.php, src/Sulu/Component/Content/Repository/ContentRepository.php
=> Changed version name to original filename

CHANGELOG.md, src/Sulu/Component/Content/Compat/StructureManager.php, src/Sulu/Component/Content/ContentTypeManager.php, src/Sulu/Component/Webspace/Manager/WebspaceManager.php
Removed deprecations of initial admin request.
=> Removed some deprecations

src/Sulu/Bundle/ContentBundle/Document/BasePageDocument.php
add desc of properties for BasePageDocument:
It can be usefull for https://github.com/sulu-io/sulu/issues/1715
__tasks:__
| Fixed tickets    | none 
=> [ENHANCEMENT] add desc of properties for BasePageDocument

.travis.yml, CHANGELOG.md, composer.json, src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/ContentNavigationRegistryTest.php, src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php, src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationTest.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/IndexComparatorTest.php, src/Sulu/Bundle/ContactBundle/Tests/bootstrap.php, src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php, src/Sulu/Component/Webspace/Manager/WebspaceManager.php, tests/bootstrap.php
__tasks:__
| Fixed tickets    | fixes https://github.com/sulu-io/sulu-standard/issues/583
| Related PRs      | https://github.com/sulu-io/sulu-standard/pull/579
=> [WIP] PHP 7.0 support

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Form/Type/AbstractStructureBehaviorType.php, src/Sulu/Bundle/ContentBundle/Form/Type/BasePageDocumentType.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php, src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, tests/Sulu/Component/Content/Document/Subscriber/StructureSubscriberTest.php
__tasks:__
| Fixed tickets    | fixes #1929
=> Fix updating template and values at the same time

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Controller/SecurityController.php, src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/SecurityControllerTest.php, src/Sulu/Bundle/AdminBundle/Tests/app/AppKernel.php, src/Sulu/Bundle/AdminBundle/Tests/app/config/config.yml, src/Sulu/Bundle/AdminBundle/Tests/app/config/routing.yml
=> Fixed password reset twig template

CHANGELOG.md, UPGRADE.md, src/Sulu/Component/Webspace/Analyzer/WebsiteRequestAnalyzer.php
Changed name of protected setters to match getters.
__tasks:__
| BC breaks        | name of protected setters have been changed
=> cleanup of the WebsiteRequestAnalyzer

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
=> removed unnecessary ob_clean in WebsiteController

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml, src/Sulu/Bundle/ContactBundle/Resources/config/services.xml, src/Sulu/Bundle/ContentBundle/Form/Type/BasePageDocumentType.php, src/Sulu/Bundle/ContentBundle/Form/Type/PageDocumentType.php, src/Sulu/Bundle/ContentBundle/Resources/config/form.xml, src/Sulu/Bundle/ContentBundle/Resources/config/serializer.xml, src/Sulu/Bundle/ContentBundle/Tests/Functional/Compat/StructureBridgeSerializationTest.php, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml, src/Sulu/Bundle/ResourceBundle/Resources/config/services.xml, src/Sulu/Bundle/TagBundle/Resources/config/services.xml, src/Sulu/Component/Content/Compat/Serializer/PageBridgeHandler.php, src/Sulu/Component/Content/Document/Serializer/Subscriber/DocumentSubscriber.php, tests/Sulu/Component/Content/Compat/Serializer/PageBridgeHandlerTest.php
__tasks:__
| Fixed tickets    | fixes #1886
| BC breaks        | see upgrade
=> Added class to serialization process

CHANGELOG.md, src/Sulu/Bundle/PersistenceBundle/Resources/config/services.xml
Fixed mapped superclass inheritance
__tasks:__
=> Fixed mapped superclass inheritance

CHANGELOG.md, src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/SnippetContentTest.php, src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetContentTest.php, src/Sulu/Component/Content/Compat/Structure/SnippetBridge.php
__tasks:__
| Fixed tickets    | fixes sulu-io/sulu-standard#596
=> Fixed bug with snippet in snippet

CHANGELOG.md, src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/AbstractDoctrineFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCaseFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineFieldDescriptor.php, tests/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCaseFieldDescriptorTest.php
__tasks:__
| Fixed tickets    | fixes #1959 
=> Fixed category search

.gitattributes
This setting forces a union merge, lines will be taken from both sides.
=> Use merge=union for changelog

.gitattributes, CHANGELOG.md, src/Sulu/Component/Collaboration/CollaborationMessageHandler.php, src/Sulu/Component/Collaboration/Tests/Unit/CollaborationMessageHandlerTest.php
=> fixed leaking connection in CollaborationMessageHandler

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/Resources/config/serializer.xml, src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
| Related PRs      | https://github.com/sulu-io/sulu-standard/pull/607
=> fixed serializer naming strategy for tests

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/StructureSubscriber.php, src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php, src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Bridge/DocumentInspectorTest.php, src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php, src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php, src/Sulu/Bundle/SnippetBundle/Resources/config/serializer/Document.SnippetDocument.xml, src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml, src/Sulu/Bundle/SnippetBundle/Snippet/SnippetRepository.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/BaseFunctionalTestCase.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Snippet/SnippetRepositoryTest.php, src/Sulu/Component/Content/Document/Structure/ManagedStructure.php, src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php, src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/StructureSubscriberTest.php, tests/app/Resources/snippets/hotel.xml
This PR focuses on converting the SnippetController to using the Serializer by way of the DocumentManager.
Subsequently this has affected the SnippetRepository class.
=> Make the snippet controller use the DocumentManager and Serializer.

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Resources/views/Template/content-types/contact-selection.html.twig
| Fixed tickets    | fixes #1995
=> fixed sorting in contact collection content type

CHANGELOG.md, src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php, src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Bridge/DocumentInspectorTest.php
Allow `-` in the webspace. Fixes #589
=> Allow - in webspace

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Resources/config/list-builder/Account.xml
=> Added 'hasEmail' parameter to accounts api

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/User.orm.xml, src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php, src/Sulu/Component/Persistence/Tests/Functional/EventSubscriber/ORM/UserBlameSubscriberIntegrationTest.php
__Tasks:__
| Fixed tickets | fixes #1987 
| BC Breaks     | yes
=> User contact should not be nullable

.github/PULL_REQUEST_TEMPLATE.md
| Q | A
| --- | ---
| Related issues/PRs | #2080
I'd like to put an alternative proposal to #2080 up for discussion. This version puts a focus on:
- Usability: Reduce the number of interactions needed to adapt the template.
- Conciseness: Short and concise text that is easily understood.
- Usefulness: Remove everything from the template that is not commonly needed.
- Examples: Provide code examples. They speak more than thousand words.
At the moment, it's hard to understand the PRs created in this repository without deep inside knowledge. Both #2080 and this PR try to fix this.
=> Added a meaningful PR template (Alternative 1)

.github/ISSUE_TEMPLATE.md
| Q | A
| --- | ---
| Tests pass? | n/a
| Doc PR | none
This PR adds a meaningful issue template, which defines a structure to encourage high quality issues, which are understandable for new collaborators at every time.
Most of the issues in this repo have less or no description at all. Thus it is very hard to follow your daily business as an outside collaborator. And as @webmozart is already questioning most of the issues and pull requests to add a meaningful description, this is the next logical step.
=> Add a meaningful issue template

.github/PULL_REQUEST_TEMPLATE.md
| Q | A
| --- | ---
| Related issues/PRs | #2090
I improved the PR template to advise the user to remove the "Why?" section if an issue exists and is referenced in the PR table. The description of that issue should suffice as clarification.
At the moment, it's not clear to what extent an issue should be described again under "Why?" when creating a PR that fixes the issue.
=> Improved the PR template

.github/ISSUE_TEMPLATE.md
| Q | A
| --- | ---
This PR improves the template used by GitHub to prepopulate the description of a new issue.
I found several issues:
1. The browser version was missing, which is needed especially to reproduce CSS/JS bugs
2. The actual/expected description are ordered against a user's intuition (IMO). When you want to file a bug, you usually first describe the bug and then the expected behavior. The current template inverses that order.
=> Improved the issue template for GitHub

CHANGELOG.md, src/Sulu/Component/Webspace/Loader/Exception/InvalidCustomUrlException.php, src/Sulu/Component/Webspace/Loader/XmlFileLoader.php, src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.0.xsd, src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php, src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig, src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoaderTest.php, src/Sulu/Component/Webspace/Tests/Unit/UrlTest.php, src/Sulu/Component/Webspace/Url.php, tests/Resources/DataFixtures/Webspace/invalid/massiveart_invalid_custom_url.xml
| Q | A
| --- | ---
This PR adds validation for custom-url.
A custom-url has to contain a placeholder `*`.
=> Added check for custom-url placeholder

src/Sulu/Bundle/AdminBundle/Behat/AdminContext.php
| Q | A
New behat test step for clicking tab.
=> Added new behat step: Click tab item

src/Sulu/Bundle/TestBundle/Behat/DefaultContext.php
| Q | A
| --- | ---
Bugfix for following behat step:
"I wait and expect to see element"
=> [BUGFIX] Fixed behat step

CHANGELOG.md, appveyor.yml, bin/runtests, src/Sulu/Bundle/AdminBundle/Tests/bootstrap.php, src/Sulu/Bundle/CategoryBundle/Tests/bootstrap.php, src/Sulu/Bundle/ContactBundle/Tests/bootstrap.php, src/Sulu/Bundle/ContentBundle/Tests/bootstrap.php, src/Sulu/Bundle/CoreBundle/Tests/bootstrap.php, src/Sulu/Bundle/CustomUrlBundle/Tests/bootstrap.php, src/Sulu/Bundle/GeneratorBundle/Resources/skeleton/sulu/travis/Tests/bootstrap.php.twig, src/Sulu/Bundle/GeneratorBundle/Tests/bootstrap.php, src/Sulu/Bundle/LocationBundle/Tests/bootstrap.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Video/VideoThumbnailServiceTest.php, src/Sulu/Bundle/MediaBundle/Tests/bootstrap.php, src/Sulu/Bundle/PersistenceBundle/Tests/bootstrap.php, src/Sulu/Bundle/ResourceBundle/Tests/bootstrap.php, src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateUserCommandTest.php, src/Sulu/Bundle/SecurityBundle/Tests/bootstrap.php, src/Sulu/Bundle/SnippetBundle/Tests/bootstrap.php, src/Sulu/Bundle/TagBundle/Tests/bootstrap.php, src/Sulu/Bundle/TranslateBundle/Tests/bootstrap.php, src/Sulu/Bundle/WebsiteBundle/Tests/bootstrap.php, src/Sulu/Bundle/WebsocketBundle/Tests/bootstrap.php, src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactory.php, src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2071
This PR adds support for running continuous integration tests on [appveyor](https://ci.appveyor.com).
Because some people use Windows, apparently.
=> App veyor (windows) support

src/Sulu/Bundle/TestBundle/Behat/BaseContext.php, src/Sulu/Bundle/TestBundle/Behat/DefaultContext.php
| Q | A
| --- | ---
Some more bugfixes for behat tests.
=> [BUGFIX] Behat test bugfixes

UPGRADE.md
| Q | A
| --- | ---
Consolidate the upgrade script to avoid having the same commands included multiple times.
Because the upgrade gets less complicated.
=> Updated upgrade guide

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#670
This PR fixes the search in the documents tab of contact/accounts.
=> Fixed contact media search

CHANGELOG.md, src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php, src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2322
This PR fixes a problem when using the request analyzer or translator in a command.
If you using one of this services in a command you get a null excption.
=> Fixed analyze for not existing current request

src/Sulu/Bundle/PreviewBundle/.gitignore, src/Sulu/Bundle/PreviewBundle/Admin/PreviewAdmin.php, src/Sulu/Bundle/PreviewBundle/DependencyInjection/SuluPreviewExtension.php, src/Sulu/Bundle/PreviewBundle/Gruntfile.js, src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml, src/Sulu/Bundle/PreviewBundle/SuluPreviewBundle.php, src/Sulu/Bundle/PreviewBundle/Tests/app/AppKernel.php, src/Sulu/Bundle/PreviewBundle/Tests/app/Resources/pages/default.xml, src/Sulu/Bundle/PreviewBundle/Tests/app/Resources/views/default.twig, src/Sulu/Bundle/PreviewBundle/Tests/app/Resources/webspaces/sulu.io.xml, src/Sulu/Bundle/PreviewBundle/package.json, src/Sulu/Bundle/PreviewBundle/phpunit.xml.dist
| Q | A
| --- | ---
This PR bootstraps the preview-bundle. The functionality will be added in the PR https://github.com/sulu/sulu/pull/2299 .
This PR adds the default bundle files to make the PR smaller.
=> Initialize preview-bundle

CHANGELOG.md, src/Sulu/Bundle/WebsocketBundle/DependencyInjection/Configuration.php
| Q | A
| --- | ---
This PR default disables websocket check.
=> Changed configuration to default disable websocket

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php, src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/RlpStrategyTest.php, src/Sulu/Component/Content/Tests/Unit/SmartContent/Orm/BaseDataProviderTest.php, src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
| Q | A
| --- | ---
| Documentation PR |none
This PR fixes the current Warning testcases.
Some method mocks seems to be wrong.
=> Fixed missing and wrong method mocks

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Entity/FileVersionMetaRepository.php, src/Sulu/Bundle/MediaBundle/Resources/config/massive-search/FileVersionMeta.xml
| Q | A
| --- | ---
| Fixed tickets |none
This PR adds batch indexing medias.
=> Added batch indexing for medias

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
| Q | A
| --- | ---
This PR fixes the appveyor tests.
=> Fixed appveyor tests for collections

CHANGELOG.md, composer.json, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | adds a testcase for https://github.com/sulu/sulu-document-manager/pull/83
Adds a testcase for auto-rename bug
=> Added tests for auto-rename bug

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Controller/AbstractMediaController.php, src/Sulu/Bundle/MediaBundle/Controller/MediaController.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepositoryInterface.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Media.orm.xml, src/Sulu/Bundle/MediaBundle/Resources/config/list-builder/Media.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #2410 fixes #2409
This PR fixes some very slow queries when displaying the media.
=> Fixed slow media queries

src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | N/A
| Related issues/PRs | #2424
| Documentation PR | N/A
A fix for an incidentally occurring issue in the CustomUrlControllerTest::testCGet test
=> Store date directly after request

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Admin/ContentContentNavigationProvider.php
| Q | A
| --- | ---
This PR fixes the tab visibility for tabs in create new localization form.
=> Fixed tab visibility for create new page localization

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php
| Q | A
| --- | ---
Fixed depcrecation for getEntityManager
=> Fixed deprecation for getEntityManager

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml, src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/ExceptionControllerTest.php
Backport for https://github.com/sulu/sulu/pull/2305/files
=> Fixed handling of non-default formats in error handling

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php, src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php, src/Sulu/Bundle/MediaBundle/Entity/Media.php, src/Sulu/Bundle/MediaBundle/Entity/MediaInterface.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Media.orm.xml, src/Sulu/Bundle/MediaBundle/SuluMediaBundle.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
Made Sulu Media entity extendable.
=> [Feature] Extendable media entity

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/ContactAddress.orm.xml, src/Sulu/Bundle/ContactBundle/Resources/config/list-builder/Account.xml, src/Sulu/Bundle/ContactBundle/Resources/config/list-builder/Contact.xml, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php, src/Sulu/Bundle/TestBundle/Resources/dist/context_admin.yml
| Q | A
| --- | ---
This PR adds cascade persist for contact addresses.
=> Added cascade-persist for contact addresses

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Controller/AbstractMediaController.php
| Q | A
| --- | ---
Refactored handling of post data for media
=> [ENHANCEMENT] Refactored handling of post data for media

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
Fixed clear cache http-cache) for sulu-minimal
=> Fixed http-cache clear if var dir exists

CHANGELOG.md, bin/runtests, composer.json, src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd, src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLegacyLoaderTest.php, tests/Resources/DataFixtures/Page/template_with_xinclude.xml, tests/Resources/DataFixtures/Page/template_with_xinclude_main.xml, tests/Resources/DataFixtures/Page/template_with_xinclude_properties.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/issues/2510
This PR fixes the appveyor tests.
The appveyor tests should run before we can require it before merge
=> Fixed appveyor tests

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Form/Type/AbstractStructureBehaviorType.php, src/Sulu/Bundle/ContentBundle/Resources/config/document.xml, src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php, src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/StructureSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the determination of default-structure types in the StructureSubscriber.
=> Set default structure-type if non given

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Controller/TemplateController.php, src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactoryInterface.php, src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php, src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLegacyLoaderTest.php
| Q | A
| --- | ---
Added loading of template attributes for non page-structures
=> Added loading of template attributes for non page-structures

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Preview/PageRouteDefaultsProvider.php, src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php, src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php, src/Sulu/Bundle/RouteBundle/Routing/Defaults/RouteDefaultsProvider.php, src/Sulu/Bundle/RouteBundle/Routing/Defaults/RouteDefaultsProviderInterface.php, src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php, src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/Defaults/DefaultsProviderTest.php, src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php, src/Sulu/Component/Webspace/Analyzer/Attributes/ParameterRequestProcessor.php
| Q | A
| --- | ---
This PR adds the locale to route-defaults provider.
=> Added locale to route-defaults

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Controller/SecurityController.php, src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/AdminPoolTest.php, src/Sulu/Bundle/AdminBundle/Tests/Unit/Widgets/WidgetsHandlerTest.php, src/Sulu/Component/Webspace/Loader/XmlFileLoader.php
| Q | A
| --- | ---
This PR removes some deprecations from the AdminBundle.
Because the deprecations will be removed at some point, and they are cluttering the build.
=> removed deprecation notices from AdminBundle

CHANGELOG.md, src/Sulu/Bundle/PreviewBundle/Resources/public/js/components/preview/main.js, src/Sulu/Bundle/PreviewBundle/Resources/public/js/services/preview.js
| Q | A
| --- | ---
| Fixed tickets | fixes #2446
closing of the document after writing to it in the preview; clearing of the preview before again setting new content.
=> bugfix for firefox preview

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php, src/Sulu/Bundle/ContentBundle/Repository/NodeRepositoryInterface.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/NodeRepositoryTest.php
| Q | A
| --- | ---
This PR removes some unused functions and tests which were already covered by other tests.
Because jackrabbit breaks the connection if too much write processes are happening on travis.
=> removed unused code and tests

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201607181533.php
| Q | A
| --- | ---
This PR contains a migration which creates and correctly fills the workspace for published content.
Because copying the entire tree over to the other workspace also contains test pages.
=> added migration for publishing

CHANGELOG.md, src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php, src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php, src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepositoryInterface.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/CollectionRepositoryTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Collection/CollectionManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/1797, fixes https://github.com/sulu/sulu/issues/2645
see title.
=> Made sulu compatible with mysql 5.7

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/ContentBundle/Resources/views/Template/settings.html.twig, src/Sulu/Bundle/DocumentManagerBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/DocumentManagerBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/DocumentManagerBundle/Resources/translations/sulu/backend.fr.xlf
| Q | A
| --- | ---
This PR removes some duplicated translations and rephrases the unpublishing item in the toolbar.
=> removed and fixed some publishing translations

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/config/document.xml, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php, src/Sulu/Component/Content/Document/Subscriber/StructureRemoveSubscriber.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2752 
This PR also deletes the references on the public workspace, when a page with references is deleted.
=> deleting referenced pages also on public workspace

CHANGELOG.md, src/Sulu/Bundle/CoreBundle/DataFixtures/replacers.xml
| Q | A
| --- | ---
Extended path replacers
Missing `&`
=> Extended path replacers

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/CategoryBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/CollaborationBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/CustomUrlBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/DocumentManagerBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/LocationBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/PreviewBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/ResourceBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/SearchBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/TagBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/WebsiteBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Related issues/PRs | #1905
The Dutch translation of the admin interface.
Because it is cool to have Sulu in Dutch.
I will create a tool to see what source-tags are in a base file compared to the target file and keep track on your development branch, but please do not hesitate to contact me for a translation when needed.
n/a
=> Dutch translation

.travis.yml, CHANGELOG.md, src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php, src/Sulu/Bundle/ContactBundle/Behat/ContactContext.php, src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadDefaultTypes.php, src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php, src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php, src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php, src/Sulu/Bundle/MediaBundle/DataFixtures/ORM/LoadCollectionTypes.php, src/Sulu/Bundle/MediaBundle/DataFixtures/ORM/LoadMediaTypes.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php, src/Sulu/Bundle/ResourceBundle/DataFixtures/ORM/Operators/LoadOperators.php, src/Sulu/Bundle/ResourceBundle/Resource/FilterManager.php, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/User.orm.xml, src/Sulu/Bundle/TagBundle/Tag/TagManager.php, src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml.dist, src/Sulu/Bundle/WebsiteBundle/Entity/AnalyticsRepository.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml, src/Sulu/Component/Content/Query/ContentQueryBuilder.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/2241, fixes https://github.com/sulu/sulu/issues/2226
| Related issues/PRs | https://github.com/sulu/sulu/pull/2695
see title.
This PR builds upon https://github.com/sulu/sulu/pull/2695.
=> Fixed some postgres bugs

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js, src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js, src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml, src/Sulu/Component/HttpCache/EventSubscriber/InvalidationSubscriber.php, src/Sulu/Component/HttpCache/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2735
This PR fixes the problems I have mentioned in [this comment](https://github.com/sulu/sulu/issues/2735#issuecomment-238807377).
=> Fixed publish handling for internal and external links

CHANGELOG.md, src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php, src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php, src/Sulu/Bundle/SecurityBundle/Exception/RoleNameAlreadyExistsException.php, src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2641
When changing role title to an existing one now shows specific error message, not general one.
=> Added specific error message when changing role title to existing one

UPGRADE.md
| Q | A
| --- | ---
What's in this PR?
Fix link in Upgrade.md
=> fix configure format link in upgrade file

src/Sulu/Bundle/CollaborationBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Related issues/PRs | #2761 
A typo in the translation needs to be removed
n/a
=> Remove typo from translation

src/Sulu/Component/Rest/Tests/Unit/RestControllerTest.php
| Q | A
| --- | ---
This PR removes the phpunit mocks from the tests for the `RestController`
The behavior of the mocks changed.
=> removed phpunit mocks in RestControllerTest

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Controller/TemplateController.php, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/TemplateControllerTest.php, src/Sulu/Bundle/ContentBundle/Tests/app/Resources/pages/default.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #2850 
This PR orders the templates in the dropdown for pages alphabetically.
=> Fixed ordering of templates

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Build/NodeOrderBuilder.php, src/Sulu/Bundle/ContentBundle/Resources/config/services.xml, src/Sulu/Bundle/ContentBundle/Tests/Unit/Build/NodeOrderBuilderTest.php, src/Sulu/Bundle/CoreBundle/Resources/config/build.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #2818 
This PR removes a broken dependency from the `NodeOrderBuilder` and adapt it for the changes introduced by the publishing feature.
Because the command was crashing immediately.
=> fixed NodeOrderBuilder for publishing

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Resources/views/Extension/seo.html.twig
| Q | A
| --- | ---
fixed seo twig extension when e.g. on none content page it is used.
=> Fix seo twig template without data

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml, src/Sulu/Component/Contact/Model/ContactInterface.php, src/Sulu/Component/HttpCache/Handler/TagsHandler.php
| Q | A
| --- | ---
| Bug fix? | yes (if using varnish)
This PR fixes the cache clearer if using varnish proxy-client.
The cache-clear button in the backend has no effect (for vanish).
=> Fixed cache-clearer if using varnisch

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/checkbox.html.twig
| Q | A
| --- | ---
Fixed click on label for toggle checkbox
For better usability.
```xml
<property name="checkbox" type="checkbox">
<meta>
<title lang="de">Checkbox</title>
<title lang="en">Checkbox</title>
</meta>
<params>
<param name="type" value="toggler"/>
</params>
</property>
```
=> Fix toggler by click on label

src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
| Related issues/PRs | #1531
This PR adds the test added in #1531. The rest of the changes in this PR are not necessary anymore, because the bug has already been fixed since then.
To make sure that the ListBuilder can also sort concatenated fields.
=> added test for sorting concatenation field in ListBuilder

src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php, src/Sulu/Bundle/TestBundle/Testing/KernelTestCase.php
| Q | A
| --- | ---
This PR fixes phpdoc/type-hint.
=> Fixed phpdoc and type-hint

src/Sulu/Bundle/CategoryBundle/Tests/Features/category_management.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_management.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_checkbox.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_color.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_date.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_email.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_internal_links.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_multiple_select.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_password.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_phone.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_single_internal_link.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_single_select.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_smart_content.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_text_area.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_text_editor.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_text_line.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_time.feature, src/Sulu/Bundle/ContentBundle/Tests/Features/content_type_url.feature, src/Sulu/Bundle/LocationBundle/Tests/Features/content_type_location.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/collection_management.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/content_type_media_selection.feature, src/Sulu/Bundle/MediaBundle/Tests/Features/media_move.feature, src/Sulu/Bundle/SnippetBundle/Tests/Features/content_type_snippet.feature, src/Sulu/Bundle/TagBundle/Tests/Features/content_type_tag_list.feature
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2947 https://github.com/sulu/sulu/pull/2889
This PR fixes the Behat tests.
Because they were broken by our changes in the UI.
=> fixed behat tests

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/config/smart_content.xml
| Q | A
| --- | ---
This PR fixes the configuration for smart-content proxy-factory.
=> Fixed proxy-factory configuration for smart-content

CHANGELOG.md, src/Sulu/Bundle/SnippetBundle/Twig/MemoizedSnippetTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Content/MemoizedContentTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/MemoizedNavigationTwigExtension.php, src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/MemoizedSitemapTwigExtension.php, src/Sulu/Component/Cache/MemoizeTwigExtensionTrait.php, src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTwigExtensionTraitTest.php
Backport to master from https://github.com/sulu/sulu/pull/2959
=> Fixed compatibility for twig 1.26

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml, src/Sulu/Component/Content/Mapper/ContentMapper.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2987 
This PR fixes the problem when using internal-links in internal-links (see #2987 for more details).
=> Fixed internal-link in query-builder

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php, src/Sulu/Bundle/WebsiteBundle/Controller/SitemapController.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/sitemap.xml, src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig, src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPool.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPoolInterface.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperInterface.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php, src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererInterface.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPoolTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/XmlSitemapRendererTest.php, src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
| Q | A |
| --- | --- |
| Fixed tickets | none |
| Related issues/PRs | none |
| Documentation PR | https://github.com/sulu/sulu-docs/pull/278 |
This PR fixes the dumping of complex sitemaps.
=> Fixed dumping of sitemaps

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Resources/config/services.xml, src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php, src/Sulu/Component/Content/Document/Subscriber/ShadowLocaleSubscriber.php, src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php, src/Sulu/Component/Localization/Manager/LocalizationManager.php, src/Sulu/Component/Security/Authentication/SaltGenerator.php, src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php, src/Sulu/Component/Webspace/Manager/WebspaceManager.php
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #2106 
This PR removes a few deprecations.
Because I was annoyed by a few outputs when I run commands in verbose mode.
=> removed deprecations

CHANGELOG.md, appveyor.yml, src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #2106
This PR removes a deprecation. See https://github.com/twigphp/Twig/issues/2267 for more details.
=> fixed deprecation in WebspaceCollection rendering

CHANGELOG.md, src/Sulu/Bundle/ResourceBundle/Resources/config/services.xml, src/Sulu/Bundle/SearchBundle/Resources/config/search.xml, src/Sulu/Bundle/TestBundle/Resources/dist/context_admin.yml
| Q | A
| --- | ---
| Fixed tickets |none
| Related issues/PRs |none
This PR fixes some config deprecations for symfony3.
=> Fixed some config files for symfony3

CHANGELOG.md, composer.json
| Q | A
| --- | ---
| Related issues/PRs | is a part of #2106 
This PR updated willdurand/hateoas-bundle to `^1.0`
=> Updated willdurand/hateoas-bundle

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Entity/MediaDataProviderRepository.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php, src/Sulu/Component/Media/SmartContent/MediaDataProvider.php, src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
| Q | A
| --- | ---
This PR introduces sortability for media smart-content data-provider.
=> Added sort-by for media-dataprovider

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Navigation/ContentNavigationRegistry.php, src/Sulu/Bundle/AdminBundle/Tests/app/config/config.yml, src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php, src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/ListRestHelperTest.php, src/Sulu/Component/Rest/Tests/Unit/Listing/ListRestHelperTest.php, src/Sulu/Component/Rest/Tests/Unit/RequestParametersTraitTest.php
| Q | A
| --- | ---
| Related issues/PRs | is a part of #2106 
This PR fixes testcases of admin- and snippet-bundle for symfony 3.
* AdminBundle
* SnippetBundle
=> Fixed testcases of admin- and snippet-bundle for symfony 3.0

CHANGELOG.md, composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #3081
This PR fixes the constraint for sulu/document-manager
=> Fixed document-manager constraint

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Permission.orm.xml
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu-standard/issues/768
This PR increases the length of the security context field in the database.
=> increased length of context field

CHANGELOG.md, src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php, src/Sulu/Bundle/SnippetBundle/Snippet/SnippetRepository.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Command/SnippetLocaleCopyCommandTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3079 
This PR add the publish command for copied locale document.
=> Added publish snippet after copy locale

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml, src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/ExceptionControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes part of #2106 
| Related issues/PRs | https://github.com/sulu/sulu-minimal/pull/36 https://github.com/sulu/sulu-standard/pull/779
This PR fixes deprecation of flatten-exception by decorating twig-exception-controller.
=> Fixes deprecation of flatten-exception

CHANGELOG.md, appveyor.yml, composer.json, src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/text_editor.html.twig, src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig, src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig, src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig, src/Sulu/Component/Webspace/StructureProvider/WebspaceStructureProvider.php, src/Sulu/Component/Webspace/Tests/Unit/StructureProvider/WebspaceStructureProviderTest.php
| Q | A
| --- | ---
This PR fixes deprecations to be compatible to twig2.
=> Fix deprecations to be compatible to twig2

CHANGELOG.md, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#780
This PR fixes copy-locale on homepages.
=> Fixed copy-locale for homepage

UPGRADE.md
| Q | A
| --- | ---
| Deprecations? | see UPGRADE
=> Added upgrade note for twig2

CHANGELOG.md, src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php
| Q | A
| --- | ---
Explain the contents of the PR.
This PR fixes a problem when both PHPCR sessions are identically.
=> SuluTestCase: Adopted initPhpcr to work for all kernels

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php, src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php
| Q | A
| --- | ---
Backport #2923 to 1.3
Needed.
=> fix system collection creation on '.anon' user for 1.3

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Resources/views/Extension/seo.html.twig
| Q | A
| --- | ---
| Fixed tickets | fixes #3174 
This PR rewrites the locale from written with a underscore to a dash.
=> fixed wrong hreflang tag

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201702021447.php, src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
| Q | A
| --- | ---
This PR introduces `author` and `authored` as reserved-property-name.
=> Added author and authored to reserved-property-names

CHANGELOG.md, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineGroupConcatFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Metadata/Doctrine/Driver/XmlDriver.php, src/Sulu/Component/Rest/ListBuilder/Metadata/Doctrine/Type/GroupConcatTypeMetadata.php, src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php, src/Sulu/Component/Rest/ListBuilder/Metadata/Resources/schema/metadata/list-builder-doctrine-1.0.xsd
| Q | A
| --- | ---
GroupConcatFieldDescriptor: Added possibility to set `DISTINCT` via attribute `orm:distinct`
=> GroupConcatFieldDescriptor DISTINCT

CHANGELOG.md, src/Sulu/Bundle/SecurityBundle/Tests/app/config/config.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/symfony/swiftmailer-bundle/pull/159
This PR fixes a bug in the swiftmailer for our tests.
Because our tests are not running with that bug.
=> fixed breaking change in swiftmailer for tests

CHANGELOG.md, composer.json, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/VersionControllerTest.php, src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
| Q | A
| --- | ---
Added VersionNotFoundException to fos_rest configuration.
=> Added VersionNotFoundException to fos_rest configuration

CHANGELOG.md, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml, src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml, src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml, src/Sulu/Bundle/TagBundle/Resources/config/services.xml, src/Sulu/Bundle/TagBundle/Tag/TagManager.php
| Q | A
| --- | ---
Use the persistance repository instead of the normal sulu repository.
Else it will return the false enity class when overwrite the tag entity.
=> Fixed tag persistence with tag manager

CHANGELOG.md, src/Sulu/Bundle/TagBundle/Controller/TagController.php
| Q | A
| --- | ---
Added all parameters to tag manager
To make overwriting tags easier.
=> Added all parameters to tag manager

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/RouteBundle/Entity/BaseRoute.php
| Q | A
| --- | ---
This PR add auditable information to route-entity.
=> Added auditable to route

src/Sulu/Bundle/RouteBundle/Tests/Functional/Controller/RouteControllerTest.php
| Q | A
| --- | ---
This PR fixes the `RouteControllerTest`s.
=> Fixed RouteControllerTests

CHANGELOG.md, src/Sulu/Bundle/RouteBundle/Resources/config/doctrine/BaseRoute.orm.xml
| Q | A
| --- | ---
This PR adds a default value to created field in route-entity.
=> Added default value to route-created field

src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
The missing translations for the audience targeting.
=> added missing audience targeting translations

src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetDataProviderTest.php
| Q | A
| --- | ---
A fix for the new proxy manager.
Tests were failing.
=> fixed tests for SnippetDataProvider

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/EventListener/RedirectExceptionSubscriber.php, src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RedirectExceptionSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the partial matches for webspace redirects.
=> Fixed partial redirect

CHANGELOG.md, src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml, src/Sulu/Bundle/AudienceTargetingBundle/Resources/public/js/components/target-groups/edit/details/conditions/main.js, src/Sulu/Bundle/AudienceTargetingBundle/Resources/public/js/validation/types/condition-list.js, src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.de.xlf, src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.nl.xlf, src/Sulu/Bundle/AudienceTargetingBundle/Rule/BrowserRule.php, src/Sulu/Bundle/AudienceTargetingBundle/Rule/DeviceTypeRule.php, src/Sulu/Bundle/AudienceTargetingBundle/Rule/OperatingSystemRule.php, src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/DeviceTypeRuleTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #3203
This PR adds a new rule to detect the type of the device (mobile, tablet, desktop)
=> add rule for detecting device type

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php, src/Sulu/Bundle/SnippetBundle/Snippet/SnippetRepository.php, src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
| Q | A
| --- | ---
Snippet list: Changed sortable of some fields
Snippet copy locale: Fixed bug with live index
=> Snippet list: Changed field sortable; Fixed bug with copy locale functionality

CHANGELOG.md, UPGRADE.md, src/Sulu/Bundle/RouteBundle/Resources/config/doctrine/BaseRoute.orm.xml
| Q | A
| --- | ---
Added forgotten default value for changed column in route table.
=> Added default value for changed row

UPGRADE.md
| Q | A
| --- | ---
This PR add an additional UPGRADE step.
=> Added upgrade lines for route-bundle routing file

src/Sulu/Bundle/CollaborationBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/issues/3407
A small correction to a Dutch translation.
n/a
=> Add word to Dutch translation

CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf, src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Related issues/PRs | #3423 
This PR fixes the translations in en/nl/fr for the seo restrictions.
=> Fixed translations for seo in en/nl/fr

.eslintrc.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/Icon.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Item.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Item.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/Translator.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/tests/Translator.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
| Q | A
| --- | ---
The import plugin of eslint got enabled. Moreover the code got refactored to be valid with respect to the enabled plugins.
=> Added eslint import check

CHANGELOG.md, bin/runtests, src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php, src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
| Q | A
| --- | ---
Create preview request with correct scheme.
Scheme wasn't set correctly in preview. Therefore some things didn't worked correctly.
=> Preview with https

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
| Q | A
| --- | ---
| Related issues/PRs | #3474 
This PR fixes the scrolling behaviour of the content area
PR #3474 made the content area unscrollable. This PR fixes that problem.
=> Restored scrolling for the content area

src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/colors.scss
| Q | A
| --- | ---
A general input component which is able to display an icon on the left side of it.
The input component is a central element in sulu.
~~~javascript
const onChange = (value) => {console.log(value)};
<Input onChange={onChange} />
~~~
=> Implemented input component

src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/checkbox.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/Checkbox.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/__snapshots__/Checkbox.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
| Q | A
| --- | ---
A custom checkbox component
Checkboxes are needed in all kind of use cases. This PR introduces a component which implements the common style all checkboxes should have.
~~~javascript
initialState = {checked: false};
onChange = (checked) => setState({checked});
<Checkbox checked={state.checked} onChange={onChange} />
~~~
=> Implemented checkbox frontend component

.eslintrc.json, package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/Switch.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/ButtonCell.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Cell.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/HeaderCell.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/Toggler.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/button.scss, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
| Q | A
| --- | ---
Related PR https://github.com/sulu/sulu/pull/3497
Row selection for the table component. 
Row selection is needed.
=> Added row selection feature

package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/Action.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/OverlayList.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/RadioGroup.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
| Q | A
| --- | ---
This PR reintroduces the changes I've implemented for flow typing in tables and seem to got lost.
Because there was no flow error thrown in https://github.com/sulu/sulu/pull/3457 when I rebased, although it should have been.
=> fix flow types for table

package.json, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap, src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php, src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php, src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php, src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php, src/Sulu/Bundle/TagBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/TagBundle/Resources/translations/admin.en.json, styleguide.config.js
| Q | A
| --- | ---
This PR adds the possibility to select items in the datagrid, and delete the selected items in the List view.
Because this is an essential feature of the datagrid 😃
=> Implement selection in datagrid

package.json
| Q | A
| --- | ---
Removing the direct dependency on `js-beautifer` again, because https://github.com/beautify-web/js-beautify/issues/1247 have been solved.
Because the issue with the newer version have been solved upstream.
=> remove js-beautify

src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/tests/__snapshots__/DisplayValue.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/tests/__snapshots__/GenericSelect.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/tests/__snapshots__/Option.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/Icon.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/__snapshots__/Icon.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/__snapshots__/Pagination.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Button.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Dropdown.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Select.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
| Q | A
| --- | ---
This PR improves the accessibility of the icon. It allows to be clicked using assistive technologies.
We want our system to be accessible.
=> improve icon accessibility when clickable

.eslintrc.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/FolderList/FolderList.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/PopoverPositioner.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/Radio.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Option.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
| Q | A
| --- | ---
Trailing commas make it easier to look at diffs, and functions shouldn't be an exception.
=> insert trailing comma in multiline function arguments

src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
| Q | A
| --- | ---
This PR introduces a parent parameter to collection api.
=> Added parent parameter to collection controller

src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/Divider.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/divider.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/tests/Divider.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/tests/__snapshots__/Divider.test.js.snap
| Q | A
| --- | ---
A `Divider` component
To have an indicator to distinguish different page sections.
~~~js
<Divider>I am the mighty Divider</Divider>
~~~
=> Added divider component

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Analytics/AnalyticsManager.php, src/Sulu/Bundle/WebsiteBundle/Analytics/AnalyticsManagerInterface.php, src/Sulu/Bundle/WebsiteBundle/Controller/AnalyticsController.php, src/Sulu/Bundle/WebsiteBundle/Entity/AnalyticsRepository.php, src/Sulu/Bundle/WebsiteBundle/Resources/config/analytics.xml, src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Analytics/AnalyticsManagerTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/AnalyticsControllerTest.php, src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Entity/AnalyticsRepositoryTest.php
| Q | A
| --- | ---
Only display analytics in the actual environment.
All analytics are displayed in the list. Even the wrong ones.
=>  Only display analytics in the actual environment

src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/Button.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Actions.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/actions.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/overlay.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Actions.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Actions.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
| Q | A
| --- | ---
Use Button component in Overlay component.
Added third skin `link` for buttons.
Button class was generated.
=> Overlay component: Use Button component

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
This PR fixes the tests for content-route tests.
=> Fixed content-route tests for umlauts

src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/Checkbox.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownList.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownListOption.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbarDropdown.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbarDropdownOption.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/Dialog.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/tests/MultiSelect.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/tests/RadioGroup.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/RectangleSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Action.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Select.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/test/Toggler.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
| Q | A
| --- | ---
Fixed a few inline functions passed to JSX components.
The updated JSX rule in eslint seems to be better now, and recognizes more errors.
=> Fix jsx no-bind rule from eslint

.eslintrc.json, appveyor.yml, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/resourceLocator.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/__snapshots__/ResourceLocator.test.js.snap
| Q | A
| --- | ---
Sulu 2.0 ResourceLocator component.
~~~javascript
initialState = {value: '/parent/child'};
onChange = (newValue) => {
setState({value: newValue});
};
<div>
<div style={{paddingBottom: '50px'}}>Current value: {state.value}</div>
<ResourceLocator onChange={onChange} value={state.value} mode="leaf"/>
</div>
~~~
=> ResourceLocator component

src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/RatioNormalizer.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/RatioNormalizer.test.js
| Q | A
| --- | ---
Fixed the weird dragging behavior of the `RectangleSelection` caused by the implementation of the `RatioNormalizer`
Wrong or not intuitive behavior
=> Fixed Rectangle selection

src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
| Q | A
| --- | ---
Added z-index with 100 to Dialog component.
Dialog component doesn't work correctly.
=> Bugfix: Fixed z-index for Dialog component

appveyor.yml, src/Sulu/Bundle/HttpCacheBundle/Resources/config/event-subscribers.xml, src/Sulu/Bundle/HttpCacheBundle/Resources/config/structure-cache-handlers.xml, src/Sulu/Bundle/PreviewBundle/Command/CacheClearCommand.php, src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php, src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/shouldbes/sulu-test.en.xlf, src/Sulu/Bundle/TranslateBundle/Tests/DataFixtures/Files/shouldbes/sulu-test.frontend.en.xlf, src/Sulu/Bundle/TranslateBundle/Tests/Functional/Translate/ExportTest.php
| Q | A
| --- | ---
This PR fixes the regressions in Symfony 3.4, and should make the tests running again. However, this does not include the deprecations.
Please remember to merge back to develop!
Because we want the tests to succeed 😃
=> fix regressions in Symfony 3.4

src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/tests/__snapshots__/InfiniteScroller.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Loader/Loader.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Loader/loader.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Loader/tests/Loader.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Loader/tests/__snapshots__/Loader.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Header.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/header.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/multiItemSelection.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/MultiItemSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/__snapshots__/MultiItemSelection.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Button.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Dropdown.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Select.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/stores/MediaSelectionStore.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js, src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php, src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
…ction
| Q | A
| --- | ---
A bugfix for the `MediaSelection`.
Errors showed up when you pressed escape without opening the Overlay
=> Fixed MediaSelection Bugs

appveyor.yml, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/stores/MediaSelectionStore.js, src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/CollectionStore.js, src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
| Q | A
| --- | ---
This PR fixes the mobx flow types.
MobX seems to have updated their flow types, so we are having some issues now.
=> Fixing mobx flow types

src/Sulu/Bundle/AdminBundle/Resources/js/containers/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/ResourceMetadataStore.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/singleMediaDropzone.scss, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/mediaDetail.scss, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
| Q | A
| --- | ---
This PR adds a form to the `MediaDetail` view which you can use to edit information about the media.
=> Added form to MediaDetail view

.flowconfig, package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/AutoComplete.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/InfiniteScroller.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Masonry/Masonry.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Menu/Menu.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Option.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/withContainerSize.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/FullLoadingStrategy.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/InfiniteLoadingStrategy.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/PaginatedLoadingStrategy.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/ImageFocusPointCell.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/types.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/DownloadList.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/MimeTypeIndicator/MimeTypeIndicator.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/MimeTypeIndicator/MimeTypeMapper.js
| Q | A
| --- | ---
This PR updates flow to 0.64.
This is needed because react 16 comes with a few new features, which are not working in our old flow version, like react fragments.
=> update to flow 0.64

src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/__snapshots__/AutoComplete.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/Backdrop.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/tests/Backdrop.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/__snapshots__/Popover.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
Updated library react-portal to version 4.0
This version is using the native react portal function.
=> Update react-portal to version 4

src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/croppedText.scss, src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/README.md
| Q | A
| --- | ---
Fixed bug in ColumnList component.
A bug where the text isn't fully visible
=> Fixed bug with line-height in ColumnList component

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss
| Q | A
| --- | ---
Enable font smoothing when it's possible.
Fonts are nice!
=> Enable font smoothing

src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php, src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js, src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/AdminPoolTest.php, src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php, src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php, src/Sulu/Bundle/ContactBundle/Controller/ContactController.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php, src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php, src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
| Q | A
| --- | ---
This PR will allow to add new entites using the standard list and form react components.
Because that's one of our most basic functionility.
=> Implement creating new entities using Forms

src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/PopoverPositioner.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/PopoverPositioner.test.js
| Q | A
| --- | ---
Fixed bug when position of PopOver wasn't correctly calculated.
=> Fixed bug when position of PopOver wasn't correctly calculated

package.json
| Q | A
| --- | ---
This PR updates to the latest flow version, because it has a lot nicer error messages.
=> upgrade flow to get better error messages

bin/travis/script_js.sh, package.json
| Q | A
| --- | ---
Try to speed up travis.
=> Speed up travis javascript tests

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
| Q | A
| --- | ---
Added `change` method on stores.
We need to distinguish between initializing and changing.
=> Added change method to stores

CHANGELOG.md, src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php, src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
| Q | A
| --- | ---
Fix xml loader internal flag. 
Was false resolved and the new content type check was needed to be added.
=> Fix xml loader internal flag

src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
| Q | A
| --- | ---
Fix the encodeAlias for the new query list builder changes.
When merging from master to develop it was forgotten adding encodeAlias.
=> Fix doctrine list builder encode alias with new createFullQueryBuilder

.eslintrc.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/AutoComplete.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/InfiniteScroller.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/Popover.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Button.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionBreadcrumb.js
| Q | A
| --- | ---
Add new eslint rules:
* no-multi-spaces
* space-infix-ops
Because..
=> Add new eslint rules for handling spaces

.circleci/config.yml, .travis.yml, CHANGELOG.md, appveyor.yml, bin/build-bundles.sh, bin/ci/validate-build-bundles.sh, src/Sulu/Bundle/AdminBundle/package.json, src/Sulu/Bundle/CategoryBundle/package.json, src/Sulu/Bundle/CollaborationBundle/package.json, src/Sulu/Bundle/ContactBundle/package.json, src/Sulu/Bundle/ContentBundle/package.json, src/Sulu/Bundle/CustomUrlBundle/package.json, src/Sulu/Bundle/DocumentManagerBundle/package.json, src/Sulu/Bundle/LocationBundle/package.json, src/Sulu/Bundle/MediaBundle/package.json, src/Sulu/Bundle/PreviewBundle/package.json, src/Sulu/Bundle/ResourceBundle/package.json, src/Sulu/Bundle/SearchBundle/package.json, src/Sulu/Bundle/SecurityBundle/package.json, src/Sulu/Bundle/SnippetBundle/package.json, src/Sulu/Bundle/TagBundle/package.json, src/Sulu/Bundle/WebsiteBundle/package.json, src/Sulu/Bundle/WebsocketBundle/package.json
| Q | A
| --- | ---
Use circle ci to test if grunt build was run for the bundles.
So no PR is merged where the build is missing.
=> Use circle ci to test if grunt build was run

CHANGELOG.md, src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig, src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.twig, src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig, src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.twig
| Q | A
| --- | ---
| Fixed tickets | N/A
| Related issues/PRs | N/A
| Documentation PR | N/A
Added Twig blocks to allow inheritance
It will allow to add additional elements and buttons to the login and admin interface.
=> Add Twig main blocks to be able to use inheritance

package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/__snapshots__/ArrowMenu.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/__snapshots__/AutoComplete.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/datePicker.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/DatePicker.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/PopoverPositioner.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/popover.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/package.json, src/Sulu/Bundle/ContentBundle/Resources/js/components/WebspaceSelect/tests/__snapshots__/WebspaceSelect.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap, stylelint.config.js
| Q | A
| --- | ---
Sulu 2.0 Datepicker component.
=> Datepicker Component

src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/AdminBundle/ResourceMetadata/FormResourceMetadataProvider.php, src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadata.php, src/Sulu/Bundle/AdminBundle/ResourceMetadata/StructureResourceMetadataProvider.php, src/Sulu/Bundle/AdminBundle/ResourceMetadata/TypedResourceMetadata.php, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/MetadataStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/MetadataStore.test.js, src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php, src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php, src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php, src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php, src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php, src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
| Q | A
| --- | ---
Configuration for datagrid changed from "list" to "datagrid".
Consistent
=> Rename "list" to "datagrid"

src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/services/Bundles/Bundles.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/README.md, styleguide.config.js
| Q | A
| --- | ---
There were some errors in the styleguide, which had to be fixed.
Because it doesn't look professional if there are loads of errors in the logs :-)
=> Fix errors in styleguide

composer.json
| Q | A
| --- | ---
Fix problem with: https://github.com/symfony/symfony/issues/26755
Sulu minimal does not work.
=> Add web profiler 3.4.7 as conflict version

app/config/config.yml
| Q | A
| --- | ---
| BC breaks | no
| Related issues/PRs | #3878, #3428
Fix tests by fixing configuration in test kernel.
Because #3878 was merged after #3428, but not rebased anymore.
=> fix caching config in test environment

src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/mediaSelectionOverlay.scss, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap, src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
| Q | A
| --- | ---
Fixes the height and two scrolling bars.
Because two scrollbars behave strangely.
=> Fix scrolling and height of datagrid in media section and overlay

src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCaseFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineConcatenationFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineGroupConcatFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineIdentityFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/FieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Metadata/General/PropertyMetadata.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/Driver/Resources/complete.xml, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/Driver/Resources/minimal.xml
| Q | A
| --- | ---
Fix bug in FieldDescriptor in `getDisabled` method.
Correct `disable` property.
=> Fix bug in FieldDescriptor

src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Time.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Time.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js
| Q | A
| --- | ---
Add field `time`.
We had it in Sulu 1.* already.
=> Field "time"

src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
| Q | A
| --- | ---
Remove border from icon.
It's already there with box shadow.
=> Input component: Fixed double borders

CHANGELOG.md, src/Sulu/Component/Rest/Csv/CsvHandler.php, src/Sulu/Component/Rest/RestController.php, src/Sulu/Component/Rest/Tests/Unit/Csv/CsvHandlerTest.php
| Q | A
| --- | ---
Fix serialization of boolean in CSV export.
Serialization of boolean ends up in  `1` and ``.
=> CSV export boolean

src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilderFactory.php
| Q | A
| --- | ---
This PR add the already existing interface to the `DoctrineListBuilderFactory`
=> Added interface to doctrine-list-builder

src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/__snapshots__/ViewRenderer.test.js.snap
| Q | A
| --- | ---
ViewRenderer: Do not change change state in render!
Bad idea.
=> ViewRenderer: Do not change state in render

UPGRADE.md
| Q | A
| --- | ---
| Related issues/PRs | #3878
Add upgrade for test setup changes
Was forgot in #3878
=> Add upgrade for test setup changes

.github/PULL_REQUEST_TEMPLATE.md, UPGRADE.md, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCaseFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineConcatenationFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineGroupConcatFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineIdentityFieldDescriptor.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineJoinDescriptor.php, src/Sulu/Component/Rest/ListBuilder/FieldDescriptor.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/FieldDescriptor/DoctrineConcatenationFieldDescriptorTest.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/FieldDescriptor/DoctrineGroupConcatFieldDescriptorTest.php
| Q | A
| --- | ---
| Related issues/PRs | #3895, #3896
Add upgrade for field descriptor visibility flag.
Howto update field descriptors to sulu 2.0
=> Add upgrade for field descriptor visibility flag

src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/checkbox.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/Checkbox.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/__snapshots__/Checkbox.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/Switch.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/tests/Switch.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/tests/__snapshots__/Switch.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/BoolFieldTransformer.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js
| Q | A
| --- | ---
This PR add a field-transformer for boolean values and an inactive state to the checkbox and switch component.
=> Added inactive state for checkbox

src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
| Q | A
| --- | ---
This PR adds the route definitions for account add and edit form.
=> Added routes for account add/edit forms

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/DatePicker.test.js
| Q | A
| --- | ---
Field type  `date`:
Corrected converting of value.
Frontend crashed.
=> Bugfix: Fixed converting of date

.eslintrc.json, package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/ColorPicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/colorPicker.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/colorPickerGlobal.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/ColorPicker.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/datePicker.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/Email.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/tests/__snapshots__/Email.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/field.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ColorPicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ColorPicker.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
Adds component and field type `ColorPicker`.
We need such a component! ;)
=> Color picker component

src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
| Q | A
| --- | ---
This PR fixes the font-size in the `Dialog` component.
Because it didn't match the design.
=> fix font size in dialog

src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
| Q | A
| --- | ---
This PR improves the table design in terms of contrast.
The icons in the header were hardly recognizable and the buttons at the beginning of each row were hard to find.
=> Improve contrast in table styles

webpack.config.js
| Q | A
| --- | ---
| Related issues/PRs | #3978 
#3978 somehow removed source map from the build, this PR adds them again.
=> add sourcemaps to build

src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/baseItem.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/grid.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/__snapshots__/Grid.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/variables.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/PasswordConfirmation.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/passwordConfirmation.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/__snapshots__/PasswordConfirmation.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/Tabs.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tabs.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tests/__snapshots__/Tabs.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/variables.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/renderer.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Form.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/variables.scss, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/form.scss, src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/__snapshots__/ResourceTabs.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/mediaDetail.scss, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap, webpack.config.js
| Q | A
| --- | ---
This PR makes the grid responsive.
Because on a very narrow view port it should be displayed as a single column.
=> Make grid responsive

package.json
| Q | A
| --- | ---
Update jest to 23.0.0
New is always better!
=> Update jest to 23.0.0

src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php, src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php, src/Sulu/Bundle/TagBundle/Resources/config/forms/Tag.xml, src/Sulu/Bundle/TagBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/TagBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds a form to create and edit tags.
Because we need a way to edit tags, and we decided to not implement the inline editing for now, because making a form is a lot easier.
=> add form for Tags

bin/runtests, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
The travis build is failing since #3997, and this PR tries to fix that.
We also want to know if our code is running on PHP 7.2.
=> fix travis build which is stalling in contact tests

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
| Q | A
| --- | ---
This PR register the time field transformer.
=> Added time-field-transformer to registry

src/Sulu/Bundle/AdminBundle/Controller/AdminController.php, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/Config.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/ResourceMetadataStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/tests/ResourceMetadataStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig, src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php, src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php, src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js, testSetup.config.js
| Q | A
| --- | ---
Load correct translations after user has logged in successfully.
User wants to see the translations in chosen language.
=> Load correct translations

UPGRADE.md
| Q | A
| --- | ---
Explain the contents of the PR.
Add missing upgrade for contact and account entity parameter.
=> Add missing upgrade for contact and account entity parameter

src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php, src/Sulu/Bundle/TestBundle/Resources/app/config/context_admin.yml, src/Sulu/Bundle/TestBundle/Resources/app/config/context_website.yml, src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluCommunityBundle/pull/96
Fix test configuration for website test kernel.
Can not redefine a firewall in sulu community bundle to run the tests there.
try to run the tests on develop
=> Fix test configuration for website test kernel

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php, src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | extract parts from #3706
Log errors in image calculation.
That errors are logged why a image could not be calculated.
=> Log errors in image generation

src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/textArea.scss, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/mediaDetail.scss, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
| Q | A
| --- | ---
This PR removes a few display errors in Firefox.
Because we also want to support that browser :-)
=> Fix display errors in Firefox

src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/buttonGroup.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
| Q | A
| --- | ---
Fixed some display errors.
=> Fixed some display errors

UPGRADE.md
| Q | A
| --- | ---
This PR fixes the upgrade command for reindex command
=> Fixed upgrade commands for reindex

CHANGELOG.md, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
| Q | A
| --- | ---
A fix for the copy of the extension date from one locale into another.
That the extension data will be copied from the first language or not even at all.
=> Bugfix: Copy language feature

UPGRADE.md
| Q | A
| --- | ---
Some hints on how to upgrade an existing sulu-minimal project are missing
I had problems upgrading an existing sulu-minimal project.
=> Improve UPGRADING.md

src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
| Q | A
| --- | ---
This PR centers the loading icon of buttons correctly.
=> Center loading icon of Button

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | #4079 
The changes in #4079 broke the Media Detail view, which is fixed in this PR.
=> Fix missing image in MediaDetail view

src/Sulu/Bundle/ContentBundle/Admin/ContentAdmin.php, src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php, src/Sulu/Bundle/ContentBundle/Controller/ExcerptController.php, src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php, src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml, src/Sulu/Bundle/ContentBundle/Resources/config/routing_api.yml, src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
| Q | A
| --- | ---
Add the excerpt tab to the page form.
It adds a missing tab :-)
=> add excerpt tab to page

CHANGELOG.md, src/Sulu/Bundle/ResourceBundle/Resources/config/services.xml, src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php, src/Sulu/Bundle/TestBundle/Resources/dist/context_admin.yml, src/Sulu/Bundle/TestBundle/Resources/dist/context_website.yml, src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml.dist, src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
| Q | A
| --- | ---
| Related PRs | #3995
Remove firewall settings for website kernel in test bundle. Also register the same bundles as in sulu-minimal for TestKernels.
Currently security is overwriteable by the community bundle which is needed.
=> Fixed firewall in test website kernel for community bundle

src/Sulu/Component/Content/Document/Behavior/NavigationContextBehavior.php
| Q | A
| --- | ---
Adding documentation after not finding a good example usage in the code.
=> Added documentation to the navigation context

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/registries/ToolbarActionRegistry.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractToolbarAction.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/index.js, src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/ContentBundle/Admin/ContentAdmin.php, src/Sulu/Bundle/ContentBundle/Resources/js/index.js, src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleDialog.test.js, src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js, src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/__snapshots__/CopyLocaleDialog.test.js.snap, src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/CopyLocaleDialog.js, src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js, src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/copyLocaleDialog.scss, src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js, styleguide.config.js
| Q | A
| --- | ---
This PR adds the possibility to add copy locales to another locale within pages.
=> Copy locales in pages

src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Select.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/displayValue.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/DisplayValue.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/__snapshots__/Url.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/url.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
| Q | A
| --- | ---
| Related issues/PRs | #3798 
This PR adds the `url` field type.
=> Add a URL field type

src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/withSidebar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/types.js, src/Sulu/Bundle/ContentBundle/Resources/js/containers/Form/fields/SearchResult.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaUpload.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
| Q | A
| --- | ---
This PR add the possibility to hook into the response of the config.
This will be needed to distribute the config all over the application bundles.
=> Implemented initializer update-config hooks

src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/collectionSection.scss, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
| Q | A
| --- | ---
Changed add icon into a button.
Styled the edit and delete icon to only appear on hover.
=> Styled icons and buttons in media overview.

src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/displayValue.scss
| Q | A
| --- | ---
Fixed a bug that only occurred in firefox in select boxes. The text wasn't vertically centered.
=> Bugfix in select boxes in firefox

src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
| Q | A
| --- | ---
This PR fixes an error for empty preview option.
=> Fixed bug with undefined preview option

src/Sulu/Bundle/SearchBundle/Resources/config/search.xml
| Q | A
| --- | ---
This PR makes the search-controller public.
=> Added public flag to search-controller

composer.json, src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php, src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
| Q | A
| --- | ---
Fixed deprecation message for seo twig extension.
Currently an error could happen based on the php settings.
=> Fixed deprecation message for seo twig extension

src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js, src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js, src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap, src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
This PR changes the timing of requests for starting and rendering preview.
The render request fails.
=> Changed the timing of requests for starting and rendering preview

.gitignore, src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form.xml, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_expression_param.xml, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_sections.xml, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_without_label.xml, src/Sulu/Bundle/CategoryBundle/Resources/config/forms/Category.xml, src/Sulu/Bundle/ContactBundle/Resources/config/forms/Account.xml, src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml, src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml, src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSeo.xml, src/Sulu/Bundle/MediaBundle/Resources/config/forms/Collection.xml, src/Sulu/Bundle/MediaBundle/Resources/config/forms/Media.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/forms/Role.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml, src/Sulu/Bundle/TagBundle/Resources/config/forms/Tag.xml, src/Sulu/Component/Content/Metadata/Loader/schema/form-1.0.xsd
| Q | A
| --- | ---
| Related issues/PRs | extracted from #4101 
This PR adds a `form` node around the form xmls.
To allow adding a schema in #4101.
=> add form node to form schema

src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form.xml, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_expression_param.xml, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_sections.xml, src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_without_label.xml, src/Sulu/Bundle/CategoryBundle/Resources/config/forms/Category.xml, src/Sulu/Bundle/ContactBundle/Resources/config/forms/Account.xml, src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml, src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml, src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSeo.xml, src/Sulu/Bundle/MediaBundle/Resources/config/forms/Collection.xml, src/Sulu/Bundle/MediaBundle/Resources/config/forms/Media.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/forms/Role.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml, src/Sulu/Bundle/TagBundle/Resources/config/forms/Tag.xml
| Q | A
| --- | ---
| Related issues/PRs | #4183
This PR adapts the linked xsd files of the form XMLs.
Because that was forgotten i #4183.
=> update references to form xsd

src/Sulu/Bundle/AdminBundle/Controller/AdminController.php, src/Sulu/Bundle/AdminBundle/Resources/config/services.xml, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/Navigation.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/Navigation.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig, src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
| Q | A
| --- | ---
This PR uses the correct Sulu version in the navigation.
=> use correct Sulu version in Navigation

src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRule.php, src/Sulu/Bundle/CategoryBundle/Entity/Category.php, src/Sulu/Bundle/CategoryBundle/Entity/CategoryInterface.php, src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslation.php, src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslationInterface.php, src/Sulu/Bundle/CategoryBundle/Entity/Keyword.php, src/Sulu/Bundle/ContactBundle/Entity/Account.php, src/Sulu/Bundle/ContactBundle/Entity/AccountContact.php, src/Sulu/Bundle/ContactBundle/Entity/Address.php, src/Sulu/Bundle/ContactBundle/Entity/Contact.php, src/Sulu/Bundle/ContactBundle/Entity/ContactInterface.php, src/Sulu/Bundle/ContactBundle/Entity/Fax.php, src/Sulu/Bundle/ContactBundle/Entity/SocialMediaProfile.php, src/Sulu/Bundle/ContactBundle/Entity/SocialMediaProfileType.php, src/Sulu/Bundle/MediaBundle/Entity/Collection.php, src/Sulu/Bundle/MediaBundle/Entity/CollectionType.php, src/Sulu/Bundle/MediaBundle/Entity/File.php, src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php, src/Sulu/Bundle/MediaBundle/Entity/Media.php, src/Sulu/Bundle/MediaBundle/Entity/MediaInterface.php, src/Sulu/Bundle/SecurityBundle/Entity/BaseRole.php, src/Sulu/Bundle/SecurityBundle/Entity/Group.php, src/Sulu/Bundle/SecurityBundle/Entity/Role.php, src/Sulu/Bundle/SecurityBundle/Entity/User.php, src/Sulu/Bundle/WebsiteBundle/Entity/Analytics.php, src/Sulu/Component/Content/Document/Behavior/RedirectTypeBehavior.php, src/Sulu/Component/Security/Authentication/RoleInterface.php
| Q | A
| --- | ---
Improve phpdoc types for phpstan of Documents and Entities and use AuditableTrait where possible.
False return types make phpstan errors.
=> Improve phpdoc types  for phpstan and use AuditableTrait

src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/MediaFormats.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/tests/MediaFormats.test.js
| Q | A
| --- | ---
| Related issues/PRs | #4224 
This PR adds the host to the copied URL.
Because it was forgotten in #4224.
=> fix copy of media format url

src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php, src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
=> Fix plural form of "person" to "people".

.travis.yml, composer.json
| Q | A
| --- | ---
Validate composer json
To avoid problems in the composer.json
Errors in the composer.json will be validated by the travis ci when create a PR.
=> Validate composer json

CHANGELOG.md, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4088 
| Related issues/PRs | #4236 
Rotate images based on the orientation of the picture (Exif Data)
=> Added image rotation based on exif

src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
| Q | A
| --- | ---
| Related issues/PRs | #4259
Fixed param default value.
Accidently usage of the default value (copy & paste error?)
=> Fixed param default value

src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
| Bug fix? | yes?
This PR fixes a single typo in admin.en.json
=> Fix "salutations" typo in admin.en.json

src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4232 
This PR will fix the error, which is retrieved when creating a new organization without uploading a logo.
Becuase that should be possible :-)
=> fix creating of new account without logo

README.md
| Q | A
| --- | ---
Update readme file with installation and more badges.
https://github.com/sulu/sulu/blob/0ab22a3b29452d03ae3f3462438ece89d01f84ce/README.md
Link to documentation is missing. Badges are awesome.
=> Update readme file with installation and more badges

.eslintrc.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/Icon.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/MultiDatagridOverlay.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/SingleDatagridOverlay.js, src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
| Q | A
| --- | ---
This PR adds the `object-curly-spacing` rule to our eslint configuration and adjusts the spacing in various files.
=> added object-curly-spacing rule to eslint configuration

UPGRADE.md
| Q | A
| --- | ---
| Related issues/PRs | #4299
This PR adds the missing upgrade instructions in #4299.
Because quite some stuff changed, and it is important to know how to upgrade.
=> Add upgrade for metadata refactoring

src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/AccountRepositoryTest.php
| Q | A
| --- | ---
This PR should fix the build in TravisCI.
Because we want the test to run.
=> Fix stalling TravisCI build

UPGRADE.md, src/Sulu/Bundle/TagBundle/Controller/TagController.php, src/Sulu/Bundle/TagBundle/Entity/Tag.php, src/Sulu/Bundle/TagBundle/Resources/config/services.xml, src/Sulu/Bundle/TagBundle/Tag/TagInterface.php, src/Sulu/Bundle/TagBundle/Tag/TagManager.php, src/Sulu/Bundle/TagBundle/Tag/TagManagerInterface.php, src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/TagControllerTest.php, src/Sulu/Bundle/TagBundle/Tests/Unit/Tag/TagManagerTest.php
| Q | A
| --- | ---
Cleanup tag bundle dependencies.
Less dependencies = less circular reference problems in tag manager.
See UPGRADE.md
=> Cleanup tag bundle dependencies

.circleci/config.yml, package.json
| Q | A
| --- | ---
Add npm audit security check to ci. And fix [vulnerability with styleguidist](https://circleci.com/gh/sulu/sulu/3974)
Check vor vulnerabilities in the ci build.
=> Add npm audit security check to ci

composer.json, src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/CachingTest.php, src/Sulu/Bundle/ContactBundle/Content/Types/SingleContactSelection.php, src/Sulu/Bundle/HttpCacheBundle/Cache/SuluHttpCache.php, src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php, src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Add tag invalidation for Symfony http cache.
Also fixes not working invalidation at all.
Tag invalidation is nice! ;)
=> Fix cache invalidation and add tag invalidation

CHANGELOG.md, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/NavigationTwigExtensionTest.php, src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php
| Q | A
| --- | ---
This PR add exception handling for missing document when query for breadcrumb.
=> Add exception handling for breadcrumb function

UPGRADE.md
| Q | A
| --- | ---
This PR improves the upgrade for the datagrid refactoring.
=> Improve datagrid-metadata upgrade

src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/ArrowMenu.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/__snapshots__/ArrowMenu.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarButton.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdown.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/Dialog.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/Popover.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/__snapshots__/Popover.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceSingleSelect/tests/ResourceSingleSelect.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js, src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
| Q | A
| --- | ---
Some of the tests had to be updated, because a new enzyme version broke them.
Because the tests should be running :slightly_smiling_face: And some of the snapshot tests were very duplicated anyway...
=> Fix tests for new enzyme update

config/packages/security_admin.yaml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-minimal/pull/128
Change the algorithm also for sulu/sulu.
This was also change in sulu-minimal some time ago: https://github.com/sulu/sulu-minimal/pull/128
=> Replace sha512 with bcrypt password encoder

src/Sulu/Bundle/ContactBundle/Content/Types/SingleAccountSelection.php, src/Sulu/Bundle/ContactBundle/Resources/config/content.xml, src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php
| Q | A
| --- | ---
Added new content type for single account selection
=> Added single-account-selection content type

src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/MultiMediaSelection.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/__snapshots__/MultiMediaSelection.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/__snapshots__/SingleMediaSelection.test.js.snap
| Q | A
| --- | ---
Check if media has thumbnails set in media selections.
When non picture media (e.g. Word document) is uploaded to single or multi media selection, whole admin interface broke down, because thumbnails property is undefined.
=> Check whether media has thumbnails

src/Sulu/Component/HttpKernel/SuluKernel.php
Added a fallback to GlobResource if GLOB_BRACE does not exist
| Q | A
| --- | ---
| Fixed tickets | fixes #4513 
Fix for GLOB_BRACE not working on systems that don't support GLOB_BRACE.
=> Fix SuluKernel without GLOB_BRACE support

src/Sulu/Bundle/ContactBundle/Resources/js/index.js
| Q | A
| --- | ---
| Related issues/PRs | #4459
This PR fixes the colspans of the forms in the contact overlays.
Because it seems that this was forgotten in #4459.
=> Fix colspan of overlays in contact form

src/Sulu/Bundle/SnippetBundle/Resources/config/lists/snippets.xml
| Q | A
| --- | ---
This PR adds more fields to the snippet list.
Because they were also available in the old UI.
=> Add more fields to snippet list

src/Sulu/Bundle/SnippetBundle/Resources/config/lists/snippets.xml
| Q | A
| --- | ---
This PR adds the correct types to the snippet list.
=> Add correct type to created and changed fields in snippet list

.travis.yml, CHANGELOG.md, src/Sulu/Bundle/ContentBundle/Command/ValidateWebspacesCommand.php
| Q | A
| --- | ---
Fix controller reference validation with FQCN.
Its recommended way to reference controllers and the bundle syntax is deprecated now.
~~~xml
<controller>Sulu\Bundle\WebsiteBundle\Controller\DefaultController::indexAction</controller>
~~~
=> Fix controller reference validation with FQCN

src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js, src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR sorts the collection list in the media overview alphabetically.
Because this way it is easier to find what you are looking for.
=> Sort collections alphabetically

src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/MediaSelectionOverlay.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap, src/Sulu/Bundle/PageBundle/Resources/js/components/WebspaceSelect/tests/WebspaceSelect.test.js, src/Sulu/Bundle/PageBundle/Resources/js/components/WebspaceSelect/tests/__snapshots__/WebspaceSelect.test.js.snap
| Q | A
| --- | ---
Enzyme 3.10 broke some of our tests. However, the good news is that fragments seem to be correctly supported now :-)
=> Fix tests for new enzyme version

src/Sulu/Bundle/AdminBundle/Resources/js/containers/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js, src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Controller/ContactController.php, src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php, src/Sulu/Bundle/ContactBundle/Resources/js/index.js, src/Sulu/Bundle/ContactBundle/Resources/js/views/List/tests/toolbarActions/AddContactToolbarAction.test.js, src/Sulu/Bundle/ContactBundle/Resources/js/views/List/toolbarActions/AddContactToolbarAction.js, src/Sulu/Bundle/ContactBundle/Resources/js/views/List/toolbarActions/addContactToolbarAction.scss, src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
This PR adds a new action for the peoples tab in the account form to add more contacts to the account.
Because this was already possible in the old UI.
=> Add ToolbarAction to add contacts in accounts people list

UPGRADE.md
| Q | A
| --- | ---
Add upgrade skeleton link to upgrade.md
Any release should have a link to the skeleton changes so they are not forgotten.
=> Add upgrade skeleton link to upgrade.md

src/Sulu/Bundle/AdminBundle/Resources/js/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/PublishTogglerToolbarAction.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractFormToolbarAction.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/PublishTogglerToolbarAction.js
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluCommentBundle/pull/23
This PR add a toolbar-action which contains a toggler to allow publish/unpblish the resource.
=> Add publish toggler toolbar action

phpstan.neon, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Controller/ContactTitleController.php, src/Sulu/Bundle/ContactBundle/Controller/PositionController.php, src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadCountries.php, src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php, src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentFixtureLoader.php, src/Sulu/Bundle/MediaBundle/Entity/File.php, src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Focus/Focus.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php, src/Sulu/Bundle/PageBundle/Content/Types/PageSelection.php, src/Sulu/Bundle/PageBundle/Controller/VersionController.php, src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php, src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php, src/Sulu/Bundle/SecurityBundle/Controller/UserController.php, src/Sulu/Bundle/SecurityBundle/DataFixtures/ORM/LoadSecurityTypes.php, src/Sulu/Component/Content/Compat/Structure.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Metadata/ItemMetadata.php, src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php, src/Sulu/Component/Snippet/Import/SnippetImport.php
| Q | A
| --- | ---
This PR includes some minor refactorings that allow to increase the phpstan level from 0 to 1.
Because static code analysis is awesome 😉
=> Increase phpstan level from 0 to 1 in phpstan.neon

src/Sulu/Component/Doctrine/ReferencesOption.php
| Q | A
| --- | ---
This PR updates the reference-options doctrine extension to avoid `ALTER TABLE` scripts in `doctrine:schema:update` and `doctrine:migrations:diff`.
=> Update reference-options doctrine extension

UPGRADE.md, src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php, src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php, src/Sulu/Bundle/PageBundle/Tests/Unit/Build/NodeOrderBuilderTest.php, src/Sulu/Bundle/PageBundle/Tests/Unit/Command/MaintainResourceLocatorCommandTest.php, src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php, src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php, src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php, src/Sulu/Component/Content/Repository/ContentRepository.php, src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php, src/Sulu/Component/Localization/Manager/LocalizationManager.php, src/Sulu/Component/Localization/Manager/LocalizationManagerInterface.php, src/Sulu/Component/Localization/Provider/LocalizationProvider.php, src/Sulu/Component/Localization/Provider/LocalizationProviderInterface.php, src/Sulu/Component/Webspace/Analyzer/Attributes/ParameterRequestProcessor.php, src/Sulu/Component/Webspace/Manager/WebspaceCollection.php, src/Sulu/Component/Webspace/Manager/WebspaceManager.php, src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3922
This PR add the method `getAllLocales` to webspace-manager.
=> Add 'getAllLocales' to webspace-manager

src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Navigation.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/navigation.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Navigation.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/Navigation.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
| Q | A
| --- | ---
This PR fixes the display issues of the pin button in the navigation. This includes:
- The icon in the button was not centered correctly
- When hovering the button it looked strange
=> Fix display issues with pin button of navigation

src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/Snackbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/snackbar.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/Snackbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/__snapshots__/Snackbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/stores/ToolbarStore.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/formOverlayList.scss, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR will add some messages to errors, and introduce a new warning snackbar as an alternative.
Because error message at least give some feeling what is going wrong, and for the collaboration feature we need a warning, to signal to the user that somebody else is already editing this item.
None yet
=> Show errors with message

composer.json
| Q | A
| --- | ---
Allow massive/search-bundle 1.0
Massive search was tagged with 1.0
=> Allow massive/search-bundle 1.0

src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php, src/Sulu/Bundle/LocationBundle/Geolocator/Service/GoogleGeolocator.php, src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php, src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php, src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php, src/Sulu/Bundle/TagBundle/Tag/TagManager.php, src/Sulu/Component/Content/Document/Subscriber/Compat/ContentMapperSubscriber.php, src/Sulu/Component/Content/Mapper/ContentMapper.php, src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/Compat/ContentMapperSubscriberTest.php, src/Sulu/Component/DocumentManager/Collection/ChildrenCollection.php, src/Sulu/Component/DocumentManager/Collection/QueryResultCollection.php, src/Sulu/Component/DocumentManager/Collection/ReferrerCollection.php, src/Sulu/Component/DocumentManager/DocumentManager.php, src/Sulu/Component/DocumentManager/Metadata/BaseMetadataFactory.php, src/Sulu/Component/DocumentManager/ProxyFactory.php, src/Sulu/Component/DocumentManager/Query/Query.php, src/Sulu/Component/DocumentManager/Subscriber/Phpcr/FindSubscriber.php, src/Sulu/Component/DocumentManager/Subscriber/Phpcr/RefreshSubscriber.php, src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ChildrenCollectionTest.php, src/Sulu/Component/DocumentManager/Tests/Unit/Collection/QueryResultCollectionTest.php, src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ReferrerCollectionTest.php, src/Sulu/Component/DocumentManager/Tests/Unit/ProxyFactoryTest.php, src/Sulu/Component/DocumentManager/Tests/Unit/Query/QueryTest.php, src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/FindSubscriberTest.php, src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/RefreshSubscriberTest.php, src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php, src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php, src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php, src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
| Q | A
| --- | ---
Rearrange arguments in the dispatch method of the event dispatcher
=> Fix deprecation for dispatch method

src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/stores/SmartContentStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/SmartContentStore.test.js, src/Sulu/Bundle/PageBundle/Controller/SmartContentItemController.php, src/Sulu/Component/Media/SmartContent/MediaDataProvider.php, src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php, src/Sulu/Component/SmartContent/Rest/ItemCollectionRepresentation.php
| Q | A
| --- | ---
| Related issues/PRs | fixes https://github.com/sulu/SuluArticleBundle/issues/395
This PR removes the check if something is selected from JS and use the check in PHP which is already implemented there.
=> Remove check in javascript if a request is fired

src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php, src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/WebspaceControllerTest.php
| Q | A
| --- | ---
Fix localization serialization in webspaces request.
Avoid bc break in webspaces controller and fix the drop down.
=> Fix localization serialization in webspaces request

composer.json
| Q | A
| --- | ---
This PR updates to the latest version of the MassiveSearchBundle.
=> Update version of MassiveSearchBundle

README.md, composer.json
| Q | A
| --- | ---
This PR completely restructures and rewords our README.md. Visit https://github.com/nnatter/sulu/tree/enhancement/readme to have a look at it.
Because the old README.md was as exciting as the terms and services of Oracle. Also probably 70% of the information was outdated anyway.
=> Restructure and reword README.md

src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
| Q | A
| --- | ---
This PR removes some unreachable `break` statement.
This code is never executed / unreachable.
=> Remove unreachable code

src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/InfiniteScroller.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/adapters/CKEditor5.js
| Q | A
| --- | ---
This PR simplifies some boolean checks which are not needed.
Some conditions were already matched by the previous lines.
=> Simplify some boolean checks

src/Sulu/Bundle/ContactBundle/Entity/Account.php, src/Sulu/Bundle/ContactBundle/Entity/Address.php, src/Sulu/Bundle/ContactBundle/Entity/BankAccount.php, src/Sulu/Bundle/ContactBundle/Entity/Contact.php, src/Sulu/Bundle/ContactBundle/Entity/ContactInterface.php, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManagerInterface.php, src/Sulu/Bundle/SecurityBundle/Entity/User.php, src/Sulu/Bundle/TestBundle/Testing/CreateClientTrait.php, src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
Improve phpdoc for webspace, contact and user
Better validation with static code analyzers like phpstan.
=> Improve phpdoc for static code analyzers

src/Sulu/Bundle/AdminBundle/Resources/config/services.xml, src/Sulu/Bundle/CoreBundle/Resources/config/serializer.xml, src/Sulu/Component/Serializer/RepresentationSubscriber.php
| Q | A
| --- | ---
Fix CollectionRepresentation serialization in website context
The Representation classes should also be serialized correctly in website context.
=> Fix CollectionRepresentation serialization in website context

src/Sulu/Bundle/ContentBundle/Rule/PageRule.php, src/Sulu/Bundle/ContentBundle/Tests/Unit/Rule/PageRuleTest.php
| Q | A
| --- | ---
This PR contains a fix to ignore redirects for history and trailing slashes.
Histories and trailing slashes throw an exception.
=> Fix page rule to allow history and redirect pages

src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php, src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
Resolves #3670
| Q | A
| --- | ---
| Fixed tickets | fixes #3670
| Related issues/PRs | #3670
Resolves #3670 by ignoring required attributes
=> Ignore required fields when initialize webspace

src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
The travis build is stalling again, and I hope that this fixes it.
I have no idea. I would seriously consider getting rid of travis.
=> Fix stalling travis build

src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml, src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4864
Allow the content manager to make a working redirect into another webspace.
=> Consider webspace when creating an internal redirect

src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
| Q | A
| --- | ---
Get the extensionData directly from document not from the bridge as `getExt` which is called is not in a interface and the function checks for WorkflowBehaviour on the Document and so we should get the extension also from the document.
Less code in a custom StructureBridge.
=> Improve structureResolver getExtensionData from document

src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
=> Fix the download-build command for Windows

src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3622
This PR fixes a comment.
=> Fix wrong comment in SnippetController

src/Sulu/Component/Rest/ListBuilder/ListBuilderInterface.php
=> Fix phpdoc for $value parameter of createWhereExpression

src/Sulu/Component/SmartContent/DataProviderInterface.php
| Q | A
| --- | ---
Fix some doc blocks of the data provider interface
The doc block is now incorrect
=> Fix parameters order in docblock

UPGRADE.md, src/Sulu/Bundle/RouteBundle/Entity/RouteRepository.php, src/Sulu/Bundle/RouteBundle/Entity/RouteRepositoryInterface.php, src/Sulu/Bundle/RouteBundle/Tests/Functional/Entity/RouteRepositoryTest.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/469
This PR add a method to remove the route with the repository.
New method introduced to repository interface
=> Add remove method to route-repository

.github/workflows/crowdin-upload.yaml, .github/workflows/test-application.yaml, src/Sulu/Bundle/AdminBundle/Command/DownloadLanguageCommand.php, src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #4902
| Documentation PR | sulu/sulu-docs#477
This PR will automatically update the crowdin translations for our project, and impement a command that will automatically recognize which translations should be downloaded.
Because this way it enables contributors from the community to translate Sulu in multiple languages, without the need for us to have all the translations in our repository.
~~~bash
bin/console sulu:admin:download-language nl
~~~
=> Add crowdin integration

.env
=> Add comment to explain purpose of SULU_ADMIN_EMAIL environment variable

.env
| Q | A
| --- | ---
Hopefully the diff is self explanatory here 🙂
=> Adjust explanation of SULU_ADMIN_EMAIL environment variable

README.md
- Changed "Sulus" to "Sulu's"
- Changed "Run" to "Ran", to match the other entries (e.g. "Found").
| Q | A
| --- | ---
=> Fix typo and verb tense in the README

.github/workflows/test-application.yaml
| Q | A
| --- | ---
| Documentation PR | sulu---
This PR moves php-cs-fixer to github actions.
Because prettyci constantly changes and makes our build fail.
=> Run php-cs-fixer in GitHub Actions

phpstan.neon, src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/Chip.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/README.md, src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/chip.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/index.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/Chip.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/__snapshots__/Chip.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/MultiAutoComplete.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
| Q | A
| --- | ---
This PR is extracted from #5035 and contains a new `Chip` component.
Because the `Chip` component will also be used when filtering lists. Until now this component was only available to the `MultiAutoComplete`.
=> Extract chip component for better reusability

src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/Resources/options.xml
| Q | A
| --- | ---
This PR fixes a wrong resolvation of a merge-conflict.
=> Resolve merge-conflict error

package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Section.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Section.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/OptionList.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Select.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractFormToolbarAction.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/AbstractListToolbarAction.js
| Q | A
| --- | ---
Update and necessary changes to Flow 0.110.0.
=> Update flow to 0.110.0

src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/userStore.js
| Q | A
| --- | ---
This PR introduces another check to avoid a warning from mobx.
=> Fix test warning from mobx

package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Toolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js, src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/MultiSelectionStore.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js, src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/TeaserSelection.js, src/Sulu/Bundle/RouteBundle/Resources/js/containers/types.js
| Q | A
| --- | ---
Updates flow to version 0.120 with all required changes.
=> Update to flow 0.120

src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing.yml, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php, src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php, src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5142 
This PR fixes the loading of doctrine entities in smart contents with sorting.
=> Fix sorting of smart-content for doctrine entities

composer.json, src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php, src/Sulu/Bundle/MediaBundle/Media/Storage/AzureBlobStorage.php, src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_azure_blob.xml, src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/AzureBlobStorageTest.php
| Q | A
| --- | ---
| Related issues/PRs |-
| Documentation PR | sulu/sulu-docs#502
Azure Blob Storage implementation
We have a proposal from a potential client that requires the use of azure. More and more companies are using the Microsoft cloud
See docs
I suggest to refactor s3 Storage because in 2.0 access to client in s3 will be removed ( see https://github.com/thephpleague/flysystem-azure-blob-storage/pull/18 )
=> [MediaBundle] Azure Blob Storage implementation

config/packages/prod/sulu_document_manager.yaml
| Q | A
| --- | ---
| Related issues/PRs | Requires: https://github.com/sulu/sulu/pull/5184, Skeleton: https://github.com/sulu/skeleton/pull/45
Activate phpcr node cache.
Can increase the performance drastically.
See example configuration in this PR.
=> Add phpcr node cache configuration

composer.json
| Q | A
| --- | ---
Fix lowest test for azure storage.
Require min version of microsoft azure library.
=> Fix lowest test for azure storage

flow-typed/npm/react-dom_v16.x.x.js, package.json, src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/AutoCompletePopover.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Select.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js, src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/defaultWebspace.js, src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/index.js, src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/ContactDetails.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaVersionUpload.js, src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/PageList.test.js, src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Permissions/tests/Permissions.test.js, src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/tests/SnippetAreas.test.js
| Q | A
| --- | ---
This PR updates the `flow-bin` dependency to the version `0.122`. Furthermore, it adjusts the codebase to be compatible with the new version.
=> Update flow version to version 0.122

src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/AccountRepositoryTest.php, src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php
| Q | A
| --- | ---
This PR refactorss the `AccountRepositoryTest` and the `ContactRepositoryTest`, so that they have a better performance.
Because Appveyor stalls quite often when these tests are executed.
=> Improve performance of ContactBundle Tests

.php_cs.dist, src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php, src/Sulu/Component/CustomUrl/Repository/RowsIterator.php, src/Sulu/Component/Localization/Localization.php, src/Sulu/Component/Rest/Listing/ListQueryBuilder.php
| Q | A
| --- | ---
This PR fixes a regression introduced in `php-cs-fixer` 2.16.2.
Because otherwise our build fails.
=> Fix regression of php-cs-fixer

.php_cs.dist, src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/MetadataProviderRegistryTest.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/SingleMediaSelectionTest.php, src/Sulu/Component/CustomUrl/Repository/RowsIterator.php
Just created a PR to check if build is working.
=> Merge 1.6 into 2.0

.php_cs.dist, src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/MetadataProviderRegistryTest.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php, src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/SingleMediaSelectionTest.php, src/Sulu/Bundle/PreviewBundle/EventSubscriber/CacheCommandSubscriber.php, src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml, src/Sulu/Bundle/PreviewBundle/Tests/Unit/EventSubscriber/CacheCommandSubscriberTest.php, src/Sulu/Component/CustomUrl/Repository/RowsIterator.php
Just created to run the build.
=> Merge 2.0 into master

.github/workflows/test-application.yaml, README.md
See: https://github.com/nnatter/sulu/tree/enhancement/readme-123/README.md
=> Add Github actions badge to README.md

src/Sulu/Component/Rest/Tests/Unit/Csv/CsvHandlerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5223 
This PR adds a test case for calling the CsvHandler with a CollectionRepresentation instance.
=> Add test case for calling CsvHandler with CollectionRepresentation

composer.json
| Q | A
| --- | ---
https://github.com/sulu/SuluArticleBundle/pull/459#discussion_r411246237
=> Remove full stop in description in composer.json

src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
=> Typo in InitializeCommand.php

src/Sulu/Bundle/HttpCacheBundle/Resources/varnish/sulu.vcl
| Q | A
| --- | ---
| Fixed tickets | fixes #4647
| Related issues/PRs | https://github.com/sulu/sulu-docs/pull/426
Remove headers in varnish example sulu vcl
See  https://github.com/sulu/sulu-docs/pull/426
=> Remove headers in varnish example sulu vcl

src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202005191116.php
| Q | A
| --- | ---
Add missing migration for page-teaser provider in snippets.
=> Add page teaser migration for snippets

src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | #5315
This PR fixes some flow errors.
=> Fix flow error

src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountMediaControllerTest.php
| Q | A
| --- | ---
This PR improves the perfomance of the `AccountMediaControllerTest`
Because we currently have stalling builds sometimes again.
=> Improve performance of AccountMediaControllerTest

composer.json
| Q | A
| --- | ---
Update branch aliases.
As long as we use the release prefixes in sulu for branches we need to update them also in the composer.json.
=> Update branch aliases

config/packages/cache.yaml, config/packages/dev/debug.yaml, config/packages/dev/monolog.yaml, config/packages/dev/routing.yaml, config/packages/framework.yaml, config/packages/prod/doctrine.yaml, config/packages/prod/monolog.yaml, config/packages/routing.yaml, config/packages/stage/routing.yaml, config/packages/test/routing.yaml
| Q | A
| --- | ---
Update recipe config files.
Also the config files should atleast be updated to symfony 4.4.
=> Update recipe config files

src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactMediaControllerTest.php
| Q | A
| --- | ---
This PR improves the perfomance of the `ContactMediaControllerTest`
Because we currently have stalling builds sometimes again.
=> Improve performance of ContactMediaControllerTest

src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/SearchIntegration/SearchIntegrationTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5320 
This PR fixes the search indexing of `single_media_selection` fields on pages.
=> Fix indexing of single_media_selection

composer.json, src/Sulu/Bundle/AdminBundle/Admin/Admin.php, src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlControllerTest.php, src/Sulu/Component/Security/Authorization/AccessControl/SecuredEntityInterface.php
| Q | A
| --- | ---
Remove aferrandini/urlizer for php 7.4 compatibility.
Add missing typehints for phpstan
=> Remove aferrandini/urlizer and add missing typehints

src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
| Q | A
| --- | ---
This PR fixes an issue with ESLint.
A new version of jsx-a11y has been released, that caused an error in our code.
=> Fix eslint regression regarding a11y

src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Item.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/__snapshots__/MultiItemSelection.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap, src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/TeaserSelection.js, src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/tests/TeaserSelection.test.js, src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/tests/__snapshots__/TeaserSelection.test.js.snap
| Q | A
| --- | ---
Fix edit of Teaser with deep link.
Currently you can not edit any teasers.
=> Fix edit of Teaser with deep link

src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/README.md, styleguide.config.js
| Q | A
| --- | ---
Fix README of Grid component and change title of styleguide
Because the old `size` attribute was used instead of `colSpan`
=> Fix Grid documentation

UPGRADE.md, src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php, src/Sulu/Bundle/DocumentManagerBundle/Initializer/Initializer.php, src/Sulu/Bundle/SecurityBundle/Build/InitSecurityBuilder.php, src/Sulu/Bundle/SecurityBundle/Build/SecurityBuilder.php, src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php, src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php, src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php, src/Sulu/Bundle/SecurityBundle/Entity/Role.php, src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php, src/Sulu/Bundle/SecurityBundle/Entity/UserRole.php, src/Sulu/Bundle/SecurityBundle/Exception/AssignAnonymousRoleException.php, src/Sulu/Bundle/SecurityBundle/Resources/config/command.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/lists/roles.xml, src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml, src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/RolePermissions.js, src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php, src/Sulu/Bundle/SecurityBundle/Tests/Unit/Entity/UserRoleTest.php, src/Sulu/Component/Security/Authentication/RoleInterface.php, src/Sulu/Component/Security/Authentication/RoleRepositoryInterface.php
| Q | A
| --- | ---
Add anonymous flag to role.
We need the possibility to set permissions for anonymous users so we need anonymous roles in every system.
=> Add anonymous roles for each system

src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/PermissionControllerTest.php, src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
| Q | A
| --- | ---
| Related issues/PRs | #5406 
#5406 introduced some failing tests for `prefer-lowest`, this PR is going to fix that.
=> Fix failing tests

config/bundles.php, config/packages/security_website.yaml, config/routes/sulu_website.yml, templates/static/login.html.twig
| Q | A
| --- | ---
This PR adds a firewall and a login to the website kernel.
Because it is easier to test certain features this way.
=> Add website security to properly test security related features

src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/NavigationTwigExtensionTest.php, src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php, src/Sulu/Component/Content/Query/ContentQueryExecutor.php, src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
| Q | A
| --- | ---
This PR fixes the navigation twig extension if the security is enabled but no token isset.
This can happen if the current route is not inside a firewall or no token was initialized.
=> Fix function to get user from token-storage if no token is set

src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/ExportToolbarAction.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/ExportToolbarAction.js
| Q | A
| --- | ---
| Fixed tickets | fixes #4943 
| Related issues/PRs | #4943 
Pass filters and search parameters to export.
=> Include filters and search to list export button

src/Sulu/Bundle/AdminBundle/Resources/js/components/CircleSelection/CircleSelection.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/CircleSelection/ModifiableCircle.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/CircleSelection/circleSelection.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/CircleSelection/tests/CircleSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/CircleSelection/tests/ModifiableCircle.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/CircleSelection/types.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/ModifiableRectangle.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/rectangleSelection.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/ModifiableRectangle.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/ImageMap/imageRenderer.scss, templates/pages/includes/image_map.html.twig
| Q | A
| --- | ---
Fixes `CircleSelection`/`RectangleSelection` performance issues on safari
Because safari is a supported browser and therefore users should not experience any issues when using it.
=> Fix image map on safari

.github/workflows/trigger-styleguide-build.yaml
Looks like i broke this with https://github.com/sulu/sulu-javascript-docs/pull/2 😇
=> Fix workflow name in trigger-styleguide-build action

src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
| Q | A
| --- | ---
Add return 0 for success build download.
Fix exit code for update build command.
```
bin/console sulu:admin:update-build
```
=> Fix exit code for update build command

src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/ImageMap/ImageMap.js, src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/ImageMap.test.js
| Q | A
| --- | ---
Fixes default values for ImageMap similar to https://github.com/sulu/sulu/pull/5576
Furthermore some changes in `FieldBlocks` have been made to be more consistent with other components.
Default values should work as expected.
=> Fix ImageMap default values

src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php, src/Sulu/Bundle/AdminBundle/Admin/View/ViewRegistry.php, src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
| Q | A
| --- | ---
| New feature? | AdminBundle phpstan level 5
Implemented together with @rogoit some typhint fixes acording to phpstan and increased the phpstan level from 1 to 5 in the AdminBundle
Its always better to have better sofware and also because of Hacktoberfest2020 event, if you merge the PR please add a label "hacktoberfest-accepted" so i can win a t-shirt
=> Improve phpdoc in AdminBundle

src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkPlugin.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/InternalLinkPlugin.js, src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json, src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
* Add subscript, superscript and code plugins to ckeditor
* Fix styling issues of ckeditor's dropdown panels
=> Add subscript, superscript and code plugins to ckeditor

src/Sulu/Bundle/CategoryBundle/Api/Category.php, src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php, src/Sulu/Bundle/CategoryBundle/Category/CategoryManagerInterface.php, src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepositoryInterface.php
| Q | A
| --- | ---
Easy fixes in AudienceTargetingBundle for PHPStan level 2
Open source is passion and i want to give something back
=> Some fixes for PHPStan level 2 on AudienceTargetingBundle

src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
See https://github.com/sulu/skeleton/pull/76
=> Include postcss.config.js in UpdateBuildCommand

src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/divider.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Divider/variables.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Section.js, src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/grid.scss, src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/__snapshots__/Section.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap, src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap, src/Sulu/Component/Content/Metadata/BlockMetadata.php, src/Sulu/Component/Content/Metadata/ItemMetadata.php, src/Sulu/Component/Content/Metadata/PropertiesMetadata.php, src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php, tests/Resources/DataFixtures/Page/template_block_with_sections.xml
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/5028
Removes the `SectionProperties` for blocks similar to the sections in forms and thus fixing the bug from https://github.com/sulu/sulu/issues/5028
=> Fix sections in blocks

src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
| Q | A
| --- | ---
Add autowire for the storage interface.
Improve the DX to have autowiring for the storage interface.
=> Add autowire for the storage interface

src/Sulu/Bundle/ContactBundle/Api/Account.php, src/Sulu/Bundle/ContactBundle/Api/Contact.php, src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php, src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php, src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php, src/Sulu/Bundle/ContactBundle/Contact/ContactManagerInterface.php, src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php, src/Sulu/Bundle/ContactBundle/Controller/AccountController.php, src/Sulu/Bundle/ContactBundle/Controller/ContactController.php, src/Sulu/Bundle/ContactBundle/Controller/ContactTitleController.php, src/Sulu/Bundle/ContactBundle/Controller/PositionController.php, src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php, src/Sulu/Bundle/ContactBundle/Entity/Contact.php
| Q | A
| --- | ---
More work to go forward to PHPStan level 2
Because we support every saturday night this great CMS
=> Fix some type issues for phpstan level 2

src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/multiSelection.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/singleSelection.scss, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js, src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/__snapshots__/SingleSelection.test.js.snap, src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/tests/fields/__snapshots__/PageTreeRoute.test.js.snap
| Q | A
| --- | ---
| Fixed tickets | fixes #5632 
Add publish indicator to selection and single_selection field types
To enhance user experience
=> Add publish indicator to selection and single_selection field types

src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php, src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #5598 
I've implemented a fix for issue #5598. I have appended the requestFormat in the getRedirectRoute method.
=> Fix add request format to redirect url

src/Sulu/Bundle/CoreBundle/Cache/StructureWarmer.php, src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php, src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php
| Q | A
| --- | ---
Improvements for PHPStan level 2 on CoreBundle
Because we love open source projects and want to go up in the contributer ranking
=> Fixes for PHPStan level 2 in Core bundle

.github/workflows/test-application.yaml
| Q | A
| --- | ---
Enhance test-application workflow by adding database to job name and specifying postgres version `12.5` since sulu has some performance issues with `latest`
=> Enhance test-application workflow

UPGRADE.md, src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
Fixes #5601
| Q | A
| --- | ---
| Fixed tickets | fixes #5601
Added a default for the new anonymous column
PGSql won't be able to upgrade
=> Adding default to anonymous column

.github/workflows/test-application.yaml
| Q | A
| --- | ---
Fix db version of postgres
Symfony thought, postgres version would be `5.7`, but postgres service is running on `12.5`
=> Fix db version of postgres

src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/InvalidationSubscriber.php
| Q | A
| --- | ---
Improvements for PHPStan level 2 on
Better type hint in our ide´s
=> add better php doc for phpstan lvl2 HttpCacheBundle

src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php, src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php, src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php, src/Sulu/Bundle/MediaBundle/Controller/AbstractMediaController.php, src/Sulu/Bundle/MediaBundle/Controller/MediaController.php, src/Sulu/Bundle/MediaBundle/Controller/MediaFormatController.php, src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php, src/Sulu/Bundle/MediaBundle/Entity/FileVersionContentLanguage.php, src/Sulu/Bundle/MediaBundle/Entity/FileVersionPublishLanguage.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php, src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php, src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php, src/Sulu/Bundle/MediaBundle/Media/FormatLoader/BaseXmlFormatLoader.php, src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManagerInterface.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Cropper/Cropper.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Scaler/Scaler.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Scaler/ScalerInterface.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/PasteTransformation.php, src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/TransformationInterface.php, src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php, src/Sulu/Bundle/MediaBundle/Search/Subscriber/MediaSearchSubscriber.php, src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php
| Q | A
| --- | ---
What's in this PR?
Improvements for PHPStan level 2 on MediaBundle
40 errors are still open for PHPStan level 2 on MediaBundle
Why?
Better type hint in our ide´s
=> add better php doc for phpstan lvl2 MediaBundle

src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php, src/Sulu/Component/Contact/SmartContent/ContactDataProvider.php, src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php, src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
| Q | A
| --- | ---
Fixes the query built with the `DataProviderRepositoryTrait`.
Currently limiting is done first and therefore sorting only works on the first limited results.
=> Fix query issue when sorting and limiting

src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php
| Q | A
| --- | ---
just fix a little copy paste typo
=> Fix little copy paste typo

src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php, src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/AdminControllerTest.php, src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
| Q | A
| --- | ---
Remove unnecessary type from media_selection json schema
=> Remove unnecessary type from media_selection json schema
