- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Entity/BaseCollection.php
This PR sets the `BaseCollection`-properties to protected, because one of our servers didn't handle that correctly (although it works on a lot of machines). And it looks like what you should do, according to the [Doctrine documentation](http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html)
__Tasks:__
> changed base collection properties to protected for inheritance

- CHANGELOG.md
- src/Sulu/Component/Content/Types/ResourceLocator.php
avoid url move in resource locator content type called when nothing changed
__Tasks:__
| Fixed tickets | #741
> Hotfix avoid call move resourcelocator on none changed url

- src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/Compiler/HandlerPass.php
In the cache handler pass we get the class of the service definition, however this is a parameter name and it needs to be resolved to a class name.
> [HOTFIX] Resolve configuration parameter

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/http-cache.xml
The incorrect event name was being used for the invalidator due to a recent change.
> [HOTFIX] Incorrect event name used for HTTP cache invalidator

- src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
- src/Sulu/Component/Content/StructureManager.php
this needs to be done, because otherwise default configs can not be overwritten by other bundles in other webspaces. this issue occurred because it was no longer possible to user an other excerpt.xml defined in the configs.
> [BUGFIX] reversed structure paths

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Content/Types/SingleInternalLink.php
> Fixed bug with empty selection with single internal link

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Content/Types/SmartContent/SmartContent.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Types/SmartContent/SmartContentTest.php
__Tasks:__
| Doc           | https://github.com/sulu-cmf/docs/commit/040257e43fc7d50d5c8b8f571278caffb811974c
> Added default values for smart content view vars

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/CoreBundle/Tests/DependencyInjection/SuluCoreExtensionTest.php
- src/Sulu/Bundle/SecurityBundle/Command/CreateRoleCommand.php
- src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
- src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateRoleCommandTest.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateUserCommandTest.php
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
- Do not crash if role already exists
- Show error message instead and exit with status 1
- Handle case where no roles exist
- Handle errors in CreateUser command
- Handle case where requested role does not exist
- Handle case where username already exists
__Tasks:__
| Fixed tickets | fixes https://github.com/sulu-cmf/sulu/issues/465
| BC Breaks     | 
| Doc           |
> SecurityBundle command improvements

- src/Sulu/Bundle/SecurityBundle/Behat/SecurityContext.php
In the behat tests the login screen no longer seems to contain the HTML form when the DOM is ready.
This fix waits for the `#username` selector to appear before filling the form in.
> Wait for username to appear on login screen

- src/Sulu/Component/HttpCache/HttpCache.php
Do not send a 404 on purge when the (Sulu) HTTP cache does not find a cached page to purge.
> Send 200 instead of 404 in HTTP cache

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/permission-tab/components/form/main.js
Fixed small bug, which prevented the "Select All" and "Select None" in the matrix to be working.
> fixed select all for permission-tab

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
__Tasks:__
| Fixed tickets | fixes #983, fixes #982 
| BC Breaks     | yes?
Part of: https://github.com/sulu-io/sulu-standard/pull/437/files
> Set functional defaults for media headers and ghostscript path 

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
__Tasks:__
| Fixed tickets | fixes sulu-io/sulu-standard#423
| BC Breaks     | yes => UPGRADE
> Changed internal link title for navigation, smartcontent and internal link

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureDriver.php
Why is the webspace key index to unstored? does this mean that it is not stored in the index? @danrot @dantleech @chirimoya 
__tasks:__
> Webspace key index

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/config/search.xml
- src/Sulu/Bundle/MediaBundle/Search/Subscriber/MediaSearchSubscriber.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Search/Subscriber/MediaSearchSubscriberTest.php
It makes no sense to try and determine an image URL for a video, pdf or office document (at least not yet).
This PR changes the media search indexer to only determine the image URL for medias whose mime type starts with `image`.
Fixes: #1089
> Do not try and determine the image URL for non-image media in search

- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Component/Security/Authorization/AccessControl/SymfonyAccessControlManager.php
- src/Sulu/Component/Security/Event/PermissionUpdateEvent.php
- src/Sulu/Component/Security/Event/SecurityEvents.php
- tests/Sulu/Component/Security/Authorization/AccessControl/SymfonyAccessControlManagerTest.php
Adds the `sulu.security.permission.update` event, which will be required to copy some of the permission settings to other objects for better performance in lists.
__tasks:__
> added an event for updated permissions

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/MediaBundle/DependencyInjection/ImageCommandCompilerPass.php
- src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/Manager/CommandManager.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/SuluMediaBundle.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/ImageCommandCompilerPassTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/SuluMediaExtensionTest.php
The image converter commands are now handled via the `sulu_media.image.command` service container tag. No need for the 
`sulu_media.image.command.prefix` anymore.
__Tasks:__
| Fixed tickets | #1032 
| BC Breaks     | yes, if application devs created own image converter commands
> [ENHANCEMENT] Use tagged services instead of prefix for image converter commands

- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
Fixes the namespace for the initializer in the webspace bundle.
Anything relating to the document manager should be in `Document/` namespace. Documents should be directly in this namespace `Document/FooDocument` and other things should be in sub namespaces, such as `Document\Initializer`, `Document\Subsciber` etc.
> Fixed document namespace

- src/Sulu/Bundle/ContentBundle/Document/BasePageDocument.php
- src/Sulu/Bundle/ContentBundle/Form/Type/AbstractStructureBehaviorType.php
- src/Sulu/Bundle/ContentBundle/Form/Type/BasePageDocumentType.php
- src/Sulu/Bundle/ContentBundle/Resources/config/document.xml
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
- src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php
- src/Sulu/Bundle/DocumentManagerBundle/Bridge/PropertyEncoder.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Bridge/DocumentInspectorTest.php
- src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php
- src/Sulu/Bundle/SearchBundle/EventListener/ContentSubscriber.php
- src/Sulu/Bundle/SearchBundle/EventListener/StructureSubscriber.php
- src/Sulu/Bundle/SearchBundle/Resources/config/search.xml
- src/Sulu/Bundle/SnippetBundle/Document/SnippetDocument.php
- src/Sulu/Bundle/SnippetBundle/Form/SnippetType.php
- src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
- src/Sulu/Component/Content/Document/Behavior/ExtensionBehavior.php
- src/Sulu/Component/Content/Document/Behavior/LocalizedStructureBehavior.php
- src/Sulu/Component/Content/Document/Behavior/StructureBehavior.php
- src/Sulu/Component/Content/Document/Behavior/StructureTypeFilingBehavior.php
- src/Sulu/Component/Content/Document/Subscriber/Compat/MapperRemoveSubscriber.php
- src/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriber.php
- src/Sulu/Component/Content/Document/Subscriber/StructureRemoveSubscriber.php
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- tests/Sulu/Component/Content/Document/Property/ManagedPropertyContainerTest.php
- tests/Sulu/Component/Content/Document/Subscriber/ContentSubscriberTest.php
- tests/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriberTest.php
- tests/Sulu/Component/Content/Document/Subscriber/StructureSubscriberTest.php
- tests/Sulu/Component/Content/Document/Subscriber/WorkflowStageSubscriberTest.php
This PR will change all references to `Content` in class names to `Structure`.
The term `Content` is generally not used, and will be removed from the Glossary.
> Refactoring "Content" to "Subscriber"

- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
- src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
- src/Sulu/Component/Content/Document/Property/ManagedPropertyContainer.php
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Metadata/BlockMetadata.php
- src/Sulu/Component/Content/Metadata/ComponentMetadata.php
- src/Sulu/Component/Content/Metadata/ItemMetadata.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php
- src/Sulu/Component/Content/Metadata/PropertyMetadata.php
- src/Sulu/Component/Content/Metadata/SectionMetadata.php
- src/Sulu/Component/Content/Metadata/StructureMetadata.php
- tests/Sulu/Component/Content/Document/Property/ManagedPropertyContainerTest.php
- tests/Sulu/Component/Content/Document/Subscriber/StructureSubscriberTest.php
- tests/Sulu/Component/Content/Metadata/ItemMetadataCase.php
- tests/Sulu/Component/Content/Metadata/StructureMetdataTest.php
This PR changes the API for `Structure`:
- `getModelProperties` => `getProperties`.
- `getProperties(true)` => `getProperties`. get properties now always returns only non-UI children. `->getChildren` can be used to get everything including Sections.
> Renamed structure methods

- CHANGELOG.md
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
if you have a shadow page the url for that in the language switcher on the webpage.
__tasks:__
> URL of shadow pages are not delivered in the urls array

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
- src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/CollectionMeta.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/File.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionMeta.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Media.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/MediaType.orm.xml
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
Something like this would be the solution for the products issue (https://github.com/sulu-io/sulu/issues/1224) too.
__tasks:__
> Improved speed for media list query

- src/Sulu/Bundle/ContentBundle/Behat/BaseStructureContext.php
- src/Sulu/Bundle/ContentBundle/Resources/config/serializer/Document.BasePageDocument.xml
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeResourcelocatorControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Search/BaseTestCase.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Search/DeleteDocumentTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Search/SaveDocumentTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Search/SearchManagerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/app/Resources/pages/blocks.xml
- src/Sulu/Bundle/ContentBundle/Tests/app/config/search.yml
- src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php
- src/Sulu/Bundle/TranslateBundle/Tests/Functional/Controller/CodeControllerTest.php
- src/Sulu/Component/Content/Document/Subscriber/WebspaceSubscriber.php
This PR prevents all block properties from being indexed by default.
In addition it fixes the webspace indexing, changes the search tests to use the `zend_lucene` implementation (instead of the `test` adapter) and fixes a behat issue.
> Do not index non tagged block fields

- CHANGELOG.md
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
- src/Sulu/Component/Content/Mapper/ContentMapper.php
Also reintroduces the possibility to use csrf protection on the website.
Should be merged together with https://github.com/sulu-io/sulu-standard/pull/471, since this PR is enabling the csrf_protection again.
__tasks:__
> reenabled csrf protection and disabled it only for the content mapper

- CHANGELOG.md
- src/Sulu/Bundle/AdminBundle/Navigation/NavigationItem.php
Currently this is only a quickfix, i would prefer delete the ID from the API and handle it better in the frontend?
__Tasks:__
| Fixed tickets | fixes https://github.com/sulu-io/sulu-standard/issues/472
> Fixes unique navigation id

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Build/DatabaseBuilder.php
There was an error if the database has not been created yet in the `app/console sulu:build` command.
The "test" is in https://github.com/sulu-io/sulu-standard/pull/479
__tasks:__
> fixed database builder for instantiating not exsting database

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
- src/Sulu/Component/Content/Document/Subscriber/AbstractMappingSubscriber.php
- src/Sulu/Component/Content/Document/Subscriber/OrderSubscriber.php
- tests/Sulu/Component/Content/Document/Subscriber/OrderSubscriberTest.php
- tests/Sulu/Component/Content/Document/Subscriber/SubscriberTestCase.php
The `sulu:order` property have not been properly updated for existing pages, this worked only for new ones. This PR fixes that.
Should be also merged to master, and probably be released as a hotfix.
__tasks:__
| Fixed tickets    | fixes #1377 
> Fixed sorting of pages

- CHANGELOG.md
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
- tests/app/Resources/pages/overview_smart_content.xml
The `published` value in the resolved smart content was a boolean again, instead of a `DateTime` object.
__tasks:__
| Fixed tickets    | fixes #648 (again)
| BC breaks        | `published` is a `DateTime` object instead of a boolean
> set published to date instead boolean

- CHANGELOG.md
- src/Sulu/Component/Localization/Provider/LocalizationProvider.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
When the value is provided by a Doctrine query result, it was returned as a string.
__Information__
| Q                | A
| Fixed tickets    | N/A
| BC breaks        | None
| Documentation PR | N/A
> Cast DoctrineListBuilder::count return value to an integer

- CHANGELOG.md
- src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php
- tests/Resources/DataFixtures/Page/template.xml
- tests/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoaderTest.php
Booleans were not interpreted as booleans by the XmlLoader, this has been fixed.
__tasks:__
| Fixed tickets    | fixes #1430 
| BC breaks        | `"true"` and `"false"` are not interpreted as strings anymore
> fixed displayOptions in media selection

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/smart_content.xml
- src/Sulu/Bundle/TagBundle/Resources/config/services.xml
- src/Sulu/Bundle/TagBundle/Tests/Unit/Twig/TagTwigExtensionTest.php
- src/Sulu/Bundle/TagBundle/Twig/TagTwigExtension.php
- src/Sulu/Component/SmartContent/ContentType.php
- src/Sulu/Component/Tag/Request/TagRequestHandler.php
- src/Sulu/Component/Tag/Request/TagRequestHandlerInterface.php
- tests/Sulu/Component/SmartContent/ContentTypeTest.php
- tests/Sulu/Component/Tag/Request/TagRequestHandlerTest.php
Ability to add tags from the website URL to the filters.
__tasks:__
Related PR: https://github.com/sulu-io/sulu-standard/pull/486
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/64
> Append SmartContent tags from website URL parameter

- src/Sulu/Bundle/ContentBundle/Admin/ContentAdmin.php
- src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
- src/Sulu/Bundle/ContentBundle/Controller/PreviewController.php
- src/Sulu/Bundle/ContentBundle/Preview/PreviewMessageHandler.php
- src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
- src/Sulu/Bundle/ContentBundle/Repository/NodeRepositoryInterface.php
- src/Sulu/Bundle/ContentBundle/Resources/config/services.xml
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/resource-locator/main.js
- src/Sulu/Bundle/ContentBundle/Resources/public/js/main.js
- src/Sulu/Bundle/ContentBundle/Resources/public/js/model/content.js
- src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/resourceLocator.js
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/NodeRepositoryTest.php
- src/Sulu/Bundle/SearchBundle/Resources/public/js/components/search-results/main.js
- src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/snippet/main.js
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Mapper/ContentMapperInterface.php
- tests/Sulu/Component/Content/Mapper/ContentMapperTest.php
Removes the special handling for an ID called `index`, and uses the real ID of the startpage also in the frontend instead.
Required in order for the permissions in #1477 to be working with the start page.
__tasks:__
| BC breaks        | `saveStartPage` and corresponding methods have been removed
> removed index specific code from content

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
Currently the external link does redirect to the resource locator of the page, instead of its defined external link.
__tasks:__
> fixed redirect on external link page

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Structure/SeoStructureExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Meta/MetaTwigExtension.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
Fixes the canonical tag issue for shadow pages in a new twig extension. Also fixes #1533.
__tasks:__
| Fixed tickets    | fixes #1533 
| BC breaks        | `sulu_meta_seo` twig method is now deprecated, use `sulu_seo` instead
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/70
> fixed canonical tag for shadow pages

- CHANGELOG.md
- src/Sulu/Component/Webspace/Analyzer/WebsiteRequestAnalyzer.php
- tests/Sulu/Component/Webspace/Analyzer/RequestAnalyzerTest.php
Moved PR #1586 to master branch as hotfix
The ```WebsiteRequestAnalyzer``` sets the request format by exploding the requested file name by dots and extract the format from the resulting array. When a filename has multiple dots in it, the second item will be set as the request format (and not the last one as it should be).
This is behaviour is fixed by this PR.
Example:
A request for ```bootstrap.min.css``` results the file format ```min```. Expected would be ```css```
> [hotfix] fix website request analyzer

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Admin/MediaContentNavigationProvider.php
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
This missing check caused the search reindex command to fail.
__tasks:__
> added further null reference checks to MediaManager

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Component/Content/Document/Subscriber/OrderSubscriber.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
Without this the ordering of pages is not working in the navigation of the website.
Created issue https://github.com/sulu-io/sulu-document-manager/issues/39
__tasks:__
> readded the reorder event to the OrderSubscriber

- .travis.yml
I decided to remove the allowed failure for jackalope doctrine dbal, because they are slowing down our tests, although all of us know they are currently failing. We can add them later again, once we fixed the jackalope doctrine dbal issues.
__tasks:__
> removed allowed failures to improve test speed

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php
currently its not possible to use attribute overrides in doctrine on the email. in my case I have on my website a protected area with login where the email address should not be unique.
e.g.
``` xml
<attribute-overrides>
<attribute-override name="email">
<field unique="false" nullable="true" />
</attribute-override>
</attribute-overrides>
```
__Tasks:__
> Change email to protected to allow attribute overrides

- CHANGELOG.md
- src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
Let the rest api return status 409 instead of 500, if the resource locator is already existing. Merge with https://github.com/sulu-io/sulu-standard/pull/525
__tasks:__
| Fixed tickets    | fixes #1112 
> added separate status code for occupied resource locator

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/smartContent.js
It only happens with a clean new install of sulu.
The homepage form cannot be loaded because no config (null) will be set to smart-content.
__tasks:__
> Fixed null value for smart content

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
Replaced StreamedResponse with BinaryFileResponse.
StreamedResponse is not able to make use of the "range" header, which is needed to display videos inline.
> Support for Video-Stream

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/ShadowLocaleSubscriber.php
- tests/Sulu/Component/Content/Document/Subscriber/ShadowLocaleSubscriberTest.php
__tasks:__
__Related PR:__
* https://github.com/sulu-io/sulu-document-manager/pull/52
| Fixed tickets    | fixes #1704 
> Added empty locale condition

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Entity/UserRepository.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Entity/UserRepositoryTest.php
That's actually an issue targeted at the 1.2 release, but I think we could also include it in 1.1, since it is not a big change.
__tasks:__
| Fixed tickets    | fixes #1630 
> added missing joins to user to prevent lazy loading

- CHANGELOG.md
- src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
- tests/Sulu/Component/Security/Authorization/AccessControl/AccessControlManagerTest.php
__tasks:__
| BC breaks        | Locale security works now as expected
> fixed missing locale check for security

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/smart-content/main.js
When opening smart-content overlay there is an error of preselectedElements are null in select component.
> Fixed preselected select elements null 

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/NodeResourcelocatorController.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Types/ResourceLocator.php
- src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php
- tests/Sulu/Component/Content/Document/Subscriber/StructureSubscriberTest.php
- tests/Sulu/Component/Content/Rlp/Mapper/PhpcrMapperTest.php
This fixes the disappearance of entire route trees. Also the handling of content types have been improved, so that it will be easier to find errors in production systems.
__tasks:__
| BC breaks        | hopefully none, every introduced BC break would be a bug
> Refactored url and content type handling

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
- src/Sulu/Bundle/CoreBundle/Tests/DependencyInjection/SuluCoreExtensionTest.php
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
__tasks:__
| Related PRs      | https://github.com/sulu-io/sulu-standard/pull/567
| BC breaks        | `sulu_core.content.structure.typeMap` is now `sulu_core.content.structure.type_map`
> fixed name of type map config parameter

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201512090753.php
There are problems with the index-command if you have properties which looks like this: `i18n:-*` you get the error 
````
Error indexing or de-indexing page (path: ...) No structure type was available and no default exists for document with alias "home"
```
| BC breaks        | run `phpcr:migrations:migrate`
> Added upgrade script which removes non-translated properties

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201511240843.php
- src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201511240844.php
The phpcr migrations had problems with the automatic renaming of nodes,
so there we make use of the new auto_name option, so that we can disable
that.
@wachterjohannes That should probably be used in all migrations in the
future.
__tasks:__
| Related PRs      | https://github.com/sulu-io/sulu-document-manager/pull/56
> used auto_name in phpcr migrations

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Build/UserBuilder.php
fix default locale user builder :
Hardcoded locale `de` into user builder, but when `de` is not defined into 
```
sulu_core:
locales:
fr: Francais
en: English
```
leads error in command `sulu:build` and user is not created.
__tasks:__
- [ x ] Fix it 
> fix default locale user builder

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/BaseCollection.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/CollectionType.orm.xml
The given index definitions are not neccessary, because the fields mentioned there are already marked unique, and therefore are already indexed. In addition to that the index name `key_idx` was used twice. That caused postgresql to throw the error mentioned in https://github.com/sulu-io/sulu-standard/issues/584. MySQL doesn't seem to bother about this error.
| Fixed tickets    | fixes https://github.com/sulu-io/sulu-standard/issues/584
| BC breaks        | works better with postgres now :wink:
> removed unnecessary index definitions

- CHANGELOG.md
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- tests/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilderTest.php
Disable the GROUP BY clause for ID- and COUNT-Select (Performance)
__tasks:__
> Added possibility to disable the GROUP BY clause

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php
- src/Sulu/Bundle/MediaBundle/DependencyInjection/FormatCacheClearerCompilerPass.php
- src/Sulu/Bundle/MediaBundle/Media/Exception/CacheNotFoundException.php
- src/Sulu/Bundle/MediaBundle/Media/Exception/MediaException.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheClearer.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheClearerInterface.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheInterface.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManagerInterface.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/SuluMediaBundle.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/FormatCacheClearerCompilerPassTest.php
Simply renames the cache dir, deletes it as a whole and creates a new one. The command name is `sulu:media:cache:clear`
__tasks:__
| q             | a
| Fixed tickets | fixes #808 
| Related PRs | #1052 
| BC Breaks     | Webserver write permissions must be set on `web/uploads` instead of `web/uploads/media`
| Documentation PR | sulu-io/sulu-docs#166
Reopens #1052 as the branch was deleted by accident and GitHub no longer allows reopening it after rebase :dizzy_face:
> [FEATURE] Clear local image cache via cache clear service and command

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/ScaleCommand.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/ScaleCommandTest.php
The image scale command used the `x` parameter for duplicating the new height instead of the `y` parameter if the `retina` option is true.
__tasks:__
| Fixed tickets    | n/a
| Related PRs      | n/a
> [HOTFIX] Fixed retina height for image scale command

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
Merge Twig globals and add output buffer handling for rendering blocks in preview and other locations. Twigs `renderBlock()` is an internal method and thus the call must be wrapped into proper output buffer handling.
See twigphp/Twig#676
__tasks:__
| Fixed tickets    | n/a
| Related PRs      | n/a
> [HOTFIX] Merge Twig globals and add output buffer handling

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/UserLocaleListenerTest.php
__tasks:__
| BC breaks        | The language of the requests have the user language instead of the default one
> set user language for request in backend

- CHANGELOG.md
- src/Sulu/Component/Rest/ListBuilder/Metadata/Doctrine/Driver/XmlDriver.php
- src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
- src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactoryInterface.php
- tests/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactoryTest.php
- tests/Sulu/Component/Rest/ListBuilder/Metadata/Resources/options.xml
You can use `:locale` and the `$options` parameter to use request params in the metadata.
__tasks:__
> Added options for creating field-descriptors with meta-data

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
This PR enables indexing of the structure-type. It can be used to search for specific page page. 
| BC breaks        | YES reindex to use this feature
> Added structure type to index

- CHANGELOG.md
- src/Sulu/Component/Rest/ListBuilder/Metadata/PropertyMetadata.php
- src/Sulu/Component/Rest/ListBuilder/Metadata/VirtualPropertyMetadata.php
- tests/Sulu/Component/Rest/ListBuilder/Metadata/PropertyMetadataTest.php
- tests/Sulu/Component/Rest/ListBuilder/Metadata/VirtualPropertyMetadataTest.php
If you load the cached field-descriptors you get the wrong response (e.g. no display property and wrong `filter-type`) because the `GeneralMetadataSerializeSubscriber` (https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Component/Rest/ListBuilder/Metadata/Listener/GeneralMetadataSerializeSubscriber.php#L53) get null from the metadata and not appends the values from the `PropertyMetadata`.
> Added metadata property to serialization process

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
| Tests pass? | yes
| Related PRs | sulu-io/sulu-standard#626
With the new `react/socket` release 0.4.3 which requires again `evenement/evenemt: ^2.0|^1.0` it's possible to get rid of the aliased statement in Sulu itself.
Such an easy pick with the new react release, after I begun to clean up the libs which require the v1.0 :weary:
> [All] Get rid of the aliased evenement composer constraint

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/TranslateBundle/Resources/config/doctrine/Code.orm.xml
| Q | A
| --- | ---
| BC breaks? | yes (see UPGRADE)
| Fixed tickets | fixes #1997 
This PR extend the maximum length of translation codes.
> Fixed translation code length in database schema

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Resources/config/list-builder/Account.xml
| Q | A
| --- | ---
Added filter for account tags.
Because this filter wasn't implemented yet. (whaaaaat?)
Go to contacts / account list and filter the list by tag(s)
> [ENHANCEMENT] Added account tag filter

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
- src/Sulu/Bundle/CategoryBundle/Category/Exception/KeyNotUniqueException.php
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/Category.orm.xml
- src/Sulu/Bundle/CategoryBundle/Resources/views/Template/category.form.details.html.twig
- src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Controller/CountryController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Sitemap/SitemapXMLGeneratorTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/FieldDescriptorFactoryTest.php
- src/Sulu/Component/Util/ArrayUtils.php
- src/Sulu/Component/Util/Tests/Unit/ArrayUtilsTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #871 and fixes #2040 
The category key is limited to the length of 45 characters without any reason. This PR extend this to 255 and add the validation in the frontend. Additionally it fixes a bug with catching and hiding all doctrine exceptions when saving a category.
> Fixed maximum length of category-key

- .github/PULL_REQUEST_TEMPLATE.md
| Q | A
| --- | ---
This PR toggles the default values of the flags in the PR table of the PR template from "yes" to "no".
Most PRs require most of these flags to be set to "no". The current template requires 3-4 extra interactions for each PR:
~~~
~~~
Most of these have to be replaced by "no" most of the time. While the original idea was to make the creator of the PR *think* about this, I think that this quickly becomes repetitive and thus doesn't fulfill its purpose.
> Toggled the flags in the PR template from "yes" to "no"

- .travis.yml
- CHANGELOG.md
- bin/runtests.sh
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu-io/sulu/pull/2116
This content introduces a flag for restarting jackrabbit between bundle tests.
We need the restarts between the bundles for avoiding flaky tests. But on the local machine it is very annoying when executing the tests. So a flag seems like the best solution.
~~~bash
bin/runtests.sh -i -a # execute all tests with restarting jackrabbit
bin/runtests.sh -i -a -r # execute all testes without restarting jackrabbit
~~~
> added option to restart jackrabbit in tests

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
| New feature? | no, improvement
Updates the `pulse00/ffmpeg-bundle` and thus the `php-ffmpeg/php-ffmpeg` lib. Both packages contain only fixes and no BC breaks.
Symfony 3.0 compatibility. Can be merged already, independent of all other PRs coming.
> Update ffmpeg bundle and lib

- .travis.yml
- CHANGELOG.md
| Q | A
| --- | ---
| New feature? | no, improvement
It sets composer cache dir to be cached by travis, thus subsequent builds install composer dependencies from cache instead downloading it every time. As a consequence `--prefer-dist` is added, because only dist packages are cached by composer.
To improve the speed of the Travis builds. Composer has only a minor impact, but it does not harm to utilize the Travis caches.
Travis creates separate caches for every matrix line. Also a separate cache is created for every branch (an on push test). Pull requests with the same target share the same cache.
> Cache composer cache dir and prefer dist downloads on Travis

- .travis.yml
- CHANGELOG.md
| Q | A
| --- | ---
| New feature? | no, improvement
It disables xdebug on Travis. As long as code-coverage is not needed, xdebug has a major performance impact. It improves over all build time about 30% or about 15-25 minutes in absolutes. Heavily depends on the performance of the workers. Build time of Sulu is relatively volatile.
Short build times are necessary to give quicker feedback to outside collaborators. Although one should test on his work machine, for example I execute only the test runner on the affected bundle which I change. Even If I activate Travis on my fork (see https://travis-ci.org/Karisch/sulu/builds/115661561 for example), then …
> Disable xdebug on Travis to speed up composer and tests

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/AdminBundle/composer.json
- src/Sulu/Bundle/CategoryBundle/composer.json
- src/Sulu/Bundle/ContactBundle/composer.json
- src/Sulu/Bundle/ContentBundle/composer.json
- src/Sulu/Bundle/GeneratorBundle/Resources/skeleton/sulu/other/composer.json.twig
- src/Sulu/Bundle/LocationBundle/composer.json
- src/Sulu/Bundle/MediaBundle/composer.json
- src/Sulu/Bundle/ResourceBundle/composer.json
- src/Sulu/Bundle/SecurityBundle/composer.json
- src/Sulu/Bundle/SnippetBundle/composer.json
- src/Sulu/Bundle/TagBundle/composer.json
- src/Sulu/Bundle/TestBundle/composer.json
- src/Sulu/Bundle/TranslateBundle/composer.json
- src/Sulu/Bundle/WebsiteBundle/composer.json
- src/Sulu/Bundle/WebsocketBundle/composer.json
| Q | A
| --- | ---
| Related issues/PRs | #2118 
Fixes the `composer.json` files to correctly support only PHP `^5.5` and `^7.0`, so Sulu will not be installable in a future PHP 8 version :grin: 
Because `>=5.5` is wrong in terms of semver :smiley:
> Fix required version of PHP to support only ^5.5 and ^7.0

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #1471 
This PR removes the recursion appeared on the action `/admin/api/accounts` by specifically defining the SerializationContexts which should be used.
The response of the action `/admin/api/accounts` does not contain as much information about the contacts assigned to the account as it did before.
> Excluded recursion from accounts REST API

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php
- src/Sulu/Bundle/WebsiteBundle/Controller/RedirectController.php
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/RedirectControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #1946 
This PR fixes the `PortalRouteLoader` to generate redirects for partial matched Portals. If you register your custom-routes they will be generated for each Portal.
For example the website_search in the sulu-standard:
```yml
website_search:
pattern: /search
defaults:
_controller: "ClientWebsiteBundle:Search:query"
```
Generates routes for `sulu.lo/de/search` and `sulu.lo/en/search` and also for `sulu.lo/search`. The last should redirect to /en/search (en is the default locale) because sulu-pages has the same behaviour.
In this PR i have deprecated the functions: 
* …
> Fixed portal redirect to local

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Composer/MediaScriptHandler.php
| Q | A
| --- | ---
Expands console dir determination boundaries to newer symfony distribution possibilities.
As of 4.0 of Sensio Distribution Bundle (5.0 is default in Symfony 2.8 and 3.0) console "binary" has been moved to the `bin/` directory. In this case, `app/console` is no longer an option.
> Fix console dir determination to support new symfony distributions

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
This PR fixes the behavior when fetching accounts by providing ids.
Before, when you provided e.g. 20 id's, you just got 10 id's returned. Because limit was set to 10 by default. Now you get exactly the the specified amount. When providing a limit, the result will be cut.
This fixes the following issue, but only for accounts:
https://github.com/sulu-io/sulu/issues/2146
> Fixed account cget filtering of ids

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Behat/SecurityContext.php
| Q | A
| --- | ---
Replaces the duplicated logic of creating a role in the Behat context with a simple command execution. Also fixes a regression causing the behat tests to fail, because the required UI elements were hidden due to missing permissions.
Behat tests were failing because of that, and it is seldom a good idea to duplicate code :grinning:
> Fixed behat context to create correct roles

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Preview/PreviewMessageHandler.php
- src/Sulu/Bundle/ContentBundle/Resources/config/serializer/Document.BasePageDocument.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/PreviewControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Preview/DoctrineCacheProviderTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Preview/PreviewTest.php
- src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/routing.xml
- src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Request/CustomUrlRequestProcessorTest.php
- src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Compiler/RouteProviderCompilerPass.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Sitemap/SitemapXMLGeneratorTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Localization/Localization.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/AbstractRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Manager/WebspaceCollection.php
- src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
This PR fixes routes which are not managed by sulu (custom-routes and error pages).
Also in this PR is:
* Route generation fixed for custom-urls
* Preview exception (non-object)
With the changes for custom-urls there was introduced a bug which causes undetected routes and webspace not exception.
> Fixed route-validation in request processor

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php
- src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php
- src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php
| Q | A
| --- | ---
This PR fixes a bug, which caused an error to be thrown when the homepage is saved saying that the resource locator is not valid. This only happened when there was already another page, apart from the homepage, created.
Because content manager might also want to change the homepage without an error :-)
> Fixed saving of homepage

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/type/google.html.twig
| Q | A
| --- | ---
Adds the anonymizeIp option to the default google analytics template.
It is required within europe.
> IP-Anonymization for Google Analytics

- CHANGELOG.md
- src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php
| Q | A
| --- | ---
| Fixed tickets | fixes behat tests
Adds a missing locale parameter to a load for routing documents.
The behat tests are broken because of that.
> added missing locale for loading route document

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
- src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactTwigExtensionTest.php
- src/Sulu/Bundle/ContactBundle/Twig/ContactTwigExtension.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/Twig/UserTwigExtensionTest.php
- src/Sulu/Bundle/SecurityBundle/Twig/UserTwigExtension.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2089 
| Related issues/PRs | https://github.com/sulu-io/sulu-standard/pull/645
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/191
This PR fixes the behavior of the `sulu_resolve_user` function.
The old version of this function returns the contact and you cannot get the user. This PR introduces a function `sulu_resolve_contact` function which returns a contact and it fixes the `sulu_resolve_user` to return a user.
~~~php
{{ sulu_resolve_user(userId).contact.fullName }}
~~~
The `sulu_resolve_user` returns now the user to get the contact call `.contact` and the you can use it like before (see example of UPGRADE)
> Fixed resolve sulu_resolve_user function

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Translator/RequestAnalyzerTranslatorTest.php
- src/Sulu/Bundle/WebsiteBundle/Translator/RequestAnalyzerTranslator.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2188
This PR decorates the translator and lazy initialize the locale of it.
Because if you use for example in our sulu-standard `SearchController` the translator service you get all messages in the default locale (mostly en) and not in the content language. This is because the translator uses the request to determine the locale on kernel request. This PR set the locale to the locale of the reuquest-analyzer by wrapping it and set the locale to the locale of the request-analyzer.
> Fixed wrong translator locale by decorating translator

- CHANGELOG.md
- src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
- src/Sulu/Bundle/WebsiteBundle/EventSubscriber/AnalyticsSerializeEventSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/EventSubscriber/GeneratorEventSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/analytics.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml
- src/Sulu/Bundle/WebsiteBundle/SuluWebsiteBundle.php
| Q | A
| --- | ---
| Fixed tickets | fixes #1247
Adds the X-Powered-By HTTP header which can be used for Wappalyzer Sulu detection. (https://wappalyzer.com)
Sulu website detection.
> X-Powered-By HTTP header

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/DocumentManagerBundle/Initializer/RootPathPurger.php
- src/Sulu/Bundle/DocumentManagerBundle/Initializer/WorkspaceInitializer.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/RootPathPurgerTest.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/WorkspaceInitializerTest.php
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
| Q | A
| --- | ---
| Fixed tickets | fixes #2013 
This PR will remove the `check_login_on_server` check which avoids Jackalope logging into the server before workspace has been created.
When the DoctrinePHPCRBundle tries to login by default before doing anything, which makes causes a problem when needing to create the `default` workspace, as we cannot login if it does not exist.
The 1.3 version of the PHPCRBundle introduced the "admin" connection which can be used for such purposes.
> Use admin connection to initialize the system

- src/Sulu/Bundle/DocumentManagerBundle/Initializer/WorkspaceInitializer.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/WorkspaceInitializerTest.php
| Q | A
| --- | ---
| Documentation PR | sulu-io/sulu-docs#prnum
Quick fix for regression whereby the `$workspace` was not defined (code path was not tested where by the first session did not throw an exception).
> Fixed issue with workspace not being defined

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/StructureSubscriberTest.php
- src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
- src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
| Q | A
| --- | ---
| Fixed tickets | #1951
This PR adds a new, undocumented, persist option to ignore require properties in tempates.
Currently the user may define a "home" template that has required fields, in sch a case the initialization will fail.
> Added option to ignore required properties

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
| Q | A
| --- | ---
This PR fixes a mistake in the snippet-controller which creates a wrong response when snippet is referenced.
The response contains only the path to one "other" reference. This is not correct because of a typo in the SnippetController (missing append operator)
> Fixed syntax mistake in snippet-controller

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/EventListener/WebspaceSerializeEventSubscriber.php
- src/Sulu/Bundle/ContentBundle/Resources/config/services.xml
- src/Sulu/Bundle/ContentBundle/Tests/Unit/EventListener/WebspaceSerializeEventSubscriberTest.php
- src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/WebspaceUrlProviderCompilerPass.php
- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Bundle/CoreBundle/SuluCoreBundle.php
- src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/document.xml
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/routing.xml
- src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Request/CustomUrlRequestProcessorTest.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
- src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
- src/Sulu/Component/CustomUrl/Manager/CustomUrlManagerInterface.php
- src/Sulu/Component/CustomUrl/Repository/CustomUrlRepository.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php
- src/Sulu/Component/CustomUrl/Tests/Unit/WebspaceCustomUrlProviderTest.php
- src/Sulu/Component/CustomUrl/WebspaceCustomUrlProvider.php
- src/Sulu/Component/Util/Tests/Unit/WildcardUrlUtilTest.php
- src/Sulu/Component/Util/WildcardUrlUtil.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Url/WebspaceUrlChainProviderTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Url/WebspaceUrlProviderTest.php
- src/Sulu/Component/Webspace/Url.php
- src/Sulu/Component/Webspace/Url/WebspaceUrlChainProvider.php
- src/Sulu/Component/Webspace/Url/WebspaceUrlProvider.php
- src/Sulu/Component/Webspace/Url/WebspaceUrlProviderInterface.php
| Q | A
| --- | ---
| Fixed tickets | missing feature of PR #1927 and fixes https://github.com/sulu-io/sulu-standard/issues/594
This PR integrates the custom-urls into the analytics.
After merging that you can manage own analytic keys for the custom-urls.
> Integrated custom-urls into analytics

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalRoute.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
| Q | A
| --- | ---
| BC breaks? | yes see UPGRADE
| Related issues/PRs | https://github.com/sulu-io/sulu-standard/pull/655
This PR changes the way to define custom-routes.
Currently you have to know how the name of the route has been build `{portalurl}.{locale}.{custom-route-name}`. This is quite complicated and hard to maintain.
To simplify this i have changed the way routes are generated. 2 parameters (`host` and `prefix`) will be applied automatically by sulu to generate the route successfully for all portals.
~~~yml
website_search:
path: /search
defaults:
_controller: "ClientWebsiteBundle:Search:query"
~~~
~~~twig
{{ path('website_search', request.routeParameter) …
> Enhanced custom-route creation

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Api/Media.php
- src/Sulu/Bundle/MediaBundle/Controller/AbstractMediaController.php
- src/Sulu/Bundle/MediaBundle/Entity/FileVersionMeta.php
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionMeta.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/copyright.html
- src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/main.js
- src/Sulu/Bundle/MediaBundle/Resources/public/js/models/media.js
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/MediaBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu-io/sulu-standard/pull/652
This PR introduces a media-credit field.
To differentiate credits from copyright information.
> Added media field credits

- appveyor.yml
App veyor builds currently hang on `composer install`, noticed that the `zend-search` dependency times out after 300seconds cloning from Github, does not explain the ~50m wait but maybe related, switching to `--prefer-dist` to see if this improves the situation.
> Use prefer dist in composer install app_veyor

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php
- src/Sulu/Component/Content/Tests/Functional/Rlp/Mapper/PhpcrMapperTest.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the permission tab for pages. If the user changes the permissions on the page, the request erred, because the `ResourceSegmentSubscriber` couldn't handle the persist call without a locale.
This PR fixes the bug for the permission tab with pages. It was failing with the following message:
```
{"code":0,"message":"Invalid path '\/cmf\/sulu_io\/routes\/'","errors":[{"message":"Invalid path '\/cmf\/sulu_io\/routes\/'","code":0,"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/Users\/daniel\/Development\/massiveart\/sulu-standard\/vendor\/phpcr\/phpcr-utils\/ …
```
> Fixed saving of resource locator without locale

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/PortalInformation.php
- src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/PortalInformationTest.php
- src/Sulu/Component/Webspace/Url/Replacer.php
- src/Sulu/Component/Webspace/Url/ReplacerInterface.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu-io/sulu-standard/pull/654 https://github.com/sulu-io/sulu/pull/2204
| Documentation PR | https://github.com/sulu/sulu-docs/pull/195
This PR adds the `{host}` placeholder to the urls. This can be used to match every host to a portal.
In some cases its not possible to determine one single host for a portal (see platform.sh) there you get a URL which changes over time.
Also if sulu is used by a single portal this placeholder can be used to simplify the creation of webspaces.
~~~php
<environment type="dev">
<urls>
<url>{host}/{localization}</url>
</urls>
</environment>
~~~
> Added wildcard url

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Search/Reindex/StructureProvider.php
- src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/ExtensionContainerSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/2228
This PR adds the escaping of seo html tags.
if you use quotes in your seo-title or other fields the generated HTML is not valid.
> Fixed escaping of seo tags

- CHANGELOG.md
- src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionBuilderTest.php
- tests/Resources/DataFixtures/Webspace/custom-url/sulu.io.xml
| Q | A
| --- | ---
This PR removes the generation of double wildcards for custom-urls.
It cannot be selected in the base-domain dropdown and custom-urls without wildcard will not be accepted by webspace validation. Therefor it has no additional value.
> Removed double wildcard for custom-url

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
| Q | A
| --- | ---
This PR changes the alias of system-collection type in the media-repository.
If you filter for system-collections and types you will get an error becaus the same alias is used twice.
> Fixed filter media by symstem-collection and type

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/PreviewRendererTest.php
- src/Sulu/Bundle/WebsocketBundle/App/WebsocketApp.php
- src/Sulu/Component/Websocket/RatchetAppManager.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/201
This PR fixes a problem when two websockets are running on the same server.
The websocket - component from ratchet try to connect to the port 8843 for each websocket server. this cannot be disabled or the port cannot be changed.
> Introduced own websocket app to avoid connecting to port 8843

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/RedirectControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2261
This PR adds the query string to redirects caused by the internal link node type, as shown in the screenshot:
> added query string to redirect for internal links

- .travis.yml
- CHANGELOG.md
- bin/runtests
| Q | A
| --- | ---
This PR will try and cache the jackrabbit-stanalone.jar file, which is around 70M andis downloaded everytime the build runs.
Because jackrabbit can take some time to download
> Cache jackrabbit download in travis

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2266
This PR fixes the `sulu_content_path` twig function.
After changing the behavior and always returning the full-qualified-domain the domain and scheme switches if the url is not the main of the portal or the scheme was not passed to the function.
> Fixed domain switching in sulu-content path

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2026
This PR hides the webspace in internal-links selection if the webspace is not translated to the selected content locale.
The internal-link selection is broken when you have two webspaces like this:
* sulu.lo with locales de and en
* 1.sulu.lo with locale de
if you open the internal link for sulu.lo in en the internal-link don't work properly.
In the linked issue we have decided to ignore this internal-links in the first step.
> Fixed internal link webspace locale bug

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
- src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
If a different webspace is passed to default domain has to be checked if it exists in the webspace otherwise you get null for the url.
> Fixed domain problem with different webspaces

- .travis.yml
- bin/runtests
- composer.json
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/document.xml
- src/Sulu/Bundle/DocumentManagerBundle/Initializer/WorkspaceInitializer.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/WorkspaceInitializerTest.php
- src/Sulu/Bundle/MediaBundle/Entity/Media.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Entity/MediaTest.php
- src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
- src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php
- src/Sulu/Bundle/TranslateBundle/Controller/CodeController.php
- src/Sulu/Bundle/TranslateBundle/Tests/Functional/Translate/ImportTest.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
- src/Sulu/Component/CustomUrl/Document/Initializer/CustomUrlInitializer.php
- src/Sulu/Component/PHPCR/SessionManager/SessionManager.php
| Q | A
| --- | ---
| Fixed tickets | https://github.com/sulu/sulu/issues/1257
This PR will fix the Doctrine DBAL PHPCR tests (for both the ORM and Jackalope). It also (re)introduces sqlite and postgres to the test matrix (as allowed fails).
Because we should test Sulu with the more commonly used DBAL Jackalope implementation and not only
the Jackalope Jackrabbit PHPCR implementation.
> Fix DBAL MySQL tests (ORM + Jackalope). Introduce Sqlite + Postgres to matrix.

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/AbstractRequestProcessor.php
- src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
This PR fixes the redirect handling of the website routing for following configuration:
```xml
<environment type="dev">
<urls>
<url>sulu.lo/{localization}</url>
<url redirect="sulu.lo">{host}</url>
</urls>
<custom-urls>
<custom-url>*.sulu.lo</custom-url>
</custom-urls>
</environment>
```
> Fixed redirect urls for webspace

- CHANGELOG.md
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
| Q | A
| --- | ---
The `usort` callback in the `WebsiteRequestProcessor` was only sorting based on the given priority. But in addition to that, it should also sort based on the length of the matching URL, since it might be possible that multiple `portalInformation`s have the same priority. So the matching portal should be the one with the highest priority and the longest URL.
An environment configuration in the webspace xml like the following did not work as it did in 1.1:
```xml
<environment type="dev">
<urls>
<url>sulu.lo/{localization}</url>
<url language="en">sulu.lo</url>
</urls>
</environment>
```
We would suppose …
> Fixed detecting webspaces for URLs with same priority

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Entity/AnalyticsRepository.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Entity/AnalyticsRepositoryTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2293
This PR fixes the fact that analytics with `allDomains=true` appears on all webspaces.
> Fixed analytics with all domains only in created webspace

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Controller/ExceptionController.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/ExceptionControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2297
This PR changes the handling of error pages. Instead of only replacing the handling for errors in HTML mode, Sulu now takes over handling of all formats Symfony does not support (and of HTML).
> Fixed handling of non-default formats in error handling

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Preview/PreviewTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/PreviewRendererTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/SnippetTwigExtensionTest.php
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
This PR enables the request analyzer to hold attributes per request.
The public values of the request analyzer should never be overriden.
> Fixed overriding request attributes and set them on the request

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
This PR introduces the possibility to render only the content block of a page using the `partial=true` query string.
Because this behavior was already there and is required by some existing projects.
> Fixed partial rendering using query parameter

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml
- src/Sulu/Component/Rest/ListBuilder/AbstractListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilderFactory.php
- src/Sulu/Component/Rest/ListBuilder/ListBuilderInterface.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
- src/Sulu/Component/Security/Authorization/AccessControl/SecuredEntityRepositoryTrait.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2310
| Documentation PR | https://github.com/sulu/sulu-docs/pull/214
This PR adds the method `setPermissionCheck` taking a user and a permission type to the `DoctrineListBuilder`, in order to only return the values the given user has the given permission type for. This does not happen automatically, but the method has to be called manually in the controller.
~~~php
$listBuilder = $factory->create($this->container->getParameter('sulu.model.contact.class'));
$restHelper->initializeListBuilder($listBuilder, $this->getFieldDescriptors());
$listBuilder->setPermissionCheck($this->getUser(), PermissionTypes::VIEW);
$result …
> Added security checks to DoctrineListBuilder

- CHANGELOG.md
- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
| Q | A
| --- | ---
This PR fixes a "typo" in the `AdminController` which leads into return wrong system if a specific system is requested and multiple systems are configured.
> Fixed admin-controller to return correct system

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php
- src/Sulu/Bundle/ContentBundle/Resources/config/preview.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Preview/PreviewTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/PreviewRendererTest.php
- src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yml
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/SnippetTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/DataCollector/SuluCollector.php
- src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Compiler/DeregisterDefaultRouteListenerCompilerPass.php
- src/Sulu/Bundle/WebsiteBundle/EventListener/RouterListener.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml
- src/Sulu/Bundle/WebsiteBundle/SuluWebsiteBundle.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/DataCollector/SuluCollectorTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/RouterListenerTest.php
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzerInterface.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
| Related issues/PRs | includes changes from https://github.com/sulu/sulu/pull/2322, prerequisite of https://github.com/sulu/sulu/pull/2324
| Documentation PR | TODO (check)
This PR reintroduces the `RequestListener`, which will call the `RequestAnalyzer`. This change somehow discards what was changed in https://github.com/sulu/sulu/pull/2153. Instead of lazily loading, which caused circular referencing issues in the DIC, the request analyzer can now be deactivated for single routes.
Also includes a backport which has only been merged to develop.
Because we were having circular referencing issues with the lazy loading of the `RequestAnalyzer`.
> Removed lazy analyzing of the request

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#678
| Related issues/PRs | uses the same fix as https://github.com/sulu/sulu/pull/2303
This PR fixes the account-contact search like done in the PR https://github.com/sulu/sulu/pull/2303.
> Fixed account-contact search

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
| Bug fix? | yse
| Related issues/PRs | #2324 
This PR fixes a bug introduced in #2324. A method was renamed there, but has not been updated in the `ContactController`.
Because the action `/admin/api/contacts?bySystem=true` was throwing an exception now.
> fixed listing of contacts with Sulu users

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/NavigationTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/MemoizedNavigationTwigExtension.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtensionInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #492
| Related issues/PRs | #492
I created a twig-function to check which nav-item is active in these cases:
sulu.lo/overview
sulu.lo/overview?q=test
sulu.lo/overview/subpage
with this twig-extension the overview is in all cases the active element.
~~~twig
<ul class="nav nav-justified">
{% for item in sulu_navigation_root_tree('main', 2) %}
{% set activeNav = sulu_is_active_nav_element(request.resourceLocator, item.url) ? 'nav-item-active' : '' %}
<li>
<a href="{{ sulu_content_path(item.url) }}" title="{{ item.title }}">{{ item.title }}</a>
{{ activeNav }}
</li>
{% endfor %}
</ul>
~~~
> added twig-function to check if navigation-item is active

- CHANGELOG.md
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2318
This PR fixes loading of ghost-children loading by returning original locale when loading a ghost.
This locale will be used to generate the children locale.
> Fixes ghost children loading

- CHANGELOG.md
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
This PR changes the default value to `false` for `getResourceLocator` in the `RequestAnalyzer`.
False was returned before refactoring the `RequestAnalyzer` and will be needed to render the `hreflang` tag for the homepage see following file: https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php#L205
> Fixed hreflang-tag for homepage

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentPathTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathInterface.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2358
| Documentation PR | non
This PR introduces a fallback if a url for for current host does not exists.
If you pass no domain to `sulu_content_path('/test', 'sulu_io', 'en')` but the the domain of `en` is a different one than the current one.
Explained in the linked issue.
> Fixed sulu-content-path for webspaces with different domains for locales

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
| Bug fix? | (yes)
Install the symfony phpunit bridge again to get the count of deprecation notices in the phpunit tests.
The phpunit bridge was unintentionally removed with #2242 when the `symfony-cmf/testing` was removed. I never checked if the bridge was a direct dev dependency of sulu.
> Install the symfony phpunit bridge again

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/ShadowCopyPropertiesSubscriber.php
- src/Sulu/Component/Content/Tests/Functional/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
| Q | A
| --- | ---
This PR corrects the priority of the `ShadowCopySubscriber`.
The `ShadowCopySubscriber` must be called after the `MappingSubscriber`, because otherwise the navigation contexts are not already written on the node and therefore not copied.
> fixed copying shadow properties

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #2359 
This PR removes the usage of the entity manager to get the `CollectionRepository` using the entity manager and injects the `CollectionRepository` instead.
#2359 removed some constants, but another usage of this constant was added in the `develop` branch.
> inject CategoryRepositoy in MediaManager to avoid using removed constant

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
- src/Sulu/Component/Security/Authorization/AccessControl/PhpcrAccessControlProvider.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/PhpcrAccessControlProviderTest.php
| Q | A
| --- | ---
This content repairs the saving of document security.
There was a bug concerning documents with security. If the document had some security set, and was save another time using the content tab in the Sulu-Admin, the `sec:*` properties in the node contained boolean values instead of the permission strings. This lead to a not properly working Sulu-Admin (the document was not editable anymore, because the wrong permissions were used to evaluate that)
> fixed writing security for page documents

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Entity/AnalyticsRepository.php
| Q | A
| --- | ---
A where clause with a boolean field is changed from "field = 1" to "field = TRUE"
When using a boolean field in the where clause, on Postgres you cannot compare with an integer.
Comparing with the constant TRUE should work in both Postgres and MySQL
Without this fix you cannot view the front page of a Sulu installation on Postgres.
> Fix one where clause to work on Postgresql.

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Search/Reindex/StructureProvider.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Search/ReIndex/StructureProviderTest.php
| Q | A
| --- | ---
| Bug fix? | yes (momory-usage)
| Fixed tickets | fixes #1762
| Related issues/PRs | https://github.com/massiveart/MassiveSearchBundle/pull/92
This PR introduces a cleanup method for StructureProvider. This cleanup the document-manager to reduce memory usage.
After a while and enough entities the memory usage raises up to the limit.
> Added cleanup for structure reindex provider

- CHANGELOG.md
- src/Sulu/Bundle/ResourceBundle/Resources/config/doctrine/Condition.orm.xml
- src/Sulu/Bundle/ResourceBundle/Resources/config/doctrine/Filter.orm.xml
- src/Sulu/Bundle/ResourceBundle/Resources/config/doctrine/FilterTranslation.orm.xml
- src/Sulu/Bundle/ResourceBundle/Resources/config/doctrine/OperatorTranslation.orm.xml
- src/Sulu/Bundle/ResourceBundle/Resources/config/doctrine/OperatorValueTranslation.orm.xml
| Q | A
| --- | ---
| Bug fix? | yes (it avoids a propably bug)
| Related issues/PRs | https://github.com/sulu/sulu-standard/pull/693
| Documentation PR | none 
This PR adds column definitions for doctrine-orm entities. To avoid dropping of columns when naming-strategy will be changed. 
Doctrine drops columns which name is generated and recreate it if the naming-strategy was changed.
> Added column definitions to resource-bundle

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2383
| Related issues/PRs | https://github.com/sulu/sulu/issues/2385
This PR adds the condition for for custom-routs which only matches for `RequestAnalyzerInterface::MATCH_TYPE_FULL`. All the other will not match and automatically redirected by `ContentRouteProvider`.
After refactoring of Custom-Route generation there was a bug which also matches `RequestAnalyzerInterface::MATCH_TYPE_PARTIAL` or `RequestAnalyzerInterface::MATCH_TYPE_REDIRECT`. Which causes an exception when following this route.
> Added condition to custom-routes to match only full-matches

- CHANGELOG.md
- src/Sulu/Component/Rest/ListBuilder/AbstractListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineFieldDescriptor.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineIdentityFieldDescriptor.php
- src/Sulu/Component/Rest/ListBuilder/FieldDescriptor.php
- src/Sulu/Component/Rest/ListBuilder/FieldDescriptorInterface.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
| Fixed tickets | none 
| Related issues/PRs | none 
| Documentation PR | none 
Fixing issue when applying same FieldDescriptor multiple times.
In order to be able to change a given sorting, you can now overwrite the sort-order of the field descriptor.
Until now this would lead to an exception. (This happens since Sulu 1.2)
The interface of `FieldDescriptor` has been extended by a function `compare(FieldDescriptorInterface $other)` which needs to be implemented by all FieldDescriptors (outside of the sulu project)
> Fixed issue when applying same field descriptor multiple times to sort of list builder

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
| Q | A
| --- | ---
This PR removes the second media navigation item in the navigation.
Because with certain permission settings the media navigation item was appearing twice. Actually this should have happend all the time, but the merge mechanism removed one of both items somehow sometimes.
> removed twice adding of media navigation item

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
| Q | A
| --- | ---
This PR uses the `DocumentManager` for the `NodeController::postAction`.
This makes the publishing process easier when the document is created and published immediately, since the `publish` method of the `DocumentManager` can be called directly (will be added in https://github.com/sulu/sulu-document-manager/pull/81). And in general it makes the code more consistent and removes a few more deprecated method calls.
The `postAction` does not return an `_embedded` field anymore, but this one was always empty anyway, so I would not add it again, although it is a small BC break. Maybe I can add it to the …
> Use DocumentManager for NodeController postAction

- CHANGELOG.md
- src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml
| Q | A
| --- | ---
| Documentation PR | sulu/sulu-docs#222
Changes the default PHPCR-Backend for the tests to Doctrine DBAL instead of jackrabbit, thus first timers who quickly want to run the tests don't have to hussle with Jackrabbit.
For me it was relative easy to get Jackrabbit installed with the bash snippet extracted from `.travis.yml`, but anyone new to the project, doesn't know how to download Jackrabbit to the correct location. And the docs were misleading since the `bin/jacrabbit.sh` script was removed.
> Use Doctrine DBAL as default PHPCR-Backend for tests

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Composer/MediaScriptHandler.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/massiveart/MassiveSearchBundle/pull/93
This PR fixes warnings which will be thrown by composer when updating or installing.
Try calling composer install in sulu-standard you will see this warning:
````
Deprecation Notice: The callback Sulu\Bundle\MediaBundle\Composer\MediaScriptHandler::initBundle declared at /Users/johannes/Development/sulu/sulu-standard/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Composer/MediaScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see …
```
> Fixed composer-events

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Command/DetermineServerInfoTrait.php
- src/Sulu/Bundle/CoreBundle/Command/ServerRunCommand.php
- src/Sulu/Bundle/CoreBundle/Command/ServerStartCommand.php
- src/Sulu/Bundle/CoreBundle/Command/ServerStatusCommand.php
- src/Sulu/Bundle/CoreBundle/Command/ServerStopCommand.php
- src/Sulu/Bundle/CoreBundle/Resources/config/router_admin.php
- src/Sulu/Bundle/CoreBundle/Resources/config/router_website.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2069, fixes #2070
| Documentation PR | to do
This PR simplifies running Sulu with PHP's built-in server. Running the server is as simple as:
~~~
$ app/console server:start
$ app/webconsole server:start
~~~
The servers for the admin and the website are started on the ports 8000 respectively 8001.
Currently, a user has to pass the correct values in the `--router`, `--env` and `--port` options of the server:run and server:start commands. This makes getting started with Sulu harder than necessary.
> Made --router and --env optional when running the console commands server:run and server:start

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
- src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/routing.xml
- src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Request/CustomUrlRequestProcessorTest.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/ParameterRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/RequestAttributes.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/ParameterRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/RequestAttributesTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/220
This PR introduces another `RequestProcessor`, the `ParameterRequestProcessor`, which takes the information for portals from the `_locale` and `_request` parameters from the request. These take precedence over the other methods to analyze the request.
This is necessary because ESI requests can't be properly handled otherwise. So if there is a twig line like the following:
```jinja
{{ render(controller('ClientWebsiteBundle:Search:query')) }}
```
It's not working properly, because the underlying controller needs values from the `RequestAnalyzer`. This worked before …
> Fixed RequestAnalyzer to be usable with ESI

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
- src/Sulu/Bundle/ContentBundle/Repository/NodeRepositoryInterface.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/NodeRepositoryTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/ContentOnPageTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Twig/SnippetTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Mapper/ContentMapperInterface.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperSnippetTest.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
- src/Sulu/Component/Content/Tests/Functional/SmartContent/SmartContentQueryBuilderTest.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ShadowLocaleSubscriberTest.php
- src/Sulu/Component/PHPCR/Tests/Unit/PathCleanupTest.php
| Q | A
| --- | ---
While create #2361 some tests were failing, and I realized that the `save` and `saveRequest` methods were not used anymore (or better said only in the tests). So this PR removes these methods.
Because this way it is less work to fix the tests for #2361 and we get rid of quite a lot legacy code (which was already deprecated when we release 1.0).
> Removed save method of ContentMapper and NodeRepository

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes none
| Related issues/PRs none
Bugfix
accounts/<id>/contacts API returns same contact several times if it is assigned to several accounts
> [Bugfix] Fixed account contacts api

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
| Q | A
| --- | ---
This PR fixes a bug for the route-bundle `RouteProvider` which happens when no resource-locator-prefix isset.
The function `PathHelper::relativizePath` cannot handle a null value as second parameter.
> Fixed route-provider when no resource-locator prefix isset

- CHANGELOG.md
- phpunit.xml.dist
- src/Sulu/Bundle/ContactBundle/Resources/public/js/components/accounts/edit/main.js
- src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/Configuration.php
- src/Sulu/Component/Hash/Serializer/Subscriber/HashSerializeEventSubscriber.php
- src/Sulu/Component/Hash/Tests/Serializer/Subscriber/HashSerializeEventSubscriberTest.php
- src/Sulu/Component/Rest/Tests/Unit/DoctrineRestHelperTest.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
HashSerializeEventSubscriber called addData for every Visitor, even though it's only supported by GenericVisitor instances.
Because that was a bug ;)
> Fixed bug when using non generic visitor in HashSerializeEventSubscriber

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Behat/SecurityContext.php
| Q | A
| --- | ---
| Deprecations? | -
New behat step for admin login with default locale.
> [FEATURE] New behat step for admin login with default locale

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
| Q | A
| --- | ---
This PR fixes an issue with the profiler when no portal is found for the route `/_profiler/`
> Added portal check for portal-routes

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#694
This PR fixes the sorting of the media-selection caused by refactoring of the media api to field descriptors.
The media-api doesn't return the assets with the sorting of given ids.
> Fixed media-selection sorting

- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Document/BasePageDocument.php
- src/Sulu/Bundle/ContentBundle/Document/HomeDocument.php
- src/Sulu/Bundle/ContentBundle/Tests/app/Resources/pages/blocks.xml
- src/Sulu/Bundle/CustomUrlBundle/DependencyInjection/SuluCustomUrlExtension.php
- src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Document/SnippetDocument.php
- src/Sulu/Component/Content/Document/Structure/ManagedStructure.php
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Document/Subscriber/TitleSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/TitleSubscriberTest.php
- src/Sulu/Component/CustomUrl/Document/CustomUrlDocument.php
- src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-document-manager/pull/89
This PR tries to use the `AutoNameBehavior` for the `CustomUrlDocument`. It was not used until now, because the `AutoNameBehavior` implicitly required the Document to also implement the `StructureBehavior`, which the `CustomUrlDocument` does not.
This is required for #2361, because using the `parent_path` and `node_name` options in the `CustomUrlManager` break the syncing of the structure to the published workspace, which will be introduced in #2361.
The `title` in the page type xml file is now only required for being displayed in the form of the …
> Use AutoNameBehavior for CustomUrlDocument

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/CoreBundle/Command/ServerStatusCommand.php
| Q | A
| --- | ---
This PR removes the `port` option from our own `ServerStatusCommand`.
Because the `port` option has now been added to Symfony 2.8.7.
> removed port parameter from ServerStatusCommand because it has been added in Symfony

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Command/ScaleCommand.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Command/ScaleCommandTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2447 
This PR fixes the problem mentioned in the issue.
The `forceRatio` would be disabled for inset image scale. This makes no sense because the inset command wont keep ratios and this make problems with calculating the image size.
> Fixed inset image scale image-size 0

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/Types/InternalLink/InternalLinksTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
| Q | A
| --- | ---
Two tests were still containing its own implementation from the `PHPCR\NodeInterface`. This was relevant back in the days, because of a bug in PHPUnit (https://github.com/sebastianbergmann/phpunit/issues/604).
IntelliJ also offered the implementations from these tests as suggestions, so you ended up sometimes to use the wrong implementation.
> Removed unneccessary NodeInterface definitions in tests

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php
- src/Sulu/Bundle/SecurityBundle/DependencyInjection/Compiler/UserManagerCompilerPass.php
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
- src/Sulu/Component/Persistence/Tests/Functional/EventSubscriber/ORM/UserBlameSubscriberIntegrationTest.php
| Q | A
| --- | ---
| BC breaks? | not sure
Replace `security.context` with `security.token_storage`
The `security.context` service is deprecated.
> Replace deprecated security.context with security.token_storage service

- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/RequestListener.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RequestListenerTest.php
| Q | A
| --- | ---
The `request.routeParameters` is not required for using `path` or `url` in a twig template.
When you render your own template and have no `request.routeParameters` you needed to call the request analyzer or create a twig extension which will load from the current request routeParameters.
```twig
{{ path('client_website.search') }}
{{ url('client_website.search') }}
```
> Add host and prefix automatically in twig url generation

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverInterface.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverTest.php
| Q | A
| --- | ---
Add a template attribute resolver to add sulu specific params to template rendering.
If you render a twig template over a custom controller you use mostly the same master.html.twig. So you need in this action the same template attributes.
```php
/**
* {@inheritdoc}
*/
public function render($view, array $parameters = [], Response $response = null)
{
return parent::render(
$view,
$this->get('sulu_website.resolver.template_attribute')->resolve($parameters),
$response
);
}
```
> Template attributes resolver for custom controllers

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/TestBundle/Testing/WebsiteTestCase.php
| Q | A
| --- | ---
Added website test case.
Easier website test setup
~~~php
namespace AppBundle\Tests\Controller;
use Sulu\Bundle\TestBundle\Testing\WebsiteTestCase;
class DefaultControllerTest extends WebsiteTestCase
{
public function testIndex()
{
$client = static::createClient();
$crawler = $client->request('GET', '/hello-world');
$this->assertContains('Hello World', $client->getResponse()->getContent());
}
}
~~~
> Website Test Case

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
- src/Sulu/Bundle/TestBundle/Resources/config/test_user_provider.xml
- src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
- src/Sulu/Component/Contact/Model/ContactRepositoryInterface.php
- src/Sulu/Component/Security/Authentication/UserRepositoryInterface.php
| Q | A
| --- | ---
TestUserProvider was creating Contact and User by calling `new Contact()` and `new User()`. That way it was not possible to use the UserTestProvider in projects that were extending Contact and/or User.
Now the UserRepositories and ContactRepositories `createNew()` Function is used for creating a User and Contact.
A Interface for the ContactRepository has been created. Due to the refactoring
the function `appendJoins` has been changed from public to protected.
Therefore this function cannot be called anymore.
> Fixed TestUserProvider for inheritance of contact. Created ContactRepositoryInterface

- CHANGELOG.md
- src/Sulu/Bundle/SearchBundle/Controller/SearchController.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2360 
| Related issues/PRs | [#79 from MassiveSearchBundle](https://github.com/massiveart/MassiveSearchBundle/pull/79)
This PR is required after merging PR #79 from the MassiveSearchBundle which adds functionality for limit and offset. Fixes the expected result, which must be an array
> Changed search adapter (to fit MassiveSearchBundle)

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Document/BasePageDocument.php
- src/Sulu/Bundle/ContentBundle/Document/PageDocument.php
- src/Sulu/Bundle/ContentBundle/Form/Type/BasePageDocumentType.php
- src/Sulu/Bundle/ContentBundle/Form/Type/PageDocumentType.php
- src/Sulu/Bundle/ContentBundle/Resources/config/form.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/serializer/Document.BasePageDocument.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/serializer/Document.PageDocument.xml
| Q | A
| --- | ---
| Related issues/PRs | prerequesite for #2361 
This content moves the `parent` variable from the `BasePageDocument` to the `PageDocument`, because the `HomeDocument` also inherits from the `BasePageDocument`, although it doesn't have a parent document.
This PR is necessary because the architectural flaw described here prevents #2361 from working correctly.
> moved parent from BasePageDocument to PageDocument

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/NodeResourcelocatorController.php
- src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php
| Q | A
| --- | ---
| Related issues/PRs | prerequesite of #2361 
This PR uses the `DocumentManager` to delete routes instead of deleting them manually using the session.
1. Because the logic is already implemented in the `RouteSubscriber`, and does not need to be duplicated in the `PhpcrMapper`.
2. Because the `DocumentManager` uses the correct session, when publishing is introduced (#2361).
> delete routes using the DocumentManager

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/permission-tab/components/form/main.js
| Q | A
| --- | ---
| Related issues/PRs | prerequesite for #2361 
This PR fixes the assignment of data to the internal arrays of the permission tab component.
Because the non-visible permission types in the matrix were always overridden with false.
1. Navigate to `Settings > User Roles`
2. Create a new role with the following media permission:
3. Navigate to `Media` and select a collection without permissions
4. Click the lock to open the permission overlay
5. Add the live permission and click ok
6. Open the overlay again and see that the live permission is missing
> fixed error with non-visible permissions types in matrix

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/NodeResourcelocatorController.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php
- src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
- src/Sulu/Bundle/CoreBundle/Resources/config/phpcr.xml
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
- src/Sulu/Component/Content/Tests/Functional/Rlp/Mapper/PhpcrMapperTest.php
- src/Sulu/Component/Content/Tests/Functional/Rlp/Strategy/TreeStrategyTest.php
| Q | A
| --- | ---
| Related issues/PRs | prerequesite for #2361 
`doctrine_phpcr.default_session` is not the default session, but the session actually named "default". `doctrine_phpcr.session` refers to the real default session. This PR changes these occurences.
Because it doesn't work if the session is named different from `default`.
> use correct default phpcr session

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php
- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
| Q | A
| --- | ---
Replaced static usage of media repository which causes an error when the media entity is replaced by
a custom one.
> [BUGFIX] Refactored media repository

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/WebsiteKernelFactory.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
| Q | A
| --- | ---
This PR introduces PreviewKernel which wraps the WebsiteKernel and append configuration to disable profiler and session-storage.
If you enable file session-storage there will be an exception because of ini_set
> Wrapped website-kernel and append preview-specific configs

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Entity/RouteRepositoryInterface.php
- src/Sulu/Bundle/RouteBundle/Resources/config/routing.xml
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php
| Q | A
| --- | ---
This will allow to generate a route by the route service.
Is needed when the template resolver service is used.
```php
$this->router->generate('sulu_route_1');
```
> Allow route generation for dynamic entity routes

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/EventListener/LastLoginListener.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/checker.xml
| Q | A
| --- | ---
Add last login listener.
To set the last login automatically when the user logged in.
> Add last login listener

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
| Q | A
| --- | ---
This PR disables the WebDebugToolbar of Symfony for the preview.
Because #2535 disabled the profiler, which is required for the WebDebugToolbar. This is also causing the 404 errors when opening pages.
> deactivated WebDebugToolbar for preview

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadCountries.php
- src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadDefaultTypes.php
- src/Sulu/Bundle/CoreBundle/Build/FixturesBuilder.php
- src/Sulu/Bundle/MediaBundle/DataFixtures/ORM/LoadCollectionTypes.php
- src/Sulu/Bundle/MediaBundle/DataFixtures/ORM/LoadMediaTypes.php
- src/Sulu/Bundle/SecurityBundle/DataFixtures/ORM/LoadSecurityTypes.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2521
| Related issues/PRs | #2521
This PR fixes the issue of wiped assets on sulu:build commands by implementing the doctrine fixtures non-destructive.
This is done by setting the fixtures append-mode which prevents database purging and adjusting the insert strategy to enable updating the database, if the fixtures are already (partially) present.
> add fixtures without purging database

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview_dev.yml
| Q | A
| --- | ---
This PR introduces a `config_preview_dev.yml` file, which is only loaded in the dev environment, and disables the debug toolbar.
This configuration was previously in a file which was loaded also in a `prod` environment, and this caused an error, because the `web_profiler` extension is not available there.
> fixed preview for prod environment

- CHANGELOG.md
- src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
- src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
| Q | A
| --- | ---
The depth has to be sorted first for the categories, because all the other sortings must apply later.
Otherwise the datagrid won't properly render it.
> fixed order in combination with depth

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
- src/Sulu/Bundle/ContentBundle/Document/Subscriber/PublishSubscriber.php
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
- src/Sulu/Bundle/ContentBundle/Resources/public/js/services/content-manager.js
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Document/Subscriber/PublishSubscriberTest.php
- src/Sulu/Component/Content/Document/Subscriber/WorkflowStageSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/WorkflowStageSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2028 
| Related issues/PRs | based on #2361, https://github.com/sulu/sulu-document-manager/pull/92
This PR adds the possibility to unpublish a page. When a page is unpublished, the content in its language is deleted in the live workspace, and the state is set to test and the published date is reset to null in the draft workspace.
Because it should be possible to remove a page from the live workspace without deleting it entirely.
> added unpublishing functionality

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php
- src/Sulu/Bundle/ContentBundle/Resources/config/services.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #2433
This PR fixes the bug which occured when generating resource locator paths for new pages with a ghost-page parent (See #2433).
The misbehaviour is fixed by using the first ancestor of the new page which is not a ghost-page for path generation.
> ignore ghost page parent when generating resource locator

- CHANGELOG.md
- src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Bridge/DocumentInspectorTest.php
| Q | A
| --- | ---
| Documentation PR |none
This PR avoids that the `DocumentInspector::getConcreteLocales` method returns an array which indexes do not start with 0.
Because if it starts with something different than 0, the serializer will turn it into an object instead array.
> fixed serialization of concrete locales

- CHANGELOG.md
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
| Q | A
| --- | ---
This PR sorts the categories for the fallback test.
To have predictable results (appveyor was failing)
> added sort criteria for category fallback test

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Controller/TemplateController.php
- src/Sulu/Bundle/ContactBundle/DependencyInjection/Configuration.php
| Q | A
| --- | ---
This PR sets the default country in the contact-bundle by the country-code instead of the auto-generated id. 
The id column of the country is not immutable. When reloading fixtures without reseting auto-increment values, the id of the countries can change. This can lead to non existing default-countries.
> setting default country by code instead of id

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/SmartContentItemController.php
| Q | A
| --- | ---
Removed force flag for webspace key parameter.
Media data provider do not need any webspace key and it causes problems outside webspace.
> Removed force flag for webspace key parameter

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Controller/RedirectController.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/RedirectControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #1068
This PR fixes the redirect if the portal is placed into a subfolder.
> Fixed portal redirect when using subfolder

- CHANGELOG.md
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/structure-cache-handlers.xml
- src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
- src/Sulu/Component/HttpCache/Handler/PathsHandler.php
- src/Sulu/Component/HttpCache/Tests/Unit/Handler/PathsHandlerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2531
This PR (partially) fixes cache-clearing on page-publishing when using a host-placeholder in webspace.xml.
The misbehaviour is fixed by storing the host of the request on a publish request and fill the host-placeholder of the url with the stored host when clearing cache.
This method does not fix the problem on multi-host portals.
> fill host-placeholder before clearing cache

- CHANGELOG.md
- src/Sulu/Bundle/LocationBundle/Content/Types/LocationContentType.php
- src/Sulu/Bundle/LocationBundle/Tests/Unit/Content/Types/LocationContentTypeTest.php
| Q | A
| --- | ---
This PR adds the usage for intl-component to generate the dropdown in the content-type overlay.
> Used intl-component to generate countries for location-content-type

- CHANGELOG.md
- src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
| Q | A
| --- | ---
| Bug fix? | yes, hotfix
| Fixed tickets | fixes #2631 
Fixes the wrong acces of `documentInspector` instead of `inspector.
> [HOTFIX] Fix usage of document inspector in StructureBridge

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Document/Subscriber/PublishSubscriber.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Document/Subscriber/PublishSubscriberTest.php
| Q | A
| --- | ---
This PR fixes an issue with the reordering in the public workspace. It was reordering the node in the draft workspace.
Because the node should also be reordered on the live workspace. The node is already reordered in another subscriber for the draft workspace.
> fixed reordering for published workspace

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml
- src/Sulu/Component/Rest/ExceptionWrapperHandler.php
| Q | A
| --- | ---
This PR hides the exception details, if an error occurs on a rest-api request in prod environment.
The exception details are still visible in the response in dev and test environment.
The exception details should not be visible if an error occurs in prod environment.
> hide exception details on rest-api error in prod environment

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Build/CacheBuilder.php
- src/Sulu/Bundle/CoreBundle/Resources/config/build.xml
- src/Sulu/Component/Media/SystemCollections/SystemCollectionBuilder.php
| Q | A
| --- | ---
This PR implements a CacheBuilder for the MassiveBuildBundle which clears the symfony cache.
The CacheBuilder is set as dependency of the SystemCollectionBuilder. (see next paragraph)
The SystemCollectionBuilder is used to initialize the system collections. When executing the sulu:build command with the --destroy flag, the database is removed, but the cache is not cleared. The SystemCollectionBuilder does not recognize that the collections are removed from the database, because they are still present in the cache. Therefore the system collections are not recreated and missing after executing sulu:build with the …
> clear cache before system collection initialization

- CHANGELOG.md
- src/Sulu/Component/Contact/SmartContent/AccountDataProvider.php
- src/Sulu/Component/Contact/SmartContent/ContactDataProvider.php
- src/Sulu/Component/Contact/Tests/Unit/SmartContent/AccountDataProviderTest.php
- src/Sulu/Component/Contact/Tests/Unit/SmartContent/ContactDataProviderTest.php
| Q | A
| --- | ---
This PR fixes the serialization for contact-categories in smart-content.
> Fixed contact-serialization for smart-content

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php
- src/Sulu/Component/Contact/Model/ContactRepositoryInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2151 
This PR fixes the warning and error which occured when using the `findGetAll()`-method of the `ContactRepository`-class by adjusting the signature of the method and selecting the correct joint-table.
Also tests for the `findGetAll()`-method are added.
> fixed find-get-all of contact-repository

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
| Q | A
| --- | ---
The if statement for showing the draft label was adjusted.
The draft label was also started when a ghost page opened, because the early return wasn't executed. This leaded to a request for the changer, which didn't exist, and therefore threw an error.
> fixed error caused by draft label when opening a ghost page

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
- src/Sulu/Bundle/SearchBundle/Resources/config/routing_website.xml
- src/Sulu/Bundle/SearchBundle/Resources/config/search.xml
- src/Sulu/Bundle/SearchBundle/Tests/Unit/Controller/WebsiteSearchControllerTest.php
- src/Sulu/Component/Webspace/Exception/PortalException.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu-standard/issues/593
| Related issues/PRs | based on https://github.com/sulu/sulu/pull/2665, prerequesite for https://github.com/sulu/sulu-standard/pull/728 https://github.com/sulu/sulu-minimal/pull/10
This PR introduces the `WebsiteSearchController`, which can be used on the website. The file is basically copied from sulu-standard.
Because the `ClientWebsiteBundle` should not contain such basic logic. It is now also required, because there are multiple sulu editions now (standard and minimal, ...)
The name of the route changed from `website_search` to `sulu_search.website_search`.
> Added a WebsiteSearchController

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Preview/PageRouteDefaultsProvider.php
- src/Sulu/Bundle/RouteBundle/Routing/Defaults/RouteDefaultsProvider.php
- src/Sulu/Bundle/RouteBundle/Routing/Defaults/RouteDefaultsProviderInterface.php
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/Defaults/RouteDefaultsProviderTest.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/7
This PR adds the isPublished method to route-defaults provider to allow unpublished state for routable-entities.
> Added is-published method for route-defaults-provider

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
| Q | A
| --- | ---
| Fixed tickets | fixes #2667
This PR displays the `unpublish` option in the toolbar of a page only if the page has already been published. Also, it only shows the `delete` and `copyLocale` action if the page is not in add mode.
Because these operations were executed on a click, and lead to errors in certain situations. These errors were happening when:
* Clicking delete on a adding page form
* Trying to copy a locale on a adding page form
* Unpublish a page which has not been published yet (was not throwing an error, but might be confusing)
> Disabled options in toolbar item which are not available when editing a page

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
| Q | A
| --- | ---
This PR changes the logic to generate the cache and log directory. Now the context will be switched for these functions, so that the directory is generated correctly.
Because if the absolute path contained the context at multiple places it was replaced everywhere, leading to wrong paths.
> Fixed generation of log and cache directoy when context is part of path

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Search/EventSubscriber/StructureSubscriberTest.php
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
| Q | A
| --- | ---
This PR deindexes the page after it has been unpublished. In addition to that it adds a confirm overlay after a click on the unpublish button.
Because the search index on the website was not updated when a page was unpublished.
> deindex page after unpublishing

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Entity/Address.php
- src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Address.orm.xml
| Q | A
| --- | ---
Allow country to be nullable.
If you migrate an old system to sulu you have some incomplete address data where the country is not set.
> Allow country to be nullable

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Controller/SmartContentItemController.php
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/smart-content/main.js
- src/Sulu/Component/Content/Compat/PropertyParameter.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/10
This PR adds the ability to react on property-params for admin items request.
> Added params to smart-content-item-controller

- src/Sulu/Bundle/ContentBundle/Controller/SmartContentItemController.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
| Q | A
| --- | ---
The content of this PR fixes the issue that the server responded with 500 when smart-content items were loaded with passed params. Moreover a test was added.
> Fixed bug when loading smart-content items with passed params

- CHANGELOG.md
- src/Sulu/Bundle/DocumentManagerBundle/phpunit.xml.dist
| Q | A
| --- | ---
Don't allow symfony deprecations in DocumentManagerBundle anymore.
> Don't allow symfony deprecations in DocumentManagerBundle anymore

- CHANGELOG.md
- src/Sulu/Bundle/GeneratorBundle/phpunit.xml.dist
| Q | A
| --- | ---
Don't allow symfony deprecations in GeneratorBundle anymore.
Although there are no tests yet, further additions and tests to the bundle are not allowed to use deprecated code parts from now.
> Don't allow symfony deprecations in GeneratorBundle anymore

- CHANGELOG.md
- src/Sulu/Bundle/HttpCacheBundle/phpunit.xml.dist
| Q | A
| --- | ---
Don't allow symfony deprecations in HttpCacheBundle anymore.
> Don't allow symfony deprecations in HttpCacheBundle anymore

- CHANGELOG.md
- src/Sulu/Bundle/MarkupBundle/phpunit.xml.dist
| Q | A
| --- | ---
Don't allow symfony deprecations in MarkupBundle anymore.
> Don't allow symfony deprecations in MarkupBundle anymore

- CHANGELOG.md
- src/Sulu/Bundle/PersistenceBundle/phpunit.xml.dist
| Q | A
| --- | ---
Don't allow symfony deprecations in PersistenceBundle anymore.
> Don't allow symfony deprecations in PersistenceBundle anymore

- CHANGELOG.md
- appveyor.yml
| Q | A
| --- | ---
| Related issues/PRs | #2106, #2120
Remove `SYMFONY_DEPRECATIONS_HELPER` environment from AppVeyor config, because this is already configured in the individual `phpunit.xml.dist` files, made in #2120.
Was unfortunately added when the `appveyor.yml` was created :smile:
> Remove SYMFONY_DEPRECATIONS_HELPER environment from AppVeyor config

- CHANGELOG.md
| Q | A
| --- | ---
My IDE autoremoves the trailing whitespaces from the change log. I think they should be removed.
> Fix change log white spaces

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/public/js/components/webspace/settings/analytics/overlay/main.js
- src/Sulu/Bundle/WebsiteBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/WebsiteBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/WebsiteBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/type/google_tag_manager.html.twig
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Analytics/AnalyticsManagerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/AnalyticsControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | n/a
| Documentation PR | sulu/sulu-docs#239
Add Google Tag Manager script to the webspace analytics settings.
Because it's easier and more failsafe if Sulu supports the GTM code directly instead of using the custom type.
I renamed the translation of the google type to "Google Analytics" to be more clear and added `google_tag_manager` for the GTM type. Through the small width of the type field a database schema update is needed.
> Add Google Tag Manager to the webspace analytics settings

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Mapper/ContentMapperInterface.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
| Q | A
| --- | ---
This PR removes the published checks from the `ContentRouteProvider`, because it is already searching for the pages in the correct workspace.
Because it is faster and makes the `ContentRouteProvider` slimmer and better understandable.
> Removed published checks from ContentRouteProvider

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
| Q | A
| --- | ---
This PR adds the publish action to the button in the settings tab.
Because when the page is saved as as shadow it should also be published, although there is only a single button.
> fixed publishing for the settings tab

- CHANGELOG.md
- src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig
- src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.twig
- src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig
- src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.twig
| Q | A
| --- | ---
| Related issues/PRs | n/a
Added Twig block tags to allow better inheritance
It allows to add additional stylesheets and javascript without the need to copy the whole twig templates in the AdminBundle.
See http://twig.sensiolabs.org/doc/tags/extends.html
None, tested the grunt build, which works fine.
> Add Twig blocks to be able to use inheritance

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
- src/Sulu/Bundle/DocumentManagerBundle/Session/SessionManager.php
- src/Sulu/Bundle/DocumentManagerBundle/Session/SessionManagerInterface.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Session/SessionManagerTest.php
- src/Sulu/Component/PHPCR/SessionManager/SessionManager.php
- src/Sulu/Component/PHPCR/SessionManager/SessionManagerInterface.php
- src/Sulu/Component/Webspace/Settings/SettingsManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Settings/SettingsManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2739
This PR introduces a new `SessionManager`, which will set the property of a node for the default and live workspace. This `SessionManager` will then be used for the `SettingsManager`, which writes the current default snippets on the webspace node.
Because currently the default snippets are only saved in the default workspace, hence have no impact on the live website.
> Fixed default snippets for public workspace

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml
| Q | A
| --- | ---
| Fixed tickets | fixed #2337 
| Related issues/PRs | https://github.com/massiveart/MassiveSearchBundle/pull/98 (already merged)
This PR add exception images and icons to massive-search index.
> Added images/icons of excerpt to search index

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Search/EventSubscriber/StructureSubscriberTest.php
- src/Sulu/Component/Content/Document/WorkflowStage.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2779
This PR sets the workflowstage to both possible values before deindexing them. This is necessary because the document is only removed from one of both indexes otherwise.
> fixed deindexing of documents for both workspaces

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Document/Subscriber/PublishSubscriber.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Document/Subscriber/PublishSubscriberTest.php
- src/Sulu/Component/Content/Document/Subscriber/WorkflowStageSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/WorkflowStageSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2690
This PR sets the workflowstage for copied nodes and its children to test.
Because the copied pages should not be published immediately. This already works for routes (there are no routes generated), but was not applied to the state of the nodes. This caused some wrong displaying in the column navigation and some functionality was broken (e.g. the copied page could not be deleted when it has children).
> set workflowstage of copied nodes to draft

- .travis.yml
- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Translator/RequestAnalyzerTranslator.php
- src/Sulu/Component/Content/Compat/LocalizationFinder.php
- src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php
- src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactory.php
- src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactoryInterface.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/FallbackLocalizationSubscriberTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
- src/Sulu/Component/Localization/Localization.php
- src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2770
This PR allows to load a document without any translation. When no translation is given at all a completely empty document is returned.
This PR fixes #2770, but in a different way. Instead of removing the mixin from this document it is allowed to have a document without any translation at all. This can then be loaded and doesn't throw any exceptions.
I have implemented it this way, because we might need that behavior in the future anyway. The way it was implemented currently it would not be possible to load a document when no language exists, but this situation might occur when we provide the …
> allow to load document without any translation

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml
- src/Sulu/Bundle/CoreBundle/phpunit.xml.dist
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
- src/Sulu/Component/Rest/ListBuilder/ListRestHelper.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/ListRestHelperTest.php
| Q | A
| --- | ---
Remove symfony deprecations in `CoreBundle` and don't allow them anymore.
> Remove symfony deprecations in CoreBundle

- CHANGELOG.md
- src/Sulu/Bundle/SearchBundle/DependencyInjection/SuluSearchExtension.php
- src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
This PR fixes the query-builder when the ids-query depends on group-by.
Additionally the prepend for activating orm-indexing in massive-search was missing.
> Fixed ids-query in doctrine-list-builder

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
| Q | A
| --- | ---
This PR improves the speed of `sulu:route:update` for lots of entities. It introduces a batch-size option which will be used to determine how ofter the flush should be called.
For lots of entities the command was fucking slow (:
> Improved speed of route-update-command for lots of entities

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Resources/public/js/components/card-decorator/card-view.js
- src/Sulu/Bundle/ContactBundle/Resources/public/js/components/contacts/list/main.js
| Q | A
| --- | ---
| Fixed tickets | fixes #2732 
Contact cards now load in the correct order and are sorted by fullName by default.
> Fixed order of contact cards

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Teaser/ContentTeaserProvider.php
- src/Sulu/Bundle/ContentBundle/Teaser/Teaser.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Teaser/ContentTeaserProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/16
This PR introduces an dynamic teaser-attributes property which can contain dynamic data related to the teaser-item.
> Added teaser-attributes

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/serializer/Document.BasePageDocument.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Compat/StructureBridgeSerializationTest.php
- src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2837 
The PR includes the `changed`, `changer`, `created`, `creator` and `published` fields to the preview serialization, so that the fields are correctly passed to the preview.
> fixed preview serialization to include dates and authors

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentPathTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2423, fixes #2824
This PR adds the correct port to links on the website.
The port has now also to be added in the webspace configuration. However, nothing has to be changed if standard ports are used.
> Include port in URLs

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Resources/views/Template/account.form.html.twig
| Q | A
| --- | ---
Remove the minlength of 3 from organisation name.
The content manager should be allowed to enter whatever he want to enter as organisation name.
> Remove minlength from account

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2854
This PR returns a 404 http code if the media is not found for a download URL.
> Return 404 http code for not existing media

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Controller/AbstractMediaController.php
- src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2657
Fix for #2657
To allow media upload without any extension.
> Fixes #2657 allow media upload without extension

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Entity/Media.php
- src/Sulu/Component/Persistence/EventSubscriber/ORM/MetadataSubscriber.php
| Q | A
| --- | ---
| Fixed tickets | fixes #1343 
It checks if the class exists before calling `class_parents` function.
This will fix problems with the doctrine generators.
> Fix doctrine generators when class not exists

- CHANGELOG.md
- src/Sulu/Component/Content/Mapper/ContentMapper.php
| Q | A
| --- | ---
| Fixes? | fixes part of #2101 
Fixed crash of website on page without a template.
When a template is removed and still a page in the navigation has this template the website will crash.
> Fixed navigation on removed template

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Command/MaintainResourceLocatorCommand.php
- src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
- src/Sulu/Bundle/ContentBundle/Resources/config/command.xml
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Command/MaintainResourceLocatorCommandTest.php
- src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2818
This PR fixes the command for maintaining the resource locator. It only fixes them in the live workspace, because on the draft workspace it might contain data that has been edited by the content manager.
> fixed maintain command for resource locator

- CHANGELOG.md
- src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
- src/Sulu/Component/Content/Tests/Unit/Compat/Structure/StructureBridgeTest.php
| Q | A
| --- | ---
This PR introduces a check for ShadowLocaleBehavior for functions which are defined there.
> Added instanceof check for shadow-behavior functions

- CHANGELOG.md
- src/Sulu/Bundle/SearchBundle/Build/IndexBuilder.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2818 
This PR uses the `massive:search:reindex` command in the `IndexBuilder`.
Because the previously used command doesn't exist anymore.
> use new reindex command in IndexBuilder

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Entity/Contact.php
| Q | A
| --- | ---
| BC breaks? | only if somebody used it wrong before
This PR fixes the return result of the toArray Function inside the Contact Entity. Now it returns the contacts id, not its lastname.
Without this PR the toArray function returns the contacts lastname as id.
> Fix toArray function in Contact Entity

- CHANGELOG.md
- src/Sulu/Component/Localization/Provider/LocalizationProvider.php
| Q | A
| --- | ---
| New feature? | kind of
| Fixed tickets | nope
| Related issues/PRs | no
| Documentation PR | sulu/sulu-docs#271
This PR reintroduces the localization provider class which got removed in Sulu version 1.3 (http://github.com/sulu/sulu/pull/2618)
Before it was possible to add system locales by just create a tagged service. With the removal of the localization provider every bundle would have to create it's own localization provider class.
Now it's possible to add locales by simple defining a service as follows:
Example:
```{xml}
<service id="sulu_product.localization_provider" class="Sulu\Component\Localization\Provider\LocalizationProvider">
<argument>%sulu_core.locales%</argument>
<tag …
```
> Reintroducing localization provider

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
| Q | A
| --- | ---
This PR introduces an array-cache in the route-provider which enhances the generation of route objects.
This Provider will be called mutliple times when using Symfony router.
> Added route-provider cache

- CHANGELOG.md
- src/Sulu/Bundle/SearchBundle/Controller/SearchController.php
| Q | A
| --- | ---
This PR adds the requested limit to the search query. Otherwise the searchquery would return 10 entries, ignoring the requests limit.
Otherwise you are not able to get more than 10 searchresults. If you use the 'all' index, it could be possible you only get one type of results although there are even more.
> Fix limit in SearchController

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Extension/seo.html.twig
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
| Q | A
| --- | ---
| Fixes / issues | fixes #2050 
Move the logic and creation of the seo tags into an twig template to make it better rewriteable.
In some cases you want to overwrite the seo data from sulu without rewrite the whole seo data. With a simple twig include it can be partial rewriteable for users.
Simple include:
```twig
{%- include 'SuluWebsiteBundle:Extension:seo.html.twig' 
seo: extension.seo,
content: content,
urls: urls,
shadowBaseLocale: shadowBaseLocale,
defaultLocale: request.defaultLocale|default('de')
} -%}
```
Example how to overwrite just the canonical:
```twig
{%- embed 'SuluWebsiteBundle:Extension:seo.html.twig' with {
seo: extension.seo,
content: content,
urls: urls, …
```
> Seo info as twig template to make it rewriteable

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
| Q | A
| --- | ---
It avoid that seo information is injected over the request get or post attributes.
Its evil e.g.: http://demo.sulu.io/en?_seo[title]=H4x
> Avoid seo information injection by url

- src/Sulu/Bundle/WebsiteBundle/Controller/SitemapController.php
| Q | A
| --- | ---
Fixed sitemap binary file response http caching.
Because!
> fixed sitemap binary file response http caching

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
- src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php
| Q | A
| --- | ---
Fix system collection generation for anon. user.
When a system collection is used on the website and the user is authenticated as `anon.` it will not possible the system collection can not be created.
> Fix system collection generation for anon. user

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/block.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/content.html.twig
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/issues/646
Improves problem with elements not floating correctly.
Please do not use grid like this:
```
<div class="grid">
<div class="grid-row">
<div class="grid-col-9 floating form-group" />
<div class="grid-col-3 floating form-group" />
<div class="grid-col-9 floating form-group" />
<div class="grid-col-3 floating form-group" />
</div>
</div>
```
Use it like this:
```
<div class="grid">
<div class="grid-row">
<div class="grid-col-9 floating form-group" />
<div class="grid-col-3 floating form-group" />
</div>
<div class="grid-row">
<div …
```
> Improved bug with grid elements not floating correctly

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/public/css/main.css
- src/Sulu/Bundle/MediaBundle/Resources/public/scss/modules/media-selection.scss
| Q | A
| --- | ---
This PR adds the width of the image to the css definition of the itembox for the media selection.
Because the change introduce in https://github.com/massiveart/husky/pull/723/files#diff-4a59b707508451aa4f6af17a968071ffR350 doesn't seem to work for images. And since we know the exact dimensions of the image anyway it's also not a big deal.
> show missing image in media selection

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/public/css/main.css
- src/Sulu/Bundle/MediaBundle/Resources/public/scss/modules/media-selection.scss
| Q | A
| --- | ---
This PR fixes the length of the underline for the title in the media selection overlay.
The problem was that the `sulu-title` class is part of a css definition with media queries, and the overlay is located within this element, so these rules apply. I had to add another rule which is more specific then the existing one, that's why the nesting level is a bit deep.
Actually the real problem is that the `sulu-title` class has a width on its own. But fixing that would probably be too much work right now.
> fixed length of underline in media selection

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Twig/MemoizedSnippetTwigExtension.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/MemoizedContentTwigExtension.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/MemoizedNavigationTwigExtension.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/MemoizedSitemapTwigExtension.php
- src/Sulu/Component/Cache/MemoizeTwigExtensionTrait.php
- src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTwigExtensionTraitTest.php
| Q | A
| --- | ---
This PR ensures compatibility with twig/twig 1.26.
Twig changes the way they write the cache. Before 1.26: they get the extension by "name". With 1.26: The class-name is used for array-index. We wrap the extension at some places there the wrong class name will be used.
> Fixed compatibility for twig 1.26

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Markup/Link/PageLinkProvider.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Markup/Link/PageLinkProviderTest.php
| Q | A
| --- | ---
The PageLinkProvider throws an error if there is no request (like reindexing).
> Fixed page-link-provider without request

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Entity/CollectionInterface.php
- src/Sulu/Bundle/MediaBundle/Entity/Media.php
- src/Sulu/Component/Persistence/EventSubscriber/ORM/MetadataSubscriber.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2990 
Backport #2513 to 1.3.
Fix namespace conflict.
> Fixed namespace collision in media entity

- CHANGELOG.md
- UPGRADE.md
- composer.json
- src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
- src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/services.xml
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/structure-cache-handlers.xml
- src/Sulu/Component/Content/Compat/PageInterface.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php
- src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
- src/Sulu/Component/Content/Metadata/StructureMetadata.php
- src/Sulu/Component/Content/Tests/Functional/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLegacyLoaderTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
- src/Sulu/Component/HttpCache/CacheLifetimeResolver.php
- src/Sulu/Component/HttpCache/CacheLifetimeResolverInterface.php
- src/Sulu/Component/HttpCache/Handler/DebugHandler.php
- src/Sulu/Component/HttpCache/Handler/PublicHandler.php
- src/Sulu/Component/HttpCache/Tests/Unit/CacheLifetimeResolverTest.php
- src/Sulu/Component/HttpCache/Tests/Unit/Handler/DebugHandlerTest.php
- src/Sulu/Component/HttpCache/Tests/Unit/Handler/PublicHandlerTest.php
- tests/Resources/DataFixtures/Page/template_expression.xml
- tests/Resources/DataFixtures/Page/template_invalid_expression.xml
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/283
Added cache lifetime types.
Currently we support only absolute values in seconds. Now we added the support different types. For now seconds and cron expressions are implemented.
> Added cache lifetime types

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/DependencyInjection/ImageTransformationCompilerPass.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/PasteTransformation.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/ImageTransformationCompilerPassTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/PasteTransformationTest.php
| Q | A |
| --- | --- |
| New feature? | yes |
Fix the media transformator pool compiler pass. Added a paste transformator to overlay an image.
With the paste function a image can be added above another image.
``` xml
<format>
<name>400x400-mask</name>
<commands>
<command>
<action>scale</action>
<parameters>
<parameter name="x">400</parameter>
<parameter name="y">400</parameter>
</parameters>
</command>
<command>
<action>paste</action>
<parameters>
<parameter name="image">@AppBundle/Resources/public/border.png</parameter>
</parameters>
</command>
</commands>
</format>
```
> Added paste media transformator

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
- src/Sulu/Bundle/MediaBundle/Resources/config/list-builder/Media.xml
- src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php
- src/Sulu/Component/Media/SystemCollections/SystemCollectionManagerInterface.php
| Q | A |
| --- | --- |
| Fixed tickets | fixes #2841 |
| Related issues/PRs | none |
| Documentation PR | none |
This PR includes a join to the collections for the query done in the screen with all media. This is necessary to check if the media is in a system collection, which is required to check if it should be returned based on the user's permission.
> return system collection media only with granted permissions

- CHANGELOG.md
- src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactory.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/data/apostrophe/apostrophe.xml
| Q | A |
| --- | --- |
| Fixed tickets | fixes #2932 |
| Related issues/PRs | #issuenum |
| Documentation PR | sulu/sulu-docs#prnum |
Apostrophes can now be used in template titles.
> Fixed apostrophe bug in template

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A |
| --- | --- |
| Bug fix? | Yes |
| Fixed tickets | fixes #2422 |
| Related issues/PRs | #issuenum |
| Documentation PR | sulu/sulu-docs#prnum |
Fixes bug which disabled video upload without ffmpeg.
> Videos can now be uploaded without ffmpeg

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/public/css/main.css
- src/Sulu/Bundle/MediaBundle/Resources/public/scss/modules/media-edit-overlay.scss
| Q | A
| --- | ---
Previously the preview in the media overlay for non-images looked something like this:
This PR fixes the design, it removes the background with the squares and the border and fixes the positioning.
> fixed background of media overlay for preview icons

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/document.xml
- src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/2973
| Related issues/PRs | https://github.com/sulu/sulu-minimal/pull/29 https://github.com/sulu/sulu-standard/pull/758
This PR makes the PHPCR session use the correct session, so that it also finds pages which have never been published yet.
Because the preview breaks otherwise.
> use the correct PHPCR session for the preview

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Twig/MediaTwigExtensionTest.php
- src/Sulu/Bundle/MediaBundle/Twig/MediaTwigExtension.php
| Q | A |
| --- | --- |
| Fixed tickets | fixes #2881 |
Fixed #2881 call of sulu_media_resolve with not exist media.
You are not able to catch exceptions in twig.
{% set media = sulu_media_resolve(null, 'de') %}
> fixed uncatchable exception when use sulu_media_resolve twig extension

- CHANGELOG.md
- src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-standard/pull/760
This PR insures that the http-cache flush will only be called after in prod-environment.
> Activate cache handlers only in prod-environment

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/PHPCR/SuluNode.php
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/PHPCR/SuluNodeTest.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/StructureSubscriberTest.php
- src/Sulu/Component/Content/Types/BlockContentType.php
| Q | A
| --- | ---
| Bug fix? | yes (in some cases)
| Fixed tickets | non
This PR changes the write handling of content-types and removes the `remove`-call and remove old properties only if type has changed.
> Changed content-type write handling

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/288
This PR adds the usage of the missing port when manipulating a URL.
When Sulu was run on a port different from the default port, the homepage was not working.
The port must be included in the webspace configuration file if it is not the default port.
> Fixed port handling for webspaces

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2562, fixes #3020 
This PR changes the redirect to match all routes. This is necessary because of [Symfony trims routes](https://github.com/sulu/sulu/issues/2562#issuecomment-259144408).
The route returned when a redirect is happening changed to a more general format. Hopefully other applications haven't been relying on that exact return value.
> make redirects for all routes to circumvent double slash problem

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu-standard/issues/753
The cases of the translations were fixed, because they read in combination with the label as a sentence:
> fix cases in navigation translations

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/DocumentManagerTest.php
- src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
- src/Sulu/Bundle/CoreBundle/Resources/config/phpcr.xml
- src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
- src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php
- src/Sulu/Component/Content/Tests/Functional/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
- src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
- src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Strategy/TreeFullEditStrategyTest.php
- src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Strategy/TreeLeafEditStrategyTest.php
| Q | A
| --- | ---
This PR uses the PHPCR session from the document manager. 
Because then other bundles don't have to know about PHPCR at all, but can simply rely on the values from the `DocumentManager`.
> use session from document manager instead doctrine

- CHANGELOG.md
- src/Sulu/Bundle/LocationBundle/Resources/public/js/map/google.js
- src/Sulu/Bundle/LocationBundle/Resources/public/js/map/leaflet.js
| Q | A
| --- | ---
| Fixed tickets | fixes #3003 
| Related issues/PRs | #3029
A fix for location content type errors when loading over https
Otherwise the location content types breaks
OSM doesn't support https for their short url, so maybe there is someone depending on the short url somehow, but I can't imagine that.
> Load external map data over https

- CHANGELOG.md
- composer.json
- src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
- src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
- src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-document-manager/pull/96
This PR fixes a bug if a route already exists as empty node.
This happens with resource-locator `tree_full_edit` strategy, where its possible to create a tree for routes and afterwards create a "parent" of this tree. This crashes currently "fataly" so that the page cannot be saved (published) anymore.
> Fixed bug for save if route already exists empty

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Component/Util/SuluNodeHelper.php
- src/Sulu/Component/Util/Tests/Unit/SuluNodeHelperTest.php
- src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.0.xsd
- src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.1.xsd
- src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader10Test.php
- src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
- tests/Resources/DataFixtures/Webspace/invalid/sulu.io_deprecated_invalid_webspace_key.xml
- tests/Resources/DataFixtures/Webspace/invalid/sulu.io_invalid_webspace_key.xml
- tests/Resources/DataFixtures/Webspace/xdefault/sulu.io_xdefault_locale.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #3008, fixes sulu-standard#536
This PR changes the Regex for returning the webspace from a path. Previously it only recognized the regex group `\w*` as webspace, which e.g. didn't include `-`.
> fixed wrong parsing of webspace from path

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Structure/ManagedStructure.php
- src/Sulu/Component/Content/Tests/Unit/Document/Structure/ManagedStructureTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/3045
The value of the url property cannot be removed. The null value will be ignored.
> Fixed bind null values on managed-structure

- .styleci.yml
- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/PreviewBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/PreviewBundle/DependencyInjection/SuluPreviewExtension.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
- src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
- src/Sulu/Bundle/WebsocketBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/WebsocketBundle/DependencyInjection/SuluWebsocketExtension.php
- src/Sulu/Bundle/WebsocketBundle/Resources/config/services.xml
| Q | A
| --- | ---
Cache configuration for preview & web socket.
If you have multiple web servers you need a central cache for the preview and web socket connection.
~~~yml
sulu_preview:
cache:
type: redis
sulu_websocket:
cache:
type: redis
~~~
> Added cache configuration for preview & websocket

- CHANGELOG.md
- src/Sulu/Component/Content/Tests/Unit/Block/BlockContentTypeTest.php
- src/Sulu/Component/Content/Types/BlockContentType.php
| Q | A
| --- | ---
Adds the aggregated referenced UUIDs from all content types nested in a block to the block element itself.
This allows the nesting of complex datatypes (eg. Internal Links, Smart Content) in a block element and having the Sulu HttpCacheBundle Tag handler setting the correct ban keys for every element displayed on the site.
Setup:
* Create a simple template with a block containing a smart content element.
* Configure Sulu HTTP HttpCacheBundle to use the Tag handler
Usage:
* Create a page using the simple template
* Configure smart content so it has a result set
* Request the published page and check for the …
> Fixed missing referenced UUIDs for contentTypes nested in a block

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/ContentBundle/Command/ContentLocaleCopyCommand.php
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
- src/Sulu/Bundle/SecurityBundle/Entity/Group.php
- src/Sulu/Bundle/SecurityBundle/Entity/Role.php
- src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
- src/Sulu/Bundle/WebsiteBundle/Entity/Analytics.php
- src/Sulu/Bundle/WebsiteBundle/EventSubscriber/AnalyticsSerializeEventSubscriber.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-document-manager/pull/103 https://github.com/sulu/sulu-minimal/pull/33 https://github.com/sulu/sulu-standard/pull/772
This PR removes the direct dependency to phpcr/odm (it is inherited by another phpcr repo) and also remove the config which initializes it.
This is done because the odm isnt used currently.
> Removed phpcr-odm

- CHANGELOG.md
- src/Sulu/Component/Contact/Tests/Unit/SmartContent/ContactDataProviderTest.php
- src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
| Q | A
| --- | ---
This PR fixes a bug when the sort-by of smart-content is null. 
https://github.com/sulu/sulu/pull/3078#pullrequestreview-13283850
> Fixed sort-by for data-provider

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheInterface.php
- src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
- src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManagerInterface.php
- src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/SearchIntegration/SearchIntegrationTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatOptionsManager/FormatOptionsManagerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Twig/DispositionTypeTwigExtensionTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3086 
This PR fixes an issue when the extension of the uploaded media is uppercase. This extension will be corrected by the function `replaceExtension` which was not called in the `purge` method. For more information see linked issue.
> Fixed extension when purging media

- CHANGELOG.md
- src/Sulu/Bundle/AdminBundle/Resources/translations/sulu/backend.en.xlf
| Q | A
| --- | ---
| Bug fix? | Yes
| Fixed tickets | fixes #3098 
Minor fix for the typo/wrong language in the backend.en.xlf for AdminBundle
Line 755.
Was: "Num**m**er"
Become: "Num**b**er"
> Fixed typo in the backend.en.xlf for AdminBundle

- CHANGELOG.md
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Content/Tests/Functional/Repository/ContentRepositoryTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3063 
This PR adds the `published` field to the non-fallback fields for resolving internal links with the `ContentRepository`.
> display draft internal link in test mode

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/block.js
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/block.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/add_button.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/multiple.html.twig
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
- src/Sulu/Bundle/ContentBundle/Twig/ContentTwigExtension.php
- src/Sulu/Component/Content/Compat/Block/BlockProperty.php
- src/Sulu/Component/Content/Compat/Property.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php
- src/Sulu/Component/Content/Tests/Unit/Block/BlockPropertyTest.php
- src/Sulu/Component/Content/Tests/Unit/Compat/PropertyTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3046 
| Related issues/PRs | replaces #2653 
This PR fixes the behavior of the `minOccurs` property on the template xml with a value of 1.
The behavior of the `minOccurs` and `maxOccurs` fields have slightly changed. However, if somebody has set them, they were not acting correctly, so I would not really say it is a BC break.
> fixed support for multiple properties with minOccurs of 1

- CHANGELOG.md
- src/Sulu/Bundle/MarkupBundle/DependencyInjection/CompilerPass/TagCompilerPass.php
- src/Sulu/Bundle/MarkupBundle/Markup/DelegatingTagExtractor.php
- src/Sulu/Bundle/MarkupBundle/Markup/HtmlMarkupParser.php
- src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php
- src/Sulu/Bundle/MarkupBundle/Markup/TagExtractorInterface.php
- src/Sulu/Bundle/MarkupBundle/Markup/TagMatchGroup.php
- src/Sulu/Bundle/MarkupBundle/Resources/config/services.xml
- src/Sulu/Bundle/MarkupBundle/SuluMarkupBundle.php
- src/Sulu/Bundle/MarkupBundle/Tag/TagNotFoundException.php
- src/Sulu/Bundle/MarkupBundle/Tag/TagRegistry.php
- src/Sulu/Bundle/MarkupBundle/Tag/TagRegistryInterface.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/DelegatingTagExtractorTest.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/HtmlMarkupParserTest.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/HtmlTagExtractorTest.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Tag/TagRegistryTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2786 
| Related issues/PRs | https://github.com/sulu/sulu/issues/3105
| Documentation PR | https://github.com/sulu/sulu-docs/pull/297
This PR introduces a new service which will be used to extract tags from html-markup.
> Extracted tag-extractor from html-markup-parser

- CHANGELOG.md
- appveyor.yml
- composer.json
| Q | A
| --- | ---
This PR bumps version of twig to `^1.11`
> Bumped twig version to ^1.11

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentPathTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Tests/Unit/PortalTest.php
- src/Sulu/Component/Webspace/Tests/Unit/UrlTest.php
- src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
- src/Sulu/Component/Webspace/Url.php
- src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#787
This PR adds an additional check to the `hasDomain` method of the webspace, which allows to check if a domain is existing in a certain locale. It works as before if no locale is passed.
This is required because we need to check if the given domain also exists in the given locale of the `sulu_content_path` twig method.
> fixed sulu_content_path for language-specific domains

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/app/Resources/exports/tree.xml
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/TreeStrategyTest.php
- src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php
- src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php
| Q | A
| --- | ---
Changed Rlp PhpcrMapper and Strategy to use always original locale instead of the local. 
We had consistency if you moved a page with a shadow local.
> Updated the Rlp PhpcrMapper and Strategy to use the original locale

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
This PR fixes the tests for `TaskManager` because they currently fail in develop (e.g. https://travis-ci.org/sulu/sulu/jobs/192337103)
PHPUnit `4.8.31` relies on `"phpspec/prophecy": "^1.3.1"` which does not supports `willReturnArgument` with an `index !== 0`.
see:
* https://github.com/phpspec/prophecy/blob/v1.4.0/src/Prophecy/Prophecy/MethodProphecy.php#L149
* https://github.com/phpspec/prophecy/blob/v1.3.1/src/Prophecy/Prophecy/MethodProphecy.php#L147
i have changed the implementation to an own one to avoid the direct dependency on prophecy in sulu.
> Updated minimum "phpspec/prophecy" version

- CHANGELOG.md
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
| Q | A
| --- | ---
Fixed doctrine list builder id when name is not id
Listbuilder entities without `id` dont work.
```php
$idFieldDescriptor = new DoctrineFieldDescriptor(
'uuid',
'other',
TaskExecution::class,
'public.id',
[],
true,
false
);
$listBuilder->setIdField($idFieldDescriptor]);
```
> Fixed doctrine list builder id when name is not id

- CHANGELOG.md
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/event-subscribers.xml
- src/Sulu/Component/HttpCache/EventSubscriber/InvalidationSubscriber.php
- src/Sulu/Component/HttpCache/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#791
The scheme of the purge url will not be handled.
The `webspaceManager->findUrlsByResourceLocator` function has a parameter `scheme` a default value `http` this function has to be called twice one call with `http` and one call with `https`.
> Fixed invalidate cache for https

- CHANGELOG.md
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3158
| Related issues/PRs | #3158
Adds the requestUri request attribute, which is used by the WebsiteRequestProcessor class to get the current URI.
> Fixes #3158 by adding the URI to the request attributes

- CHANGELOG.md
- src/Sulu/Component/HttpCache/ProxyClient/Symfony.php
| Q | A
| --- | ---
This PR waits for the promises sent by the cache purging requests. Otherwise the php process will be killed too early leaving the cache intact.
> fixed cache clearing on publishing

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Sitemap/Provider/PagesSitemapProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/PagesSitemapProviderTest.php
| Q | A
| --- | ---
This PR removes internal/external links from sitemap.
From SEO perspective external links are not part of the website and internal links are present from the linked page.
> Fixed hide internal/external link in sitemap

- CHANGELOG.md
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/ResourceLocatorStrategyTest.php
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/TreeFullEditStrategyTest.php
- src/Sulu/Component/Content/Tests/Unit/Rlp/Strategy/TreeLeafEditStrategyTest.php
- src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php
| Q | A
| --- | ---
This PR changes the logic to get the resolvable parent. Instead of simply checking if the node is published the real data from the route tree is loaded.
The current logic is not sufficient, because internal links do not have a node in the route tree. This breaks the generating of routes in the page form and while copying pages, where the page is copied under a page, which has content but no route in a language.
> fixed generating of resource locator with missing parents

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Resources/config/list-builder/Account.xml
- src/Sulu/Component/Rest/ListBuilder/Metadata/Doctrine/Driver/XmlDriver.php
| Q | A
| --- | ---
Currently when load meta data for the field descriptor and add a none exist reference as joins the driver will not fail.
It should throw an exception to avoid problems which only appears when the user hide view specific columns only
~~~xml
<class xmlns="http://schemas.sulu.io/class/general"
xmlns:orm="http://schemas.sulu.io/class/doctrine"
xmlns:list="http://schemas.sulu.io/class/list">
<orm:joins name="creator">
<orm:join>
<orm:entity-name>%sulu.model.user.class%</orm:entity-name>
<orm:field-name>%sulu.model.comment.class%.creator</orm:field-name>
</orm:join>
</orm:joins>
<properties>
<property name="creatorId" filter-type="integer" list:translation="public.creator" …
> Added exception throw when field descriptor reference is not found

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Permission.orm.xml
| Q | A
| --- | ---
Added unique constraint for permission context and role
To avoid duplicated add permissions to a role.
~~~sql
INSERT INTO `se_permissions` (`context`, `module`, `permissions`, `idRoles`) VALUES ('app.test', NULL, 80, 1);
INSERT INTO `se_permissions` (`context`, `module`, `permissions`, `idRoles`) VALUES ('app.test', NULL, 80, 1);
~~~
> added unique constraint for permission context and role

- CHANGELOG.md
- src/Sulu/Bundle/CategoryBundle/Twig/CategoryTwigExtension.php
- src/Sulu/Bundle/TagBundle/Twig/TagTwigExtension.php
- src/Sulu/Component/Cache/MemoizeInterface.php
- src/Sulu/Component/Cache/MemoizeTwigExtensionTrait.php
- src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTwigExtensionTraitTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#799
This PR changes the `getFunctions` implementation of the `MemoizeTwigExtensionTrait` to use the actual parameters and the `memoizeById` method instead of relying on the `debug_backtrace` magic happening in the `Memoize` class.
I still left the `memoize` method of the `Memoize` class there, because the twig extensions for categories and tags still use it, but they could be refactored to use the same way as the twig extension for content. Then we could get rid of the ugly `debug_backtrace` call.
The question is if we should already deprecate the `memoize` call, so that it is safe to …
> fixed wrong cache key generation for MemoizeTwigExtensionTrait

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/automation.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluAutomationBundle/pull/4
There was a condition missing in the content navigation for the automation.
The automation tab also occured when creating a new language of an already existing page.
> remove the automation tab from ghost page forms

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Structure/PropertyValue.php
- src/Sulu/Component/Content/Tests/Unit/Document/Structure/PropertyValueTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3016
This PR fixes offset-set for class `PropertyValue`
> Fixed property-value offset set

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/DependencyInjection/Compiler/UserManagerCompilerPass.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/DependencyInjection/Compiler/UserManagerCompilerPassTest.php
- src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3196 
This PR adds all the parameters to the `UserManager` except for the one really being absent when used without Security. Then all the queries should work.
> fixed broken UserManager when used without Security

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/DependencyInjection/AbstractImageFormatCompilerPass.php
| Q | A
| --- | ---
This PR is an addition to https://github.com/sulu/sulu/pull/3040. It allows multiple themes to have the same image format key, if the format behind the key is exactly the same.
If two different themes have the exact same format it doesn't make sense to have two different keys, because also too many files are dumped.
> allow same image format key if formats are identical

- CHANGELOG.md
- src/Sulu/Component/CustomUrl/Routing/CustomUrlRouteProvider.php
- src/Sulu/Component/CustomUrl/Routing/Enhancers/ExternalLinkEnhancer.php
- src/Sulu/Component/CustomUrl/Routing/Enhancers/RedirectEnhancer.php
- src/Sulu/Component/CustomUrl/Routing/Enhancers/TrailingHTMLEnhancer.php
- src/Sulu/Component/CustomUrl/Routing/Enhancers/TrailingSlashEnhancer.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/ExternalLinkEnhancerTest.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/RedirectEnhancerTest.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/TrailingHTMLEnhancerTest.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/TrailingSlashEnhancerTest.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/RouteProviderTest.php
| Q | A
| --- | ---
Fixes redirects to RedirectController
`SuluWebsiteBundle:Default:redirect` no longer exists
> Use RedirectController for route redirects

- CHANGELOG.md
- src/Sulu/Component/HttpCache/EventSubscriber/FlushSubscriber.php
| Q | A
| --- | ---
This PR fixes cache clear when done in commands (automation).
> Added console terminate to flush-subscriber

- CHANGELOG.md
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
- src/Sulu/Component/Content/Document/Subscriber/AuthorSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/AuthorSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the problem that new pages get the creator-id as author. But the author should be the contact id of the author.
> Fixed set default author to creator contact-id

- CHANGELOG.md
- src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
- src/Sulu/Component/Rest/ListBuilder/Metadata/Resources/schema/metadata/list-builder-general-1.0.xsd
| Q | A
| --- | ---
FieldDescriptor: Corrected implementation of attribute `display` with value `yes
> Bugfix list builder attribute display

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Extension/seo.html.twig
| Q | A
| --- | ---
Use the correct locale to generate the shadow url.
Currently the false locale will be used to generate the shadow url.
> Fixed seo canonical tag with shadow

- CHANGELOG.md
- src/Sulu/Component/Webspace/Tests/Unit/UrlTest.php
- src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
- src/Sulu/Component/Webspace/Url.php
- src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
In the following domain configuration:
```xml
<url language="de">sulu.de</url>
<url language="de" country="it">sulu.it</url>
```
The first domain will also match for `de-it` because the country check will be ignored when the url has no country attribute.
The sulu.it will not be used to generate the `sulu_content_path` meta tags like alternate urls.
```twig
{{ sulu_content_path('/', null, 'de_it') }}
```
> Fixed webspace country specific domain match

- CHANGELOG.md
- src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php
- src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
- src/Sulu/Component/Localization/Localization.php
- src/Sulu/Component/Localization/Tests/Unit/LocalizationTest.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/AdminRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/AdminRequestProcessorTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3250
This PR fixes the detection of localization in the backend if no webspace is given.
The route-manager uses the `RequestAnalyzerTranslator` to translate the routes. Currently if no webspace is given not locale will be set on the translator.
Additionally the command `sulu:route:update` get a new argument locale - which enables it to generate locale specific routes.
> Fixed detect localization in admin

- CHANGELOG.md
- src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
- src/Sulu/Bundle/SearchBundle/Tests/Unit/Controller/WebsiteSearchControllerTest.php
| Q | A
| --- | ---
Search terms are escaped.
Words containing special characters have led to empty search result.
> Escape search terms

- CHANGELOG.md
- src/Sulu/Bundle/MarkupBundle/Listener/MarkupListener.php
- src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/MarkupListenerTest.php
| Q | A
| --- | ---
Fix an issue with how the request format is handled in the MarkupBundle.
MarkupBundle currently does not work at all.
Possibly.
> Fix markup listener

- CHANGELOG.md
- src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepository.php
| Q | A
| --- | ---
Currently the deprecated 'findCategoryByIds' function is missing
a return statement and is not usable.
This commit adds the missing statement.
> Add missing return statement in CategoryRepository

- CHANGELOG.md
- src/Sulu/Component/Util/SuluVersionPass.php
- src/Sulu/Component/Util/Tests/Resources/VersionPass/composer.json
- src/Sulu/Component/Util/Tests/Resources/VersionPass/composer.lock
- src/Sulu/Component/Util/Tests/Unit/SuluVersionPassTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3064 
| Related issues/PRs | https://github.com/sulu/sulu-minimal/pull/41 https://github.com/sulu/sulu-standard/pull/808
This PR changes the way to determine sulu version and use composer.lock instead of json.
> Used composer lock to read sulu version

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/WebspaceLocalizationNotFoundException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Exception/WebspaceNotFoundException.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Resources/public/js/components/preview/main.js
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
| Q | A
| --- | ---
| Related issues/PRs | #3270 
This PR adds a fake portal if no matching portal is found. 
This is necessary because #3270 removed the necessity of having all localization assigned to a portal. Until now there was a "dummy portal" providing the necessary information, and now this is not even necessary anymore.
> added fake portal for preview when nothing matches

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Search/EventListener/HitListener.php
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Search/EventListener/HitListenerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/SuluArticleBundle/issues/113
Pages with internal or external link type indexes their "not existing" resource-segment as url.
This PR add an expression to determine correct URL:
* internal: resource-segment of target
* external: external URL
The teaser-provider uses this field to extract URL from lucene document.
> Fixed index pages with redirect-behavior

- CHANGELOG.md
- src/Sulu/Bundle/AudienceTargetingBundle/DependencyInjection/Compiler/AddRulesPass.php
- src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupConditionInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRepository.php
- src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRepositoryInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRuleInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/doctrine/TargetGroupCondition.orm.xml
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/LocaleRule.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/RuleCollection.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/RuleCollectionInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/RuleInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/RuleNotFoundException.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/TargetGroupEvaluator.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/TargetGroupEvaluatorInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/SuluAudienceTargetingBundle.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Entity/TargetGroupRepositoryTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/LocaleRuleTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/RuleCollectionTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/TargetGroupEvaluatorTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #3203
| Documentation PR | TODO
This PR adds the recognizing of the target group for the current request. This is done by implementing different `RuleInterface`s, which evaluate the given circumstances against options which are passed to the method.
The `TargetGroupEvaluator` iterates over all `TargetGroup`s and evaluates all required implementations of the `RuleInterface` with the data provided by the `TargetGroup`.
> added rule evaluation

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
- src/Sulu/Bundle/WebsiteBundle/Resources/config/analytics.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-standard#806
This PR disable analytics listener for preview.
The analytics should not be there in the preview.
> fixed analytics for preview

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Entity/Analytics.php
- src/Sulu/Bundle/WebsiteBundle/EventSubscriber/AnalyticsSerializeEventSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/AnalyticsControllerTest.php
| Q | A
| --- | ---
This PR fixes the `allDomains` options for the Analytics webspace settings.
Because it was throwing an error before.
> Fixed allDomains option for analytics

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap-index.xml.twig
| Q | A
| --- | ---
Will fix sitemap index generation when maxPage of a sitemap provider is 0.
It would render `1..0` which would create a sitemap e.g. `sitemaps/articles-0.xml` and `sitemaps/articles-1.xml`.
> Fixed sitemap index provider without items

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
- src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php
- src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
- src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLegacyLoaderTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
- tests/Resources/DataFixtures/Page/template_with_invalid_ignore.xml
- tests/Resources/DataFixtures/Page/template_without_invalid_ignore.xml
| Q | A
| --- | ---
| Related issues/PRs | #3204
This PR allows to add an `onInvalid` attribute to the properties in the XML templates. If the attribute is set to `ignore` the property will not be added, in case a non-existing type is configured.
Because we want to add an audience target group content type to the `excerpt.xml` template, and it is not said that it is existing in all installation (most installations will probably turn of audience targeting).
This is the only easy way we found to add it to the `excerpt` template and keep it working when the audience target group content type is not available in the current installation.
This is because …
> added onInvalid flag with ignore option to properties

- src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
The constant PHP_EOL evaluates to "\r\n" (CR LF) on Windows while the .gitignore file is versioned with LF end-of-lines. So in essence, this fixes the script to work on Windows, otherwise it would leave the .gitignore untouched since the "search" part cannot be found.
| Q | A
| --- | ---
Small change to fix the post-create-project-cmd on Windows.
PHP_EOL on Windows is different than the EOL used in .gitignore, thus the script fails currently.
~~~shell
composer run-script post-create-project-cmd
~~~
> Make removeComposerLockFromGitIgnore compatible with Windows

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
This PR adapts the service definition of the document manager.
See main PR https://github.com/sulu/sulu-document-manager/pull/110
> Adapted document-manager service definition for new NodeNameSlugifier

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Document/Subscriber/PublishSubscriber.php
- src/Sulu/Bundle/ContentBundle/Resources/config/document.xml
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Document/Subscriber/PublishSubscriberTest.php
| Q | A
| --- | ---
| Related issues/PRs | requires https://github.com/sulu/sulu-document-manager/pull/109 and related to https://github.com/sulu/SuluArticleBundle/pull/139 build ontop https://github.com/sulu/sulu/pull/3299
This PR adds a check which uses a new metadata property to avoid removing the live node for special documents.
> Added metadata to configure remove-live

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
This PR fixes the conflicts constraint of `jacklope/jackalope`.
> Fixed jackalope conflict in composer.json

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201702021447.php
| Q | A
| --- | ---
It is not possible to upgrade to sulu 1.5 when you have a removed user referenced as creator in the nodes. `Call getContact on a none object` when running `phpcr:migrations:migrate` for the author migration.
To avoid errors in migration script when author not longer exists.
~~~bash
app/console phpcr:migrations:migrate
~~~
> Fixed author migration script for removed users

- CHANGELOG.md
- src/Sulu/Component/Content/Document/Subscriber/WorkflowStageSubscriber.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/WorkflowStageSubscriberTest.php
| Q | A
| --- | ---
Set the document published date when property is not set.
It allow to set the published date by reflection for import scripts.
> Added possibility to overwrite published date of document

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Command/ContentTypesDumpCommand.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
| Q | A
| --- | ---
This PR fixes the `sulu:content:types:dump` for symfony `3.2`.
> Fixed "sulu:content:types:dump" command

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Exception/RouteIsNotUniqueException.php
- src/Sulu/Bundle/RouteBundle/Manager/RouteManager.php
- src/Sulu/Bundle/RouteBundle/Manager/RouteManagerInterface.php
- src/Sulu/Bundle/RouteBundle/Resources/config/manager.xml
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Manager/RouteManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/164
This PR add a new parameter to disable conflict-resolver for `RouteManager`.
The `SuluArticleBundle` generates and unify the routes at another place. The `RouteManager` should then only throw an exception.
~~~php
try{
$routeManager->create($entity, '/test-entity', false);
} catch (RouteIsNotUniqueException $exception) {
// Handle conflict
}
~~~
> Added parameter to disable conflict-resolver

- CHANGELOG.md
- composer.json
- src/Sulu/Component/Content/Repository/Serializer/SerializerEventListener.php
| Q | A
| --- | ---
This PR fixes a problem when calling a URL with a field which is automatically populated. (call `/admin/api/nodes?language=<locale>&webspace=<webspace>&fields=title,order,published,url` for an example
The serializer throws an exception when using `addData` and the property already exists. Version `1.4` introduces a method `setData` which overwrites the property without exception.
> Fixed overwrite data in content-serialization

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Entity/BaseRoute.php
- src/Sulu/Bundle/RouteBundle/Manager/RouteManager.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Manager/RouteManagerTest.php
| Q | A
| --- | ---
This PR reintroduces restore for disabled conflict-resolver.
This happens when you try to restore a route in SuluArticleBundle. There the conflict-resolver is disabled and you change the route to an old one - you will see an error instead of restoring the route.
> Fixed restore route when conflict resolver is disabled

- src/Sulu/Bundle/AudienceTargetingBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/AudienceTargetingBundle/DependencyInjection/SuluAudienceTargetingExtension.php
- src/Sulu/Bundle/AudienceTargetingBundle/Request/ForwardedUrlRequestProcessor.php
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/PageRule.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Request/ForwardedUrlRequestProcessorTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/PageRuleTest.php
- src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Component/HttpCache/HttpCache.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/UrlRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/UrlRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
| Q | A
| --- | ---
This PR fixes the session and visitor evaluation of the page rule, which previously only worked in the dev environment. The problem was that the structure attribute was not written at the time it was read. So I have to pass the original URL and do a lookup for it.
> fixed session and visitor evaluation for page rule

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Markup/LinkTag.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Markup/LinkTagTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3323
This PR extends the `LinkTag` to allow additional attributes.
In links `class` or other attributes makes sense.
~~~twig
<sulu:link provider="content" href="123-123-123" class="btn">My link</sulu:link>
~~~
> Added possibility to add additional attributes to "sulu:link"-tag

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/CategoryBundle/Content/Types/CategoryList.php
- src/Sulu/Bundle/ContactBundle/Content/Types/ContactSelectionContentType.php
- src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactSelectionContentTypeTest.php
- src/Sulu/Bundle/ContentBundle/Content/Types/InternalLinks.php
- src/Sulu/Bundle/LocationBundle/Content/Types/LocationContentType.php
- src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
- src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
- src/Sulu/Bundle/TagBundle/Content/Types/TagList.php
- src/Sulu/Component/Content/ContentTypeInterface.php
- src/Sulu/Component/Content/SimpleContentType.php
- src/Sulu/Component/Content/Types/BlockContentType.php
- src/Sulu/Component/SmartContent/ContentType.php
| Q | A
| --- | ---
| BC breaks? | yes (removed deprecated methods)
This PR removes the deprecated method `getType` and the two deprecated constants `PRE_SAVE` and `POST_SAVE` from `ContentTypeInterface`.
> Removed get-type from content-type-interface

- src/Sulu/Bundle/AudienceTargetingBundle/Controller/TargetGroupEvaluationController.php
- src/Sulu/Bundle/AudienceTargetingBundle/EventListener/TargetGroupSubscriber.php
- src/Sulu/Bundle/AudienceTargetingBundle/TargetGroup/TargetGroupStore.php
- src/Sulu/Bundle/AudienceTargetingBundle/TargetGroup/TargetGroupStoreInterface.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Controller/TargetGroupEvaluationControllerTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/TargetGroupSubscriberTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/UserContext/TargetGroupStoreTest.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/app/AppKernel.php
- src/Sulu/Component/HttpCache/HttpCache.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/327
This PR checks if the Target Group influenced the rendered body of the response using the `TargetGroupStore`, and only set the `Vary` and `s-maxage` header if the response was influenced by the target group.
This should result in more cache hits, since pages which are not influenced by target groups do also not vary based on this header in the cache.
Simply call `$targetGroupStore->getTargetGroupId()` where ever you are in need of the target group. The service will remember that and Sulu sets the correct headers for you.
> add audience targeting caching headers only if necessary

- CHANGELOG.md
- src/Sulu/Component/CustomUrl/Routing/Enhancers/RedirectEnhancer.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/RedirectEnhancerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #2308
This PR appends the `$request->getQueryString()` to the redirected URL.
> Added redirect parameter of custom-url

- src/Sulu/Bundle/ContentBundle/Command/ContentTypesDumpCommand.php
- src/Sulu/Bundle/ContentBundle/Command/ValidatePagesCommand.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ValidatePagesCommandTest.php
- src/Sulu/Bundle/WebsocketBundle/Command/DumpWebsocketAppsCommand.php
- src/Sulu/Bundle/WebsocketBundle/Tests/Functional/Command/DumpWebsocketAppsCommandTest.php
- src/Sulu/Bundle/WebsocketBundle/phpunit.xml.dist
| Q | A
| --- | ---
| Fixed tickets | fixes #3365
| Related issues/PRs | #2106
Get rid of deprecated console helpers still used by some cli commands
This could be a show-stopper for Symfony 3.x support
> Get rid of deprecated "table" console helper

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
Allow imagine 0.7 version to be installed.
The old 0.6 is incompatible with the newset Imagick version.
No BC Break 0.6 is still allowed.
[Changes 0.6-0.7](https://github.com/avalanche123/Imagine/compare/v0.6.3...v0.7.0)
- https://github.com/avalanche123/Imagine/pull/547
- https://github.com/avalanche123/Imagine/issues/539
> Update imagine dependency

- src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.nl.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/QueryStringRule.php
- src/Sulu/Bundle/AudienceTargetingBundle/Rule/Type/KeyValue.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/QueryStringRuleTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #3203 
This PR adds a rule which allows to define certain values of the query string.
E.g. the target group could check this way if the user landed here because of a campaign.
> added audience targeting rule for query string

- src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.nl.xlf
- src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
- src/Sulu/Bundle/ContentBundle/Resources/config/rule.xml
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.nl.xlf
- src/Sulu/Bundle/ContentBundle/Rule/PageRule.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Rule/PageRuleTest.php
| Q | A
| --- | ---
This PR moves the `PageRule` from the `AudienceTargetingBundle` to the `ContentBundle`, because that's the correct location. If you think further the `ArticleBundle` will also have its own rule later.
> move the PageRule to ContentBundle

- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/CachingTest.php
- src/Sulu/Component/HttpCache/HttpCache.php
| Q | A
| --- | ---
| Documentation PR | https://github.com/sulu/sulu-docs/pull/329
Renamed cookies from audience targeting to shorter names.
> renamed audience targeting cookies

- CHANGELOG.md
- src/Sulu/Bundle/AudienceTargetingBundle/Request/ForwardedUrlRequestProcessor.php
- src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Request/ForwardedUrlRequestProcessorTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentPathTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Analyzer/Attributes/UrlRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/UrlRequestProcessorTest.php
| Q | A
| --- | ---
| Related issues/PRs | replaces https://github.com/sulu/sulu/pull/3211
This PR replaces `Request::getHttpHost` calls with `Request::getHost`.
The difference between these calls is, that `getHttpHost` also includes the port if it is a non-default port. The problem with that is, that our application should actually not care about the port at all, as it is also the case with Symfony. (also see comment in https://github.com/sulu/sulu/pull/3211#issuecomment-280271005)
The thing is that we can't solve all of that at once. So for now I fixed this call everywhere, but our `sulu_content_path` twig method still have to add the port to the …
> fixed usage of Sulu with non-default HTTP port

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
- src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/UserLocaleListenerTest.php
| Q | A
| --- | ---
This PR fixes the `UserLocaleListener`. It has to set the locale on both the `Request` and the `Translator`, because it cannot have a higher priority than the 
This bug was the reason that the conditions in the audience targeting were not translated.
> fixed UserLocaleListener

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Resources/views/Template/content-types/route.html.twig
| Q | A
| --- | ---
| BC breaks? | avoid one
This PR avoid a BC break in the content form for  `route` content-type.
The form will be used in SuluArticleBundle and breaks current versions with the current RC1.
> Avoid BC break in content-type "route" form

- CHANGELOG.md
- src/Sulu/Bundle/AudienceTargetingBundle/Controller/TemplateController.php
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
This PR adds a clearer translation for the frequency in the ruleset overlay of the audience targeting.
Because the previous texts were not self-explaining.
> added translations for frequencies

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3380
This add the host to the fake request of the preview.
@danrot but there is no host in websocket mode. what should we do then?
> Added host to preview request

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
- src/Sulu/Component/SmartContent/ContentType.php
- src/Sulu/Component/SmartContent/Exception/PageOutOfBoundsException.php
- src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3388
This PR fixes a bug when passing invalid values for current page over request to smart-content.
If you pass `$page < 1 || $page > PHP_INT_MAX` to smart-content doctrine throws exception later on.
> Fixed smart-content out of range

- CHANGELOG.md
- src/Sulu/Bundle/DocumentManagerBundle/Document/Subscriber/SecuritySubscriber.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3389 
| Related issues/PRs | https://github.com/sulu/sulu/pull/3042
This PR removes the exception when a User does not implement our `UserInterface`, but returns `null` instead.
> remove exception for non-Sulu user

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/sitemap.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig
- src/Sulu/Bundle/WebsiteBundle/Sitemap/Provider/PagesSitemapProvider.php
- src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderInterface.php
- src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapUrl.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/PagesSitemapProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php
- src/Sulu/Bundle/WebsiteBundle/Tests/app/Resources/webspaces/sulu_with_localized_tld.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #3187, fixes #3163 
| Related issues/PRs | #2916 
| Documentation PR | https://github.com/sulu/sulu-docs/pull/346
This PR adds all localizations as separate URLs to the sitemap, which was changed back in version 1.5.
> fixed localization of sitemaps

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Entity/BaseRoute.php
- src/Sulu/Bundle/RouteBundle/Model/RouteInterface.php
| Q | A
| --- | ---
| BC breaks? | yes?
Allow to reset the route entity target to null.
When a history url is changed from `history=1` to `history=0` also the Target need to set to null e.g. ArticleBundle. 
~~~php
$entity->setHistory(false);
$entity->setTarget(false);
~~~
yes?
> Allow to reset the route entity target to null

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Api/Media.php
| Q | A
| --- | ---
This PR add additional check for media api object `getTargetGroups`. This function returns null if the AudienceTargetBudnle` is not registered.
> Added check for null target-groups

- .eslintignore
- .travis.yml
- appveyor.yml
- composer.json
- src/Sulu/Bundle/AdminBundle/Admin/Admin.php
- src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/Route.php
- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/stores/RouteStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/stores/RouteStore.test.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/AdminPoolTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
| Q | A
| --- | ---
This PR loads the routes for the react application from the server.
`add metadata action` is the first commit from this PR, the rest comes from #3405
> Load react routes from server

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3424 
Add rawurlencode for the filename of the media url.
None browser e.g. native android avoid request to a none RFC valid url.
~~~php
$media->getUrl(); // should return a rawurlencoded filename
~~~
> Fixed file download url filename encoding

- CHANGELOG.md
- src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
- src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
| Q | A
| --- | ---
Set the current localization to default localization when not exist.
Fixed rendering of 404 page when e.g. webspace config is: `<url>sulu.io/{localization}</url>` and the request page is `sulu.io/test`.
```php
$requestAnalyzer->getCurrentLocalization();
$request->getLocale();
```
There always exist a current localization.
> Fixed 404 page for none localized urls

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
- src/Sulu/Component/Webspace/Manager/WebspaceManager.php
- src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
| Q | A
| --- | ---
Add a slash to the  homepage of a webspace when it is not a folder e.g. `https://example.org` will be `https://example.org/`.
A browser always request `https://example.org/` and tools like onpage will throw an error that the current page `https://example.org/` is not listed in the sitemap or are false in the content. So all root urls of a domain should keep the `/`. 
```twig
{{ sulu_content_path('/') }} {# should output `https://example.org/` instead of `https://example.org`
```
> Fixed url generation for domain root url

- src/Sulu/Bundle/AdminBundle/Admin/Routing/Route.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/AdminPoolTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
| Q | A
| --- | ---
This PR changes the order of the route parameters, so that the name and pattern come first, and the react part at the end.
This way the elements belonging together stand next to each other.
> changed order of route parameters

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Item.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
| Q | A
| --- | ---
This PR replaces the `item-disabled` class with the usage of the `disabled` attribute.
Because this makes the application more accessible.
> use disabled attribute instead of separate class

- .flowconfig
- .travis.yml
- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/__snapshots__/Icon.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Item.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
- styleguide.config.js
| Q | A
| --- | ---
This PR adds [react-styleguidist](https://react-styleguidist.js.org/), which allows to document our components. It also adds a small documentation for the Icon component, but without any rendered example, because the webpack configuration would be quite complicated, and it's probably not worth it.
On the side it also adds the `aria-hidden` tag on the icon itself, which was missing before.
Because we would like to properly document our components.
> add react styleguidist to document components

- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/Translator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/tests/Translator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
- src/Sulu/Component/Cache/Tests/Unit/Cache/DataCacheTest.php
| Q | A
| --- | ---
This PR adds a Symfony endpoint `/v2/translations` which takes a locale and returns all translations in that locale from the `admin` domain.
The react admin will do a request to this domain, and set the result to the translator (also implemented in this PR), which can be used to translate the UI afterwards.
Because loading translations from the server via a endpoint allows an external developer to easily override/add translations without touching and javascript or creating a new webpack build.
~~~javscript
translator.set({'save': 'Save'});
translator.translate('save');
~~~
> Load admin translations from Symfony endpoint

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
This PR adds polyfill packages. They also need to be configured in the `webpack.config.js` file of sulu-minimal, PR is in the making.
Because we want to support IE11, and these polyfills are required in order for our application to run there.
> add polyfills for IE11

- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/Translator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/tests/Translator.test.js
| Q | A
| --- | ---
This PR adds a logging library, which allows us to set different log levels and activate them differently. The first use case will be to warn about missing translations.
Because we care about good DX.
> log a warning when translation is missing

- .eslintrc.json
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/Translator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/tests/Translator.test.js
| Q | A
| --- | ---
This PR will change the default log level based on the build environment. On the production build only errors will be logged, and on a development build all logs will be shown.
In addition to that it exposes the `log` variable to `window`. This allows to change the log level using the console of the developer tools using a statement like `log.setLevel(0)` (this would change from the current setting to show all logs).
Because we want different logs in different environments. And the log level can be changed on the fly, which allows for easier debugging in certain situations.
> set log level based on build environment

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/Icon.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/__snapshots__/Icon.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Item.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Item.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/withToolbar.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
Explain the contents of the PR.
Enzyme wrappers ware very convenient when writing tests. However, they cannot be used together with the jest snapshot functionality. This PR introduces a dependency which allows this.
~~~javascript
const view = mount(<MyComponent />);
expect(view).toMatchSnapshot();
~~~
> Use enzyme wrappers in snapshots

- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/TemplateControllerTest.php
| Q | A
| --- | ---
The `webspace` parameter had to be added to a test, because based on it there will be a call to a doctrine library.
The doctrine library has been updated, and this update includes some static type hints, which make our tests currently fail.
> fix call to doctrine including type hints

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/search.xml
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes parts of #3427 
This PR fixes the error explained in #3427, but only the reindexing part.
The problem that still persists is that if a page is configured to be a shadow page, it will be indexed in the wrong language. It's like that because the `DocumentManager` only sets the `shadowLocale` property on the document, and leaves all other properties as they are, which means that at [this line](https://github.com/sulu/sulu/blob/2676cbd/src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php#L115) the non-shadow properties are placed. This probably also has to be like that, because …
> index correct language of shadow document

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
| Q | A
| --- | ---
Only add extension as name when extension exist in pathinfo.
Else PHP Logs a notice error when accessing an error key which does not exist.
> Fixed error when downloading media without extension

- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
Removes the `promise-polyfill` in exchange for the `babel-polyfill`, which will be introduce in https://github.com/sulu/sulu-minimal/pull/57.
Because the `babel-polyfill` includes a few more polyfills which are needed.
> removed promise polyfill in favour of babel-polyfill

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/PositionNormalizer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/RatioNormalizer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/RoundingNormalizer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/SizeNormalizer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/PositionNormalizer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/RatioNormalizer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/RoundingNormalizer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/SizeNormalizer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/types.js
| Q | A
| --- | ---
- The data normalizers in the rectangle selection component got renamed to just `normalizers`.
- The normalizers in the rectangle selection are not constructed through a getter anymore, but with an via a designated method.
The getter was called way to often (when moving the rectangle). As most calls were unnecessary, the creation of the normalizers was moved to a method which gets called only when really necessary.
> Bugfix in rectangle selection

- CHANGELOG.md
- src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/FixturesLoadCommandTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3458
This PR fixes the command `sulu:document:fixtures:load` which uses a deprecated (and in 3.0 removed helper).
> Fixed document-manager load-fixtures command

- CHANGELOG.md
- src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml.dist
| Q | A
| --- | ---
This PR sets the database version in the tests to 5.6, to avoid using the `JSON` datatype which is not available before mysql 5.7.
Because we want to support older mysql versions as well.
> fix doctrine errors for mysql older than 5.7

- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/Backdrop.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/ModifiableRectangle.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/__mocks__/withContainerSize.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/withContainerSize.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SplitView/SplitView.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/stores/ViewStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/react/buildHocDisplayName.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/react/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/react/tests/buildHocDisplayName.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
| Q | A
| --- | ---
This PR uses the typing of children in react using flow, which is available since [flow 0.53](https://github.com/facebook/flow/issues/1964#issuecomment-322865281).
More information about this can be found in the flow documentation:
- [React components](https://flow.org/en/docs/react/components/)
- [React children](https://flow.org/en/docs/react/children/)
- [React type reference](https://flow.org/en/docs/react/types/#toc-react-node)
Because typing is great 😄 
The description of props in flow have changed. Instead of an own property they have to be defined as generics.
Old version:
```javascript
// @flow …
```
> update flow and add children annotations

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/Radio.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/RadioGroup.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/radio.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/tests/Radio.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/tests/RadioGroup.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/tests/__snapshots__/Radio.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/tests/__snapshots__/RadioGroup.test.js.snap
| Q | A
| --- | ---
A custom radio button component as well as a radio group component.
The radio component is needed in various use cases. The group component makes the state management of the radio components easier, as it wraps multiple of them and makes sure that only a single one of them is checked.
~~~javascript
initialState = {value: '1'};
<div>
<Radio checked={state.value === '1'} onChange={() => setState({value: '1'})} />
<Radio checked={state.value === '2'} onChange={() => setState({value: '2'})} />
<Radio checked={state.value === '3'} onChange={() => setState({value: '3'})} />
</div>
~~~
```javascript
initialState = {value: '1'};
<RadioGroup value={state.value} onChange={(value) => …
```
> Implemented radio and radio-group component

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/Checkbox.test.js
| Q | A
| --- | ---
The value property gets passed to the change callback as a second optional parameter.
~~~javascript
initialState = {checked: false};
onChange = (checked, value) => setState({checked});
<Checkbox value="my-value" checked={state.checked} onChange={onChange} />
~~~
> Added value as second parameter of the checkbox change callback

- src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/CroppedText.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/croppedText.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/tests/CroppedText.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/tests/__snapshots__/CroppedText.test.js.snap
| Q | A
| --- | ---
A component which crops text if it gets to long.
The issue that text can be to long for the given space is present in plenty components. This PR introduces a feature which copes with this issue.
~~~javascript
<CroppedText>The next sentence is false. The previous sentence is true.</CroppedText>
~~~
> Implemented cropped text component

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
| Q | A
| --- | ---
Fixed a problem with the symfony frozen parameters bag that `get` converts the given parameter to `strtolower` but the constructor of the FrozenParameterBag doesn't. 
It need to be fixed here as discussed in symfony/symfony#24065 they will not fix it in the FrozenParametersBag.
> Fixed snippet area with upper case

- .styleci.yml
- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | fixes https://github.com/sulu/sulu/issues/3493
This PR adds the remove call for `FileVersionMeta` - this will trigger the `onRemove` event of doctrine to deindex the media from massive-search index.
> Fixed deindex of medias

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
| Q | A
| --- | ---
| Related issues/PRs | #3457, depends on https://github.com/sulu/sulu-minimal/pull/64
This PR adds the possibility to bind certain observable values to a parameter of the query string using the Router.
Because this way it is possible to implement the datagrid without any knowledge of the routing, and the parent of the datagrid can decide to "sync" the value to the URL.
~~~php
const page = observable(1);
router.bind('page', page);
page.set(2); // this will also change the URL
~~~
> Add parameter binding to router

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
| Q | A
| --- | ---
It activated on-delete cascade so when a tag is deleted a tag-fileversion media relation is also deleted.
Currently its not possible to remove a Tag which is referenced in a media FileVersion entity.
> Fix deletion of tag when referenced by media file version

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
| Q | A
| --- | ---
A fix for the table header button cells issue which was spotted by @chirimoya. The button cells, which are marking the columns of clickable buttons did't have a fixed width. For tables with content the issue didn't occur because the header button cells got the same width as the underneath columns inside the table body. For empty tables (tables with an empty body) the width of the header button cell was flexible.
Also the height of the table row inside the header was set back to the height used inside the design.
See above
> fixed table header sizing issue for empty tables

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/FolderList/tests/__snapshots__/Folder.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/FolderList/tests/__snapshots__/FolderList.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/GenericSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/Option.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/GenericSelect/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Menu/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/tests/MultiSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/Radio.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Select.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Select.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/Switch.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/Toggler.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Translator/Translator.js
| Q | A
| --- | ---
In this PR all child components which had to be imported on their own for usage can now be accessed as static properties through their parent component. Imports and exports of components and other JavaScript modules are now more consistent.
To provide a better API for developers using components with child components.
~~~php
import Table from './Table';
const Header = Table.Header;
const Body = Table.Body;
const Row = Table.Row;
const Cell = Table.Cell;
const HeaderCell = Table.HeaderCell;
<Table>
<Header>
<HeaderCell>Column 1</HeaderCell>
<HeaderCell>Column …
> refactoring component export

- CHANGELOG.md
- src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
- src/Sulu/Component/Content/Tests/Unit/Compat/Structure/StructureBridgeTest.php
| Q | A
| --- | ---
StructureBridge shouldn't crash when no document is attached.
> Fix bug in structure bridge when no document is available

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/config/document.xml
- src/Sulu/Component/Content/Document/Subscriber/RouteSubscriber.php
- src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
- src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/RouteSubscriberTest.php
| Q | A
| --- | ---
This PR fixes a problem when using the `tree_full_edit`.
Use following config in your webspace.xml:
```
<resource-locator>
<strategy>tree_full_edit</strategy>
</resource-locator>
```
Create a page tree like:
* page 1
* page 1.1
* page 1.2
* page 2
Change the resource-locator of `page 1.1` to `page-3/page-1-1` and click "save and publish".
Go to `page 1` and change the resource-locator to `page-3` and see the exception because the resource-locator is already in use.
> Fixed override route when using "tree_full_edit"

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Content/SnippetDataProvider.php
- src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Import/SnippetImportTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetDataProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3439
This PR introduces the `exclude_duplicates` configuration to `SnippetDataProvider`.
This is missing in the data-provider.
> Added reference-store to snippet data-provider

- .gitignore
| Q | A
| --- | ---
Today we were discussing how to update our .gitignore and I used sulus as example. By this we found some doublications and restructured the whole file.
I changed those to folder rules as I believe it is a more cleare statement and those folders will be generated during run time. But this means no .gitkeep would keep those folders.
Moved composer to it's own section
I didn't know what that ~* really meant and added a headline to make this clear.
At least I do use meld and the .orig files should be excluded.
Same as before.
Added headline and package-lock.json was excluded three times.
*.iml are intelliJ files and should only appear inside the .idea folder.
Was there twice.
As …
> Removed redundancy from .gitignore, restructured it and added some comments

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
| Q | A
| --- | ---
| Related issues/PRs | [#3552](https://github.com/sulu/sulu/pull/3552)
On 'single_internal_link' the webspace key is not accessible and we need it to set link to another webspace.
~~~twig
{% set target = sulu_content_load(content.myLink) %}
{{ sulu_content_path(target.path, target.webspaceKey) }}
~~~
> Return webspaceKey on StructureResolver

- CHANGELOG.md
- src/Sulu/Component/Security/Authorization/SecurityContextVoter.php
- src/Sulu/Component/Security/Tests/Unit/Authorization/SecurityContextVoterTest.php
| Q | A
| --- | ---
This PR fixes a bug with the security system. When the user has no role the user has all roles. This happens when you remove all roles from a user and the user reset his password. The autologin then logs in the user and then the user has then all rights in the system.
> Fixed permissions for user with no role

- .gitignore
- package.json
- src/Sulu/Bundle/AdminBundle/.gitignore
- src/Sulu/Bundle/AudienceTargetingBundle/.gitignore
- src/Sulu/Bundle/CategoryBundle/.gitignore
- src/Sulu/Bundle/CollaborationBundle/.gitignore
- src/Sulu/Bundle/ContactBundle/.gitignore
- src/Sulu/Bundle/ContentBundle/.gitignore
- src/Sulu/Bundle/CustomUrlBundle/.gitignore
- src/Sulu/Bundle/DocumentManagerBundle/.gitignore
- src/Sulu/Bundle/LocationBundle/.gitignore
- src/Sulu/Bundle/MarkupBundle/.gitignore
- src/Sulu/Bundle/MediaBundle/.gitignore
- src/Sulu/Bundle/PersistenceBundle/.gitignore
- src/Sulu/Bundle/PreviewBundle/.gitignore
- src/Sulu/Bundle/ResourceBundle/.gitignore
- src/Sulu/Bundle/RouteBundle/.gitignore
- src/Sulu/Bundle/SearchBundle/.gitignore
- src/Sulu/Bundle/SecurityBundle/.gitignore
- src/Sulu/Bundle/SnippetBundle/.gitignore
- src/Sulu/Bundle/TagBundle/.gitignore
- src/Sulu/Bundle/TestBundle/.gitignore
- src/Sulu/Bundle/WebsiteBundle/.gitignore
| Q | A
| --- | ---
| Related issues/PRs | #3550 
This PR removes the trailing slash from the folders, because older versions of git don't seem to ignore these folders then.
> fix folders in gitignore

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
| Q | A
| --- | ---
Renamed argument in `onChange`prop of `Input` component from `password` to `value` 
The `Input` can have different `types`. Calling the argument `password` makes no sense.
> Renamed argument in `onChange` of `Input` component

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/SuluArticleBundle#226
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/pull/257
This PR introduces a config value to allow decorating index name (e.g. `article_published`) for different document types than `page`.
This is needed to index articles properly.
> Added option to decorate index name for document types

- CHANGELOG.md
- src/Sulu/Component/Content/Mapper/ContentMapper.php
- src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes https://github.com/sulu/SuluArticleBundle/issues/185
This PR set the published datetime to null when copying from one locale to another.
The state of the document is "published" and has a "draft" but is not present in the live workspace.
> Fixed "awkward" state of documents after copy-locale

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/registries/FieldRegistry.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/registries/ViewRegistry.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/registries/RouteRegistry.test.js
| Q | A
| --- | ---
| Related issues/PRs | #3559
The folder structure in the tests for registries was not aligned with the actual code.
We want the folder structures to reflect each other.
> moved registry tests to correct folders

- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/DownloadList.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/DownloadListItem.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/README.md
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/downloadListItem.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/mediaCard.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/package.json
| Q | A
| --- | ---
A dropdown inside the `MediaCard` component which contains the download urls for the different sizes of the image.
URLs of the different image sizes need to be copyable.
~~~js
const imageSizes = [
{
url: 'http://lorempixel.com/300/200',
label: '300/200',
},
{
url: 'http://lorempixel.com/600/300',
label: '600/300',
},
{
url: 'http://lorempixel.com/150/200',
label: '150/200',
}
];
<div style={{backgroundColor: '#e5e5e5', padding: 20}}>
<MediaCard
id="What is luv?"
icon="check"
onSelectionChange={handleSelection}
onClick={handleClick}
selected={state.selected}
meta="image/png, 3,2 MB"
title="Lorempixel sdsdasdsd sdadasd asdasd" …
> Added downloadlist to mediacard

- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
| Q | A
| --- | ---
| Related issues/PRs | probably introduced in #3547
This PR fixes lists for usage without a locale.
Because there are also lists without a locale.
> fix List without locales

- src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/type/piwik.html.twig
Trim trailing slash to avoid double slashes and to always get a correct URL.
| Q | A
| --- | ---
Replaces double slashes in piwik tracker url
> Trim trailing slash

- CHANGELOG.md
- src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php
- src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Request/CustomUrlRequestProcessorTest.php
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
- src/Sulu/Component/CustomUrl/Routing/CustomUrlRouteProvider.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Routing/CustomUrlRouteProviderTest.php
| Q | A
| --- | ---
This PR fixes an issue with umlauts in the source. The server encodes the URL and Symfony returns this in getPathInfo. We use this to find the redirect-route. This leads into a not found route.
Routes with `ß` or umlauts does not work.
> Added rawurldecode to decode path-info before searching for route

- .gitignore
- bin/travis/script_js.sh
- package.json
- postcss.config.js
- webpack.config.js
| Q | A
| --- | ---
| Fixed tickets |---
This PR moves the webpack configuration from sulu-minimal to this repository. The postcss configuration can be moved completely to this repository, because it is loaded relatively from the basepath of the CSS file.
This is required for a functional testing setup (we need a javascript build in this repository to make acceptance tests using http://www.nightmarejs.org/).
> Move webpack configuration to this repository

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
| Q | A
| --- | ---
This PR introduces a second parameter in `unbindQuery`, which is the observable to delete. This should avoid deleting the wrong observable as binding by accident.
This PR fixes two different bugs:
* In the `List` view the locale changer does not change the URL when the first page is loaded.
* When switching between `List` and `Form` the locale switcher does not update the URL anymore.
The `router.unbindQuery` method takes another parameter.
> Fix router binding query parameter when changing views

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
| Q | A
| --- | ---
| Fixed tickets | fixes none
This PR refactors the `withToolbar` high-order-component to use inheritance inversion.
This improves the stackability of such functions (in favor of upcoming `withSidebar` function).
See https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e
> Refactored with-toolbar to use inheritance-inversion

- CHANGELOG.md
- src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
- src/Sulu/Component/Persistence/Tests/Functional/EventSubscriber/ORM/UserBlameSubscriberIntegrationTest.php
- src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/UserBlameSubscriberTest.php
| Q | A
| --- | ---
It avoids to throw an exception in the blame subscriber when the current user is not a sulu user.
If the website user is not a sulu user it will throw `RuntimeException: Expected user object to be an instance of (Sulu) UserInterface` currently. It should just ignore this user and don't set changer or creator for this entity.
BlameSubscriber will not longer throw an exception when symfony returns a none sulu user.
> Fixed exception of blame for none sulu users

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/__snapshots__/ViewRenderer.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
| Q | A
| --- | ---
This PR adds the possibility to share data between tabs by allowing tabs to call its children as a function and pass more props.
Because we want to share data between multiple tabs when implementing forms.
> Share data between snippet tabs

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/README.md
| Q | A
| --- | ---
Two childnodes without a wrapping div caused an error in the styleguide docs
> Fixed error in styleguide

- src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/InfiniteScroller.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/tests/InfiniteScroller.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
| Q | A
| --- | ---
This PR adds an infinite scroll component
We need one to load content inside the masonry view.
~~~js
const handleLoad = (pageToLoad) => {
// do something
};
<div id="scrollable">
<InfiniteScroller
total={10}
current={1}
onLoad={handleLoad}
>
<div className="content-item" />
<div className="content-item" />
<div className="content-item" />
<div className="content-item" />
</InfiniteScroller>
</div>
~~~
> Added infinite scroller component

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.de.xlf
- src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.en.xlf
- src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.fr.xlf
- src/Sulu/Bundle/SecurityBundle/Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
Change the security warning message to reload the browser instead of system.
From a slack discussion I was asked by a user which system he now need to reload after he changed the permissions. So this message seems to be misleading the user.
> Fix misleading security warning message

- .eslintignore
- .gitignore
- flow-typed/npm/jest_v21.x.x.js
- package.json
- src/Sulu/Bundle/AdminBundle/Admin/Routing/Route.php
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
- src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
| Q | A
| --- | ---
This PR will implement the possibility to add default values for attributes. This can be done on the serverside with the new `addAttributeDefault` function of the route.
It also combines the `attributes` and `query` from the router to just `query`.
Because we want to be able to set a default locale for every section, which means that navigating always works for these routes.
And we combined `attributes` and `query`, because this way the caller doesn't need to know where to place the arguments.
The `navigate` function has no `query` parameter anymore and the
> Implement default values for attributes

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Grid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Section.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/grid.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/section.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/Grid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/__snapshots__/Grid.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
| Q | A
| --- | ---
This PR adds a grid component to the UI library.
To display the form fields properly we need a grid system.
~~~js
<Grid>
<Grid.Section size={12}>
<Grid.Item size={4}>
<div style={boxStyles}>
<Input />
</div>
</Grid.Item>
<Grid.Item size={4}>
<div style={boxStyles}>
<Input />
</div>
</Grid.Item>
</Grid.Section>
<Grid.Section size={12}>
<Grid.Item size={4}>
<div style={boxStyles}>
<Input />
</div>
</Grid.Item>
<Grid.Item size={4}>
<div style={boxStyles}>
<Input />
</div>
</Grid.Item>
<Grid.Item size={4}>
<div style={boxStyles}>
<Input />
</div>
</Grid.Item>
</Grid.Section> …
> added grid component

- src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yml
Starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0
| Q | A
| --- | ---
| Fixed tickets | fixes N/A
| Related issues/PRs | N/A
A deprecation fix
Because without fixing deprecations things will break in in newer symfony releases.
Not quoting the scalar "%sulu_media.format_cache.media_proxy_path%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0
> Fixed deprecation: starting with "%" in yml file

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds a history function to the router. It therefore keeps an object, which keeps track of the previous routes to which have been navigated. Then there is the `restore` function on the router, which allows to restore these old attributes and queries, which are merged with the additional passed parameters.
Because this way we can implement the back button correctly. All the parameters like for pagination will be taken from the old storage.
~~~javascript
router.restore('page', {uuid: '123'}, {locale: 'de'});
~~~
> Restore routes instead of navigate when clicking back button

- flow-typed/npm/jest_v21.x.x.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/MetadataStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/MetadataStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MetadataStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MetadataStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/ResourceMetadataStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/tests/ResourceMetadataStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR makes it possible to load the form using the metadata from the `ResourceMetadataStore` instead of being hardcoded in the `Form` view.
Because we want to load different forms.
> build form using metadata

- src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php
- src/Sulu/Bundle/AdminBundle/Admin/Routing/Route.php
- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/AdminPoolTest.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
| Q | A
| --- | ---
| Related issues/PRs | #3549 
This PR merges the options of the routes from the `Admin` with the options from the parent route. 
This will enable e.g. #3549 to remove the `locales` from the `sulu_snippet.form.detail` route, because it will be taken from `sulu_snippet.form`.
> Merge options of routes with parent options

- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
- src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
- src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
| Q | A
| --- | ---
| Fixed tickets | parts of #3548 
This PR implements a form for the contacts, because contacts are not translated. So this complements #3489.
Because we need locale-less forms anyway, and there are some obstacles for implementing them. So we are doing this quite early.
> build locale-less form for contact

- src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
- src/Sulu/Component/Rest/ListBuilder/AbstractListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
- src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineBetweenExpression.php
- src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineNotExpression.php
- src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineWhereExpression.php
- src/Sulu/Component/Rest/ListBuilder/ListBuilderInterface.php
- src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Expression/Doctrine/DoctrineNotExpressionTest.php
| Q | A
| --- | ---
Add excluded ids parameter to media api.
To show only unselected items in the media selection.
`/api/media?locale=en&excluded-ids=1,2,3`
> Add excluded ids parameter to media api

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss
| Q | A
| --- | ---
Reset button round corners.
Chrome 62 on OSX has a border radius of 4px.
> Chrome: Fixed bug with Chrom in Version 62

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php
- src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php
Fixed sulu_content_load throwing exception when reference was deleted
| Q | A
| --- | ---
| Fixed tickets | fixes #3050 
This fixes #3050. When sulu_content_load is used with a non-existing guid, it just returns null instead of throwing an exception (which is not catchable and breaks the page)
You are not able to catch exceptions in twig. This breaks the page when a referenced node is deleted.
~~~twig
{% set content = sulu_content_load(null) %}
{# content is now null #}
{% set content = sulu_content_load('not-existing-guid') %}
{# content is now null #}
~~~
Would be nice if this could be also released in the 1.4.x branch as we have existing installations and no resources to upgrade them to 1.6.x at …
> Fixed sulu_content_load throwing exception when reference was deleted

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3579
| Related issues/PRs | replaces https://github.com/sulu/sulu/pull/3591
This PR allows to open articles in different formats and create templates with ending `.*.twig`.
> Fixed bug with json routes for route-bundle

- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/RatioNormalizer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | merge after #3638 
This PR disposes the interceptor of the `DatagridStore` when a new loading strategy was chosen.
Because reseting the page is not intended on the table adapter, but it happens if the media card adapter was chosen first, then to the table adapter is switched, and the locale is changed afterwards.
> fix page reset when locale is changed in table

- src/Sulu/Bundle/PreviewBundle/Command/CacheClearCommand.php
| Q | A
| --- | ---
| Related issues/PRs | #3664
The preview cache will be cleared before the admin cache.
Because with Symfony 3.4 it doesn't work the other way round anymore.
> fix cache clear command for preview

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/Build/CacheBuilder.php
- src/Sulu/Bundle/CoreBundle/Resources/config/build.xml
- src/Sulu/Component/Media/SystemCollections/SystemCollectionBuilder.php
| Q | A
| --- | ---
Reintroduce cache builder. And skip the cache clear for symfony >= 3.4.0
It was removed in https://github.com/sulu/sulu/pull/3671/files but it should just be deprecated and only be removed in develop branch. For bc promise we introduce this service. To avoid crashes with e.g. old article bundle versions.
> Reintroduce cache builder for bc promise

- .travis.yml
- CHANGELOG.md
- bin/runtests
- composer.json
| Q | A
| --- | ---
| Related issues/PRs | #3694
This PR keeps version 2.5 of doctrine.
The fix in  #3694 is a BC break, and even with the fix there it is not working, because there seem to be some doctrine internal issues (the purger calls a `doctrine/common` method, which does not exist anymore).
> keep doctrine 2.5

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
- src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
| Q | A
| --- | ---
This PR adds a check for empty request-format.
If you call a URI with dot ending `example.com/test.` symfony request returns empty request-format which lead into a `strpos` warning.
> Added check for empty request format

- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/AutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/Suggestion.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/autoComplete.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/suggestion.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/AutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/Suggestion.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/__snapshots__/AutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/__snapshots__/Suggestion.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/tests/Backdrop.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Loader/tests/__snapshots__/Loader.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/popover.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Button.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/button.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Button.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Dropdown.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Select.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | #3508
This PR contains an AutoComplete component.
We need an AutoComplete
~~~js
<AutoComplete
placeholder="Enter something fun..."
value={state.value}
threshold={1}
inputIcon="search"
noSuggestionsMessage="Nothing found..."
onChange={handleChange}>
{
state.suggestions.map((suggestion, index) => {
return (
<Suggestion
key={index}
icon="ticket"
value={suggestion} />
);
})
}
</AutoComplete>
~~~
> Created AutoComplete component without Tagging

- package.json
| Q | A
| --- | ---
This PR updates the ` babel-eslint`  package
Because there was a bug with older versions, also see https://github.com/eslint/eslint/issues/9767
> update eslint because of breaking bug

- .travis.yml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/TemplateControllerTest.php
- src/Sulu/Bundle/CoreBundle/Entity/ApiEntity.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Collection/CollectionManagerTest.php
- src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
- src/Sulu/Component/Webspace/Webspace.php
| Q | A
| --- | ---
This PR makes sure the `Webspace::segments`  variable is an array from the very beginning.
Because starting with PHP 7.2 the ` count`  method will fail on this variable.
See https://wiki.php.net/rfc/counting_non_countables
> Make Sulu compatible with PHP 7.2

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader11.php
- src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image/formats/version10.xml
- src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image/formats/version11.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoader10Test.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoader11Test.php
| Q | A
| --- | ---
| Related issues/PRs |
This PR fixes loading of XML file if you set the retina flag to true.
Because it always set the retina flag to false, instead of using the value from the XML.
> Fix retina flag in XmlFormatLoader11 & add tests for retina flag

- CHANGELOG.md
- src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
- src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php
| Q | A
| --- | ---
Category API: Fix bug when search is not working when the rootKey parameter is provided.
Because the search is not working
> Category API: Fix bug when searching with rootKey parameter

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php
- src/Sulu/Bundle/RouteBundle/Entity/RouteRepository.php
- src/Sulu/Bundle/RouteBundle/Entity/RouteRepositoryInterface.php
| Q | A
| --- | ---
RouteRepository: Added method `findAllByEntity`
Get all routes inclusive history.
~~~php
$routes = $this->routeRepository->findAllByEntity(get_class($object), $object->getRoute()->getEntityId());
~~~
> RouteRepository: Added method findAllByEntity

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/EventListener/RedirectExceptionSubscriber.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RedirectExceptionSubscriberTest.php
| Q | A
| --- | ---
This PR extends the trim for trailing slashes and to allow trailing slashes for homepage.
> Fixed redirect listener to allow trailing slashes for homepage

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Api/Media.php
- src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
- src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3719 
This PR fixes an error in download when the filename contains a wrong extension.
> Added extension-guesser to fix wrong extensions on download

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
| Q | A
| --- | ---
This PR fixes the field-descriptor loading for extended contacts.
If you extend the contact and want to add field-descriptors.
> Fixed class parameter to load field-descriptor

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Teaser/ContentTeaserProvider.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Teaser/ContentTeaserProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3434
This PR add the locale to the content-teaser query.
> Added locale to content-teaser query

- CHANGELOG.md
- src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3722
This PR set a proper default-locale for document-manager.
> Set proper default locale for document-manager

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
- src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php
- src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3732, fixes #3382
This PR fixes silent fail for sitemap generation.
> Added exception when default_host is needed for sitemap generation

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Export/WebspaceExportTest.php
- src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Import/SnippetImportTest.php
- src/Sulu/Component/Content/Export/WebspaceExport.php
- src/Sulu/Component/Content/Import/WebspaceImport.php
- src/Sulu/Component/Content/Import/WebspaceImportInterface.php
- src/Sulu/Component/Export/Export.php
- src/Sulu/Component/Import/Import.php
- src/Sulu/Component/Snippet/Export/SnippetExport.php
- src/Sulu/Component/Snippet/Export/SnippetExportInterface.php
- src/Sulu/Component/Snippet/Import/SnippetImport.php
- src/Sulu/Component/Snippet/Import/SnippetImportInterface.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3301 
This PR cleans-up the Import/Export component.
The missing uses/properties leads into an error when import/export blocks.
> Cleand-up xliff import/export component

- .travis.yml
- UPGRADE.md
- bin/runtests
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/Category.orm.xml
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/Keyword.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/BaseCollection.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/CollectionMeta.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/CollectionType.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionMeta.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FormatOptions.orm.xml
- src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/MediaType.orm.xml
- src/Sulu/Bundle/RouteBundle/Resources/config/doctrine/BaseRoute.orm.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/AccessControl.orm.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseUser.orm.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Permission.orm.xml
- src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/RoleSetting.orm.xml
- src/Sulu/Bundle/TagBundle/Resources/config/doctrine/Tag.orm.xml
- src/Sulu/Bundle/TestBundle/Resources/dist/parameters.yml.dist
- src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml
- src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Domain.orm.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/jackalope/jackalope-doctrine-dbal/pull/353
Decrease all indexed fields length to 191.
To support utf8mb4 the max index length on default innodb is 191. https://dev.mysql.com/doc/refman/5.6/en/charset-unicode-conversion.html
Testing this issue on different version of mysql different changes need to be done:
For example travis uses 5.6.33 there you only need to decrease indexes which are unique.
On my local installation 5.6.21 there you also need to decrease all indexed fields e.g. `FileVersion:mimeType`. So I did go the way to support also the older version of mysql with utf8mb4.
~~~php
doctrine:
dbal:
charset: utf8mb4 …
> Support utf8mb4

- .eslintrc.json
- package.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/yannickcr/eslint-plugin-react/issues/1396
This PR forbids to write whitespaces before the `>` character in opening tags.
Because we don't want that :see_no_evil: 
```javascript
// not allowed
<header >Header</header>
// write instead
<header>Header</header>
```
> update rule for spaces in JSX tags

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/FormatLoader/schema/formats/formats-1.0.xsd
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/BlurTransformation.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/GammaTransformation.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/GrayscaleTransformation.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/NegativeTransformation.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/PasteTransformation.php
- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/SharpenTransformation.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/BlurTransformationTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/GammaTransformationTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/GrayscaleTransformationTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/NegativeTransformationTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/PasteTransformationTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/SharpenTransformationTest.php
| Q | A
| --- | ---
Add the imagine effects as sulu image transformers.
Old format:
```xml
<format>
<name>400x400-effect</name>
<commands>
<command>
<action>scale</action>
<parameters>
<parameter name="x">400</parameter>
<parameter name="y">400</parameter>
</parameters>
</command>
<command>
<action>blur</action>
<parameters>
<parameter name="sigma">6</parameter>
</parameters>
</command>
</commands>
</format>
```
New format:
```xml
<format key="400x400-effect">
<meta>
<title lang="en">400x400</title>
</meta>
<scale x="400" y="400"/>
<transformations>
<transformation>
<effect>blur</effect>
<parameters>
<parameter name="sigma">6</parameter>
</parameters>
</transformation>
</transformations>
</format> …
```
> Added effect transformation for images

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss
| Q | A
| --- | ---
Add `line-height: normal` to label.
The used font leads to errors.
> Fix bug with label in Switch component

- src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/PasteTransformation.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/PasteTransformationTest.php
| Q | A
| --- | ---
Use image adapter from the service definition.
Currently it don't use the defined service for the paste adapter.
> Use correct imagine adapter for paste transformation

- src/Sulu/Bundle/AdminBundle/Resources/js/services/index.js
- src/Sulu/Bundle/ContentBundle/Resources/js/stores/WebspaceStore/WebspaceStore.js
- src/Sulu/Bundle/ContentBundle/Resources/js/stores/WebspaceStore/index.js
- src/Sulu/Bundle/ContentBundle/Resources/js/stores/WebspaceStore/tests/WebspaceStore.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/stores/WebspaceStore/types.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
| Q | A
| --- | ---
`WebspaceOverview`: Load webspaces from server.
Used is the `WebspaceStore`.
> WebspaceOverview: Load webspaces from server

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/ContentBundle/Command/WorkspaceImportCommand.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/phpcr/phpcr-utils
This PR overwrites the command `doctrine:phpcr:workspace:import` and set the default of `uuid-behavior` to `throw`.
This disables the regeneration of `uuid` while import from xml.
> Overwrite 'doctrine:phpcr:workspace:import' set default to throw

- CHANGELOG.md
- src/Sulu/Component/Webspace/Manager/Dumper/WebspaceCollectionDumper.php
- src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
| Q | A
| --- | ---
It uses the twig [is iterable](https://twig.symfony.com/doc/1.x/tests/iterable.html) instead of a custom is_array twig extension.
Better to use a twig core functionality instead of a custom function. Also did got on an older installation but can't reproduce it why this did happens once:
```
[Symfony\Component\Debug\Exception\ContextErrorException]
Catchable Fatal Error: Argument 1 passed to Twig_Function::__construct() must be an instance of string, string given, called in 
vendor/sulu/sulu/src/Sulu/Component/Webspace/Manager/Dumper/WebspaceCollectionDumper.php on line 26 and defined
```
> Replace is_array with is iterable in twig

- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlock.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/SortableBlock.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/Button.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
| Q | A
| --- | ---
This PR adds the possibility to have a min and max restriction on the blocks. It will also not be possible anymore to click add or remove if the max resp. min restriction is already met.
Because we want to be able to restrict the content manager in that regard.
> Add minOccurs and maxOccurs to Blocks

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
The removal of the extension of formats should only take place when
the format is present as extension in the url. (#3755)
| Q | A
| --- | ---
| Fixed tickets | fixes #3755
| Related issues/PRs | #3755
When using json as request format by default, without using .json extensions, the RouteProvider cut off the last character of the url, resulting in a 404.
In this PR, the stripping of the extension is only attempted if the format extension is present.
> Correct extension stripping

- composer.json
| Q | A
| --- | ---
This PR removes unnecessary `symfony/web-server-bundle`.
> Remove web-server-bundle from dependencies

- CHANGELOG.md
- src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.0.xsd
- src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.1.xsd
- src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader10Test.php
- src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
- tests/Resources/DataFixtures/Webspace/valid/sulu.io_deprecatedDynamicOrder.xml
- tests/Resources/DataFixtures/Webspace/valid/sulu.io_dynamicOrder.xml
| Q | A
| --- | ---
| Fixed tickets | fixes sulu/sulu-docs#360
It allow dynamic order of items in the webspace, template and format xmls.
For beginners a fix order can be a pitfall. 
See sulu/sulu-docs#360 issue.
> Allow dynamic order of elements in webspace xmls

- CHANGELOG.md
- src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/smart_content.xml
- src/Sulu/Bundle/HttpCacheBundle/Resources/config/event-subscribers.xml
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
- src/Sulu/Bundle/TagBundle/Resources/config/services.xml
- src/Sulu/Component/HttpCache/EventSubscriber/InvalidationSubscriber.php
- src/Sulu/Component/HttpCache/Handler/AggregateHandler.php
- src/Sulu/Component/HttpCache/Handler/TagsHandler.php
- src/Sulu/Component/HttpCache/HandlerInvalidateReferenceInterface.php
- src/Sulu/Component/HttpCache/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
- src/Sulu/Component/HttpCache/Tests/Unit/Handler/TagsHandlerTest.php
- src/Sulu/Component/SmartContent/ContentType.php
- src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
| Q | A
| --- | ---
This PR uses reference-store of categories and tags to invalidate pages where a smart-content uses tags/categories in the query.
> Improved cache-invalidation for categories/tags in excerpt tab

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Websocket/Sulu/Bundle/PreviewBundle/Tests/Unit/Websocket/PreviewMessageHandlerTest.php
- src/Sulu/Bundle/PreviewBundle/Websocket/PreviewMessageHandler.php
| Q | A
| --- | ---
This PR fixes the token not found exception if the start fails because of rendering error.
Rendering error can be:
* Twig-Exception
* Webspace not found for requested data (webspace_key, locale, ...)
> Set context data (token, locale) before render can fail

- UPGRADE.md
- composer.json
| Q | A
| --- | ---
This PR removes the dependency of `pulse00/ffmpeg-bundle` and add a suggestion note for it.
> Removed ffmpeg dependency

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Component/HttpCache/EventSubscriber/UpdateResponseSubscriber.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3792
| Related issues/PRs | #3792
This PR increases the priority of `UpdateResponseSubscriber` to set the cache-headers before symfony does it.
See issue https://github.com/sulu/sulu/issues/3792
> Increased priority of update-response-subscriber

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Content/Types/ContactSelectionContentType.php
- src/Sulu/Bundle/ContactBundle/EventListener/CacheInvalidationListener.php
- src/Sulu/Bundle/ContactBundle/Resources/config/content.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
- src/Sulu/Bundle/ContactBundle/Tests/Unit/CacheInvalidationListenerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactSelectionContentTypeTest.php
- src/Sulu/Bundle/ContentBundle/Teaser/TeaserContentType.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Teaser/TeaserContentTypeTest.php
- src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
- src/Sulu/Bundle/MediaBundle/EventListener/CacheInvalidationListener.php
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/MediaBundle/Tests/Unit/EventListener/CacheInvalidationListenerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
- src/Sulu/Component/Contact/SmartContent/AccountDataProvider.php
- src/Sulu/Component/Contact/SmartContent/ContactDataProvider.php
- src/Sulu/Component/Contact/Tests/Unit/SmartContent/AccountDataProviderTest.php
- src/Sulu/Component/Contact/Tests/Unit/SmartContent/ContactDataProviderTest.php
- src/Sulu/Component/Content/Tests/Unit/SmartContent/Orm/BaseDataProviderTest.php
- src/Sulu/Component/HttpCache/Handler/TagsHandler.php
- src/Sulu/Component/HttpCache/Tests/Unit/Handler/TagsHandlerTest.php
- src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
- src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
- src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
| Q | A
| --- | ---
This PR add the reference-store to media/contact/account content-types to improve cache-invalidation.
> Improved cache-invalidation for media/contact/account

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3404
Check if current user is sulu user in media manager.
When using the form bundle on the website and submitting medias and the current user is a none sulu user it will fail.
> Check if current user is sulu user for access control check

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Command/ValidateWebspacesCommand.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ValidateWebspacesCommandTest.php
- src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
- src/Sulu/Component/Content/Metadata/Loader/XmlLoader.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLegacyLoaderTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
- src/Sulu/Component/Webspace/Webspace.php
- tests/Resources/DataFixtures/Page/template_load_internal.xml
- tests/Resources/DataFixtures/Page/template_meta_params.xml
| Q | A
| --- | ---
| Documentation | https://github.com/sulu/sulu-docs/pull/364
Fix structure internal flag as it is readed as boolean not string.
Also add better error message when structure metadata could not be found.
Also a command to validate the webspaces was added. It checks if the xml exists, view exists and controller exists.
Currently the excerpt.xml and other internal structure the internal flag is not correctly read and is false instead of true.
Currently error message was `Calling getProperties() on null`.
There was currently no way to validate the webspace configuration is ok.
Exception: Change default template of webspace to a none exist and run sulu:build dev.
Command: …
> Fix structure internal flag and add webspace validate command

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/block.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/properties.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/section.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/single.html.twig
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.10
This is the status with this PR:
1. Create properties before the first section (space before this section is not the same as for others)
2. Create a block inside a section (space seems to big)
> Fix spacing between rows and section in content template generation

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/block.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/properties.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/section.html.twig
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/macros/single.html.twig
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3351#event-1142007764
Fix spacing between rows and section in content template generation
See https://github.com/sulu/sulu/pull/3351
> Fix spacing between rows and section in content template generation for 1.6

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Actions.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
| Q | A
| --- | ---
This PR adds `type="button"` to buttons, in order to avoid strange behavior when hitting the enter key in a form.
This fixes the issue with added blocks and opened selects in a form, when the enter button is pressed.
> fix strange behaviours on enter keypress in form

- CHANGELOG.md
- appveyor.yml
- composer.json
- src/Sulu/Component/Cache/Tests/Unit/Cache/DataCacheTest.php
| Q | A
| --- | ---
Fix requirement for sensio distribution bundle and fix appveyor implementation.
The script handlers need at least version 5.0.6 as there was a BC Break in Composer where CommandEvent was renamed to Event. https://github.com/sensiolabs/SensioDistributionBundle/compare/v5.0.5...v5.0.6
Appveyor configuration inspired by: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/.appveyor.yml
> fix compatibility on lowest and fix appveyor

- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/FlatStructureStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
| Fixed tickets | fixes #3743
This PR removes the permanent recreation of the stores in the `MediaOverview` and `MediaSelection` components.
Because we have fixed our routing issue in #3801, but the fix does break the weird behavior with the recreation of these components.
> Remove recreation of MediaStores in MediaOverview and MediaSelection

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/PageForm.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR fixes a bug, which caused some wrong update on render. The problem was that the `unbind` calls in `componentWillUnmount` were called after the `bind` calls of `componentWillMount`. That made the observables be updated on the `bind` calls and already called all reactions.
Because in quite a lot situation reactions were run, where they shouldn't. E.g. switching from the Snippet List to e.g. Contacts led to two requests, whereby one was sent to the "old" snippet endpoint with a locale of `undefined`. That should definitely not happen, and is fixed in this PR.
The `unbind` method of the `Router` was …
> fix superfluous updates on binded observable on the router

- CHANGELOG.md
- composer.json
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu-document-manager/pull/117  https://github.com/sulu/sulu-document-manager/pull/118 https://github.com/sulu/sulu-document-manager/pull/119
This PR add a flush to node-controller between `persist` and `publish` call.
This is needed because of following scenario:
1. Imagine following content tree:
* Page 1
* Page 1.1
2. Page one has an internal link (content-type) to page 1.1
3. Rename page 1 and click save and publish
The publish fails because the renaming of the node won't be synced to the repository and the following exception will be thrown.
```
Path not found (parent node …
```
> Fixed rename and publish exception if page has link to a child

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/checkbox.html.twig
| Q | A
| --- | ---
| Fixed tickets | fixes #3172 
Use id instead of property name for reference as instance name.
Avoid conflicts between toggler and enable the save button when a toggler is changed inside a block.
<details>
<summary>Example</summary>
```php
<property name="test-toggler2" type="checkbox">
<meta>
<title lang="de">Test Toggler</title>
<title lang="en">Test Toggler</title>
</meta>
<params>
<param name="type" value="toggler"/>
</params>
</property>
<block name="blockTest" default-type="test-type" minOccurs="1">
<types>
<type name="test-type">
<properties>
<property name="test-checkbox" type="checkbox">
<meta>
<title lang="de">Test Checkbox</title>
<title lang="en">Test …
```
> Enable save button when toggler is used in block

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Dropdown.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Dropdown.test.js
| Q | A
| --- | ---
Iterate over options to check if all options are disabled.
When yes, disable also the button itself.
When no active options is available, button is still clickable at the moment.
> Toolbar: Disable dropdown when all options are disabled

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
Explain the contents of the PR.
This PR makes the `DatagridStore` remember the exact objects instead of only the IDs. This is required for #3811, because it allows to use the `DatagridStore` to reuse this logic instead of implementing the same stuff as in the `MediaSelection` again.
`DatagridStore.selections` contains objects instead of IDs now, and `DatagridStore.selectionIds` has been introduced to still get the IDs.
> remember selected objects instead of ids

- composer.json
| Q | A
| --- | ---
Require symfony/web-link component.
The symfony/web-link is used for the symfony.
> Require symfony web-link component as needed

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/resourceLocator.scss
| Q | A
| --- | ---
Add white-space no wrap to the fixed part of the resource locator.
Fix that the resource locator fixed part is wrapped.
> Fix styling of resource locator field type

- .travis.yml
- CHANGELOG.md
| Q | A
| --- | ---
Add jackrabbit dependency in travis without updating dependencies.
To run composer with correct composer flags.
> Avoid duplicated run of composer update

- src/Sulu/Bundle/ContentBundle/Command/WebspaceImportCommand.php
- src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php
- src/Sulu/Bundle/ContentBundle/Resources/config/export.xml
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Import/WebspaceImportTest.php
- src/Sulu/Bundle/ContentBundle/Tests/app/Resources/import/export_ru.xliff.dist
- src/Sulu/Component/Content/Exception/ResourceLocatorGeneratorException.php
- src/Sulu/Component/Content/Import/WebspaceImport.php
- src/Sulu/Component/Content/Import/WebspaceImportInterface.php
- src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php
- src/Sulu/Component/Import/Manager/ImportManager.php
| Q | A
| --- | ---
When no URL can be generated use the one from the import file.
Our URL generator has problems with utf8 signs.
In this case when no url is generated, us the one from the import file.
> WebspaceImport: Bugfix when no url is given

- CHANGELOG.md
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/document.xml
- src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
- src/Sulu/Component/CustomUrl/Repository/CustomUrlRepository.php
- src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php
| Q | A
| --- | ---
This PR adds the base-domains to query.
Custom-URLs created for another environment can break the UI and will not work.
> Added base-domains to query for custom-urls

- src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
| Q | A
| --- | ---
This PR adds the name of the bundle as sections to admin config.
This will be needed to add other bundle configuration.
> Added bundle name to config response

- CHANGELOG.md
- src/Sulu/Bundle/CustomUrlBundle/Admin/WebspaceContentNavigationProvider.php
- src/Sulu/Bundle/CustomUrlBundle/Resources/config/admin.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #3053
Check if custom url are configured for the given webspace else avoid rendering of custom url tab.
The custom url tab will only make sense when configured for the webspace.
1. Create a webspace without custom url (e.g. sulu-minimal)
> Show custom url tab only when configured

- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3840 
This PR adds the mapping for `authored` to `BasePageDocument` metadata.
The index has to be rebuild.
> Added authored field to base-page-document index

- CHANGELOG.md
- src/Sulu/Component/Content/Mapper/ContentMapper.php
| Q | A
| --- | ---
This PR fixes `sulu_content_load` when an unpublished page should be loaded.
The document-manager returns a `UnknownDocument` which leads into an exception in the `StructureBridge`.
> Added check for unknown-document for sulu_content_load

- src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
| Q | A
| --- | ---
This PR fixes the generation of blocks.
Because the blocks were not correctly parsed in the backend.
> fix generation of blocks for form on server

- .flowconfig
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/FlatStructureStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/FullLoadingStrategy.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/InfiniteLoadingStrategy.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/PaginatedLoadingStrategy.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
| Q | A
| --- | ---
Move find from store to the structure strategies to allow custom findById implementations.
Find need a custom implementation for tree strategy to recursive search the tree for the element. Needed for Internal Links and Tree Component (https://github.com/sulu/sulu/pull/3582)
~~~php
treeStrategy.findBy(identifier);
flatStrategy.findBy(identifier);
~~~
> Implement custom find method for structure strategy

- appveyor.yml
| Q | A
| --- | ---
This PR removes the jackrabbit build from appveyor.
We only have one concurrent build on appveyor, and having multiple builds there slows us down. Also, jackrabbit is already tested on the linux build, and I think that is enough.
> remove jackrabbit build from appveyor

- webpack.config.js
| Q | A
| --- | ---
| Related issues/PRs | sulu/sulu-minimal#90
The folder for the build is renamed.
To avoid that somebody accidentially puts some own files into the build folder and it gets deleted with the new script in sulu/sulu-minimal#90.
> adjust folder for admin build

- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
This PR clears both stores of the `MediaOverview` when using the back button.
This fixes the bug which duplicates media entries in the `MediaOverview` when using the back button.
> Clear MediaOverview stores when using back button

- src/Sulu/Bundle/ContentBundle/ResourceMetadata/StructureResourceMetadataProvider.php
- src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
- src/Sulu/Bundle/ContentBundle/Tests/Unit/ResourceMetadata/StructureResourceMetadataProviderTest.php
- src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
- src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
| Q | A
| --- | ---
Moved StructureResourceMetadataProvider from Core to Content Bundle.
CoreBundle shouldn't have a dependency to AdminBundle, because on the website the AdminBundle isn't loaded at all.
> Bugfix: Moved StructureResourceMetadataProvider from Core to Content

- src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
| Q | A
| --- | ---
Only register the `StructureResourceMetadataProvider` service in Admin kernel.
It breaks the whole website.
> StructureResourceMetadataProvider only in Admin kernel

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Teaser/ContentTeaserProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3803
This PR extracts some functions to improve overriding `ContentTeaserProvider`.
> Improved developer-experience when overriding content-teaser-provider

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
| Q | A
| --- | ---
Throw an exception for the `Form` view if it is not embedded in a `ResourceTabs` component.
Because that makes it easier for the developer to find a misconfigured form.
> Throw a meaningful error when a form is not embedded in a ResourceTabs

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ItemButton.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Item.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/Assignment.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/DatagridOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/Assignment.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/DatagridOverlay.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Assignment.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Assignment.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
| Q | A
| --- | ---
| Related issues/PRs | #3855
This PR allows to disable certain items in the datagrid by passing the ids to disable in the `disabledIds` prop of the Datagrid.
Because in #3855 we introduced the internal links field type, but you can still select the page you are currently editing to itself, which the backend does not allow.
~~~jsx
<Datagrid disabledIds={[1, 4]} />
~~~
> Disable items by ids in datagrid

- UPGRADE.md
- src/Sulu/Bundle/ContactBundle/Entity/Contact.php
| Q | A
| --- | ---
| Fixed tickets | fixes #3221 
It removes the temporily position property of the contact.
It was shown as null when the contact has a position #3221 as it is also not saved to the database it doesnt make sense here.
Removes the `setCurrentPosition` from contact entity.
> Remove temp position property on contact

- .travis.yml
- CHANGELOG.md
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/DependencyInjection/Configuration.php
| Q | A
| --- | ---
| BC breaks? | yes see UPGRADE
This PR enhances the default title length for seo.
> Enhanced the default title length for seo

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
- src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
- src/Sulu/Bundle/PreviewBundle/Security/PreviewVoter.php
| Q | A
| --- | ---
| BC breaks? | no (?)
This PR adds a voter for the `PreviewKernel`, which allows all requests coming from the PreviewKernel
The preview uses no URI so the access control in `app/config/website/security.yml` wont work as expected. This could lead to access denied exceptions while the editor should be able to see the page he/she is trying to create / edit
> Preview voter

- src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
| Q | A
| --- | ---
Bugfix in `ResourceMetadataMapper` when block is in section.
Fronted crashes when it's not valid.
> Fix bug in resourcemetadatamapper when block is in section

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Api/Media.php
- src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
- src/Sulu/Bundle/MediaBundle/Entity/File.php
- src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
| Q | A
| --- | ---
Add a canonical tag to the media to link to the new version and set media to noindex.
That old media are not longer indexed by search engines.
> Set media old versioning canonical and noindex headers

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
| Q | A
| --- | ---
This PR replaces links with `#` in preview.
> Replaced links in preview with '#'

- CHANGELOG.md
- src/Sulu/Component/Content/Repository/Content.php
- src/Sulu/Component/Content/Repository/ContentRepository.php
- src/Sulu/Component/Content/Tests/Unit/Repository/ContentRepositoryTest.php
| Q | A
| --- | ---
This PR fixes an issue for following scenario:
When clicking on the parent-page the query fails because the child has no structure.
> Fixed content-query when a child is broken

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Api/ContactLocale.php
| Q | A
| --- | ---
Fix api ContactLocale constructor typehint.
Currently the false class is set in the contactLocale constructor.
> Fix api ContactLocale constructor typehint

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig
| Q | A
| --- | ---
Fix profiler for none sulu routes.
Currently the profiler fails with the following message on none sulu routes:
> Impossible to access an attribute ("id") on a null variable.
> Fix profiler for none sulu routes

- composer.json
| Q | A
| --- | ---
Add [branch alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias) for 2.0-dev. Inspired by [symfony](https://github.com/symfony/symfony/blob/master/composer.json#L134-L136)
To allow bundles require sulu on 2.0 dev.
1. set stability on dev
2. require sulu 2.0
> Add branch alias for 2.0-dev

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
| Q | A
| --- | ---
This PR fixes a problem which was introduced by #3899. It replaces the `href` of style tags and destroys website styling in preview.
> Fixed preview style-link

- UPGRADE.md
| Q | A
| --- | ---
Add upgrade for httpcache class.
This class is common used for the `HEADER_REVERSE_PROXY_TTL` constant.
Before:
```php
HttpCache::HEADER_REVERSE_PROXY_TTL
```
after
```php
AbstractHttpCache::HEADER_REVERSE_PROXY_TTL
```
> Add upgrade for HttpCache class

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/registries/RouteRegistry.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/registries/RouteRegistry.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
| Q | A
| --- | ---
This PR throws an error if the router is passed a route which does not exist. Before that something weird happened, and it is not directly obvious what the problem actually is.
This way we have a better DX.
Instead of returning `undefined` when a non-existing route is passed it will throw an error. In most cases it does not work anyway afterwards, so this should not be a big deal.
> Throw a proper error if the route passed to the router does not exist

- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
This PR changes the priority of `RouterListener` which set the context attributes `prefix` and `host` - they are used to generate routes on the website.
When an `AuthenticationException` is thrown on the website the login route cannot be generated because these attributes are not set. The `RouterListener` depends only on the `_sulu` request-attribute and this will be set with the priority of 32.
> Fixed priority of request-context-listener

- src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
Originated by http://php.net/manual/de/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
| Q | A
| --- | ---
| Fixed tickets | fixes #3925
Fix for php warning prevents users to add new contacts (without bankaccount) (see #3925)
> Fixed: Fix PHP 7.2 issue prevents adding new contacts (#3925)

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdown.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js
| Q | A
| --- | ---
This PR makes the `ToolbarDropdown` render method not an arrow function. In addition to that I renamed the `handleOptionClick` method to just `handleClick`, because (I think) it is not handling a click on the option but on the dropdown itself.
The `render` method made problems in combination with enzyme. The component was not updated in enzyme, since a babel update. Seems like arrow functions are transpiled differently now and in a way that enzyme can't handle them.
> Fix test after npm update

- CHANGELOG.md
- src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapContentQueryBuilder.php
- src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php
| Q | A
| --- | ---
| Fixed tickets | (none found)
| Related issues/PRs | (none found)
| Documentation PR | not applicable
This PR is a Bugfix in the WebsiteBundle
This PR fixes a small bug in the `SitemapContentQueryBuilder` when creating the sitemaps. When querying for the documents to load it does not filter out the documents with the `hideInSitemap`-flag unless the flag is added in the "de" locale.
This is my first contribution to Sulu, I hope I followed the contributing guidelines correctly - otherwise please tell me what I need to fix. I wasn't sure if I had to create an issue first.
> Fix: the sitemap query builder only considers the "de" hiddenInSitemap flag.

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Checkbox.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Checkbox.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
| Q | A
| --- | ---
This PR adds a new FieldType for the checkbox corresponding to the one in the Aura UI. It can show a checkbox or a toggler, based on the `schemaOptions` it gets passed.
Because we need checkboxes in forms.
> Add FieldType for checkbox

- .eslintrc.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/PopoverPositioner.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/RatioNormalizer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/RectangleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/RoundingNormalizer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/withSidebar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
- styleguide.config.js
| Q | A
| --- | ---
This eslint rule checks if it would be possible to use `const` instead of `let` or `var`.
Because I start sweating when I see `let` :wink: And it would be less work for the reviewer and reviewee when submitting PRs.
> add prefer-const rule to eslint

- CHANGELOG.md
- src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
This PR fixes the lat/long contact-form with empty lat/long.
Newer MySQL versions dont allow empty strings as null value.
> Fixed empty latitude and longitude

- CHANGELOG.md
- src/Sulu/Bundle/RouteBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/RouteBundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
- src/Sulu/Bundle/RouteBundle/Tests/app/Resources/test_config.yml
| Q | A
| --- | ---
By default symfony converts dashes to underline.
Example:
```yaml
sulu_route:
mappings:
Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
generator: template
options:
recipe-gallery: "/galerie/{object.getTitle()}"
```
Currently `recipe-gallery` will be converted to `recipe_gallery` which does not match with the template key.
http://symfony.com/doc/current/components/config/definition.html#normalization
> Fix sulu route options with dash

- src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Item.php
- src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_sections.xml
- src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
- src/Sulu/Component/Content/Metadata/SectionMetadata.php
| Q | A
| --- | ---
This PR fixes the missing colspans in form sections.
Because we would like to use sections with colspans in the account and contact form.
~~~xml
<section name="test" colspan="8">
</section>
~~~
> apply colspan from sections to form

- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Navigation.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/Assignment.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/DatagridOverlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/withSidebar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/withSidebar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/PageForm.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionFormOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
| Q | A
| --- | ---
This PR replaces all occurences from `componentWillMount` with `constructor`. I've tested the components I've touched, and they still seem to work as expected.
Because `componentWillMount` is deprecated, and we do not want to use deprecated code to avoid problems in the future.
There are a few more deprecated react methods, but they were not that easy to replace.
> remove react deprecations

- .gitattributes
| Q | A
| --- | ---
This PR removes the export-ignore git attribute for package.json files
The build in sulu-minimal needs it.
> Removed export-ignore attribute for package.json files

- src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Option.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
| Q | A
| --- | ---
Rename this field on the server side to match xml.
Also introduced some flow typings to find the necessary changes, and found a few bugs because of that.
Because we want to be consistent.
> rename info_text to infoText

- src/Sulu/Bundle/AdminBundle/ExpressionLanguage/ContainerExpressionLanguageProvider.php
- src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
- src/Sulu/Bundle/AdminBundle/Tests/ExpressionLanguage/ContainerExpressionLanguageProviderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_expression_param.xml
- src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
- src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
| Q | A
| --- | ---
This PR introduces the possibility to use the expression language in the template `param` xml tag using the `expr` attribute.
Because we need to find some params using services, e.g. when deciding to which collection images from the `SingleMediaUpload` should be uploaded.
see #3956
> read properties param value using expression language

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/FormInspector.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/FormInspector.test.js
| Q | A
| --- | ---
This PR adds a function `getValueByName` to build dependent field-types.
> Added function to get value for property name

- .flowconfig
- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/withContainerSize.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/AbstractTableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TreeListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js
- src/Sulu/Bundle/AdminBundle/Resources/js/index.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
| Q | A
| --- | ---
This PR updates to flow 0.71.
Because the `finally` method on promises are available there.
> update to flow 0.71

- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/blockCollection.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/Button.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/displayValue.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
| Q | A
| --- | ---
| Related issues/PRs | ...
This PR adds an optional `icon` prop to the `Button` component.
Because until now buttons with icons have always been faked by inserting a button as child, but that means that the icon always has to be styled. This way this styling is done in a central place, and therefore is consistent.
> add icon prop to Button

- .eslintrc.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/registries/RouteRegistry.test.js
- styleguide.config.js
- webpack.config.js
| Q | A
| --- | ---
This PR introduces a new eslint rule.
Because we want no wrong spaces around the colons in object literals.
> add eslint key-spacing rule

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
| Q | A
| --- | ---
Fix kernel.project_dir parameter for PreviewKernel.
Currently the preview kernel use the false project_dir it should use the WebsiteKernel project_dir which is currently not being used.
> Fix kernel.project_dir parameter for PreviewKernel

- src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaUpload.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaUpload.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/SingleMediaUpload.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/SingleMediaUpload.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
- src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/types.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
| Q | A
| --- | ---
This PR removes the need for mutliple Requests in the SingleMediaUploadStore. For that the dependency on the ResourceStore was removed, which caused this request.
Because this way it is more performant and works the same way as in #3989.
> Remove multiple requests for SingleMediaUpload

- src/Sulu/Bundle/ContactBundle/Api/Account.php
- src/Sulu/Bundle/ContactBundle/Api/Contact.php
- src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
- src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
- src/Sulu/Bundle/ContactBundle/Entity/Account.php
- src/Sulu/Bundle/ContactBundle/Entity/Contact.php
- src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/Account.xml
- src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
This PR adds a note field to both accounts and contacts.
Because we need this field and it was there before.
The `notes` field is deprecated now, and is replaced by a simple text field. This means that there is only one note per account/contact now.
> Add notes to account and contact

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/DateFieldTransformer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/TimeFieldTransformer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/DateFieldTransformer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/TimeFieldTransformer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Time.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Time.test.js
| Q | A
| --- | ---
Do not calculate date and time with timezone offset from UTC.
Bugfix of wrong calculated dates and times.
> Bugfix: Field date and time without utc calculation

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Search.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Search.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Search.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
| Q | A
| --- | ---
Set value of datagrid search correctly when it's changing from above (for example router/store).
Current search wasn't visible in the input when opening direct link.
> Bugfix: Datagrid search reload

- src/Sulu/Bundle/PersistenceBundle/Tests/Functional/EventSubscriber/ORM/UserBlameSubscriberIntegrationTest.php
- src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
- src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/UserBlameSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the user-blame subscriber which should set the changer (and creator).
This seems not work (no idea since when - master seems to work maybe since doctrine update).
> Fixed user-blame

- CHANGELOG.md
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
- src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
| Q | A
| --- | ---
| Related Issues | fixes #4016 
Load snippet not in ghost language over getAction.
To avoid a conflict when creating a snippet in another language as it exist.
> Fix conflict when saving snippet in new language

- CHANGELOG.md
- src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
- src/Sulu/Bundle/SecurityBundle/Security/SecurityConfig.php
- src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/SecurityConfigTest.php
| Q | A
| --- | ---
It check if the tokenstorage can provide a user and don't throw an error then.
Some commands like debug:container, debug:router didn't work on specific routes or services.
Example:
```
bin/adminconsole debug:router sulu_admin_v2.resources
```
> Allow user to be null for security expressions for debug

- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
| Q | A
| --- | ---
This PR fixes a bug when a resource-tab adds uses locales.
If you want to extend the account with localized content.
~~~php
public function getRoutes(): array
{
return [
(new Route('app.account.notes', '/notes', 'sulu_admin.form'))
->addOption('tabTitle', 'app.notes')
->addOption('backRoute', 'sulu_contact.accounts_datagrid')
->addOption('resourceKey', 'account_notes')
->addOption('locales', $locales)
->addAttributeDefault('locale', $locales ? $locales[0] : '')
->setParent('sulu_contact.account_edit_form'),
];
}
~~~
> Fixed bug when resource-tab set own locales

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/Number.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/tests/Number.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4003
This PR sets the empty value returned for the `Number` and `Input` fields to `undefined` instead of `null`. Since `JSON.stringify` seems to remove values from objects being `undefined` the `Requester` also has to replace `undefined` with `null` before actually sending the request.
An empty `Input` or `Number` field was not recognized as `required` anymore by JSON Schema, because `null` seems to be interpreted as a value sufficient for `required` fields.
> fix required validation for Input field

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
| Q | A
| --- | ---
| Related issues/PRs | #4002
This PR only reset the page of the datagrid when the loading strategy was already set before and changed afterwards.
Because otherwise the page will always be reset to 1, even when returning from a form where a page is initially passed to the URL. This was introduced with the refactoring in #4002.
> remove reset of page when returning from a form to the datagrid

- CHANGELOG.md
- composer.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/symfony/symfony/pull/27467
This PR fixes a regression introduced by https://github.com/symfony/symfony/pull/27467.
Because the tests should actually run :-)
> Add symfony 3.4.12 as conflict to fix caching tests

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Preview/PageRouteDefaultsProvider.php
- src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
- src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
| Q | A
| --- | ---
This PR fixes the webspace-initializer when the home document was extended.
The initializer uses the class hardcoded.
> Fixed document creation in webspace-initializer

- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
| Q | A
| --- | ---
Also translate the response from the server (null or empty string to undefined)
If empty data (null or empty string) is delivered from the server e.g. when delivering a ghost page, the form can be saved without the required checks failing.
> fix save validation if empty data is delivered from server

- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
| Q | A
| --- | ---
Fix preview host replacement for render calls.
Subrequest (e.g. twig render) are created with Request::create which will replace currently `SERVER_PROTOCOL`, `HTTP_HOST`, and [many other headers](https://github.com/symfony/symfony/blob/v3.4.11/src/Symfony/Component/HttpFoundation/Request.php#L344-L357) which are currently not set in our Preview Request. If we forward them correctly in the preview they will not be overwritten by defaults.
1. Open page in backend
2. Use render function in template to render a sulu:link on a webspace with {host}
3. without this fix localhost would be used instead of the current domain
> Fix correct url in preview

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/datagrid.scss
| Q | A
| --- | ---
This PR adds some margin after the pagination elements in the datagrid view.
Bedcause it does not look good if the pagination icons are on the very bottom of the screen with no margin.
> fix margins for pagination buttons in datagrid

- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
| Q | A
| --- | ---
This removes/optimizes the `AccountControllerTest`.
Because our tests are stalling again...
> remove unnecessary tests in AccountController

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/stores/AutoCompleteStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
- webpack.config.js
| Q | A
| --- | ---
This PR removes the `finally` calls on promises.
Because Edge does not support it yet.
> remove finally because edge does not support it yet

- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
- src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php
- src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
| Q | A
| --- | ---
This PR removes the password hash from the user api.
> Removed password-hash from user-api

- UPGRADE.md
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.xml
- src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/Keyword.orm.xml
| Q | A
| --- | ---
Fix naming of category tables and fields.
Currently the naming of the fields are auto generated and one table has interface in it and the other table has a false field name.
Manual database migration is needed as schema update will not work here.
> Fix naming of category tables and fields

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
| Q | A
| --- | ---
This PR only resets the page of the datagrid when an observable changed if the datagrid was not completely initialized yet.
When you follow these instructions the page was reset to 1, although this shouldn't be the case:
1. Open a datagrid (e.g. for snippets)
2. Search for something you end up with multiple pages of results
3. Go to the second page
4. Edit one of the entries
5. Click the back link in the form
6. The search term is still in the datagrid, but you are on the first page now
> fix reset of page in datagrid when search or sort is set initially

- CHANGELOG.md
- src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
- src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
| Q | A
| --- | ---
This PR avoids returning the same ID multiple times in the ID query of the smart content.
If a media has assigned Category A and B and a SmartContent using the `media` data provider has an or filter on Category A and B, then the ID query from the `DataProviderRepositoryTrait` returns the same media ID twice. That only matters if there is also a limit (either in the smart content overlay or using the `max_per_page` param in the template XML), because then less items will be returned in the final query.
> avoid returning the same id multiple times in filter query of smart content

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/datagrid.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
| Q | A
| --- | ---
The datagrid has now a title attribute, which can contain any JSX. The toolbar for the Datagrid (containing the adapter switch) will appear middled right next to it.
This saves some visual space.
> Move titles resp. webspace select and datagrid toolbar into the same line

- UPGRADE.md
| Q | A
| --- | ---
Add setNavigation to the upgrade.
Currently you get the following error message:
Attempted to call an undefined method named "setNavigation" of class "App/Admin/AppAdmin".
As I mostly would then search for `setNavigation` in the UPGRADE.md I add `setNavigation` to the UPGRADE.md sentence.
> Add setNavigation to the upgrade

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/publishIndicator.scss
| Q | A
| --- | ---
This PR centers the `PublishIndicator` component in the `ColumnList`.
Because we have used `display: inline-block` before on the `PublishIndicator`, the wrapping element added a few pixels on the bottom. A pure block elemnt doesn't suffer from this problem.
> Fix positioning of elements in ColumnList

- package.json
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Item.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Item.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Navigation.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
| Q | A
| --- | ---
This PR adds a few `role="button"` attributes to make navigating without the mouse easier, since these elements are now recognized as button by external tools as well.
The Vimium Plugin in Chrome didn't recognize some of the clickable areas as clickable. There is still more to do, but what is fixed here are the most common action.
> Make ColumnList, Table and Navigation more keyboard friendly

- UPGRADE.md
- src/Sulu/Bundle/CategoryBundle/Api/Category.php
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4079
This PR renames the `parent` parameter in the response of the `CategoryController` to `parentId`. This fixes the problem that a category already ends up on the toplevel after it is being saved.
Because this problem was introduced in #4079, where the renaming from `parent` to `parentId` obviously wasn't done everywhere.
The `parent` field is now called `parentId` in the `CategoryController` response.
> fix moving categories to top level after saving

- src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4091 
This PR makes sure to always have the `WebLink` component activated, since we are using it in order to use HTTP2 pushes for some of our resources.
Because that doesn't seem to be always the case, as @alexander-schranz has mentioned in [his comment of the original issue](https://github.com/sulu/sulu/issues/4091#issuecomment-410613925).
> always activate WebLink component

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/Navigation.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/PublishIndicator.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/tests/PublishIndicator.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Icons.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/icons.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/stores/ToolbarStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/SeoControllerTest.php
| Q | A
| --- | ---
This PR adds the `PublishIndicator` in the Form component Toolbar.
To allow seeing the Content Manager whether or not the current page is published or in draf mode.
The `icons` config option will now take JSX instead of strings.
> Show publish state in Form component

- src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/AutoCompletePopover.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/suggestion.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/AutoCompletePopover.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/Popover.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/SingleAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/MultiAutoComplete.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
- src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
| Q | A
| --- | ---
This PR adds keyboard functionality to the auto complete components.
Because it is much more comfortable to work with it this way.
> Add keyboard shortcuts to AutoComplete components

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
| Q | A
| --- | ---
This PR moves some logic from the `Toolbar::render` method into some `@computed` statements.
Because obervable data was altered in the `render` method, which is not a mobx `action`. This caused an error when following this sequence:
1. Open a page
2. Reload using the browser
3. Change something
4. Save the changes as draft
5. Quickly afterwards Publish the page
6. An error was shown and the entire React tree was unmounted
> Fix error when pressing save buttons right after each other

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/TreeStructureStrategy.test.js
| Q | A
| --- | ---
| Related issues/PRs | #4083
This PR adds a check if a item in a `TreeStructure` has children.
Because in #4083 we added the possibility to return `null` instead of an empty array, to differ whether there are no children or the children only haven't been loaded.
> Fix TreeTable view for pages

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Dropdown.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/README.md
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toggler.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Dropdown.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Toggler.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Toggler.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
- src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
- src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
- src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
| Q | A
| --- | ---
This PR adds a toggler in the `WebspaceOverview`, allowing the user to switch ghosts and shadow pages on and off.
Which problem does the PR fix? (remove this section if you linked an issue above)
> Exclude shadows on ghost via toggler

- CHANGELOG.md
- src/Sulu/Bundle/ContentBundle/Markup/LinkTag.php
- src/Sulu/Bundle/ContentBundle/Tests/Unit/Markup/LinkTagTest.php
The LinkTag adds an attribute named `validation-state` if the target is not published.
After publishing the target page and not editing the link again the resulting link contains the invalid attribute.
| Q | A
| --- | ---
The LinkTag adds an attribute named `validation-state` if the target is not published.
After publishing the target page and not editing the link again the resulting link contains the invalid attribute.
Invalid attribute is rendered
> Remove validation-state from rendered link

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/__snapshots__/ArrowMenu.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/tests/__snapshots__/Selection.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/registries/ToolbarActionRegistry.test.js
- src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleDialog.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/CollectionFormOverlay.test.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
- src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
| Q | A
| --- | ---
There was a warning shown, because some translations were used before they were loaded from the backend.
Because this has shown two non-warnings in the console.
> remove warning for missing translations

- CHANGELOG.md
- src/Sulu/Component/HttpCache/ProxyClient/Symfony.php
| Q | A
| --- | ---
Set a timeout when purging caches
The default behavior is to wait indefinitely (see [guzzle documentation](http://docs.guzzlephp.org/en/stable/request-options.html#connect-timeout)), which
may result in a very long request once the caches need to be cleared, but a long responding host is set in the config (see [example configuration](https://github.com/sulu/sulu-minimal/blob/7887ff338657fa5148c56153030d835d0da02c49/app/Resources/webspaces/example.com.xml#L43))
> Set a timeout when purging caches

- .travis.yml
- CHANGELOG.md
- src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
- src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #4135
Remove the server variable which symfony use the indicate xmlhttprequest and set preview and the other attirbutes correctly.
XMLHttpRequest was true which shouldn't and preview was not longer set.
> Fix preview renderer preview attribute and xml http request

- src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
| Q | A
| --- | ---
| Related PRs | https://github.com/sulu/sulu-minimal/pull/98
As we currently don't support symfony flex we need manually create the .env file.
Else composer create-project will fail with an error that the consoles don't work.
~~~json
"post-create-project-cmd": [
"Sulu\\Bundle\\CoreBundle\\Composer\\ScriptHandler::copyEnvDistFile"
]
~~~
> Added .env file generation

- src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
- src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
| Q | A
| --- | ---
Check for reserved keyword in right loader instead of passing that information to the `PropertiesXmlLoader`.
Nicer design.
> only check for reserved and required keyword in StructureXmlLoader

- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Remove the `/**/` from the current environment glob loaders to avoid problems with the normal glob function.
Currently no configurations under the environment folder e.g. `/config/packages/dev/web_profiler.yaml` is loaded.
Create a environment specific configuration in `/config/packages/<environment>/<yourfile>.yaml`
> Fix loading of environment specific configurations

- src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Item.php
- src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldRenderer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MetadataStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/package.json
- src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
- src/Sulu/Component/Content/Metadata/ItemMetadata.php
- src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
| Q | A
| --- | ---
This PR will allow to define expressions using the [JEXL expression language](https://github.com/TomFrost/Jexl), which define whether or not a specific field should be displayed.
Because we need this functionality in the page settings. Depending on whether the page is a normal content page, an internal link or an external link different fields have to be shown.
And in addition to that this is also a powerful feature, which can be useful in other forms as well.
Only show the url field if the title has a value of "URL":
```xml
<properties> …
```
> Add expressions in form XMLs to conditionally display field types

- src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
| Q | A
| --- | ---
| Related PRs | https://github.com/sulu/sulu-minimal/pull/112
Remove prepended fos rest zone config.
>   Configuration path "fos_rest.zone" cannot be overwritten. You have to define all options for this path, and any of its sub-paths
in one configuration section.
Instead configure this in your project configuration:
~~~php
fos_rest:
zone:
- { path: ^/admin/* }
- { path: ^/api/* }
~~~
> Remove prepended fos rest zone config

- src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
- src/Sulu/Bundle/MediaBundle/Tests/app/config/config.yml
| Q | A
| --- | ---
| Related PRs | #3966
Set image formats folder to project_dir/config/image-formats.xml
The configuration should be in the config folder not in the src folder. Its also so documented in the UPGRADE.md
> Fix image formats folder path

- src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
- src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/FixturesLoadCommandTest.php
| Q | A
| --- | ---
Added root kernel path to be available as document data fixtures paths.
As the src folder is not longer a bundle we need to add `src/DataFixtures/Document` as data fixture folder. 
~~~php
<?php
// src/DataFixtures/Document/PageFixture.php
namespace App\DataFixtures\Document;
use Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentFixtureInterface;
use Sulu\Component\DocumentManager\DocumentManager;
class PageFixture implements DocumentFixtureInterface
{
public function getOrder()
{
return 10;
}
public function load(DocumentManager $documentManager)
{
// ...
}
}
~~~
> Added root kernel path to be available as document data fixtures paths

- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Set the kernel name to avoid duplicate names.
For example opcache crashes.
> Fix kernel name

- src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
- src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
| Q | A
| --- | ---
The parameters `sulu_http_cache.cache.max_age`and `sulu_http_cache.cache.shared_max_age` are currently not available in dev and test environment because of the `shouldCache` method.
The parameters should always be available.
Mostly I use the following snippet in my custom static controllers:
~~~php
$response = new Response();
$response->setPublic();
$response->setMaxAge($this->getParameter('sulu_http_cache.cache.max_age'));
$response->setSharedMaxAge($this->getParameter('sulu_http_cache.cache.shared_max_age'));
$response->headers->set(
AbstractHttpCache::HEADER_REVERSE_PROXY_TTL,
1209600
);
~~~
This PR fixed an accidently BC Break in 2.0 and make the variables again available …
> Fixed missing http cache parameters under dev and test env

- .travis.yml
- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Command/ContentTypesDumpCommand.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
- src/Sulu/Component/Content/ContentTypeManager.php
- src/Sulu/Component/Content/ContentTypeManagerInterface.php
- src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
- src/Sulu/Component/Content/Tests/Unit/ContentTypeManagerTest.php
- src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
| Q | A
| --- | ---
| Fixed Issues | parts of #4008
Change `ContentTypeManager::getAll`to return only aliases instead of instances.
To avoid that any service initialized all content types when its not needed and avoid false error messages when unregistered content types are used.
~~~php
foreach ($contentTypeManager->getAll() as $alias) {
$contentType = $contentTypeManager->get($alias);
// ...
}
~~~
See UPGRADE.md
> Change ContentTypeManager::getAll to return only aliases instead of instances

- UPGRADE.md
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
| Q | A
| --- | ---
| Related issues/PRs | symfony/symfony#28372
The `DateTimeType` of the Symfony Form component doesn't accept any timezones anymore. Our datetime field doesn't add a timezone anyway, but the server should not return the timezone as well, because if the field is not edited, we don't update the value, and the validation will fail as well.
We might also have to backport this change to 1.x, because Symfony 3.4.16 should have the same bug, but doesn't work currently because of symfony/symfony#28658.
The tests were failing, and if a datetime field was in the form, it couldn't be sent to the server without an error without editing it first. …
> fix datetime formatting for Symfony regression

- src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
| Q | A
| --- | ---
Set service 'sulu_website.resolver.template_attribute' to public
This is used by third party bundles.
> Set service 'sulu_website.resolver.template_attribute' to public

- composer.json
| Q | A
| --- | ---
This PR inserts conflicts for symfony/symfony because of symfony/symfony#28658 and symfony/symfony#28699.
> add conflicting symfony versions

- src/Sulu/Bundle/CategoryBundle/Resources/config/forms/Category.xml
| Q | A
| --- | ---
This PR adds the description and media field to the Category form.
Because our category entities support that. The only missing field in this form are the keywords now, which probably require a separate field type.
> add missing fields to category form

- src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | #4101
The `formOfAddress` contains an id as value, which can be of type number since #4101. The `formOfAddress` uses an ID of `0`, which makes the contact controller fail.
Because the `ContactController` didn't use a strict type check, so that `null` and `0` were considered equal.
> fix error when creating male contact

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
| Q | A
| --- | ---
This PR fixes setting a default value of 0 to the SingleSelect field.
Because of a wrong check it was not recognized correctly.
> fix default value of 0 for SingleSelect

- src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/matrix.scss
| Q | A
| --- | ---
| Related issues/PRs | introduced in #4101
This PR fixes the regression in the matrix items caused by the font-size set on the `body`.
Because the icons are too small currently.
> fix font size in matrix items

- src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
- src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
- src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
- src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
- src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
- src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
- src/Sulu/Bundle/SearchBundle/Controller/SearchController.php
- src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
| Q | A
| --- | ---
| Related issues/PRs | #4190 
This PR allows to send `null` as a valid value for `medias` to the category API. Before it resulted in a 500, because an `array_key_exists` call was made with `null` as argument.
Because the new Admin will send `null` to the API, if the field hasn't been touched. And it seems like this should be valid anyway (and especially we should not return 500s from the server).
Can be tested if the `licence` and `description` field of a media has not been set yet.
> handle null values in API consistently

- src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml
| Q | A
| --- | ---
This PR adds more validation to the user form.
It was possible to create a new user without a password (resp. it was possible to send the form, and retrieving an error from the server with no good explanation).
In addition to that it was possible to not assign any roles, which makes no sense, and let the server crash as well.
> validate password and roles correctly in user tab

- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
| Q | A
| --- | ---
This PR changes the `parent` parameter to `parentId` in the `MediaOverlay`.
Because the API expects a `parentId` parameter, and this causes a bug currently. When changing the folder in the `MediaSelectionOverlay`
> fix changing of folders in MediaSelectionOverlay

- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/FolderAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
| Q | A
| --- | ---
This PR hides the pagination of the `Table` and `Folder` DatagridAdapter, if no data at all is available.
Because it looks strange in some situations, e.g. the `MediaSelectionOverlay`.
> hide pagination if no data is available

- src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
- src/Sulu/Bundle/ContentBundle/Resources/js/components/WebspaceSelect/webspaceSelect.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/collectionSection.scss
- src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
| Q | A
| --- | ---
This PR fixes the navigation to the parent collection if a collection is deleted.
> fix route navigation after deleting a media collection

- UPGRADE.md
- src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Item.php
- src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
- src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/types.js
- src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/fieldTypeDefaultProps.js
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
- src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_evaluations.xml
- src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
- src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSettings.xml
- src/Sulu/Component/Content/Metadata/ItemMetadata.php
- src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
- src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
| Q | A
| --- | ---
| Related issues/PRs | #4192 
This PR adds the `disabledCondition` to the form XML, which should allow to disabled certain fields on certain conditions. This is similar to the already existing `visibilityCondition`, which is renamed to `visibleCondition` to better match the other name.
Because we need to deactivate the shadow button in #4192 on pages, which are already the target of other locales.
`visibilityCondition` is renamed to `visibleCondition` in the form xml.
> Add disabledCondition to dynamically change disabled state of form types

- src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
| Q | A
| --- | ---
Remove the env file copy composer script.
The script was not working because post create project scripts are runned after post install scripts.
~~~php
composer create-project sulu/sulu-minimal:^2.0@dev
~~~
> Remove the env file copy composer script

- src/Sulu/Bundle/ContactBundle/Content/Types/SingleContactSelection.php
- src/Sulu/Bundle/ContactBundle/Resources/config/content.xml
- src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php
| Q | A
| --- | ---
| Related Issues | #3624 
| Documentation PR | https://github.com/sulu/sulu-docs/pull/393
Added single contact selection content type.
Have a single contact selection content type available.
See documentation: https://github.com/sulu/sulu-docs/pull/393
none
> Added single contact selection content type

- .travis.yml
- CHANGELOG.md
- src/Sulu/Bundle/SecurityBundle/User/UserProvider.php
| Q | A
| --- | ---
Added exception messages to user provider for enabled and locked.
Easier to implement a better output for the community bundle if a user is not yet enabled.
> Added exception messages to user provider for enabled and locked

- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
- src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
| Q | A
| --- | ---
This PR avoid to initialize the same entities for every test run in the ContactBundle.
Because if we only initialize the entities we need for each test, then the tests are a lot faster and need less memory. I hope that this well also reduce the stallings in our CI services.
> improve ContactBundle functional tests

- UPGRADE.md
- src/Sulu/Component/HttpKernel/SuluKernel.php
| Q | A
| --- | ---
Rename logs folder to match symfony 4 var/log folder.
Symfony renamed the var/logs folder to [var/log](https://github.com/symfony/demo/blob/4c100346da85aa94a61b77aedd90c30aa9c626ac/src/Kernel.php#L34).
I did see this because of the symfony 4 deployer script: https://github.com/deployphp/deployer/blob/master/recipe/symfony4.php#L12
> Rename logs folder to match symfony 4 var/log folder
